nifi/nifi-assembly/pom.xml

https://issues.apache.org/jira/browse/NIFI-269?jql=project%20%3D%20NIFI

NIFI-269: fix OSX build

---

nifi/nifi-docs/pom.xml
nifi/nifi-docs/src/main/asciidoc/asciidoc-mod.css
nifi/nifi-docs/src/main/asciidoc/developer-guide.adoc

I made two tiny tweaks(fixed some broken markup, and changed a "." to a ":"), and updated the processor documentation section to reflect the new generated documentation feature.  You'll see a pull request for that shortly.

NIFI-152 Dev guide update

---

nifi/nifi-nar-bundles/nifi-standard-bundle/nifi-standard-processors/src/main/java/org/apache/nifi/processors/standard/GetFTP.java
nifi/nifi-nar-bundles/nifi-standard-bundle/nifi-standard-processors/src/main/java/org/apache/nifi/processors/standard/util/FTPTransfer.java
nifi/nifi-nar-bundles/nifi-standard-bundle/nifi-standard-processors/src/main/java/org/apache/nifi/processors/standard/util/SocksProxySocketFactory.java

Change-Id: I72fee6c5f2ef576a6c7d736199aab510bee744a7

NIFI-332 Proxy support in GetFTP Processor

---

nifi/nifi-nar-bundles/nifi-hadoop-bundle/nifi-hdfs-processors/src/main/java/org/apache/nifi/processors/hadoop/CreateHadoopSequenceFile.java
nifi/nifi-nar-bundles/nifi-standard-bundle/nifi-standard-processors/src/main/java/org/apache/nifi/processors/standard/Base64EncodeContent.java
nifi/nifi-nar-bundles/nifi-standard-bundle/nifi-standard-processors/src/main/java/org/apache/nifi/processors/standard/CompressContent.java
nifi/nifi-nar-bundles/nifi-standard-bundle/nifi-standard-processors/src/main/java/org/apache/nifi/processors/standard/HashContent.java
nifi/nifi-nar-bundles/nifi-standard-bundle/nifi-standard-processors/src/main/java/org/apache/nifi/processors/standard/PutEmail.java
nifi/nifi-nar-bundles/nifi-standard-bundle/nifi-standard-processors/src/main/java/org/apache/nifi/processors/standard/SegmentContent.java
nifi/nifi-nar-bundles/nifi-standard-bundle/nifi-standard-processors/src/main/java/org/apache/nifi/processors/standard/TransformXml.java
nifi/nifi-nar-bundles/nifi-standard-bundle/nifi-standard-processors/src/test/java/org/apache/nifi/processors/standard/TestCompressContent.java
nifi/nifi-nar-bundles/nifi-standard-bundle/nifi-standard-processors/src/test/java/org/apache/nifi/processors/standard/TestPutEmail.java

Modified processors that were catching Exception to catch ProcessException.

Nifi 333 - catching ProcessException instead of Exception

---

nifi/nifi-nar-bundles/nifi-hadoop-bundle/nifi-hdfs-processors/src/main/java/org/apache/nifi/processors/hadoop/KeyValueReader.java
nifi/nifi-nar-bundles/nifi-hadoop-bundle/nifi-hdfs-processors/src/main/java/org/apache/nifi/processors/hadoop/ValueReader.java

catching ProcessException in HDFS helper classes

NIFI-333 part 2

---

nifi/nifi-commons/nifi-security-utils/src/main/java/org/apache/nifi/security/util/EncryptionMethod.java
nifi/nifi-nar-bundles/nifi-standard-bundle/nifi-standard-processors/pom.xml
nifi/nifi-nar-bundles/nifi-standard-bundle/nifi-standard-processors/src/main/java/org/apache/nifi/processors/standard/EncryptContent.java
nifi/nifi-nar-bundles/nifi-standard-bundle/nifi-standard-processors/src/main/java/org/apache/nifi/processors/standard/util/OpenPGPKeyBasedEncryptor.java
nifi/nifi-nar-bundles/nifi-standard-bundle/nifi-standard-processors/src/main/java/org/apache/nifi/processors/standard/util/OpenPGPPasswordBasedEncryptor.java
nifi/nifi-nar-bundles/nifi-standard-bundle/nifi-standard-processors/src/main/java/org/apache/nifi/processors/standard/util/PasswordBasedEncryptor.java
nifi/nifi-nar-bundles/nifi-standard-bundle/nifi-standard-processors/src/main/resources/docs/org.apache.nifi.processors.standard.EncryptContent/additionalDetails.html
nifi/nifi-nar-bundles/nifi-standard-bundle/nifi-standard-processors/src/test/java/org/apache/nifi/processors/standard/TestEncryptContent.java
nifi/nifi-nar-bundles/nifi-standard-bundle/nifi-standard-processors/src/test/resources/TestEncryptContent/text.txt
nifi/nifi-nar-bundles/nifi-standard-bundle/nifi-standard-processors/src/test/resources/TestEncryptContent/text.txt.asc
nifi/pom.xml

This PR resolves NIFI-30 and NIFI-374.  It adds bcpg-jdk16-1.46.jar to the nifi-standard-processors-nar, and I believe this jar is already covered in the existing 'Bouncy Castle JDK 1.6 Provider' part of the LICENSE, but could use some verification.

NIFI-30 and NIFI-374

---

README.md

Updated the README to have correct link for quickstart and developer guide

---

nifi-nar-bundles/nifi-standard-bundle/nifi-standard-processors/pom.xml
nifi-nar-bundles/nifi-standard-bundle/nifi-standard-processors/src/main/java/org/apache/nifi/processors/standard/JmsConsumer.java
nifi-nar-bundles/nifi-standard-bundle/nifi-standard-processors/src/main/java/org/apache/nifi/processors/standard/util/JmsFactory.java
nifi-nar-bundles/nifi-standard-bundle/nifi-standard-processors/src/test/java/org/apache/nifi/processors/standard/TestGetJMSQueue.java
pom.xml

Re-enabled JMS Tests that were annotated with @Ignore

NIFI-1000 Fixed JmsFactory to properly obtain destiniation name

---

nifi-nar-bundles/nifi-kafka-bundle/nifi-kafka-processors/src/main/java/org/apache/nifi/processors/kafka/GetKafka.java

Pull request with changes. 
@markap14 I removed the writeAttributes ones, since there is no need to write the auto.offset to the flowfile attribute. I also modified the description. Please check to see if the description is fine,
Screenshots after the build,

NIFI-1146  Allow GetKafka to be configured with auto.offset.reset to "largest" or "smallest"

---

.travis.yml
README.md
pom.xml

NIFI-1211 Adding a .travis.yml to provide CI and adding an exclusion for this file in the RAT check configuration

NIFI-1211 - This is a test PR to verify expected Travis CI functionality

---

nifi-nar-bundles/nifi-standard-bundle/nifi-standard-processors/src/main/java/org/apache/nifi/processors/standard/SplitXml.java
nifi-nar-bundles/nifi-standard-bundle/nifi-standard-processors/src/test/java/org/apache/nifi/processors/standard/TestSplitXml.java
nifi-nar-bundles/nifi-standard-bundle/nifi-standard-processors/src/test/resources/TestXml/namespace.xml

I've done a fairly minimal update to SplitXML to correctly support namespace declarations.
Let me know if I've missed anything.

NIFI-1421 Update SplitXML to support namespace declarations

---

nifi-nar-bundles/nifi-framework-bundle/nifi-framework/nifi-framework-core/src/main/java/org/apache/nifi/controller/repository/FileSystemRepository.java
nifi-nar-bundles/nifi-framework-bundle/nifi-framework/nifi-framework-core/src/test/java/org/apache/nifi/controller/repository/TestFileSystemRepository.java

added minimal interval
added WARN message if set interval is lower

NIFI-1200 fixed CPU saturation in FileSystemRepository

---

nifi-nar-bundles/nifi-standard-bundle/nifi-standard-processors/src/main/java/org/apache/nifi/processors/standard/ConvertJSONToSQL.java
nifi-nar-bundles/nifi-standard-bundle/nifi-standard-processors/src/test/java/org/apache/nifi/processors/standard/TestConvertJSONToSQL.java

Mostly based on contribution from Daniel Cave

NIFI-1093 added support for handling non-required columns

---

nifi-nar-bundles/nifi-aws-bundle/nifi-aws-processors/src/main/java/org/apache/nifi/processors/aws/AbstractAWSCredentialsProviderProcessor.java
nifi-nar-bundles/nifi-aws-bundle/nifi-aws-processors/src/main/java/org/apache/nifi/processors/aws/AbstractAWSProcessor.java
nifi-nar-bundles/nifi-aws-bundle/nifi-aws-processors/src/main/java/org/apache/nifi/processors/aws/lambda/AbstractAWSLambdaProcessor.java
nifi-nar-bundles/nifi-aws-bundle/nifi-aws-processors/src/main/java/org/apache/nifi/processors/aws/lambda/PutLambda.java
nifi-nar-bundles/nifi-aws-bundle/nifi-aws-processors/src/main/resources/META-INF/services/org.apache.nifi.processor.Processor
nifi-nar-bundles/nifi-aws-bundle/nifi-aws-processors/src/test/java/org/apache/nifi/processors/aws/lambda/ITPutLambda.java
nifi-nar-bundles/nifi-aws-bundle/nifi-aws-processors/src/test/java/org/apache/nifi/processors/aws/lambda/ITPutLambdaTest.java

Support AWS Lambda processor (https://issues.apache.org/jira/browse/NIFI-1509)

Nifi-1509 - Support aws lambda put processor

---

nifi-nar-bundles/nifi-kafka-bundle/nifi-kafka-processors/src/main/java/org/apache/nifi/processors/kafka/KafkaPublisher.java
nifi-nar-bundles/nifi-kafka-bundle/nifi-kafka-processors/src/main/java/org/apache/nifi/processors/kafka/Partitioners.java
nifi-nar-bundles/nifi-kafka-bundle/nifi-kafka-processors/src/main/java/org/apache/nifi/processors/kafka/PutKafka.java
nifi-nar-bundles/nifi-kafka-bundle/nifi-kafka-processors/src/main/java/org/apache/nifi/processors/kafka/SplittableMessageContext.java
nifi-nar-bundles/nifi-kafka-bundle/nifi-kafka-processors/src/main/java/org/apache/nifi/processors/kafka/StreamScanner.java
nifi-nar-bundles/nifi-kafka-bundle/nifi-kafka-processors/src/test/java/org/apache/nifi/processors/kafka/KafkaPublisherTest.java
nifi-nar-bundles/nifi-kafka-bundle/nifi-kafka-processors/src/test/java/org/apache/nifi/processors/kafka/TestPutKafka.java
nifi-nar-bundles/nifi-kafka-bundle/nifi-kafka-processors/src/test/resources/log4j.properties

- used newest API available in 0.8.* version
- added PutKafka integration tests
- Kafka module code coverage is at 85%
NIFI-1645 polishing

NIFI-1645 refactored PutKafka

---

nifi-nar-bundles/nifi-framework-bundle/nifi-framework/nifi-framework-core/src/test/java/org/apache/nifi/controller/state/providers/zookeeper/TestZooKeeperStateProvider.java

NIFI-1872: Allow for adequate time for embedded zookeeper server to startup for unit tests

---

nifi-nar-bundles/nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-api/src/main/java/org/apache/nifi/web/StandardNiFiServiceFacade.java
nifi-nar-bundles/nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-api/src/main/java/org/apache/nifi/web/api/ApplicationResource.java
nifi-nar-bundles/nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-api/src/main/java/org/apache/nifi/web/dao/impl/StandardSnippetDAO.java
nifi-nar-bundles/nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-api/src/main/java/org/apache/nifi/web/dao/impl/StandardTemplateDAO.java
nifi-nar-bundles/nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-api/src/main/java/org/apache/nifi/web/util/SnippetUtils.java

- fixed clustering issues discovered after NIFI-826 was applied

NIFI-826 (part deux)

---

nifi-nar-bundles/nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-ui/src/main/webapp/WEB-INF/partials/canvas/connection-configuration.jsp
nifi-nar-bundles/nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-ui/src/main/webapp/WEB-INF/partials/connection-details.jsp
nifi-nar-bundles/nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-ui/src/main/webapp/js/nf/canvas/nf-connection-configuration.js
nifi-nar-bundles/nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-ui/src/main/webapp/js/nf/nf-connection-details.js

NIFI-5661: 
- Allowing the load balance configuration to be shown/edited in both clustered and standalone mode.

NIFI-5661: Always showing load balance settings

---

nifi-nar-bundles/nifi-aws-bundle/nifi-aws-abstract-processors/src/main/java/org/apache/nifi/processors/aws/credentials/provider/factory/CredentialPropertyDescriptors.java

NIFI-5898: Updated the display name for ACCESS_KEY & SECRET_KEY

---

nifi-nar-bundles/nifi-hive-bundle/nifi-hive3-processors/src/main/java/org/apache/nifi/processors/hive/PutHive3Streaming.java
nifi-nar-bundles/nifi-hive-bundle/nifi-hive3-processors/src/test/java/org/apache/nifi/processors/hive/TestPutHive3Streaming.java

NIFI-5904: Fix PutHive3Streaming handling of RecordReaderFactoryException

---

nifi-nar-bundles/nifi-framework-bundle/nifi-framework/nifi-framework-core/src/main/java/org/apache/nifi/controller/FlowController.java

NIFI-5905 Secure S2S fails with NullPointerException

---

nifi-nar-bundles/nifi-aws-bundle/nifi-aws-abstract-processors/src/main/java/org/apache/nifi/processors/aws/AbstractAWSProcessor.java

NIFI-5893: AWS Endpoint Overriding now functions properly

---

nifi-docs/src/main/asciidoc/developer-guide.adoc
nifi-docs/src/main/asciidoc/user-guide.adoc

NIFI-5913 - Standardize Definition of UUID in Documentation

---

nifi-nar-bundles/nifi-standard-services/nifi-dbcp-service-bundle/nifi-dbcp-service/src/test/java/org/apache/nifi/dbcp/DBCPServiceTest.java

NIFI-5790 removed the last test as it's causing a race condition intermittently

---

nifi-framework-api/src/main/java/org/apache/nifi/controller/queue/FlowFileSummary.java
nifi-nar-bundles/nifi-framework-bundle/nifi-framework/nifi-client-dto/src/main/java/org/apache/nifi/web/api/dto/FlowFileSummaryDTO.java
nifi-nar-bundles/nifi-framework-bundle/nifi-framework/nifi-framework-core/src/main/java/org/apache/nifi/controller/queue/AbstractFlowFileQueue.java
nifi-nar-bundles/nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-api/src/main/java/org/apache/nifi/web/api/dto/DtoFactory.java
nifi-nar-bundles/nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-ui/src/main/webapp/js/nf/canvas/nf-queue-listing.js

NIFI-5722 Expose Penalty Remaining Duration

---

README.md

NIFI-6103 Fixed README documentation to indicate JDK 1.8 is required.

---

nifi-nar-bundles/nifi-hadoop-bundle/nifi-hdfs-processors/src/main/java/org/apache/nifi/processors/hadoop/MoveHDFS.java

NIFI-6049: Updated MoveHDFS to support FF Attribute for Output Directory

---

.github/PULL_REQUEST_TEMPLATE.md

NIFI-6296 Improved PR template messaging around commit process.

---

nifi-nar-bundles/nifi-framework-bundle/nifi-framework/nifi-administration/src/main/resources/nifi-administration-context.xml
nifi-nar-bundles/nifi-framework-bundle/nifi-framework/nifi-authorizer/src/main/resources/nifi-authorizer-context.xml
nifi-nar-bundles/nifi-framework-bundle/nifi-framework/nifi-framework-cluster-protocol/src/main/resources/nifi-cluster-protocol-context.xml
nifi-nar-bundles/nifi-framework-bundle/nifi-framework/nifi-framework-cluster/src/main/resources/nifi-cluster-manager-context.xml
nifi-nar-bundles/nifi-framework-bundle/nifi-framework/nifi-framework-core/src/main/resources/nifi-context.xml
nifi-nar-bundles/nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-api/src/main/resources/nifi-web-api-context.xml
nifi-nar-bundles/nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-security/src/main/resources/nifi-web-security-context.xml

NIFI-6439 - Revert Spring Framework HTTPS XSD

---

nifi-nar-bundles/nifi-extension-utils/nifi-reporting-utils/src/main/java/org/apache/nifi/reporting/util/metrics/MetricsService.java
nifi-nar-bundles/nifi-extension-utils/nifi-reporting-utils/src/main/java/org/apache/nifi/reporting/util/metrics/api/MetricBuilder.java
nifi-nar-bundles/nifi-extension-utils/nifi-reporting-utils/src/main/java/org/apache/nifi/reporting/util/metrics/api/MetricsBuilder.java
nifi-nar-bundles/nifi-site-to-site-reporting-bundle/nifi-site-to-site-reporting-task/src/main/java/org/apache/nifi/reporting/AbstractSiteToSiteReportingTask.java
nifi-nar-bundles/nifi-site-to-site-reporting-bundle/nifi-site-to-site-reporting-task/src/main/java/org/apache/nifi/reporting/SiteToSiteBulletinReportingTask.java
nifi-nar-bundles/nifi-site-to-site-reporting-bundle/nifi-site-to-site-reporting-task/src/main/java/org/apache/nifi/reporting/SiteToSiteMetricsReportingTask.java
nifi-nar-bundles/nifi-site-to-site-reporting-bundle/nifi-site-to-site-reporting-task/src/main/java/org/apache/nifi/reporting/SiteToSiteProvenanceReportingTask.java
nifi-nar-bundles/nifi-site-to-site-reporting-bundle/nifi-site-to-site-reporting-task/src/main/java/org/apache/nifi/reporting/SiteToSiteStatusReportingTask.java
nifi-nar-bundles/nifi-site-to-site-reporting-bundle/nifi-site-to-site-reporting-task/src/test/java/org/apache/nifi/reporting/TestSiteToSiteBulletinReportingTask.java
nifi-nar-bundles/nifi-site-to-site-reporting-bundle/nifi-site-to-site-reporting-task/src/test/java/org/apache/nifi/reporting/TestSiteToSiteMetricsReportingTask.java
nifi-nar-bundles/nifi-site-to-site-reporting-bundle/nifi-site-to-site-reporting-task/src/test/java/org/apache/nifi/reporting/TestSiteToSiteProvenanceReportingTask.java
nifi-nar-bundles/nifi-site-to-site-reporting-bundle/nifi-site-to-site-reporting-task/src/test/java/org/apache/nifi/reporting/TestSiteToSiteStatusReportingTask.java

NIFI-6429 - Added option to allow variables with null values to be included in S2S Reporting Tasks

---

nifi-nar-bundles/nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-ui/src/main/webapp/js/nf/canvas/nf-connection.js
nifi-nar-bundles/nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-ui/src/main/webapp/js/nf/summary/nf-summary-table.js

Changes required to align with the latest updates to the predictions API

NIFI-6510 - UI updates to account for minor API changes for back pressure predictions

---

nifi-nar-bundles/nifi-framework-bundle/nifi-framework/nifi-framework-core/src/main/java/org/apache/nifi/controller/leader/election/CuratorLeaderElectionManager.java

NIFI-6589: Addressed NPE

---

nifi-nar-bundles/nifi-hive-bundle/nifi-hive3-processors/pom.xml
nifi-nar-bundles/nifi-hive-bundle/nifi-hive3-processors/src/main/java/org/apache/nifi/dbcp/hive/Hive3ConnectionPool.java
nifi-nar-bundles/nifi-hive-bundle/nifi-hive3-processors/src/test/java/org/apache/nifi/dbcp/hive/Hive3ConnectionPoolTest.java
nifi-nar-bundles/nifi-standard-services/nifi-dbcp-service-api/pom.xml
nifi-nar-bundles/nifi-standard-services/nifi-dbcp-service-api/src/main/java/org/apache/nifi/dbcp/DBCPValidator.java
nifi-nar-bundles/nifi-standard-services/nifi-dbcp-service-bundle/nifi-dbcp-service/src/main/java/org/apache/nifi/dbcp/DBCPConnectionPool.java

1. Used DBCP2 to replace DBCP library
2. Added 6 properties
+ "Minimum Idle Connections"
+ "Max Idle Connections",
+ "Max Connection Lifetime"
+ "Time Between Eviction Runs"
+ "Minimum Evictable Idle Time"
+ "Soft Minimum Evictable Idle Time"

NIFI-6684 Add more property to Hive3ConnectionPool

---

nifi-nar-bundles/nifi-hive-bundle/nifi-hive3-processors/src/main/java/org/apache/nifi/dbcp/hive/Hive3ConnectionPool.java

Checkstyle violation that I missed/was not caught by Travis CI.

NIFI-6684 - Fixing checkstyle violation

---

nifi-nar-bundles/nifi-prometheus-bundle/nifi-prometheus-reporting-task/pom.xml
nifi-nar-bundles/nifi-prometheus-bundle/nifi-prometheus-reporting-task/src/main/java/org/apache/nifi/reporting/prometheus/PrometheusRecordSink.java
nifi-nar-bundles/nifi-prometheus-bundle/nifi-prometheus-reporting-task/src/main/java/org/apache/nifi/reporting/prometheus/PrometheusReportingTask.java
nifi-nar-bundles/nifi-prometheus-bundle/nifi-prometheus-reporting-task/src/main/java/org/apache/nifi/reporting/prometheus/PrometheusServer.java
nifi-nar-bundles/nifi-prometheus-bundle/nifi-prometheus-reporting-task/src/main/java/org/apache/nifi/reporting/prometheus/api/PrometheusMetricsUtil.java
nifi-nar-bundles/nifi-prometheus-bundle/nifi-prometheus-reporting-task/src/main/resources/META-INF/services/org.apache.nifi.controller.ControllerService
nifi-nar-bundles/nifi-prometheus-bundle/nifi-prometheus-reporting-task/src/test/java/org/apache/nifi/reporting/prometheus/TestPrometheusRecordSink.java
nifi-nar-bundles/nifi-prometheus-bundle/nifi-prometheus-reporting-task/src/test/java/org/apache/nifi/reporting/prometheus/TestPrometheusReportingTask.java
nifi-nar-bundles/nifi-sql-reporting-bundle/nifi-sql-reporting-tasks/src/main/java/org/apache/nifi/reporting/sql/QueryNiFiReportingTask.java
nifi-nar-bundles/nifi-sql-reporting-bundle/nifi-sql-reporting-tasks/src/test/java/org/apache/nifi/reporting/sql/TestQueryNiFiReportingTask.java
nifi-nar-bundles/nifi-standard-services/nifi-record-sink-api/src/main/java/org/apache/nifi/record/sink/RecordSinkService.java

Adds a RecordSinkService for Prometheus scraping, which illustrated the need for a reset() method on the interface (so the metrics registry could be reset between possibly different queries)

NIFI-6799: Add PrometheusRecordSink and reset() method to RecordSinkService

---

nifi-nar-bundles/nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-ui/src/main/webapp/js/nf/canvas/nf-process-group.js

Capitalized 'version' in tool tip.

NIFI-4757 Capitalized 'version' in tool tip.

---

nifi-nar-bundles/nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-ui/src/main/webapp/WEB-INF/partials/canvas/import-flow-version-dialog.jsp

NIFI-4758 Changed 'Name' to 'Flow Name' in Import Version dialog

---

nifi-toolkit/nifi-toolkit-tls/src/main/java/org/apache/nifi/toolkit/tls/configuration/InstanceDefinition.java
nifi-toolkit/nifi-toolkit-tls/src/test/java/org/apache/nifi/toolkit/tls/service/client/TlsCertificateAuthorityClientCommandLineTest.java

NIFI-6847 - fixed NPE in TLS toolkit when used in client mode with SANs

---

pom.xml

NIFI-6843:
- Bumping ranger version to 2.0.0.

NIFI-6843: Bumping to Ranger 2.0.0

---

nifi-nar-bundles/nifi-scripting-bundle/nifi-scripting-processors/pom.xml
nifi-nar-bundles/nifi-scripting-bundle/nifi-scripting-processors/src/main/java/org/apache/nifi/record/sink/script/ScriptedRecordSink.java
nifi-nar-bundles/nifi-scripting-bundle/nifi-scripting-processors/src/main/java/org/apache/nifi/rules/engine/script/ScriptedRulesEngine.java
nifi-nar-bundles/nifi-scripting-bundle/nifi-scripting-processors/src/main/java/org/apache/nifi/rules/handlers/script/ScriptedActionHandler.java
nifi-nar-bundles/nifi-scripting-bundle/nifi-scripting-processors/src/main/java/org/apache/nifi/script/impl/ClojureScriptEngineConfigurator.java
nifi-nar-bundles/nifi-scripting-bundle/nifi-scripting-processors/src/main/java/org/apache/nifi/script/impl/GroovyScriptEngineConfigurator.java
nifi-nar-bundles/nifi-scripting-bundle/nifi-scripting-processors/src/main/resources/META-INF/services/org.apache.nifi.controller.ControllerService
nifi-nar-bundles/nifi-scripting-bundle/nifi-scripting-processors/src/test/java/org/apache/nifi/record/sink/script/ScriptedRecordSinkTest.java
nifi-nar-bundles/nifi-scripting-bundle/nifi-scripting-processors/src/test/java/org/apache/nifi/rules/engine/script/ScriptedRulesEngineTest.java
nifi-nar-bundles/nifi-scripting-bundle/nifi-scripting-processors/src/test/java/org/apache/nifi/rules/handlers/script/ScriptedActionHandlerTest.java
nifi-nar-bundles/nifi-scripting-bundle/nifi-scripting-processors/src/test/java/org/apache/nifi/rules/handlers/script/TestProcessor.java
nifi-nar-bundles/nifi-scripting-bundle/nifi-scripting-processors/src/test/resources/groovy/test_action_handler.groovy
nifi-nar-bundles/nifi-scripting-bundle/nifi-scripting-processors/src/test/resources/groovy/test_propertycontext_action_handler.groovy
nifi-nar-bundles/nifi-scripting-bundle/nifi-scripting-processors/src/test/resources/groovy/test_record_sink.groovy
nifi-nar-bundles/nifi-scripting-bundle/nifi-scripting-processors/src/test/resources/groovy/test_rules_engine.groovy

Added ScriptedRecordSink, ScriptedRulesEngine, and ScriptedActionHandler.

NIFI-6859: Add scripted versions of RecordSinkService, RulesEngineService, and ActionHandler

---

nifi-nar-bundles/nifi-standard-bundle/nifi-standard-processors/src/main/java/org/apache/nifi/processors/standard/ExecuteSQL.java
nifi-nar-bundles/nifi-standard-bundle/nifi-standard-processors/src/main/java/org/apache/nifi/processors/standard/ExecuteSQLRecord.java

Added missing doc for attribute

NIFI-6953: Add missing documentation for input.flowfile.uuid attribute of ExecuteSQL processors

---

nifi-nar-bundles/nifi-hive-bundle/nifi-hive3-processors/src/main/java/org/apache/nifi/processors/hive/PutHive3Streaming.java
nifi-nar-bundles/nifi-hive-bundle/nifi-hive3-processors/src/test/java/org/apache/nifi/processors/hive/TestPutHive3Streaming.java

NIFI-6956: Fixed StreamingException handling in PutHive3Streaming

---

nifi-nar-bundles/nifi-standard-bundle/nifi-standard-processors/pom.xml
nifi-nar-bundles/nifi-standard-bundle/nifi-standard-processors/src/main/java/org/apache/nifi/processors/standard/PutRecord.java
nifi-nar-bundles/nifi-standard-bundle/nifi-standard-processors/src/main/resources/META-INF/services/org.apache.nifi.processor.Processor
nifi-nar-bundles/nifi-standard-bundle/nifi-standard-processors/src/test/java/org/apache/nifi/processors/standard/MockRecordSinkService.java
nifi-nar-bundles/nifi-standard-bundle/nifi-standard-processors/src/test/java/org/apache/nifi/processors/standard/TestPutRecord.java
nifi-nar-bundles/nifi-standard-services/nifi-record-sink-api/src/main/java/org/apache/nifi/record/sink/RetryableIOException.java

Add a generic PutRecord processor that uses a RecordSinkService implementation to send the records to the specified destination.

NIFI-6947: Add PutRecord processor using RecordSinkService

---

pom.xml

NIFI-7108 - Upgrade com.puppycrawl.tools:checkstyle

---

nifi-nar-bundles/nifi-site-to-site-reporting-bundle/nifi-site-to-site-reporting-task/src/main/resources/docs/org.apache.nifi.reporting.SiteToSiteStatusReportingTask/additionalDetails.html
nifi-nar-bundles/nifi-site-to-site-reporting-bundle/nifi-site-to-site-reporting-task/src/main/resources/schema-status.avsc

NIFI-7105 - fix NPE for counters in SiteToSiteStatusReportingTask

---

nifi-nar-bundles/nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-ui/src/main/webapp/WEB-INF/partials/login/login-form.jsp

Added `autocomplete="off"` to the password input at login page.

NIFI-7136 Added autocomplete="off" to login password input

---

nifi-docs/src/main/asciidoc/developer-guide.adoc

_Changed some formatting for readability and corrected confusing information about core attributes in Developer Guide._

NIFI-7175 Fixed core attributes formatting in Developer Guide.

---

nifi-docs/src/main/asciidoc/overview.adoc

_Fixed typo in opening line of Overview doc._

NIFI-7218 Fixed typo in Overview docs.

---

nifi-nar-bundles/nifi-extension-utils/nifi-database-utils/src/main/java/org/apache/nifi/util/db/JdbcCommon.java
nifi-nar-bundles/nifi-standard-bundle/nifi-standard-processors/src/test/java/org/apache/nifi/processors/standard/TestPutSQL.java

Removes use of java.util.Date from timestamp parsing in `setParameter`, use structures that support nanoseconds

NIFI-7208: Fixed PutSQL/JdbcCommon handling of timestamps (nanoseconds, e.g.)

---

nifi-docs/src/main/asciidoc/administration-guide.adoc

NIFI-7227 Fixed typo in Global Access Policy table

---

nifi-docker/dockerhub/pom.xml
nifi-docker/dockermaven/pom.xml
nifi-toolkit/nifi-toolkit-assembly/pom.xml

Honor Maven properties skipTests and maven.test.skip for the
shell script integration tests that verifiy docker images.

NIFI-7191 Conditionally disable docker integration tests

---

nifi-nar-bundles/nifi-mongodb-bundle/nifi-mongodb-processors/src/main/java/org/apache/nifi/processors/mongodb/AbstractMongoProcessor.java

NIFI-7233 - Fix Mongo Processors to avoid cycle in provenance graph

---

nifi-commons/nifi-security-utils/src/main/java/org/apache/nifi/security/util/crypto/Argon2SecureHasher.java
nifi-commons/nifi-security-utils/src/test/groovy/org/apache/nifi/security/util/crypto/Argon2SecureHasherTest.groovy

_Implemented boundary checking for Argon2SecureHasher cost parameters and added unit tests._

NIFI-7119 Implement boundary checking for Argon2 cost parameters

---

nifi-nar-bundles/nifi-extension-utils/nifi-database-utils/src/main/java/org/apache/nifi/util/db/JdbcCommon.java
nifi-nar-bundles/nifi-standard-bundle/nifi-standard-processors/src/test/java/org/apache/nifi/processors/standard/TestPutSQL.java

The original fix for NIFI-7208 indeed allowed support for nanoseconds in timestamps, but changed the timezone to UTC from the system default. This PR restores the use of the system default timezone

NIFI-7208: Restore default timezone in JdbcCommon

---

nifi-nar-bundles/nifi-redis-bundle/pom.xml

NIFI-7267 - Upgrade spring-data-redis in Redis bundle

---

nifi-nar-bundles/nifi-framework-bundle/nifi-framework/nifi-framework-core/src/test/java/org/apache/nifi/controller/scheduling/TestStandardProcessScheduler.java
nifi-nar-bundles/nifi-standard-services/nifi-dbcp-service-bundle/nifi-dbcp-service/src/test/java/org/apache/nifi/dbcp/DBCPServiceTest.java

NIFI-7274 add time for test conditions to be met

---

nifi-nar-bundles/nifi-extension-utils/nifi-prometheus-utils/pom.xml
nifi-nar-bundles/nifi-extension-utils/nifi-prometheus-utils/src/main/java/org/apache/nifi/prometheus/util/PrometheusMetricsUtil.java
nifi-nar-bundles/nifi-extension-utils/pom.xml
nifi-nar-bundles/nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-api/pom.xml
nifi-nar-bundles/nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-api/src/main/java/org/apache/nifi/web/NiFiServiceFacade.java
nifi-nar-bundles/nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-api/src/main/java/org/apache/nifi/web/StandardNiFiServiceFacade.java
nifi-nar-bundles/nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-api/src/main/java/org/apache/nifi/web/api/FlowResource.java
nifi-nar-bundles/nifi-prometheus-bundle/nifi-prometheus-reporting-task/pom.xml
nifi-nar-bundles/nifi-prometheus-bundle/nifi-prometheus-reporting-task/src/main/java/org/apache/nifi/reporting/prometheus/PrometheusRecordSink.java
nifi-nar-bundles/nifi-prometheus-bundle/nifi-prometheus-reporting-task/src/main/java/org/apache/nifi/reporting/prometheus/PrometheusReportingTask.java
nifi-nar-bundles/nifi-prometheus-bundle/nifi-prometheus-reporting-task/src/test/java/org/apache/nifi/reporting/prometheus/TestPrometheusRecordSink.java
nifi-nar-bundles/nifi-prometheus-bundle/nifi-prometheus-reporting-task/src/test/java/org/apache/nifi/reporting/prometheus/TestPrometheusReportingTask.java

Rather than having to add a ReportingTask to the NiFi flow in order for Prometheus to scrape NiFi metrics, this PR exposes a REST endpoint on each node as a scrape target for Prometheus. Metrics include all metrics available from the other Prometheus components in addition to connection analytics/predictions (time to backpressure, e.g.) and bulletins (for integration with AlertMananger)

NIFI-7273: Add flow metrics REST endpoint with for Prometheus scraping

---

nifi-nar-bundles/nifi-splunk-bundle/pom.xml

NIFI-7326 updated URL to find splunk artifacts

---

nifi-nar-bundles/nifi-extension-utils/nifi-prometheus-utils/pom.xml
nifi-nar-bundles/nifi-extension-utils/nifi-prometheus-utils/src/main/java/org/apache/nifi/prometheus/util/PrometheusMetricsUtil.java
nifi-nar-bundles/nifi-prometheus-bundle/nifi-prometheus-reporting-task/src/test/java/org/apache/nifi/reporting/prometheus/TestPrometheusReportingTask.java

Provides default empty string for null values used in Prometheus metric labels

NIFI-7378: Ensure label values are not null in Prometheus metrics

---

nifi-nar-bundles/nifi-framework-bundle/nifi-framework/nifi-framework-cluster/src/main/java/org/apache/nifi/cluster/coordination/node/NodeClusterCoordinator.java

Disables state updates for deleted node; fixes bug NIFI-7003

NIFI-7003: Do not update status for stopping a deleted node

---

nifi-nar-bundles/nifi-framework-bundle/nifi-framework/nifi-framework-core/src/main/java/org/apache/nifi/controller/state/manager/StandardStateManagerProvider.java

NIFI-7471 fix bug with property validation

---

nifi-nar-bundles/nifi-gcp-bundle/nifi-gcp-processors/src/main/java/org/apache/nifi/processors/gcp/pubsub/ConsumeGCPubSub.java
nifi-nar-bundles/nifi-gcp-bundle/nifi-gcp-processors/src/main/java/org/apache/nifi/processors/gcp/pubsub/PublishGCPubSub.java
nifi-nar-bundles/nifi-gcp-bundle/nifi-gcp-services-api/pom.xml
nifi-nar-bundles/nifi-gcp-bundle/pom.xml

NIFI-6701 - Fix for PublishGCPPubSub

---

nifi-nar-bundles/nifi-standard-bundle/nifi-standard-processors/src/main/java/org/apache/nifi/processors/standard/LookupRecord.java
nifi-nar-bundles/nifi-standard-bundle/nifi-standard-processors/src/test/java/org/apache/nifi/processors/standard/TestLookupRecord.java

NIFI-7430 - LookupRecord change coordinate key for in-place replacement

---

nifi-commons/nifi-utils/src/main/java/org/apache/nifi/remote/io/socket/NetworkUtils.java
nifi-nar-bundles/nifi-email-bundle/nifi-email-processors/pom.xml
nifi-nar-bundles/nifi-email-bundle/nifi-email-processors/src/test/java/org/apache/nifi/processors/email/TestListenSMTP.java
nifi-nar-bundles/nifi-standard-bundle/nifi-standard-processors/src/test/java/org/apache/nifi/processors/standard/TestListFile.java

TestListenSMTP tests started failing again on the macOS GitHub builds after an update to the macOS virtual environment for GitHub Actions [1]. This PR refactors TestListenSMTP so it isn't fussy about the concurrency and timing of the tests and makes the assertions more informative (which resolves NIFI-4760).
This also adjusts the timings in TestListFile so its not as sensitive when there's second-only mtime resolution.
1. https://github.com/actions/virtual-environments/blob/master/images/macos/macos-10.15-Readme.md

NIFI-7540: Fix TestListenSMTP and TestListFile on macOS build environment

---

nifi-docs/src/main/asciidoc/walkthroughs.adoc

NIFI-7513 added steps to walkthrough

---

nifi-commons/nifi-site-to-site-client/src/test/java/org/apache/nifi/remote/client/http/TestHttpClient.java

_Fixes a failing unit test in one of the CI/CD builds._

NIFI-7620 Fixed failing unit test due to timeout.

---

nifi-nar-bundles/nifi-hbase-bundle/nifi-hbase-processors/src/main/java/org/apache/nifi/hbase/GetHBase.java

NIFI-7667 - add variable support to GetHBase properties

---

nifi-docs/src/main/asciidoc/administration-guide.adoc
nifi-nar-bundles/nifi-standard-bundle/nifi-standard-processors/src/main/java/org/apache/nifi/processors/standard/HandleHttpRequest.java

Nifi 7640 Add documentation for temporary directory used by HandleHttpRequest

---

nifi-nar-bundles/nifi-framework-bundle/nifi-framework/nifi-resources/src/main/resources/conf/bootstrap.conf

Fixed the typo for the 17th argument in the bootstrap.conf by removing an additional ".".

NIFI-7315 Fixed typo in bootstrap.conf for 17th argument

---

nifi-docs/src/main/asciidoc/toolkit-guide.adoc
nifi-toolkit/nifi-toolkit-cli/src/main/java/org/apache/nifi/toolkit/cli/impl/client/NiFiClientFactory.java
nifi-toolkit/nifi-toolkit-cli/src/main/java/org/apache/nifi/toolkit/cli/impl/client/NiFiRegistryClientFactory.java
nifi-toolkit/nifi-toolkit-cli/src/main/java/org/apache/nifi/toolkit/cli/impl/command/CommandOption.java
nifi-toolkit/nifi-toolkit-cli/src/main/java/org/apache/nifi/toolkit/cli/impl/command/registry/NiFiRegistryCommandGroup.java
nifi-toolkit/nifi-toolkit-cli/src/main/java/org/apache/nifi/toolkit/cli/impl/command/registry/bucket/UpdateBucketPolicy.java
nifi-toolkit/nifi-toolkit-cli/src/test/java/org/apache/nifi/toolkit/cli/impl/command/registry/RegistryManualIT.java

https://issues.apache.org/jira/projects/NIFI/issues/NIFI-7681
Apart from the description present in the JIRA ticket, a few other miscellaneous changes have also been made:-
- Both `NiFiClient` and `NiFiRegistryClient` have configs to specify `readTimeout` and `connectionTimeout` parameters, however there was no way to specify those parameters in toolkit. I have added a couple of flags, `-rto` and `-cto` to specify the read and connection timeouts respectively. They can also be specified in the properties file by their longnames `readTimeout` and `connectionTimeout`.
- Toolkit documentation had a few commands missing, so I updated it to reflect all previously implemented commands
In …

NIFI-7681 - Add update-bucket-policy command, add option to specify timeout and fix documentation to include previously implemented commands

---

nifi-commons/nifi-data-provenance-utils/pom.xml
nifi-commons/nifi-security-utils/pom.xml
nifi-nar-bundles/nifi-druid-bundle/nifi-druid-controller-service-api/pom.xml
nifi-nar-bundles/nifi-framework-bundle/pom.xml
nifi-nar-bundles/nifi-provenance-repository-bundle/pom.xml
nifi-nar-bundles/nifi-standard-bundle/pom.xml
nifi-toolkit/nifi-toolkit-tls/pom.xml

_Upgraded BouncyCastle version._

NIFI-7723 Upgraded BouncyCastle version to 1.66.

---

nifi-nar-bundles/nifi-framework-bundle/nifi-framework/nifi-framework-cluster/src/main/java/org/apache/nifi/cluster/coordination/http/replication/ThreadPoolRequestReplicator.java

https://issues.apache.org/jira/browse/NIFI-7722
Catching 'Throwable' instead of 'Exception' in 'NodeHttpRequest.run()' to make sure subsequent 'Object.notify()' (when request replication has completed) is not missed out even if an 'Error' is thrown.

NIFI-7722 Enhance error-handling during request replication

---

nifi-nar-bundles/nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-api/src/main/java/org/apache/nifi/web/api/ProcessGroupResource.java

Fix: Empty All Queues performance - When authorizing request, checking read/write credentials on encapsulated process groups and connections was doubly recursive (for each element it added all child elements multiple times again, making this exponential instead of linear).

NIFI-7736 Duplicated permission checks in Empty All Queues

---

nifi-nar-bundles/nifi-framework-bundle/nifi-framework/nifi-framework-core-api/src/main/java/org/apache/nifi/connectable/Port.java
nifi-nar-bundles/nifi-framework-bundle/nifi-framework/nifi-framework-core-api/src/main/java/org/apache/nifi/controller/AbstractPort.java
nifi-nar-bundles/nifi-framework-bundle/nifi-framework/nifi-framework-core/src/main/java/org/apache/nifi/controller/StandardFlowSnippet.java
nifi-nar-bundles/nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-api/src/main/java/org/apache/nifi/web/util/SnippetUtils.java

fixes bug NIFI-7762: Disabled state of Ports is lost when copy-pasted or instanciated from a template

NIFI-7762: Disabled state of Ports is lost when copy-pasted or instanciated from a template

---

nifi-docs/src/main/asciidoc/expression-language-guide.adoc

_Add a missing # at the end of descriptions of padLeft, padRight and plus._

NIFI-7778: Made corrections in descriptions of padLeft, padRight, plus

---

nifi-nar-bundles/nifi-extension-utils/nifi-kerberos-test-utils/pom.xml
nifi-nar-bundles/nifi-extension-utils/nifi-kerberos-test-utils/src/main/java/org/apache/nifi/kerberos/MockKerberosCredentialsService.java
nifi-nar-bundles/nifi-hive-bundle/nifi-hive3-processors/pom.xml
nifi-nar-bundles/nifi-hive-bundle/nifi-hive3-processors/src/test/java/org/apache/nifi/processors/hive/TestPutHive3Streaming.java
nifi-nar-bundles/nifi-standard-services/nifi-dbcp-service-bundle/nifi-dbcp-service/pom.xml
nifi-nar-bundles/nifi-standard-services/nifi-dbcp-service-bundle/nifi-dbcp-service/src/main/java/org/apache/nifi/dbcp/DBCPConnectionPool.java
nifi-nar-bundles/nifi-standard-services/nifi-dbcp-service-bundle/nifi-dbcp-service/src/test/java/org/apache/nifi/dbcp/DBCPServiceTest.java

When using Kerberos and a load balancer to connect to a database, it is possible for DBCPConnectionPool to return a connection to the load balancer but logged in with the wrong ticket for the target database (this happens in High Availability scenarios). This PR tries to relogin to Kerberos if an exception occurs during connect.

NIFI-7799: Relogin with Kerberos on connect exception in DBCPConnectionPool

---

nifi-docs/src/main/asciidoc/walkthroughs.adoc

NIFI-7841: Correction in nifi walkthough docs: securing a cluster using nifi-tls-toolkit

---

nifi-nar-bundles/nifi-aws-bundle/nifi-aws-processors/src/main/java/org/apache/nifi/processors/aws/s3/PutS3Object.java
nifi-nar-bundles/nifi-aws-bundle/nifi-aws-processors/src/test/java/org/apache/nifi/processors/aws/s3/TestPutS3Object.java

NIFI-7827 - PutS3Object - configuration of the multipart temp dir

---

nifi-bootstrap/src/main/java/org/apache/nifi/bootstrap/RunNiFi.java

There's a missing `break` statement when the `diagnostics` command is run

NIFI-7867: Add break statement to prevent diagnostics from running env afterward

---

nifi-api/src/main/java/org/apache/nifi/reporting/EventAccess.java
nifi-mock/src/main/java/org/apache/nifi/util/MockEventAccess.java
nifi-nar-bundles/nifi-extension-utils/nifi-prometheus-utils/src/main/java/org/apache/nifi/prometheus/util/NiFiMetricsRegistry.java
nifi-nar-bundles/nifi-extension-utils/nifi-prometheus-utils/src/main/java/org/apache/nifi/prometheus/util/PrometheusMetricsUtil.java
nifi-nar-bundles/nifi-framework-bundle/nifi-framework/nifi-framework-core-api/src/main/java/org/apache/nifi/controller/repository/FlowFileEventRepository.java
nifi-nar-bundles/nifi-framework-bundle/nifi-framework/nifi-framework-core/src/main/java/org/apache/nifi/controller/FlowController.java
nifi-nar-bundles/nifi-framework-bundle/nifi-framework/nifi-framework-core/src/main/java/org/apache/nifi/controller/repository/metrics/RingBufferEventRepository.java
nifi-nar-bundles/nifi-framework-bundle/nifi-framework/nifi-framework-core/src/main/java/org/apache/nifi/reporting/StandardEventAccess.java
nifi-nar-bundles/nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-api/src/main/java/org/apache/nifi/web/StandardNiFiServiceFacade.java
nifi-nar-bundles/nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-api/src/main/java/org/apache/nifi/web/controller/ControllerFacade.java
nifi-nar-bundles/nifi-prometheus-bundle/nifi-prometheus-reporting-task/src/main/java/org/apache/nifi/reporting/prometheus/PrometheusReportingTask.java

In addition to the existing gauges for bytes sent/received, it would also be helpful to have incrementing counters to see total bytes sent/received, this PR adds those counters and populates them for the appropriate component types (ports, e.g.) I tested on a live cluster with a Prometheus instance hitting the metrics REST endpoint.

NIFI-7796: Add Prometheus counters for total bytes sent/received

---

nifi-nar-bundles/nifi-hadoop-libraries-bundle/nifi-hadoop-libraries-nar/pom.xml
nifi-nar-bundles/nifi-hive-bundle/nifi-hive3-nar/pom.xml
nifi-nar-bundles/nifi-ranger-bundle/nifi-ranger-plugin/pom.xml
pom.xml

NIFI-7869 - adding a GCP profile for GCS connector

---

nifi-commons/nifi-record/src/main/java/org/apache/nifi/serialization/record/util/DataTypeUtils.java
nifi-commons/nifi-record/src/test/java/org/apache/nifi/serialization/record/TestDataTypeUtils.java

In isArrayTypeCompatible() we just check to see if the object is an Object[] instead of verifying that each element is of the specified type. This PR runs through the objects in the array to make sure they are each compatible with the specified element type.

NIFI-7637: Ensure all array elements are compatible in DataTypeUtils.isArrayTypeCompatible()

---

nifi-nar-bundles/nifi-standard-bundle/nifi-standard-processors/src/main/java/org/apache/nifi/processors/standard/HandleHttpResponse.java
nifi-nar-bundles/nifi-standard-bundle/nifi-standard-processors/src/test/java/org/apache/nifi/processors/standard/TestHandleHttpResponse.java

NIFI-7967: Added regex support for attribute header selection on HandleHTTPResponse

---

nifi-nar-bundles/nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-security/src/main/java/org/apache/nifi/web/security/ProxiedEntitiesUtils.java
nifi-nar-bundles/nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-security/src/test/groovy/org/apache/nifi/web/security/ProxiedEntitiesUtilsTest.groovy

- Adds detection and encoding of non-ascii characters to creation of chain
- Adds unit tests that use proxied entities with Unicode
---
Relates to: 
- [NIFI-7744](https://issues.apache.org/jira/browse/NIFI-7744) 
- [NIFIREG-415](https://issues.apache.org/jira/browse/NIFIREG-415), apache/nifi-registry#302
---

NIFI-7744 Add Support for Unicode in X-ProxiedEntitiesChain

---

nifi-nar-bundles/nifi-framework-bundle/nifi-framework/nifi-framework-core/src/test/java/org/apache/nifi/controller/state/providers/zookeeper/ITZooKeeperStateProvider.java
nifi-nar-bundles/nifi-framework-bundle/nifi-framework/nifi-framework-core/src/test/java/org/apache/nifi/leader/election/ITSecureClientZooKeeperFactory.java

NIFI-8064 Convert TestSecureClientZooKeeperFactory to integration test

---

nifi-commons/nifi-record-path/src/main/java/org/apache/nifi/record/path/functions/Coalesce.java
nifi-commons/nifi-record-path/src/main/java/org/apache/nifi/record/path/paths/RecordPathCompiler.java
nifi-commons/nifi-record-path/src/test/java/org/apache/nifi/record/path/TestRecordPath.java
nifi-docs/src/main/asciidoc/record-path-guide.adoc

NIFI-8070: Added coalesce function to RecordPath

---

nifi-nar-bundles/nifi-grpc-bundle/nifi-grpc-processors/pom.xml
nifi-nar-bundles/nifi-grpc-bundle/nifi-grpc-processors/src/main/java/org/apache/nifi/processors/grpc/InvokeGRPC.java
nifi-nar-bundles/nifi-grpc-bundle/nifi-grpc-processors/src/test/java/org/apache/nifi/processors/grpc/TestGRPCClient.java
nifi-nar-bundles/nifi-grpc-bundle/pom.xml

https://issues.apache.org/jira/browse/NIFI-8066

NIFI-8066: Bump GRPC dependency versions

---

nifi-nar-bundles/nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-ui/src/main/webapp/js/jquery/tabbs/jquery.tabbs.css
nifi-nar-bundles/nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-ui/src/main/webapp/js/jquery/tabbs/jquery.tabbs.js

This PR adds keyboard functionality to the custom tabbs jquery plugin.
Build NiFi locally, open the UI and locate anywhere that uses tabs (for example, inside the Global Menu's Summary window). Click on a tab. Navigate to the next tab by pressing the Tab key. Navigate back to the previous tab with Shift + Tab. Select a tab by focusing on it and pressing Enter or Space. You'll notice focus styles have been added.
Please ensure that once the PR is submitted, you check GitHub Actions CI for build issues and submit an update to your PR as soon as …

NIFI-8062: make tabs functional with keyboard

---

nifi-nar-bundles/nifi-standard-bundle/nifi-standard-processors/src/main/java/org/apache/nifi/processors/standard/MonitorActivity.java

When using MonitorActivity, it would be interesting to use variables in "Threshold Duration", which will help maintain Version Control in ProcessGroups (Avoiding "breaking" versions when including the value manually). 
I've included the option expressionLanguageSupported(ExpressionLanguageScope.VARIABLE_REGISTRY), so we can use variables in "Threshold Duration".
Jira Ticket: https://issues.apache.org/jira/browse/NIFI-7932
Please ensure that once the PR is submitted, you check GitHub Actions CI for build issues and submit an update to your PR as soon …

NIFI-7932 Allow MonitorActivity's "Threshold Duration" property to use variables

---

nifi-nar-bundles/nifi-kudu-bundle/nifi-kudu-processors/pom.xml
nifi-nar-bundles/nifi-kudu-bundle/nifi-kudu-processors/src/main/java/org/apache/nifi/processors/kudu/AbstractKuduProcessor.java
nifi-nar-bundles/nifi-kudu-bundle/nifi-kudu-processors/src/main/java/org/apache/nifi/processors/kudu/OperationType.java
nifi-nar-bundles/nifi-kudu-bundle/nifi-kudu-processors/src/main/java/org/apache/nifi/processors/kudu/PutKudu.java
nifi-nar-bundles/nifi-kudu-bundle/nifi-kudu-processors/src/test/java/org/apache/nifi/processors/kudu/ITPutKudu.java
nifi-nar-bundles/nifi-kudu-bundle/nifi-kudu-processors/src/test/java/org/apache/nifi/processors/kudu/MockPutKudu.java

NIFI-7987: Support ignore operations in the PutKudu processor

---

nifi-nar-bundles/nifi-framework-bundle/pom.xml

NIFI-8186 Updates the `spring-security-saml2-core` dependency management definition to exclude the bcprov-ext-jdk15on library.  The `spring-security-saml2-core` depends on `com.narupley:not-going-to-be-commons-ssl` that in turn depends on `bcprov-ext-jdk15on` version 1.60.  The current version of NiFi depends on the standard `bcprov-jdk15on` library version 1.68 so inclusion of the different version of the extension library could cause unexpected problems at runtime.  The Spring Security SAML2 library does not appear to needed the obscure algorithm classes included in the `bcprov-ext-jdk15on` library, so the library should be excluded from bundled dependencies.
in the commit …

NIFI-8186 Excluded bcprov-ext-jdk15on from spring-security-saml2-core

---

nifi-nar-bundles/nifi-accumulo-bundle/nifi-accumulo-processors/src/main/java/org/apache/nifi/accumulo/processors/PutAccumuloRecord.java

_Enables X functionality; fixes bug NIFI-8235_

NIFI-8235 UnsupportedOpertationException in PutAccumuloRecord

---

nifi-nar-bundles/nifi-standard-bundle/nifi-standard-processors/src/main/java/org/apache/nifi/processors/standard/AbstractExecuteSQL.java
nifi-nar-bundles/nifi-standard-bundle/nifi-standard-processors/src/test/java/org/apache/nifi/processors/standard/TestExecuteSQLRecord.java

If successful ResultSets were written to FlowFiles, they didn't get removed from the session if an error occurs in subsequent ResultSets.

NIFI-8249: Fixed issue with error during multiple FlowFile results in ExecuteSQL processors

---

nifi-nar-bundles/nifi-standard-bundle/nifi-standard-processors/src/test/java/org/apache/nifi/processors/standard/TestQueryRecord.java
nifi-nar-bundles/nifi-standard-services/nifi-record-serialization-services-bundle/nifi-record-serialization-services/src/main/java/org/apache/nifi/csv/CSVRecordSource.java
nifi-nar-bundles/nifi-standard-services/nifi-record-serialization-services-bundle/nifi-record-serialization-services/src/main/java/org/apache/nifi/csv/CSVSchemaInference.java

CSVSchemaInference was returning an empty schema if there is a header line but no records in the FlowFile. This uses the header field names and infers a nullable string type for each.

NIFI-8259: Infer CSV field types as strings if no records are present

---

nifi-assembly/NOTICE

https://issues.apache.org/jira/browse/NIFI-8284

NIFI-8284: Removed diff merge leftover from the assembly NOTICE file

---

nifi-nar-bundles/nifi-extension-utils/nifi-hadoop-utils/src/main/java/org/apache/nifi/hadoop/SecurityUtil.java

https://issues.apache.org/jira/browse/NIFI-8285

NIFI-8285 Prevent HBase client services to throw NPE in non-kerberized environment.

---

nifi-nar-bundles/nifi-standard-services/nifi-hwx-schema-registry-bundle/nifi-hwx-schema-registry-service/src/main/java/org/apache/nifi/schemaregistry/hortonworks/HortonworksSchemaRegistry.java

NIFI-8267 - Fix for HWX Schema Registry to use integers

---

nifi-commons/nifi-site-to-site-client/pom.xml
pom.xml

NIFI-8309 updating to latest Jetty

---

nifi-commons/nifi-properties/src/main/java/org/apache/nifi/util/NiFiProperties.java
nifi-nar-bundles/nifi-framework-bundle/nifi-framework/nifi-framework-core/src/main/java/org/apache/nifi/components/monitor/LongRunningTaskMonitor.java
nifi-nar-bundles/nifi-framework-bundle/nifi-framework/nifi-framework-core/src/main/java/org/apache/nifi/controller/FlowController.java
nifi-nar-bundles/nifi-framework-bundle/nifi-framework/nifi-resources/pom.xml
nifi-nar-bundles/nifi-framework-bundle/nifi-framework/nifi-resources/src/main/resources/conf/nifi.properties

https://issues.apache.org/jira/browse/NIFI-8314

NIFI-8314: Generate warning for long-running processor tasks

---

nifi-commons/nifi-web-utils/pom.xml
nifi-nar-bundles/nifi-confluent-platform-bundle/nifi-confluent-schema-registry-service/pom.xml
nifi-nar-bundles/nifi-framework-bundle/pom.xml
nifi-nar-bundles/nifi-jolt-record-bundle/pom.xml
nifi-nar-bundles/nifi-language-translation-bundle/nifi-yandex-processors/pom.xml
nifi-nar-bundles/nifi-standard-bundle/pom.xml
nifi-nar-bundles/nifi-update-attribute-bundle/nifi-update-attribute-ui/pom.xml
nifi-toolkit/nifi-toolkit-tls/pom.xml
pom.xml

Unit tests were not added as the issue being resolved is related to user interaction with the User Interface, specifically the Advanced UI of UpdateAttribute. The Advanced UI was confirmed to display properly after being built with both Java 8 and more importantly Java 11. Behavior was confirmed when this commit was applied to main was well as support/nifi-1.13.

NIFI-8348: upgrade jersey version to one fully compatible with Java 11

---

nifi-mock/src/main/java/org/apache/nifi/util/CapturingLogger.java

Fixed the issue that the lists storing the log messages in org.apache.nifi.util.CapturingLogger
weren't thread safe.

NIFI-8655 Intermittent test failures in TestUnpackContent#testThreadSafetyUsingAutoDetect

---

nifi-commons/nifi-record-path/src/main/java/org/apache/nifi/record/path/functions/EscapeJson.java
nifi-commons/nifi-record-path/src/main/java/org/apache/nifi/record/path/functions/UnescapeJson.java
nifi-commons/nifi-record-path/src/main/java/org/apache/nifi/record/path/paths/RecordPathCompiler.java
nifi-commons/nifi-record-path/src/test/java/org/apache/nifi/record/path/TestRecordPath.java
nifi-docs/src/main/asciidoc/record-path-guide.adoc

Renamed RecordPath un/escape JSON functions

NIFI-8137 Rename RecordPath un/escape JSON functions

---

nifi-nar-bundles/nifi-extension-utils/nifi-hadoop-utils/src/main/java/org/apache/nifi/processors/hadoop/AbstractPutHDFS.java
nifi-nar-bundles/nifi-hadoop-bundle/nifi-hdfs-processors/src/main/java/org/apache/nifi/processors/hadoop/PutHDFS.java

[NIFI-8717](https://issues.apache.org/jira/browse/NIFI-8717)
This is a small proposal in order to decouple NiFi related and HDFS related logic. This will make the implementation more flexible in the long run.

NIFI-8717 Refactoring PutHDFS

---

nifi-nar-bundles/nifi-single-user-iaa-providers-bundle/nifi-single-user-iaa-providers/src/main/java/org/apache/nifi/authorization/single/user/SingleUserAuthorizer.java
nifi-nar-bundles/nifi-single-user-iaa-providers-bundle/nifi-single-user-iaa-providers/src/test/java/org/apache/nifi/authorization/single/user/SingleUserAuthorizerTest.java

NIFI-8783 Moves the check for `SingleUserLoginIdentityProvider` from `setProperties()` to `initialize()` in `SingleUserAuthorizer`. This approach allows the `SingleUserAuthorizer` definition to exist in `authorizers.xml` but continues to prevent it from being used without the `SingleUserLoginIdentityProvider` being configured as the selected Login Identity Provider.

NIFI-8783 Moved SingleUserAuthorizer Login Provider check

---

nifi-stateless/nifi-stateless-assembly/src/main/assembly/common.xml
nifi-system-tests/nifi-stateless-system-test-suite/pom.xml
nifi-system-tests/nifi-stateless-system-test-suite/src/test/assembly/dependencies.xml

NIFI-9059 Updates the NiFi Stateless assembly and associated system test module to include the dependencies required for running on Java 11. The Stateless configuration expects these dependencies to exist under a directory named `java11`, but the current assembly and system test modules do not include the required dependencies.

NIFI-9059 Add Java 11 dependencies to Stateless Assembly

---

.github/workflows/system-tests.yml
README.md
nifi-system-tests/nifi-system-test-suite/src/test/java/org/apache/nifi/tests/system/provenance/ProvenanceRepositoryIT.java
nifi-system-tests/nifi-system-test-suite/src/test/resources/conf/clustered/node1/bootstrap.conf
nifi-system-tests/nifi-system-test-suite/src/test/resources/conf/clustered/node2/bootstrap.conf
nifi-system-tests/nifi-system-test-suite/src/test/resources/conf/default/bootstrap.conf

NIFI-9040 Adds a GitHub Workflow to run integration tests in the `nifi-system-test-suite` module on a daily schedule. The workflow configuration runs on Ubuntu Java 11 and MacOS Java 8. The current integration tests fail on Windows, so separate work is necessary to evaluate potential changes for the Windows platform.
Running the integration tests on a daily basis using the default `main` branch provides additional automated verification without burdening the existing pull request workflow.
In order to optimize the job and avoid running unnecessary tests, the workflow runs two Maven commands. The first command builds the modules required for `nifi-system-test-suite`:
`mvn -V -nsu -ntp -ff install -D skipTests -am -pl nifi-system-tests/nifi-system-test-suite`
The second command runs the …

NIFI-9040 Add GitHub Workflow for System Tests

---

nifi-nar-bundles/nifi-framework-bundle/nifi-framework/nifi-resources/src/main/resources/conf/logback.xml

https://issues.apache.org/jira/browse/NIFI-9079

NIFI-9079: Set log level to WARN for Apache Atlas client logs

---

nifi-nar-bundles/nifi-accumulo-bundle/nifi-accumulo-processors/pom.xml
nifi-nar-bundles/nifi-accumulo-bundle/nifi-accumulo-services-api/pom.xml
nifi-nar-bundles/nifi-accumulo-bundle/nifi-accumulo-services/pom.xml
nifi-nar-bundles/nifi-accumulo-bundle/pom.xml

NIFI-9204 Excludes `spotbugs-annotations` from `accumulo-core` in all Accumulo NAR bundles due to LGPL licensing.

NIFI-9204 Exclude spotbugs-annotations from accumulo-core

---

nifi-nar-bundles/nifi-aws-bundle/nifi-aws-processors/src/main/java/org/apache/nifi/processors/aws/s3/FetchS3Object.java

This fixes a bug in FetchS3Object preventing reading zero byte objects. S3 uses the HTTP Range header for specifying byte ranges. Zero length content doesn't have a satisfiable byte range so we shouldn't call GetObjectRequest#setRange(0) unnecessarily when neither Range Start nor Range Length are given.

NIFI-9055 Added handling for 0- read range to FetchS3Object

---

nifi-nar-bundles/nifi-framework-bundle/nifi-framework/nifi-framework-core/src/main/java/org/apache/nifi/controller/leader/election/CuratorLeaderElectionManager.java

Prevent deadlock caused by interaction between LeaderElectionManager and ElectionListener synchronized methods on node disconnect.

NIFI-9217 - avoid deadlock on cluster operation

---

nifi-nar-bundles/nifi-standard-bundle/nifi-standard-processors/src/main/java/org/apache/nifi/processors/standard/servlets/ListenHTTPServlet.java

https://issues.apache.org/jira/browse/NIFI-9255

NIFI-9255: Support asynchronous session commits in ListenHTTP

---

nifi-nar-bundles/nifi-framework-bundle/nifi-framework/nifi-framework-components/src/main/java/org/apache/nifi/groups/StandardProcessGroup.java
nifi-nar-bundles/nifi-framework-bundle/nifi-framework/nifi-framework-core/src/test/java/org/apache/nifi/integration/versioned/ImportFlowIT.java

https://issues.apache.org/jira/browse/NIFI-9229
Fixing bug NIFI-9229

NIFI-9229 Flow upgrade not possible if a Output Port changes to a funnel

---

nifi-nar-bundles/nifi-standard-bundle/nifi-standard-processors/src/main/java/org/apache/nifi/processors/standard/InvokeHTTP.java
nifi-nar-bundles/nifi-standard-bundle/nifi-standard-processors/src/test/java/org/apache/nifi/processors/standard/InvokeHTTPTest.java

NIFI-9349 - add attribute with request duration in InvokeHTTP

---

nifi-nar-bundles/nifi-framework-bundle/nifi-framework/nifi-framework-core-api/src/main/java/org/apache/nifi/cluster/exception/NoClusterCoordinatorException.java

optimize import.

---

nifi-nar-bundles/nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-ui/src/main/webapp/WEB-INF/partials/canvas/connection-configuration.jsp
nifi-nar-bundles/nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-ui/src/main/webapp/css/connection-configuration.css
nifi-nar-bundles/nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-ui/src/main/webapp/js/nf/canvas/nf-connection-configuration.js
nifi-nar-bundles/nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-ui/src/main/webapp/js/nf/canvas/nf-parameter-contexts.js

This PR updates the prioritizers configuration on the UI. To test in the UI, create a flow and open the connections configurations. In the settings tab, try the following:
- select a prioritizer by double clicking a prioritizer from the available list
- remove a selected prioritizer, by clicking the "x" icon
- the available prioritizers list is now an ordered list and the order cannot be rearranged

NIFI-9205 - Update prioritizer configuration

---

nifi-nar-bundles/nifi-framework-bundle/nifi-framework/nifi-framework-core/src/main/java/org/apache/nifi/diagnostics/bootstrap/tasks/FlowConfigurationDiagnosticTask.java

NIFI-9432 - fix typo in diagnostic output

---

nifi-docs/src/main/asciidoc/administration-guide.adoc

NIFI-9409 Updates the NiFi Administrator's Guide to correct broken links for OpenSSL EVP BytesToKey and PBKDF2. The EVP BytesToKey link points to the updated manual documentation, and the PBKDF2 link now points to Wikipedia instead of OpenSSL.

NIFI-9409 Update links for EVP BytesToKey and PBKDF2

---

nifi-nar-bundles/nifi-framework-bundle/nifi-framework/nifi-framework-core/src/main/java/org/apache/nifi/persistence/StandardFlowConfigurationDAO.java

https://issues.apache.org/jira/browse/NIFI-9454

NIFI-9454: Moved file renaming after closing the OutputStream

---

nifi-nar-bundles/nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-ui/src/main/webapp/css/main.css
nifi-nar-bundles/nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-ui/src/main/webapp/js/jquery/propertytable/jquery.propertytable.js
nifi-nar-bundles/nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-ui/src/main/webapp/js/nf/canvas/nf-parameter-contexts.js
nifi-nar-bundles/nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-ui/src/main/webapp/js/nf/nf-common.js

_NIFI-9423 - Show icon and tooltip for Parameter values that have leading and/or trailing whitespaces_
_NIFI-9429 - Parameters should allow blank values that are non-null (only whitespace)_

[NIFI-9423-NIFI-9429]: Show icon and tooltip for Parameters with leading and/or trailing whitespace

---

nifi-nar-bundles/nifi-framework-bundle/nifi-framework/nifi-framework-components/src/main/java/org/apache/nifi/parameter/StandardParameterContext.java
nifi-nar-bundles/nifi-framework-bundle/nifi-framework/nifi-framework-components/src/test/java/org/apache/nifi/parameter/TestStandardParameterContext.java

This fixes a bug that prevented parameter descriptions from being updated, if that was the only change.

NIFI-9461: Allowing Parameter descriptions to be changed

---

nifi-registry/nifi-registry-core/nifi-registry-web-ui/src/main/.gitignore
nifi-registry/nifi-registry-core/nifi-registry-web-ui/src/main/webapp/components/explorer/grid-list/registry/nf-registry-bucket-grid-list-viewer.js
nifi-registry/nifi-registry-core/nifi-registry-web-ui/src/main/webapp/components/explorer/grid-list/registry/nf-registry-droplet-grid-list-viewer.js
nifi-registry/nifi-registry-core/nifi-registry-web-ui/src/main/webapp/components/explorer/grid-list/registry/nf-registry-grid-list-viewer.html
nifi-registry/nifi-registry-core/nifi-registry-web-ui/src/main/webapp/components/explorer/grid-list/registry/nf-registry-grid-list-viewer.js

Fixes an issue in NiFi Registry: When choosing a sort option from the dropdown, the resulting sorted items in the list were expanded.

NIFI-8821 Registry - Sorting the grid-list no longer expands the listed buckets

---

nifi-framework-api/src/main/java/org/apache/nifi/controller/repository/ContentRepository.java
nifi-framework-api/src/main/java/org/apache/nifi/controller/repository/ContentRepositoryContext.java
nifi-nar-bundles/nifi-framework-bundle/nifi-framework/nifi-framework-core/src/main/java/org/apache/nifi/controller/FlowController.java
nifi-nar-bundles/nifi-framework-bundle/nifi-framework/nifi-framework-core/src/main/java/org/apache/nifi/controller/repository/FileSystemRepository.java
nifi-nar-bundles/nifi-framework-bundle/nifi-framework/nifi-framework-core/src/main/java/org/apache/nifi/controller/repository/StandardContentRepositoryContext.java
nifi-nar-bundles/nifi-framework-bundle/nifi-framework/nifi-framework-core/src/main/java/org/apache/nifi/controller/repository/VolatileContentRepository.java
nifi-nar-bundles/nifi-framework-bundle/nifi-framework/nifi-framework-core/src/test/groovy/org/apache/nifi/controller/repository/crypto/EncryptedFileSystemRepositoryTest.groovy
nifi-nar-bundles/nifi-framework-bundle/nifi-framework/nifi-framework-core/src/test/java/org/apache/nifi/controller/repository/StandardProcessSessionIT.java
nifi-nar-bundles/nifi-framework-bundle/nifi-framework/nifi-framework-core/src/test/java/org/apache/nifi/controller/repository/TestFileSystemRepository.java
nifi-nar-bundles/nifi-framework-bundle/nifi-framework/nifi-framework-core/src/test/java/org/apache/nifi/controller/repository/TestVolatileContentRepository.java
nifi-nar-bundles/nifi-framework-bundle/nifi-framework/nifi-framework-core/src/test/java/org/apache/nifi/controller/repository/claim/TestContentClaimWriteCache.java
nifi-stateless/nifi-stateless-bundle/nifi-stateless-engine/src/main/java/org/apache/nifi/stateless/flow/StandardStatelessDataflowFactory.java
nifi-stateless/nifi-stateless-bundle/nifi-stateless-engine/src/main/java/org/apache/nifi/stateless/repository/ByteArrayContentRepository.java
nifi-stateless/nifi-stateless-bundle/nifi-stateless-engine/src/main/java/org/apache/nifi/stateless/repository/StatelessFileSystemContentRepository.java
nifi-stateless/nifi-stateless-bundle/nifi-stateless-engine/src/test/java/org/apache/nifi/stateless/repository/TestStatelessFileSystemContentRepository.java

https://issues.apache.org/jira/browse/NIFI-9434

NIFI-9434: Added bulletin to alert FileSystemRepository backpressure

---

nifi-nar-bundles/nifi-gcp-bundle/nifi-gcp-processors/pom.xml

NIFI-9530 Removes `google-cloud-pubsublite` from `nifi-gcp-processors` for the NiFi 1.15 support branch in order to avoid runtime class conflicts.
This version of `google-cloud-pubsublite` requires different versions of the Google GRPC libraries that conflict with the versions of GRPC from `google-cloud-pubsub`. This is working as expected in the main branch as a result of other changes in NIFI-9304, so this adjustment is limited to the 1.15 support branch.

NIFI-9530 Removed google-cloud-pubsublite from GCP

---

nifi-nar-bundles/nifi-standard-bundle/nifi-standard-reporting-tasks/src/main/java/org/apache/nifi/controller/ControllerStatusReportingTask.java

NIFI-9222 fix NullPointerException in ControllerStatusReportingTask when there are no Counters present on Processors.
- ~[ ] If adding new dependencies to the code, are these dependencies licensed in a way that is compatible for inclusion under [ASF 2.0](http://www.apache.org/legal/resolved.html#category-a)?~
- ~[ ] If applicable, have you updated the `LICENSE` file, including the main `LICENSE` file under `nifi-assembly`?~
- ~[ ] If applicable, have you updated the `NOTICE` file, including the main `NOTICE` file found under `nifi-assembly`?~
- ~[ ] …

NIFI-9222 allow ControllerStatusReportingTask to log details even when there are no Counters present on Processors

---

nifi-nar-bundles/nifi-standard-bundle/nifi-standard-processors/src/main/java/org/apache/nifi/processors/standard/DistributeLoad.java
nifi-nar-bundles/nifi-standard-bundle/nifi-standard-processors/src/test/java/org/apache/nifi/processors/standard/TestDistributeLoad.java

Adds an 'overflow' strategy to the DistributeLoad processor. In this strategy, flowfiles are sent to the highest weighted and available relationship. Unlike 'next available', flowfiles are not distributed among all available relationships; they are sent to only one unless/until that relationship becomes unavailable. Then, it chooses the next highest weighted relationship which is available.
Please ensure that once the PR is submitted, you check GitHub Actions CI for build issues and submit an update to …

NIFI-8962: Add overflow strategy to DistributeLoad

---

nifi-nar-bundles/nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-ui/src/main/webapp/WEB-INF/partials/users/user-delete-dialog.jsp
nifi-nar-bundles/nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-ui/src/main/webapp/css/common-ui.css
nifi-nar-bundles/nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-ui/src/main/webapp/js/nf/users/nf-users-table.js

- ids of the entities are prefixed by their types to avoid id conflict in 3rd party table library
For some authorizers the UUID calculation for users and groups based only on the name of the entity and a global seed.
This results the same UUID for a group and a user with the same name. The same ids are no longer causing any issue on the UI.
- group icon alignment is fixed for edit user dialog

NIFI-9578 NiFi user list no longer breaks if a user and group have the same id

---

nifi-nar-bundles/nifi-framework-bundle/nifi-framework/nifi-framework-core/src/main/java/org/apache/nifi/controller/StandardFlowService.java

Avoid deadlock on process shutdown during system test invocation. This `SaveReportingTask` lock usage contends with lock in `StandardFlowService.stop()` (which releases after gracefulShutdownSeconds).

NIFI-9233 - Improve reliability of system integration tests

---

pom.xml

NIFI-9652 Upgrades `jetty-schemas` from 3.1 to 5.2.  Version 5.2 includes the same schemas as version 3.1, plus additional schemas for newer versions of various specifications.  Version 5.2 requires a minimum of Java 8, which aligns with current NiFi requirements.

NIFI-9652 Upgrade jetty-schemas from 3.1 to 5.2

---

nifi-nar-bundles/nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-ui/src/main/webapp/js/nf/canvas/nf-actions.js

When starting/stopping selected process group, it sends the parent process group id to the REST interface that is responsible to enable/disable transmission for all remote process groups within a process group.
This fix makes the UI to send the id of the select process group instead.

NIFI-9684 FIx: Starting a PG starts RPGs in sibling PGs as well

---

nifi-nar-bundles/nifi-standard-bundle/nifi-standard-processors/src/test/java/org/apache/nifi/processors/standard/TestRouteText.java

NIFI-9736 Improves `TestRouteText.testPatternCache` to avoid intermittent failures due to maximum cache size checking. Changes from Guava to Caffeine altered the cache eviction behavior, resulting in intermittent failures.  The current method fills up the cache, which is an expensive operation for testing. The updated method avoids filling up the cache and simplifies the test method.

NIFI-9736 Improve TestRouteText to avoid intermittent failures

---

nifi-nar-bundles/nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-ui/src/main/webapp/WEB-INF/partials/canvas/processor-configuration.jsp
nifi-nar-bundles/nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-ui/src/main/webapp/WEB-INF/partials/processor-details.jsp
nifi-nar-bundles/nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-ui/src/main/webapp/css/common-ui.css
nifi-nar-bundles/nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-ui/src/main/webapp/css/processor-configuration.css
nifi-nar-bundles/nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-ui/src/main/webapp/css/processor-details.css
nifi-nar-bundles/nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-ui/src/main/webapp/js/nf/canvas/nf-processor-configuration.js
nifi-nar-bundles/nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-ui/src/main/webapp/js/nf/nf-common.js
nifi-nar-bundles/nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-ui/src/main/webapp/js/nf/nf-processor-details.js

This is an initial pass at adding UI controls for the retry work done in [#5593](https://github.com/apache/nifi/pull/5593). This PR is based off of the work done on that branch, so please do not merge until #5593 has been merged. The initial proposal containing UI requirements can be found [here](https://cwiki.apache.org/confluence/display/NIFI/Framework-Level+Retries+to+Improve+Failure+Handling) 
Questions:
* I don't see an example of radio buttons used in NiFi's UI, but I used them for the Backoff Policy control since it made most sense (the value is either penalize flow file or yield entire processor from what I understand). I can switch these out for checkboxes that behave like …

NIFI-9580: UI work for framework-level retry in Processors

---

nifi-nar-bundles/nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-ui/src/main/webapp/css/graph.css
nifi-nar-bundles/nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-ui/src/main/webapp/js/nf/canvas/nf-connection.js

Displays a new icon on Connection Label to show when head of the queue is penalized

[NIFI-9690] Display icon on Connection Label to show when head of the queue is penalized

---

nifi-registry/nifi-registry-core/nifi-registry-web-ui/src/main/webapp/components/administration/users/dialogs/add-user/nf-registry-add-user.js
nifi-registry/nifi-registry-core/nifi-registry-web-ui/src/main/webapp/components/administration/users/dialogs/create-new-group/nf-registry-create-new-group.js
nifi-registry/nifi-registry-core/nifi-registry-web-ui/src/main/webapp/components/administration/workflow/dialogs/add-policy-to-bucket/nf-registry-add-policy-to-bucket.js
nifi-registry/nifi-registry-core/nifi-registry-web-ui/src/main/webapp/components/administration/workflow/dialogs/create-bucket/nf-registry-create-bucket.js
nifi-registry/nifi-registry-core/nifi-registry-web-ui/src/main/webapp/components/administration/workflow/dialogs/edit-bucket-policy/nf-registry-edit-bucket-policy.js
nifi-registry/nifi-registry-core/nifi-registry-web-ui/src/main/webapp/nf-registry.js

All ViewChild queries are decorated with `{ static: true }` which is needed because of new angular version.
None of these ViewChild under `*ng` directives so they are available during init with `static:true`.

[NIFI-9746] NiFi Registry Bucket Side Nav no longer fails to open

---

nifi-registry/nifi-registry-core/nifi-registry-framework/src/main/java/org/apache/nifi/registry/db/CustomFlywayConfiguration.java

Fix https://issues.apache.org/jira/browse/NIFI-9836 bug.

NIFI-9836: fix database selection during nifi registry startup

---

nifi-nar-bundles/nifi-framework-bundle/nifi-framework/nifi-framework-components/src/main/java/org/apache/nifi/groups/StandardProcessGroupSynchronizer.java
nifi-nar-bundles/nifi-framework-bundle/nifi-framework/nifi-framework-core/src/test/java/org/apache/nifi/integration/versioned/ImportFlowIT.java

https://issues.apache.org/jira/browse/NIFI-9875
In StandardProcessGroupSynchronizer.updateConnectionDestinations handle special case when output port is moved to a child process group while kept connected.

NIFI-9875 Fix: StandardProcessGroupSynchronizer mishandles output ports

---

nifi-nar-bundles/nifi-framework-bundle/nifi-framework/nifi-framework-cluster/src/main/java/org/apache/nifi/cluster/coordination/node/NodeClusterCoordinator.java

Alter order of steps executed when UI cluster node deletion is requested.  The node should be removed from the cluster state before any notifications are sent to the cluster participants.  This ensures that communications failures do not cause the operation to fail.

NIFI-9893 - Ensure orderly cluster node removal on node delete via UI

---

nifi-nar-bundles/nifi-framework-bundle/nifi-framework/nifi-framework-components/src/main/java/org/apache/nifi/flow/synchronization/StandardVersionedComponentSynchronizer.java
nifi-nar-bundles/nifi-framework-bundle/nifi-framework/nifi-framework-components/src/main/java/org/apache/nifi/parameter/StandardParameterReferenceManager.java
nifi-nar-bundles/nifi-framework-bundle/nifi-framework/nifi-framework-components/src/main/java/org/apache/nifi/registry/flow/mapping/NiFiRegistryFlowMapper.java
nifi-nar-bundles/nifi-framework-bundle/nifi-framework/nifi-framework-components/src/test/java/org/apache/nifi/parameter/TestStandardParameterContext.java
nifi-nar-bundles/nifi-framework-bundle/nifi-framework/nifi-framework-core-api/src/main/java/org/apache/nifi/controller/AbstractComponentNode.java
nifi-nar-bundles/nifi-framework-bundle/nifi-framework/nifi-framework-core-api/src/main/java/org/apache/nifi/parameter/ParameterReferenceManager.java
nifi-nar-bundles/nifi-framework-bundle/nifi-framework/nifi-framework-core-api/src/main/java/org/apache/nifi/parameter/ParameterReferencedControllerServiceData.java
nifi-nar-bundles/nifi-framework-bundle/nifi-framework/nifi-framework-core/src/test/java/org/apache/nifi/integration/versioned/ImportFlowIT.java
nifi-nar-bundles/nifi-framework-bundle/nifi-framework/nifi-framework-core/src/test/java/org/apache/nifi/registry/flow/mapping/NiFiRegistryFlowMapperTest.java
nifi-nar-bundles/nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-api/src/main/java/org/apache/nifi/authorization/AuthorizableLookup.java
nifi-nar-bundles/nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-api/src/main/java/org/apache/nifi/authorization/AuthorizeControllerServiceReference.java
nifi-nar-bundles/nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-api/src/main/java/org/apache/nifi/authorization/ComponentAuthorizable.java
nifi-nar-bundles/nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-api/src/main/java/org/apache/nifi/authorization/StandardAuthorizableLookup.java
nifi-nar-bundles/nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-api/src/main/java/org/apache/nifi/web/api/ParameterContextResource.java
nifi-nar-bundles/nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-ui/src/main/webapp/js/jquery/propertytable/jquery.propertytable.js

https://issues.apache.org/jira/browse/NIFI-9895

NIFI-9895 Allow parameters to reference controller services

---

nifi-nar-bundles/nifi-framework-bundle/nifi-framework/nifi-framework-components/src/main/java/org/apache/nifi/controller/service/StandardControllerServiceProvider.java

[NIFI-10059](https://issues.apache.org/jira/browse/NIFI-10059)
- [X ] [Apache NiFi Jira](https://issues.apache.org/jira/browse/NIFI) issue created

NIFI-10059 Remove incorrect removal of controller service from cache

---

nifi-nar-bundles/nifi-scripting-bundle/nifi-scripting-processors/src/main/resources/docs/org.apache.nifi.processors.script.ExecuteScript/additionalDetails.html

[NIFI-1954](https://issues.apache.org/jira/browse/NIFI-1954)

NIFI-1954: Add additionalDetails page to ExecuteScript

---

nifi-nar-bundles/nifi-framework-bundle/nifi-framework/nifi-framework-components/src/main/java/org/apache/nifi/groups/StandardProcessGroup.java
nifi-nar-bundles/nifi-framework-bundle/nifi-framework/nifi-framework-core-api/src/main/java/org/apache/nifi/groups/ProcessGroup.java
nifi-nar-bundles/nifi-framework-bundle/nifi-framework/nifi-framework-core/src/main/java/org/apache/nifi/controller/FlowController.java
nifi-nar-bundles/nifi-framework-bundle/nifi-framework/nifi-framework-core/src/test/java/org/apache/nifi/controller/service/mock/MockProcessGroup.java
nifi-nar-bundles/nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-optimistic-locking/src/main/java/org/apache/nifi/web/revision/NaiveRevisionManager.java

[NIFI-10052](https://issues.apache.org/jira/browse/NIFI-10052)

NIFI-10052 Avoid obtaining any locks when creating/sending heartbeats

---

nifi-nar-bundles/nifi-scripting-bundle/nifi-scripting-processors/src/main/java/org/apache/nifi/lookup/script/BaseScriptedLookupService.java
nifi-nar-bundles/nifi-scripting-bundle/nifi-scripting-processors/src/main/java/org/apache/nifi/processors/script/InvokeScriptedProcessor.java
nifi-nar-bundles/nifi-scripting-bundle/nifi-scripting-processors/src/main/java/org/apache/nifi/record/sink/script/ScriptedRecordSink.java
nifi-nar-bundles/nifi-scripting-bundle/nifi-scripting-processors/src/main/java/org/apache/nifi/rules/engine/script/ScriptedRulesEngine.java
nifi-nar-bundles/nifi-scripting-bundle/nifi-scripting-processors/src/main/java/org/apache/nifi/rules/handlers/script/ScriptedActionHandler.java
nifi-nar-bundles/nifi-scripting-bundle/nifi-scripting-processors/src/test/groovy/org/apache/nifi/lookup/script/TestScriptedLookupService.groovy

[NIFI-10387](https://issues.apache.org/jira/browse/NIFI-10387)

NIFI-10387: Fixed negative logic bug in scripted components

---

pom.xml

NIFI-10405 updating a few dependencies

---

nifi-nar-bundles/nifi-framework-bundle/nifi-framework/nifi-framework-components/src/main/java/org/apache/nifi/flow/synchronization/StandardVersionedComponentSynchronizer.java
nifi-nar-bundles/nifi-framework-bundle/nifi-framework/nifi-framework-components/src/test/java/org/apache/nifi/flow/synchronization/StandardVersionedComponentSynchronizerTest.java
nifi-nar-bundles/nifi-framework-bundle/nifi-framework/nifi-framework-core-api/src/main/java/org/apache/nifi/groups/FlowSynchronizationCallback.java
nifi-nar-bundles/nifi-framework-bundle/nifi-framework/nifi-framework-core-api/src/main/java/org/apache/nifi/groups/FlowSynchronizationOptions.java
nifi-nar-bundles/nifi-framework-bundle/nifi-framework/nifi-framework-core-api/src/main/java/org/apache/nifi/groups/ScheduledStateChangeListener.java

[NIFI-10401](https://issues.apache.org/jira/browse/NIFI-10401)
This adds a callback to the `FlowSynchronizationOptions` that will allow client framework code to receive notification of any automatic component scheduled state updates.

NIFI-10401: Adding FlowSynchronizationCallback to synchronizer

---

nifi-nar-bundles/nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-ui/pom.xml
nifi-nar-bundles/nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-ui/src/main/resources/filters/canvas.properties
nifi-nar-bundles/nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-ui/src/main/webapp/WEB-INF/pages/canvas.jsp
nifi-nar-bundles/nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-ui/src/main/webapp/WEB-INF/partials/canvas/fetch-parameters-dialog.jsp
nifi-nar-bundles/nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-ui/src/main/webapp/WEB-INF/partials/canvas/new-parameter-context-dialog.jsp
nifi-nar-bundles/nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-ui/src/main/webapp/WEB-INF/partials/canvas/new-parameter-provider-dialog.jsp
nifi-nar-bundles/nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-ui/src/main/webapp/WEB-INF/partials/canvas/parameter-provider-configuration.jsp
nifi-nar-bundles/nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-ui/src/main/webapp/WEB-INF/partials/canvas/policy-management.jsp
nifi-nar-bundles/nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-ui/src/main/webapp/WEB-INF/partials/canvas/settings-content.jsp
nifi-nar-bundles/nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-ui/src/main/webapp/css/canvas.css
nifi-nar-bundles/nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-ui/src/main/webapp/css/dialog.css
nifi-nar-bundles/nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-ui/src/main/webapp/css/new-parameter-provider-dialog.css
nifi-nar-bundles/nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-ui/src/main/webapp/css/parameter-provider.css
nifi-nar-bundles/nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-ui/src/main/webapp/js/jquery/statusbar/jquery.statusbar.css
nifi-nar-bundles/nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-ui/src/main/webapp/js/jquery/statusbar/jquery.statusbar.js
nifi-nar-bundles/nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-ui/src/main/webapp/js/nf/canvas/nf-canvas-bootstrap.js
nifi-nar-bundles/nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-ui/src/main/webapp/js/nf/canvas/nf-controller-service.js
nifi-nar-bundles/nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-ui/src/main/webapp/js/nf/canvas/nf-parameter-contexts.js
nifi-nar-bundles/nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-ui/src/main/webapp/js/nf/canvas/nf-parameter-provider.js
nifi-nar-bundles/nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-ui/src/main/webapp/js/nf/canvas/nf-policy-management.js
nifi-nar-bundles/nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-ui/src/main/webapp/js/nf/canvas/nf-processor-configuration.js
nifi-nar-bundles/nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-ui/src/main/webapp/js/nf/canvas/nf-settings.js
nifi-nar-bundles/nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-ui/src/main/webapp/js/nf/nf-processor-details.js

This PR adds a new Parameter Providers tab in the Controller Settings UI dialog. From the Parameter Providers tab, users can add and configure Parameter Providers to fetch external parameters. Parameter contexts created from a provider will be listed in Parameter Contexts, where the parameters will be in a read-only state.
~~- To test, you'll need to check out and rebase on top of [PR 5369](https://github.com/apache/nifi/pull/5369).~~ This PR is rebased on `main`, which now includes PR 5369.
- Links to Jiras: [NIFI-9514](https://issues.apache.org/jira/browse/NIFI-9514), [NIFI-9515](https://issues.apache.org/jira/browse/NIFI-9515)
In order to streamline the review of the contribution …

NIFI-9514 NIFI-9515: Add UI support for Parameter Providers in Controller Services

---

nifi-nar-bundles/nifi-flow-registry-client-bundle/nifi-flow-registry-client-services/src/main/java/org/apache/nifi/registry/flow/NifiRegistryFlowRegistryClient.java

- [NIFI-10550](https://issues.apache.org/jira/browse/NIFI-10550)

NIFI-10550 Fixing SSH Context Service validation for NifiRegistryFlowRegistryClient

---

nifi-nar-bundles/nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-ui/src/main/webapp/WEB-INF/partials/canvas/settings-content.jsp
nifi-nar-bundles/nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-ui/src/main/webapp/js/nf/canvas/nf-controller-service.js

- fix link in controller service referencing a parameter provider
[NIFI-10566](https://issues.apache.org/jira/browse/NIFI-10566)
- update controller services text
- fix link to parameter providers

NIFI-10566: update availability text in Controller Settings

---

nifi-nar-bundles/nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-ui/src/main/webapp/js/nf/canvas/nf-parameter-provider.js

[NIFI-10715](https://issues.apache.org/jira/browse/NIFI-10715)
Improve adding and removing tooltips in parameter providers and clean up some code.

NIFI-10715: improve tooltips in parameter providers

---

nifi-nar-bundles/nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-ui/src/main/webapp/WEB-INF/partials/summary/summary-content.jsp
nifi-nar-bundles/nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-ui/src/main/webapp/css/common-ui.css
nifi-nar-bundles/nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-ui/src/main/webapp/js/nf/summary/nf-summary-table.js

[NIFI-10698](https://issues.apache.org/jira/browse/NIFI-10698)
This PR adds additional filtering to the summary table as described in the ticket linked above. To test, add multiple processors and ports to the canvas. Configure one of the processors to run on the primary node. Open the summary modal. You'll notice two new filters; a dropdown to filter by status and a checkbox to filter by processors configured to run on the primary node. 
The status filter is also available for input and output ports while the primary node filter is only available for processors. Navigating between tabs resets the filters to their initial state.

NIFI-10698: Add filtering options to summary table

---

nifi-registry/nifi-registry-core/nifi-registry-framework/src/main/java/org/apache/nifi/registry/event/EventFactory.java
nifi-registry/nifi-registry-core/nifi-registry-framework/src/test/java/org/apache/nifi/registry/event/TestEventFactory.java
nifi-registry/nifi-registry-core/nifi-registry-provider-api/src/main/java/org/apache/nifi/registry/hook/EventType.java

[NIFI-10751](https://issues.apache.org/jira/browse/NIFI-10751)

NIFI-10751 Add Username to User and Group CRUD

---

nifi-nar-bundles/nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-ui/src/main/webapp/WEB-INF/partials/canvas/import-flow-version-dialog.jsp
nifi-nar-bundles/nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-ui/src/main/webapp/css/connection-configuration.css
nifi-nar-bundles/nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-ui/src/main/webapp/css/dialog.css
nifi-nar-bundles/nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-ui/src/main/webapp/js/nf/canvas/nf-flow-version.js

[NIFI-10814](https://issues.apache.org/jira/browse/NIFI-10814)

NIFI-10814: Display description for selected flow

---

nifi-nar-bundles/nifi-kafka-bundle/nifi-kafka-2-6-processors/src/main/java/org/apache/nifi/processors/kafka/pubsub/PublisherLease.java
nifi-nar-bundles/nifi-kafka-bundle/nifi-kafka-2-6-processors/src/main/resources/docs/org.apache.nifi.processors.kafka.pubsub.PublishKafkaRecord_2_6/additionalDetails.html
nifi-nar-bundles/nifi-kafka-bundle/nifi-kafka-2-6-processors/src/test/java/org/apache/nifi/processors/kafka/pubsub/TestPublishKafkaRecordMockParameterized.java
nifi-nar-bundles/nifi-kafka-bundle/nifi-kafka-2-6-processors/src/test/resources/Publish/parameterized/flowfileInput1.json
nifi-nar-bundles/nifi-kafka-bundle/nifi-kafka-2-6-processors/src/test/resources/Publish/parameterized/flowfileInputA.json
nifi-nar-bundles/nifi-kafka-bundle/nifi-kafka-2-6-processors/src/test/resources/Publish/parameterized/kafkaOutput1A.json
nifi-nar-bundles/nifi-kafka-bundle/nifi-kafka-2-6-processors/src/test/resources/Publish/parameterized/kafkaOutput1B.json
nifi-nar-bundles/nifi-kafka-bundle/nifi-kafka-2-6-processors/src/test/resources/Publish/parameterized/kafkaOutputA1.json
nifi-nar-bundles/nifi-kafka-bundle/nifi-kafka-2-6-processors/src/test/resources/Publish/parameterized/kafkaOutputA2.json
nifi-nar-bundles/nifi-kafka-bundle/nifi-kafka-2-6-processors/src/test/resources/PublishRecord/parameterized/flowfileInputDoc1V.json
nifi-nar-bundles/nifi-kafka-bundle/nifi-kafka-2-6-processors/src/test/resources/PublishRecord/parameterized/flowfileInputDoc1W.json
nifi-nar-bundles/nifi-kafka-bundle/nifi-kafka-2-6-processors/src/test/resources/PublishRecord/parameterized/flowfileInputDoc2W.json
nifi-nar-bundles/nifi-kafka-bundle/nifi-kafka-2-6-processors/src/test/resources/PublishRecord/parameterized/kafkaOutputDoc1V.json
nifi-nar-bundles/nifi-kafka-bundle/nifi-kafka-2-6-processors/src/test/resources/PublishRecord/parameterized/kafkaOutputDoc1W.json
nifi-nar-bundles/nifi-kafka-bundle/nifi-kafka-2-6-processors/src/test/resources/PublishRecord/parameterized/kafkaOutputDoc2W.json

NIFI-10901 - PublishKafka headers not sent in ProducerRecord

---

nifi-commons/nifi-record/src/main/java/org/apache/nifi/serialization/record/util/DataTypeUtils.java
nifi-nar-bundles/nifi-standard-services/nifi-record-serialization-services-bundle/nifi-record-serialization-services/pom.xml
nifi-nar-bundles/nifi-standard-services/nifi-record-serialization-services-bundle/nifi-record-serialization-services/src/main/java/org/apache/nifi/json/JsonSchemaInference.java
nifi-nar-bundles/nifi-standard-services/nifi-record-serialization-services-bundle/nifi-record-serialization-services/src/main/java/org/apache/nifi/schema/inference/HierarchicalSchemaInference.java
nifi-nar-bundles/nifi-standard-services/nifi-record-serialization-services-bundle/nifi-record-serialization-services/src/main/java/org/apache/nifi/xml/inference/XmlSchemaInference.java
nifi-nar-bundles/nifi-standard-services/nifi-record-serialization-services-bundle/nifi-record-serialization-services/src/test/java/org/apache/nifi/json/TestJsonSchemaInference.java
nifi-nar-bundles/nifi-standard-services/nifi-record-serialization-services-bundle/nifi-record-serialization-services/src/test/java/org/apache/nifi/json/TestWriteJsonResult.java
nifi-nar-bundles/nifi-standard-services/nifi-record-serialization-services-bundle/nifi-record-serialization-services/src/test/resources/json/choice-of-array-empty-or-array-record.json
nifi-nar-bundles/nifi-standard-services/nifi-record-serialization-services-bundle/nifi-record-serialization-services/src/test/resources/json/choice-of-array-string-or-array-record.json
nifi-nar-bundles/nifi-standard-services/nifi-record-serialization-services-bundle/nifi-record-serialization-services/src/test/resources/json/empty-arrays.json

[NIFI-10956](https://issues.apache.org/jira/browse/NIFI-10956)

NIFI-10956: Fix inference issues with mixed arrays

---

nifi-nar-bundles/nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-api/pom.xml
nifi-nar-bundles/nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-api/src/main/java/org/apache/nifi/web/api/dto/DtoFactory.java
nifi-nar-bundles/nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-api/src/test/java/org/apache/nifi/web/api/dto/DtoFactoryTest.java

NIFI-10980 - correct ordering of property descriptor allowable values

---

nifi-nar-bundles/nifi-framework-bundle/nifi-framework/nifi-framework-components/src/main/java/org/apache/nifi/parameter/StandardParameterContext.java

[NIFI-11076](https://issues.apache.org/jira/browse/NIFI-11076)

NIFI-11076: Resolving deadlock issue in StandardParameterContext

---

nifi-nar-bundles/nifi-framework-bundle/nifi-framework/nifi-framework-components/src/main/java/org/apache/nifi/flow/synchronization/StandardVersionedComponentSynchronizer.java
nifi-nar-bundles/nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-api/src/main/java/org/apache/nifi/web/StandardNiFiServiceFacade.java

[NIFI-11039](https://issues.apache.org/jira/browse/NIFI-11039)

NIFI-11039: Fixing bug when importing parameter providers from nifi-registry

---

.github/workflows/system-tests.yml

[NIFI-11175](https://issues.apache.org/jira/browse/NIFI-11175) Enables the GitHub `system-tests` workflow for pull requests that include changes to `nifi-api` and framework modules to provide automated feedback on changes that could impact system behavior.

NIFI-11175 Enable system-tests for framework changes

---

nifi-docs/src/main/asciidoc/record-path-guide.adoc

[NIFI-11225](https://issues.apache.org/jira/browse/NIFI-11225 )

NIFI-11225 Fix toLowerCase and toUpperCase documentation

---

nifi-nar-bundles/nifi-framework-bundle/nifi-framework/nifi-framework-core/src/main/java/org/apache/nifi/controller/FlowController.java
nifi-nar-bundles/nifi-framework-bundle/nifi-framework/nifi-framework-core/src/test/java/org/apache/nifi/controller/TestFlowController.java

[NIFI-11245](https://issues.apache.org/jira/browse/NIFI-11245) Corrects application behavior when reducing the `Maximum Timer Driven Thread Count` property in Controller Settings, also allowing settings below the default of 10.
The original implementation checked the requested Max Thread Count against the current core pool size, and did not apply the changes if the Max Thread Count was less than current. This approach supported increasing the Max Thread Count at runtime, but required restarting the application to apply the reduction.

NIFI-11245 Correct reducing Maximum Thread Count while running

---

nifi-nar-bundles/nifi-cdc/nifi-cdc-mysql-bundle/nifi-cdc-mysql-processors/src/main/java/org/apache/nifi/cdc/mysql/processors/CaptureChangeMySQL.java
nifi-nar-bundles/nifi-cdc/nifi-cdc-mysql-bundle/nifi-cdc-mysql-processors/src/test/groovy/org/apache/nifi/cdc/mysql/processors/CaptureChangeMySQLTest.groovy

[NIFI-5501](https://issues.apache.org/jira/browse/NIFI-5501)

NIFI-5501: Refactored driver/connection logic for CaptureChangeMySQL

---

nifi-nar-bundles/nifi-cdc/nifi-cdc-mysql-bundle/nifi-cdc-mysql-processors/src/main/java/org/apache/nifi/cdc/mysql/processors/CaptureChangeMySQL.java

[NIFI-11305](https://issues.apache.org/jira/browse/NIFI-11305) This PR removes the unused logic to stop the CaptureChangeMySQL processor when it has been unscheduled, and instead checks to see if it has been unscheduled as a sign to stop the onTrigger binlog event processing loop.

NIFI-11305: Fix logic to correctly stop CaptureChangeMySQL

---

nifi-toolkit/nifi-toolkit-cli/src/main/java/org/apache/nifi/toolkit/cli/impl/client/nifi/ControllerClient.java
nifi-toolkit/nifi-toolkit-cli/src/main/java/org/apache/nifi/toolkit/cli/impl/client/nifi/impl/JerseyControllerClient.java
nifi-toolkit/nifi-toolkit-cli/src/main/java/org/apache/nifi/toolkit/cli/impl/command/nifi/NiFiCommandGroup.java
nifi-toolkit/nifi-toolkit-cli/src/main/java/org/apache/nifi/toolkit/cli/impl/command/nifi/flow/GetControllerConfiguration.java
nifi-toolkit/nifi-toolkit-cli/src/main/java/org/apache/nifi/toolkit/cli/impl/command/nifi/flow/UpdateControllerConfiguration.java
nifi-toolkit/nifi-toolkit-cli/src/main/java/org/apache/nifi/toolkit/cli/impl/result/nifi/ControllerConfigurationResult.java

[NIFI-11435](https://issues.apache.org/jira/browse/NIFI-11435)

NiFi CLI - add possibility to set 'Maximum Timer Driven Thread Count'

---

nifi-nar-bundles/nifi-framework-bundle/nifi-framework/nifi-framework-core/src/main/java/org/apache/nifi/controller/queue/clustered/client/async/nio/PeerChannel.java

[NIFI-11680](https://issues.apache.org/jira/browse/NIFI-11680) Corrects `PeerChannel` methods used for Cluster Connection Load Balancing to avoid potential `BufferOverflowException` errors with the Bouncy Castle Security Provider for TLS.
The Bouncy Castle [ProvSSLSessionBase](https://github.com/bcgit/bc-java/blob/master/tls/src/main/java/org/bouncycastle/jsse/provider/ProvSSLSessionBase.java) uses a more coarse-grained calculation for Application Buffer Size and Packet Buffer Size than the standard JDK [SSLSessionImpl](https://github.com/openjdk/jdk/blob/master/src/java.base/share/classes/sun/security/ssl/SSLSessionImpl.java). As a result of this difference in behavior, the `PeerChannel.encrypt()` method can expand the encrypted destination buffer greater than the SSLSession Application …

NIFI-11680 Correct Buffer Size Calculation for Connection Balancing

---

nifi-nar-bundles/nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-ui/src/main/webapp/js/nf/canvas/nf-settings.js

[NIFI-11769](https://issues.apache.org/jira/browse/NIFI-11769)
Currently the list of Registry Client types and actual Registry Client instances provides a limited amount of information. As various nars might be loaded in a running NiFi instance it would be useful to have information about the bundle and version of the nar presented.

NIFI-11769 Adding details on Registry Clients and Registrty Client types on UI

---

nifi-nar-bundles/nifi-framework-bundle/nifi-framework/nifi-framework-nar-utils/src/main/java/org/apache/nifi/nar/NarThreadContextClassLoader.java

NIFI-12072 moved to StackWalker API elimnating usage of SecurityManager

---

nifi-docker/dockerhub/Dockerfile
nifi-docker/dockerhub/sh/start.sh
nifi-docker/dockermaven/Dockerfile

NIFI-12138 added volume for nar extensions

---

nifi-docs/src/main/asciidoc/toolkit-guide.adoc

[NIFI-12146](https://issues.apache.org/jira/browse/NIFI-12146)

NIFI-12146: Updating nifi cli command list in documentation

---

nifi-registry/nifi-registry-core/nifi-registry-flow-diff/src/main/java/org/apache/nifi/registry/flow/diff/ConciseEvolvingDifferenceDescriptor.java
nifi-registry/nifi-registry-core/nifi-registry-flow-diff/src/main/java/org/apache/nifi/registry/flow/diff/DifferenceType.java
nifi-registry/nifi-registry-core/nifi-registry-flow-diff/src/main/java/org/apache/nifi/registry/flow/diff/StandardFlowComparator.java

NIFI-12237 change label height and width from POSITION difference to SIZE difference
[NIFI-12237](https://issues.apache.org/jira/browse/NIFI-12237)
- [n/a] New dependencies are compatible with the [Apache License 2.0](https://apache.org/licenses/LICENSE-2.0) according to the [License Policy](https://www.apache.org/legal/resolved.html)
- [n/a] New dependencies are documented in applicable `LICENSE` and `NOTICE` files
- [n/a] Documentation formatting appears as expected in rendered files

NIFI-12237 change label height and width from POSITION to SIZE difference

---

nifi-nar-bundles/nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-ui/src/main/webapp/js/jquery/combo/jquery.combo.css

NIFI-12248:
- Fixing arrow alignment in combo editor.

NIFI-12248: Fixing arrow alignment in combo editor

---

nifi-nar-bundles/nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-ui/src/main/webapp/js/nf/canvas/nf-settings.js

NIFI-12250:
- Fixing issue where the registry configuration dialog was being initialized twice.

NIFI-12250: Fixing issue where the registry configuration dialog was being initialized twice

---

nifi-nar-bundles/nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-ui/src/main/webapp/WEB-INF/partials/canvas/process-group-configuration.jsp
nifi-nar-bundles/nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-ui/src/main/webapp/css/process-group-configuration.css

… nifi-1.x line
This PR is for merging to the `support/nifi-1.x` line. There is a separate PR for merging to `main`. See https://github.com/apache/nifi/pull/7591
[NIFI-11874](https://issues.apache.org/jira/browse/NIFI-11874)

NIFI-11874: update process group configuration dialog UI, specific to nifi-1.x line

---

nifi-nar-bundles/nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-ui/src/main/webapp/WEB-INF/partials/canvas/process-group-configuration.jsp
nifi-nar-bundles/nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-ui/src/main/webapp/css/process-group-configuration.css
nifi-nar-bundles/nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-ui/src/main/webapp/js/nf/canvas/nf-process-group-configuration.js

[NIFI-11874](https://issues.apache.org/jira/browse/NIFI-11874)
UI modification for the layout of Process Group configuration. It separates the increasing number of configuration options into two columns. Also, to assist in splitting configuration input into logically related pieces as well as be consistent with the configuration of other components, the Comments section was moved to its own tab. This presents better in the UI and keeps the Apply button easily accessible without the need to scroll (for most display resolutions.)
The PR includes additional details when mouse-over/hover the new "?" icon for several of the Process Group properties to explicitly clarify that the default connections settings apply only to new connections - not existing connections. 
Please complete the …

NIFI-11874 update Process Group configuration layout in the UI

---

.github/workflows/ci-workflow.yml
nifi-nar-bundles/nifi-framework-bundle/nifi-framework/nifi-web/pom.xml

* Also updated the ci-workflow.yaml to activate that profile.
[NIFI-12419](https://issues.apache.org/jira/browse/NIFI-12419)

[NIFI-12419] - Only include the new UI module when building if the 'include-new-ui' profile is active.

---

nifi-nar-bundles/nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-frontend/src/main/nifi/angular.json
nifi-nar-bundles/nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-frontend/src/main/nifi/src/app/app.module.ts
nifi-nar-bundles/nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-frontend/src/main/nifi/src/app/pages/canvas/service/canvas-utils.service.ts
nifi-nar-bundles/nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-frontend/src/main/nifi/src/app/pages/canvas/state/flow/flow.actions.ts
nifi-nar-bundles/nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-frontend/src/main/nifi/src/app/pages/canvas/state/flow/flow.effects.ts
nifi-nar-bundles/nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-frontend/src/main/nifi/src/app/pages/canvas/ui/canvas/context-menu/context-menu.component.ts
nifi-nar-bundles/nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-frontend/src/main/nifi/src/app/pages/canvas/ui/process-group/edit-process-group/edit-process-group.component.html
nifi-nar-bundles/nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-frontend/src/main/nifi/src/app/pages/canvas/ui/process-group/edit-process-group/edit-process-group.component.scss
nifi-nar-bundles/nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-frontend/src/main/nifi/src/app/pages/canvas/ui/process-group/edit-process-group/edit-process-group.component.spec.ts
nifi-nar-bundles/nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-frontend/src/main/nifi/src/app/pages/canvas/ui/process-group/edit-process-group/edit-process-group.component.ts
nifi-nar-bundles/nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-frontend/src/main/nifi/src/styles.scss

NIFI-12417:
- Process Group Configuration.
- Removed unnecessary module imports.

NIFI-12417: Process Group Configuration

---

nifi-nar-bundles/nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-ui/src/main/webapp/js/nf/nf-status-history.js

NIFI-12470:
- Fixing forEach callback for usage with Object.entries() to address layout issue in Status History.

NIFI-12470: Fixing forEach callback for usage with Object.entries() to address layout issue in Status History

---

nifi-nar-bundles/nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-ui/src/main/webapp/js/nf/canvas/nf-flow-version.js

NIFI-12481:
- Filtering out unauthorized registry clients to avoid unhandled error.

NIFI-12481: Filtering out unauthorized registry clients to avoid unhandled error

---

nifi-nar-bundles/nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-frontend/src/main/nifi/src/app/pages/flow-designer/service/canvas-context-menu.service.ts
nifi-nar-bundles/nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-frontend/src/main/nifi/src/app/pages/flow-designer/service/canvas-utils.service.ts
nifi-nar-bundles/nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-frontend/src/main/nifi/src/app/pages/flow-designer/state/flow/flow.actions.ts
nifi-nar-bundles/nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-frontend/src/main/nifi/src/app/pages/flow-designer/state/flow/flow.effects.ts
nifi-nar-bundles/nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-frontend/src/main/nifi/src/app/pages/flow-designer/state/flow/flow.selectors.ts
nifi-nar-bundles/nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-frontend/src/main/nifi/src/app/pages/flow-designer/ui/canvas/canvas-routing.module.ts
nifi-nar-bundles/nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-frontend/src/main/nifi/src/app/pages/flow-designer/ui/canvas/canvas.component.ts
nifi-nar-bundles/nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-frontend/src/main/nifi/src/app/pages/flow-designer/ui/canvas/header/header.component.html
nifi-nar-bundles/nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-frontend/src/main/nifi/src/app/pages/flow-designer/ui/canvas/header/header.component.ts
nifi-nar-bundles/nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-frontend/src/main/nifi/src/app/service/status-history.service.ts
nifi-nar-bundles/nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-frontend/src/main/nifi/src/app/state/status-history/index.ts
nifi-nar-bundles/nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-frontend/src/main/nifi/src/app/state/status-history/status-history.actions.ts
nifi-nar-bundles/nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-frontend/src/main/nifi/src/app/state/status-history/status-history.effects.ts

[NIFI-12553](https://issues.apache.org/jira/browse/NIFI-12553)
* Added View Status History to the canvas context menu for applicable component types
* Added support for Node Status History from the flow menu

[NIFI-12553] - Context menu option for View Status History

---

nifi-nar-bundles/nifi-framework-bundle/nifi-framework/nifi-client-dto/src/main/java/org/apache/nifi/web/api/dto/BulletinDTO.java
nifi-nar-bundles/nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-api/src/main/java/org/apache/nifi/web/api/dto/DtoFactory.java
nifi-nar-bundles/nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-frontend/src/main/nifi/src/app/app-routing.module.ts
nifi-nar-bundles/nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-frontend/src/main/nifi/src/app/pages/bulletins/feature/bulletins-routing.module.ts
nifi-nar-bundles/nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-frontend/src/main/nifi/src/app/pages/bulletins/feature/bulletins.component.html
nifi-nar-bundles/nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-frontend/src/main/nifi/src/app/pages/bulletins/feature/bulletins.component.scss
nifi-nar-bundles/nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-frontend/src/main/nifi/src/app/pages/bulletins/feature/bulletins.component.spec.ts
nifi-nar-bundles/nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-frontend/src/main/nifi/src/app/pages/bulletins/feature/bulletins.component.ts
nifi-nar-bundles/nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-frontend/src/main/nifi/src/app/pages/bulletins/feature/bulletins.module.ts
nifi-nar-bundles/nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-frontend/src/main/nifi/src/app/pages/bulletins/service/bulletin-board.service.ts
nifi-nar-bundles/nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-frontend/src/main/nifi/src/app/pages/bulletins/state/bulletin-board/bulletin-board.actions.ts
nifi-nar-bundles/nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-frontend/src/main/nifi/src/app/pages/bulletins/state/bulletin-board/bulletin-board.effects.ts
nifi-nar-bundles/nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-frontend/src/main/nifi/src/app/pages/bulletins/state/bulletin-board/bulletin-board.reducer.ts
nifi-nar-bundles/nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-frontend/src/main/nifi/src/app/pages/bulletins/state/bulletin-board/bulletin-board.selectors.ts
nifi-nar-bundles/nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-frontend/src/main/nifi/src/app/pages/bulletins/state/bulletin-board/index.ts
nifi-nar-bundles/nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-frontend/src/main/nifi/src/app/pages/bulletins/state/index.ts
nifi-nar-bundles/nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-frontend/src/main/nifi/src/app/pages/bulletins/ui/bulletin-board/bulletin-board-list/bulletin-board-list.component.html
nifi-nar-bundles/nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-frontend/src/main/nifi/src/app/pages/bulletins/ui/bulletin-board/bulletin-board-list/bulletin-board-list.component.scss
nifi-nar-bundles/nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-frontend/src/main/nifi/src/app/pages/bulletins/ui/bulletin-board/bulletin-board-list/bulletin-board-list.component.spec.ts
nifi-nar-bundles/nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-frontend/src/main/nifi/src/app/pages/bulletins/ui/bulletin-board/bulletin-board-list/bulletin-board-list.component.ts
nifi-nar-bundles/nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-frontend/src/main/nifi/src/app/pages/bulletins/ui/bulletin-board/bulletin-board.component.html
nifi-nar-bundles/nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-frontend/src/main/nifi/src/app/pages/bulletins/ui/bulletin-board/bulletin-board.component.scss
nifi-nar-bundles/nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-frontend/src/main/nifi/src/app/pages/bulletins/ui/bulletin-board/bulletin-board.component.spec.ts
nifi-nar-bundles/nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-frontend/src/main/nifi/src/app/pages/bulletins/ui/bulletin-board/bulletin-board.component.ts
nifi-nar-bundles/nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-frontend/src/main/nifi/src/app/pages/flow-designer/ui/canvas/header/header.component.html
nifi-nar-bundles/nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-frontend/src/main/nifi/src/app/state/shared/index.ts
nifi-nar-bundles/nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-frontend/src/main/nifi/src/app/ui/common/controller-service/disable-controller-service/disable-controller-service.component.spec.ts
nifi-nar-bundles/nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-frontend/src/main/nifi/src/app/ui/common/controller-service/enable-controller-service/enable-controller-service.component.spec.ts
nifi-nar-bundles/nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-frontend/src/main/nifi/src/app/ui/common/tooltips/bulletins-tip/bulletins-tip.component.html

[NIFI-12560](https://issues.apache.org/jira/browse/NIFI-12560)
* Added new Bulletin Board page
* Updated the BulletinDTO (backend) to include the component type of the source of the bulletin.

[NIFI-12560] bulletin board

---

nifi-nar-bundles/nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-frontend/src/main/nifi/src/app/pages/settings/feature/settings-routing.module.ts
nifi-nar-bundles/nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-frontend/src/main/nifi/src/app/pages/settings/service/reporting-task.service.ts
nifi-nar-bundles/nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-frontend/src/main/nifi/src/app/pages/settings/state/management-controller-services/index.ts
nifi-nar-bundles/nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-frontend/src/main/nifi/src/app/pages/settings/state/management-controller-services/management-controller-services.effects.ts
nifi-nar-bundles/nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-frontend/src/main/nifi/src/app/pages/settings/state/reporting-tasks/index.ts
nifi-nar-bundles/nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-frontend/src/main/nifi/src/app/pages/settings/state/reporting-tasks/reporting-tasks.actions.ts
nifi-nar-bundles/nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-frontend/src/main/nifi/src/app/pages/settings/state/reporting-tasks/reporting-tasks.effects.ts
nifi-nar-bundles/nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-frontend/src/main/nifi/src/app/pages/settings/state/reporting-tasks/reporting-tasks.reducer.ts
nifi-nar-bundles/nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-frontend/src/main/nifi/src/app/pages/settings/state/reporting-tasks/reporting-tasks.selectors.ts
nifi-nar-bundles/nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-frontend/src/main/nifi/src/app/pages/settings/ui/reporting-tasks/edit-reporting-task/edit-reporting-task.component.html
nifi-nar-bundles/nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-frontend/src/main/nifi/src/app/pages/settings/ui/reporting-tasks/edit-reporting-task/edit-reporting-task.component.scss
nifi-nar-bundles/nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-frontend/src/main/nifi/src/app/pages/settings/ui/reporting-tasks/edit-reporting-task/edit-reporting-task.component.spec.ts
nifi-nar-bundles/nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-frontend/src/main/nifi/src/app/pages/settings/ui/reporting-tasks/edit-reporting-task/edit-reporting-task.component.ts
nifi-nar-bundles/nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-frontend/src/main/nifi/src/app/pages/settings/ui/reporting-tasks/reporting-task-table/reporting-task-table.component.html
nifi-nar-bundles/nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-frontend/src/main/nifi/src/app/pages/settings/ui/reporting-tasks/reporting-task-table/reporting-task-table.component.ts
nifi-nar-bundles/nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-frontend/src/main/nifi/src/app/pages/settings/ui/reporting-tasks/reporting-tasks.component.html
nifi-nar-bundles/nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-frontend/src/main/nifi/src/app/pages/settings/ui/reporting-tasks/reporting-tasks.component.ts
nifi-nar-bundles/nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-frontend/src/main/nifi/src/app/pages/settings/ui/reporting-tasks/reporting-tasks.module.ts
nifi-nar-bundles/nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-frontend/src/main/nifi/src/app/state/shared/index.ts
nifi-nar-bundles/nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-frontend/src/main/nifi/src/app/ui/common/controller-service/enable-controller-service/enable-controller-service.component.html

[NIFI-12563](https://issues.apache.org/jira/browse/NIFI-12563)
Configure Reporting Task:

[NIFI-12563] configure reporting task

---

nifi-nar-bundles/nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-frontend/src/main/nifi/src/app/ui/common/property-table/editors/nf-editor/nf-editor.component.html
nifi-nar-bundles/nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-frontend/src/main/nifi/src/app/ui/common/property-table/editors/nf-editor/nf-editor.component.ts

NIFI-12586:
- Fixing the handling of getParameters since the supplied input could be undefined in some instances.

NIFI-12586: Fix handling of getParameters in NF Editor

---

nifi-nar-bundles/nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-frontend/src/main/nifi/src/app/pages/flow-designer/service/canvas-context-menu.service.ts
nifi-nar-bundles/nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-frontend/src/main/nifi/src/app/pages/flow-designer/service/canvas-utils.service.ts
nifi-nar-bundles/nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-frontend/src/main/nifi/src/app/pages/flow-designer/service/flow.service.ts
nifi-nar-bundles/nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-frontend/src/main/nifi/src/app/pages/flow-designer/state/flow/flow.actions.ts
nifi-nar-bundles/nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-frontend/src/main/nifi/src/app/pages/flow-designer/state/flow/flow.effects.ts
nifi-nar-bundles/nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-frontend/src/main/nifi/src/app/pages/flow-designer/state/flow/flow.reducer.ts
nifi-nar-bundles/nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-frontend/src/main/nifi/src/app/pages/flow-designer/state/flow/index.ts
nifi-nar-bundles/nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-frontend/src/main/nifi/src/app/pages/flow-designer/ui/canvas/graph-controls/operation-control/operation-control.component.ts
nifi-nar-bundles/nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-frontend/src/main/nifi/src/app/state/shared/index.ts
nifi-nar-bundles/nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-frontend/src/main/nifi/src/app/ui/common/context-menu/context-menu.component.html
nifi-nar-bundles/nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-frontend/src/main/nifi/src/app/ui/common/context-menu/context-menu.component.scss

[NIFI-12568](https://issues.apache.org/jira/browse/NIFI-12568)
* start/stop/run once from the context menu.
* start/stop from operation panel.

[NIFI-12568] - start/stop/run once from the context menu. start/stop from operation panel.

---

nifi-nar-bundles/nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-ui/src/main/webapp/js/nf/canvas/nf-controller-service.js

[NIFI-11389](https://issues.apache.org/jira/browse/NIFI-11389)
For 2.x branch.

NIFI-11389 Fixed controller service's link to referencing controller services of lesser scope

---

nifi-nar-bundles/nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-ui/src/main/webapp/js/nf/canvas/nf-controller-service.js

[NIFI-11389](https://issues.apache.org/jira/browse/NIFI-11389)
This PR is for the 1.x branch.

NIFI-11389 Fixed controller services's link to referencing controller services of lesser scope - 1.x branch

---

nifi-nar-bundles/nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-frontend/src/main/nifi/src/app/pages/counters/ui/counter-listing/counter-table/counter-table.component.html
nifi-nar-bundles/nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-frontend/src/main/nifi/src/app/pages/counters/ui/counter-listing/counter-table/counter-table.component.ts
nifi-nar-bundles/nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-frontend/src/main/nifi/src/app/pages/parameter-contexts/ui/parameter-context-listing/parameter-context-table/parameter-context-table.component.html
nifi-nar-bundles/nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-frontend/src/main/nifi/src/app/pages/parameter-contexts/ui/parameter-context-listing/parameter-context-table/parameter-context-table.component.spec.ts
nifi-nar-bundles/nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-frontend/src/main/nifi/src/app/pages/parameter-contexts/ui/parameter-context-listing/parameter-context-table/parameter-context-table.component.ts
nifi-nar-bundles/nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-frontend/src/main/nifi/src/app/pages/settings/ui/reporting-tasks/reporting-task-table/reporting-task-table.component.html
nifi-nar-bundles/nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-frontend/src/main/nifi/src/app/pages/settings/ui/reporting-tasks/reporting-task-table/reporting-task-table.component.spec.ts
nifi-nar-bundles/nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-frontend/src/main/nifi/src/app/pages/settings/ui/reporting-tasks/reporting-task-table/reporting-task-table.component.ts
nifi-nar-bundles/nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-frontend/src/main/nifi/src/app/ui/common/controller-service/controller-service-table/controller-service-table.component.html
nifi-nar-bundles/nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-frontend/src/main/nifi/src/app/ui/common/controller-service/controller-service-table/controller-service-table.component.ts
nifi-nar-bundles/nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-frontend/src/main/nifi/src/app/ui/common/extension-creation/extension-creation.component.html
nifi-nar-bundles/nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-frontend/src/main/nifi/src/app/ui/common/extension-creation/extension-creation.component.ts

[NIFI-12615](https://issues.apache.org/jira/browse/NIFI-12615)
Fixed the `EpressionChangedAfterItHasBeenCheckedError` on the Counters page by implementing our own sorting.

[NIFI-12615] - fix ExpressionChanged error on Counters page.

---

nifi-python-extensions/nifi-text-embeddings-module/src/main/python/vectorstores/QueryPinecone.py

[NIFI-12629](https://issues.apache.org/jira/browse/NIFI-12629) - adding metadata filtering to QueryPinecone

NIFI-12629 - adding metadata filtering to QueryPinecone

---

nifi-nar-bundles/nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-frontend/src/main/nifi/src/app/pages/access-policies/service/access-policy.service.ts
nifi-nar-bundles/nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-frontend/src/main/nifi/src/app/pages/access-policies/state/access-policy/access-policy.actions.ts
nifi-nar-bundles/nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-frontend/src/main/nifi/src/app/pages/access-policies/state/access-policy/access-policy.effects.ts
nifi-nar-bundles/nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-frontend/src/main/nifi/src/app/pages/access-policies/ui/common/override-policy-dialog/override-policy-dialog.component.html
nifi-nar-bundles/nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-frontend/src/main/nifi/src/app/pages/access-policies/ui/common/override-policy-dialog/override-policy-dialog.component.scss
nifi-nar-bundles/nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-frontend/src/main/nifi/src/app/pages/access-policies/ui/common/override-policy-dialog/override-policy-dialog.component.spec.ts
nifi-nar-bundles/nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-frontend/src/main/nifi/src/app/pages/access-policies/ui/common/override-policy-dialog/override-policy-dialog.component.ts
nifi-nar-bundles/nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-frontend/src/main/nifi/src/app/pages/access-policies/ui/component-access-policies/component-access-policies.component.html
nifi-nar-bundles/nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-frontend/src/main/nifi/src/app/pages/access-policies/ui/component-access-policies/component-access-policies.component.ts
nifi-nar-bundles/nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-frontend/src/main/nifi/src/app/pages/access-policies/ui/global-access-policies/global-access-policies.component.html
nifi-nar-bundles/nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-frontend/src/main/nifi/src/app/pages/access-policies/ui/global-access-policies/global-access-policies.component.ts

NIFI-12679:
- When overriding a policy prompting whether the new policy should copy the users and groups or if it should be empty.

NIFI-12679: Prompt to copy policy during override

---

nifi-nar-bundles/nifi-framework-bundle/nifi-framework/nifi-web/pom.xml

Added an exclusion for a recently added file
nifi-nar-bundles/nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-frontend/src/main/nifi/.prettierignore
[NIFI-12701](https://issues.apache.org/jira/browse/NIFI-12701)

NIFI-12701 add .prettierignore to exclude list

---

nifi-nar-bundles/nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-frontend/src/main/nifi/src/app/pages/flow-designer/state/flow/flow.actions.ts
nifi-nar-bundles/nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-frontend/src/main/nifi/src/app/pages/flow-designer/state/flow/flow.effects.ts
nifi-nar-bundles/nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-frontend/src/main/nifi/src/app/pages/flow-designer/state/flow/flow.reducer.ts
nifi-nar-bundles/nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-frontend/src/main/nifi/src/app/pages/flow-designer/state/flow/index.ts

[NIFI-12694](https://issues.apache.org/jira/browse/NIFI-12694)

[NIFI-12694] - Fix console errors when starting/stopping process groups

---

nifi-nar-bundles/nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-frontend/src/main/nifi/src/app/pages/flow-designer/service/controller-service.service.ts
nifi-nar-bundles/nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-frontend/src/main/nifi/src/app/pages/flow-designer/service/parameter-helper.service.ts
nifi-nar-bundles/nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-frontend/src/main/nifi/src/app/pages/flow-designer/state/controller-services/controller-services.actions.ts
nifi-nar-bundles/nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-frontend/src/main/nifi/src/app/pages/flow-designer/state/controller-services/controller-services.effects.ts
nifi-nar-bundles/nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-frontend/src/main/nifi/src/app/pages/flow-designer/state/controller-services/controller-services.reducer.ts
nifi-nar-bundles/nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-frontend/src/main/nifi/src/app/pages/flow-designer/state/controller-services/controller-services.selectors.ts
nifi-nar-bundles/nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-frontend/src/main/nifi/src/app/pages/flow-designer/state/controller-services/index.ts
nifi-nar-bundles/nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-frontend/src/main/nifi/src/app/pages/flow-designer/state/flow/flow.effects.ts
nifi-nar-bundles/nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-frontend/src/main/nifi/src/app/pages/flow-designer/state/parameter/index.ts
nifi-nar-bundles/nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-frontend/src/main/nifi/src/app/pages/flow-designer/state/parameter/parameter.effects.ts
nifi-nar-bundles/nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-frontend/src/main/nifi/src/app/pages/flow-designer/state/parameter/parameter.reducer.ts
nifi-nar-bundles/nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-frontend/src/main/nifi/src/app/pages/flow-designer/ui/controller-service/controller-services.component.html
nifi-nar-bundles/nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-frontend/src/main/nifi/src/app/pages/flow-designer/ui/controller-service/controller-services.component.ts
nifi-nar-bundles/nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-frontend/src/main/nifi/src/app/pages/settings/state/management-controller-services/management-controller-services.effects.ts
nifi-nar-bundles/nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-frontend/src/main/nifi/src/app/state/contoller-service-state/controller-service-state.actions.ts
nifi-nar-bundles/nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-frontend/src/main/nifi/src/app/state/contoller-service-state/controller-service-state.effects.ts
nifi-nar-bundles/nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-frontend/src/main/nifi/src/app/state/contoller-service-state/controller-service-state.reducer.ts
nifi-nar-bundles/nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-frontend/src/main/nifi/src/app/state/contoller-service-state/index.ts

NIFI-12684:
- Handling error responses in the service listing on the canvas.
- Handling error responses when converting a Property value to a Parameter.

NIFI-12684: Handling error responses in the service listing on the canvas

---

nifi-nar-bundles/nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-frontend/src/main/nifi/src/app/pages/flow-designer/service/canvas-context-menu.service.ts
nifi-nar-bundles/nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-frontend/src/main/nifi/src/app/pages/flow-designer/service/canvas-utils.service.ts
nifi-nar-bundles/nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-frontend/src/main/nifi/src/app/pages/flow-designer/service/canvas-view.service.ts
nifi-nar-bundles/nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-frontend/src/main/nifi/src/app/pages/flow-designer/service/manager/connection-manager.service.ts
nifi-nar-bundles/nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-frontend/src/main/nifi/src/app/pages/flow-designer/state/flow/flow.actions.ts
nifi-nar-bundles/nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-frontend/src/main/nifi/src/app/pages/flow-designer/state/flow/flow.effects.ts
nifi-nar-bundles/nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-frontend/src/main/nifi/src/app/pages/flow-designer/state/flow/flow.reducer.ts
nifi-nar-bundles/nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-frontend/src/main/nifi/src/app/pages/flow-designer/state/flow/flow.selectors.ts
nifi-nar-bundles/nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-frontend/src/main/nifi/src/app/pages/flow-designer/state/flow/index.ts
nifi-nar-bundles/nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-frontend/src/main/nifi/src/app/pages/flow-designer/ui/canvas/canvas.component.ts
nifi-nar-bundles/nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-frontend/src/main/nifi/src/app/pages/flow-designer/ui/canvas/header/flow-status/flow-status.component.spec.ts
nifi-nar-bundles/nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-frontend/src/main/nifi/src/app/pages/flow-designer/ui/canvas/header/search/search.component.html
nifi-nar-bundles/nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-frontend/src/main/nifi/src/app/pages/flow-designer/ui/canvas/header/search/search.component.spec.ts
nifi-nar-bundles/nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-frontend/src/main/nifi/src/app/pages/flow-designer/ui/canvas/header/search/search.component.ts
nifi-nar-bundles/nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-frontend/src/main/nifi/src/app/ui/common/navigation/navigation.component.html
nifi-nar-bundles/nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-frontend/src/main/nifi/src/app/ui/common/navigation/navigation.component.ts

NIFI-12737:
- Removing all transitions when updating the Canvas transform.

NIFI-12737: Removing all transitions when updating the Canvas transform

---

nifi-nar-bundles/nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-frontend/src/main/nifi/src/app/app.component.ts
nifi-nar-bundles/nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-frontend/src/main/nifi/src/app/pages/flow-designer/state/transform/transform.effects.ts
nifi-nar-bundles/nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-frontend/src/main/nifi/src/app/pages/flow-designer/ui/canvas/graph-controls/navigation-control/navigation-control.component.ts
nifi-nar-bundles/nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-frontend/src/main/nifi/src/app/pages/flow-designer/ui/canvas/graph-controls/operation-control/operation-control.component.ts
nifi-nar-bundles/nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-frontend/src/main/nifi/src/app/service/storage.service.ts
nifi-nar-bundles/nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-frontend/src/main/nifi/src/app/service/theming.service.ts
nifi-nar-bundles/nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-frontend/src/main/nifi/src/app/ui/common/navigation/navigation.component.html
nifi-nar-bundles/nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-frontend/src/main/nifi/src/app/ui/common/navigation/navigation.component.ts
nifi-nar-bundles/nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-frontend/src/main/nifi/src/assets/themes/nifi.scss
nifi-nar-bundles/nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-frontend/src/main/nifi/src/assets/themes/purple.scss
nifi-nar-bundles/nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-frontend/src/main/nifi/src/styles.scss

NIFI-12727
Detect theme from OS settings. Add user override option persisted in local storage.

[NIFI-12727] Detect theme based on OS setting, allow user override

---

nifi-nar-bundles/nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-frontend/src/main/nifi/src/app/pages/queue/state/queue-listing/index.ts
nifi-nar-bundles/nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-frontend/src/main/nifi/src/app/pages/queue/state/queue-listing/queue-listing.actions.ts
nifi-nar-bundles/nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-frontend/src/main/nifi/src/app/pages/queue/state/queue-listing/queue-listing.effects.ts
nifi-nar-bundles/nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-frontend/src/main/nifi/src/app/pages/queue/state/queue-listing/queue-listing.reducer.ts
nifi-nar-bundles/nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-frontend/src/main/nifi/src/app/pages/queue/state/queue-listing/queue-listing.selectors.ts
nifi-nar-bundles/nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-frontend/src/main/nifi/src/app/pages/queue/ui/queue-listing/flowfile-table/flowfile-table.component.html
nifi-nar-bundles/nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-frontend/src/main/nifi/src/app/pages/queue/ui/queue-listing/flowfile-table/flowfile-table.component.spec.ts
nifi-nar-bundles/nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-frontend/src/main/nifi/src/app/pages/queue/ui/queue-listing/flowfile-table/flowfile-table.component.ts
nifi-nar-bundles/nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-frontend/src/main/nifi/src/app/pages/queue/ui/queue-listing/queue-listing.component.html
nifi-nar-bundles/nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-frontend/src/main/nifi/src/app/pages/queue/ui/queue-listing/queue-listing.component.ts
nifi-nar-bundles/nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-frontend/src/main/nifi/src/app/pages/queue/ui/queue-listing/queue-listing.module.ts
nifi-nar-bundles/nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-frontend/src/main/nifi/src/app/pages/summary/service/cluster-summary.service.ts
nifi-nar-bundles/nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-frontend/src/main/nifi/src/app/pages/summary/service/process-group-status.service.ts
nifi-nar-bundles/nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-frontend/src/main/nifi/src/app/pages/summary/state/summary-listing/index.ts
nifi-nar-bundles/nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-frontend/src/main/nifi/src/app/pages/summary/state/summary-listing/summary-listing.actions.ts
nifi-nar-bundles/nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-frontend/src/main/nifi/src/app/pages/summary/state/summary-listing/summary-listing.effects.ts
nifi-nar-bundles/nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-frontend/src/main/nifi/src/app/pages/summary/state/summary-listing/summary-listing.reducer.ts
nifi-nar-bundles/nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-frontend/src/main/nifi/src/app/pages/users/state/user-listing/index.ts
nifi-nar-bundles/nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-frontend/src/main/nifi/src/app/pages/users/state/user-listing/user-listing.actions.ts
nifi-nar-bundles/nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-frontend/src/main/nifi/src/app/pages/users/state/user-listing/user-listing.effects.ts
nifi-nar-bundles/nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-frontend/src/main/nifi/src/app/pages/users/state/user-listing/user-listing.reducer.ts
nifi-nar-bundles/nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-frontend/src/main/nifi/src/app/pages/users/state/user-listing/user-listing.selectors.ts
nifi-nar-bundles/nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-frontend/src/main/nifi/src/app/ui/common/edit-tenant/edit-tenant-dialog.component.html
nifi-nar-bundles/nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-frontend/src/main/nifi/src/app/ui/common/edit-tenant/edit-tenant-dialog.component.spec.ts
nifi-nar-bundles/nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-frontend/src/main/nifi/src/app/ui/common/edit-tenant/edit-tenant-dialog.component.ts

NIFI-12742: 
- Error Handling in Summary, Users, and Queue Listing

NIFI-12742: Error Handling in Summary, Users, and Queue Listing

---

nifi-nar-bundles/nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-frontend/src/main/nifi/src/app/pages/flow-designer/ui/canvas/header/search/search.component.ts

This PR fixes a bug that causes the search input to close when the user clicks on the field.

[NIFI-12746] fix search UX bug

---

nifi-nar-bundles/nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-frontend/src/main/nifi/src/app/pages/flow-designer/service/canvas-context-menu.service.ts
nifi-nar-bundles/nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-frontend/src/main/nifi/src/app/pages/flow-designer/service/flow.service.ts
nifi-nar-bundles/nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-frontend/src/main/nifi/src/app/pages/flow-designer/state/flow/flow.actions.ts
nifi-nar-bundles/nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-frontend/src/main/nifi/src/app/pages/flow-designer/state/flow/flow.effects.ts
nifi-nar-bundles/nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-frontend/src/main/nifi/src/app/pages/flow-designer/state/flow/index.ts

[NIFI-12759] go to RPG

---

nifi-nar-bundles/nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-frontend/src/main/nifi/src/app/pages/flow-designer/state/flow/flow.actions.ts
nifi-nar-bundles/nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-frontend/src/main/nifi/src/app/pages/flow-designer/state/flow/flow.effects.ts
nifi-nar-bundles/nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-frontend/src/main/nifi/src/app/pages/flow-designer/ui/canvas/items/remote-process-group/create-remote-process-group/create-remote-process-group.component.ts
nifi-nar-bundles/nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-frontend/src/main/nifi/src/app/pages/flow-designer/ui/canvas/items/remote-process-group/edit-remote-process-group/edit-remote-process-group.component.html
nifi-nar-bundles/nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-frontend/src/main/nifi/src/app/pages/flow-designer/ui/canvas/items/remote-process-group/edit-remote-process-group/edit-remote-process-group.component.scss
nifi-nar-bundles/nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-frontend/src/main/nifi/src/app/pages/flow-designer/ui/canvas/items/remote-process-group/edit-remote-process-group/edit-remote-process-group.component.spec.ts
nifi-nar-bundles/nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-frontend/src/main/nifi/src/app/pages/flow-designer/ui/canvas/items/remote-process-group/edit-remote-process-group/edit-remote-process-group.component.ts

[NIFI-12774] configure RPG

---

nifi-nar-bundles/nifi-couchbase-bundle/nifi-couchbase-processors/src/main/resources/docs/org.apache.nifi.couchbase.CouchbaseMapCacheClient/additionalDetails.html

[NIFI-12789](https://issues.apache.org/jira/browse/NIFI-12789) - fix broken link in couchbase additional details

NIFI-12789 - fix broken link in couchbase additional details

---

nifi-nar-bundles/nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-frontend/src/main/nifi/src/app/_app.component-theme.scss
nifi-nar-bundles/nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-frontend/src/main/nifi/src/app/state/error/error.effects.ts
nifi-nar-bundles/nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-frontend/src/main/nifi/src/assets/styles/_app.scss
nifi-nar-bundles/nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-frontend/src/main/nifi/src/assets/utils.scss

Removed unnecessary rules and class. The snackbars will be styled by Angular Material.
[NIFI-12912](https://issues.apache.org/jira/browse/NIFI-12912)

NIFI-12912 snackbar bug

---

nifi-nar-bundles/nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-frontend/src/main/nifi/proxy.config.mjs
nifi-nar-bundles/nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-frontend/src/main/nifi/src/app/pages/parameter-contexts/state/parameter-context-listing/index.ts
nifi-nar-bundles/nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-frontend/src/main/nifi/src/app/pages/parameter-contexts/state/parameter-context-listing/parameter-context-listing.actions.ts
nifi-nar-bundles/nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-frontend/src/main/nifi/src/app/pages/parameter-contexts/state/parameter-context-listing/parameter-context-listing.effects.ts
nifi-nar-bundles/nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-frontend/src/main/nifi/src/app/pages/parameter-contexts/state/parameter-context-listing/parameter-context-listing.reducer.ts
nifi-nar-bundles/nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-frontend/src/main/nifi/src/app/pages/parameter-contexts/state/parameter-context-listing/parameter-context-listing.selectors.ts
nifi-nar-bundles/nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-frontend/src/main/nifi/src/app/pages/parameter-contexts/ui/parameter-context-listing/edit-parameter-context/edit-parameter-context.component.html
nifi-nar-bundles/nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-frontend/src/main/nifi/src/app/pages/parameter-contexts/ui/parameter-context-listing/edit-parameter-context/edit-parameter-context.component.ts
nifi-nar-bundles/nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-frontend/src/main/nifi/src/app/pages/parameter-contexts/ui/parameter-context-listing/parameter-context-table/parameter-context-table.component.ts
nifi-nar-bundles/nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-frontend/src/main/nifi/src/app/ui/common/controller-service/disable-controller-service/disable-controller-service.component.html
nifi-nar-bundles/nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-frontend/src/main/nifi/src/app/ui/common/controller-service/enable-controller-service/enable-controller-service.component.html
nifi-nar-bundles/nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-frontend/src/main/nifi/src/assets/styles/_app.scss
nifi-nar-bundles/nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-frontend/src/main/nifi/src/assets/utils.scss

NIFI-12937:
- Adding error handling to the Parameter Context Listing page.

NIFI-12937: Adding error handling to the Parameter Context Listing page

---

nifi-nar-bundles/nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-frontend/src/main/nifi/proxy.config.mjs
nifi-nar-bundles/nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-frontend/src/main/nifi/src/app/pages/access-policies/ui/common/override-policy-dialog/override-policy-dialog.component.ts
nifi-nar-bundles/nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-frontend/src/main/nifi/src/app/pages/counters/ui/counter-listing/counter-table/counter-table.component.html
nifi-nar-bundles/nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-frontend/src/main/nifi/src/app/pages/flow-configuration-history/state/flow-configuration-history-listing/index.ts
nifi-nar-bundles/nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-frontend/src/main/nifi/src/app/pages/flow-configuration-history/ui/flow-configuration-history-listing/action-details/action-details.component.html
nifi-nar-bundles/nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-frontend/src/main/nifi/src/app/pages/flow-configuration-history/ui/flow-configuration-history-listing/action-details/action-details.component.ts
nifi-nar-bundles/nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-frontend/src/main/nifi/src/app/pages/flow-configuration-history/ui/flow-configuration-history-listing/flow-configuration-history-table/flow-configuration-history-table.component.ts
nifi-nar-bundles/nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-frontend/src/main/nifi/src/app/service/guard/flow-configuration.guard.ts
nifi-nar-bundles/nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-frontend/src/main/nifi/src/app/ui/common/edit-tenant/edit-tenant-dialog.component.html
nifi-nar-bundles/nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-frontend/src/main/nifi/src/assets/utils.scss

NIFI-12948:
- Action is optional.
- Removing duplicate check in counter table.
- Ensure flow configuration is loaded in route guard.
- Only show user/group list when there are users or groups.
- Default override policy to copy.

NIFI-12948: Various bugs discovered when migrating to Angular 17

---

nifi-nar-bundles/nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-frontend/src/main/nifi/proxy.config.mjs
nifi-nar-bundles/nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-frontend/src/main/nifi/src/app/pages/flow-designer/service/controller-service.service.ts
nifi-nar-bundles/nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-frontend/src/main/nifi/src/app/pages/flow-designer/service/flow.service.ts
nifi-nar-bundles/nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-frontend/src/main/nifi/src/app/pages/flow-designer/state/controller-services/controller-services.effects.ts
nifi-nar-bundles/nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-frontend/src/main/nifi/src/app/pages/flow-designer/state/flow/flow.effects.ts
nifi-nar-bundles/nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-frontend/src/main/nifi/src/app/pages/settings/service/management-controller-service.service.ts
nifi-nar-bundles/nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-frontend/src/main/nifi/src/app/service/controller-service-state.service.ts
nifi-nar-bundles/nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-frontend/src/main/nifi/src/assets/utils.scss

NIFI-12950:
- Updating front end to use the uiOnly flag where possible.

NIFI-12950: Updating front end to use the uiOnly flag where possible

---

nifi-nar-bundles/nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-frontend/src/main/nifi/jest.config.ts
nifi-nar-bundles/nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-frontend/src/main/nifi/package-lock.json
nifi-nar-bundles/nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-frontend/src/main/nifi/package.json
nifi-nar-bundles/nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-frontend/src/main/nifi/setup-jest.ts

[NIFI-12941](https://issues.apache.org/jira/browse/NIFI-12941)

[NIFI-12941] - adding in jest-preset-angular to enable unit testing in Idea based IDEs

---

nifi-nar-bundles/nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-frontend/src/main/nifi/src/app/pages/flow-designer/service/canvas-context-menu.service.ts
nifi-nar-bundles/nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-frontend/src/main/nifi/src/app/pages/flow-designer/service/canvas-utils.service.ts
nifi-nar-bundles/nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-frontend/src/main/nifi/src/app/pages/flow-designer/service/flow.service.ts
nifi-nar-bundles/nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-frontend/src/main/nifi/src/app/pages/flow-designer/state/flow/flow.actions.ts
nifi-nar-bundles/nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-frontend/src/main/nifi/src/app/pages/flow-designer/state/flow/flow.effects.ts
nifi-nar-bundles/nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-frontend/src/main/nifi/src/app/pages/flow-designer/state/flow/flow.reducer.ts
nifi-nar-bundles/nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-frontend/src/main/nifi/src/app/pages/flow-designer/state/flow/flow.selectors.ts
nifi-nar-bundles/nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-frontend/src/main/nifi/src/app/pages/flow-designer/state/flow/index.ts
nifi-nar-bundles/nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-frontend/src/main/nifi/src/app/pages/flow-designer/ui/canvas/items/flow/import-from-registry/import-from-registry.component.ts
nifi-nar-bundles/nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-frontend/src/main/nifi/src/app/pages/flow-designer/ui/canvas/items/flow/save-version-dialog/_save-version-dialog.component-theme.scss
nifi-nar-bundles/nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-frontend/src/main/nifi/src/app/pages/flow-designer/ui/canvas/items/flow/save-version-dialog/save-version-dialog.component.html
nifi-nar-bundles/nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-frontend/src/main/nifi/src/app/pages/flow-designer/ui/canvas/items/flow/save-version-dialog/save-version-dialog.component.scss
nifi-nar-bundles/nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-frontend/src/main/nifi/src/app/pages/flow-designer/ui/canvas/items/flow/save-version-dialog/save-version-dialog.component.spec.ts
nifi-nar-bundles/nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-frontend/src/main/nifi/src/app/pages/flow-designer/ui/canvas/items/flow/save-version-dialog/save-version-dialog.component.ts
nifi-nar-bundles/nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-frontend/src/main/nifi/src/app/state/shared/index.ts
nifi-nar-bundles/nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-frontend/src/main/nifi/src/styles.scss

[NIFI-12963](https://issues.apache.org/jira/browse/NIFI-12963)
* Start version control
* Stop version control
* Commit local changes
* (Force) Commit local changes
_Not done in this PR (these will be tacked as part of [NIFI-12995](https://issues.apache.org/jira/browse/NIFI-12995))_
* Show local changes
* Revert local changes
* Change version

[NIFI-12963] Process Group Versioning

---

nifi-nar-bundles/nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-frontend/src/main/nifi/src/app/pages/flow-designer/service/manager/process-group-manager.service.ts
nifi-nar-bundles/nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-frontend/src/main/nifi/src/app/pages/flow-designer/ui/canvas/header/flow-status/flow-status.component.html
nifi-nar-bundles/nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-frontend/src/main/nifi/src/app/pages/flow-designer/ui/common/breadcrumbs/breadcrumbs.component.ts
nifi-nar-bundles/nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-frontend/src/main/nifi/src/app/pages/login/ui/login-form/login-form.component.html
nifi-nar-bundles/nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-frontend/src/main/nifi/src/app/pages/settings/ui/general/general-form/general-form.component.html
nifi-nar-bundles/nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-frontend/src/main/nifi/src/app/pages/summary/ui/process-group-status-listing/process-group-status-table/process-group-status-table.component.ts
nifi-nar-bundles/nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-frontend/src/main/nifi/src/assets/styles/_listing-table.scss
nifi-nar-bundles/nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-frontend/src/main/nifi/src/styles.scss

[NIFI-12956] update to mat-button on general settings and login forms

---

nifi-nar-bundles/nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-frontend/src/main/nifi/.prettierrc
nifi-nar-bundles/nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-frontend/src/main/nifi/package-lock.json
nifi-nar-bundles/nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-frontend/src/main/nifi/package.json
nifi-nar-bundles/nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-frontend/src/main/nifi/project.json
nifi-nar-bundles/nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-frontend/src/main/nifi/src/app/pages/flow-designer/service/canvas-context-menu.service.ts
nifi-nar-bundles/nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-frontend/src/main/nifi/src/app/pages/flow-designer/service/flow.service.ts
nifi-nar-bundles/nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-frontend/src/main/nifi/src/app/pages/flow-designer/state/flow/flow.actions.ts
nifi-nar-bundles/nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-frontend/src/main/nifi/src/app/pages/flow-designer/state/flow/flow.effects.ts
nifi-nar-bundles/nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-frontend/src/main/nifi/src/app/pages/flow-designer/state/flow/flow.reducer.ts
nifi-nar-bundles/nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-frontend/src/main/nifi/src/app/pages/flow-designer/state/flow/flow.selectors.ts
nifi-nar-bundles/nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-frontend/src/main/nifi/src/app/pages/flow-designer/state/flow/index.ts
nifi-nar-bundles/nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-frontend/src/main/nifi/src/app/pages/flow-designer/ui/canvas/items/flow/change-version-dialog/change-version-dialog.html
nifi-nar-bundles/nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-frontend/src/main/nifi/src/app/pages/flow-designer/ui/canvas/items/flow/change-version-dialog/change-version-dialog.scss
nifi-nar-bundles/nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-frontend/src/main/nifi/src/app/pages/flow-designer/ui/canvas/items/flow/change-version-dialog/change-version-dialog.spec.ts
nifi-nar-bundles/nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-frontend/src/main/nifi/src/app/pages/flow-designer/ui/canvas/items/flow/change-version-dialog/change-version-dialog.ts
nifi-nar-bundles/nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-frontend/src/main/nifi/src/app/pages/flow-designer/ui/canvas/items/flow/change-version-progress-dialog/change-version-progress-dialog.html
nifi-nar-bundles/nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-frontend/src/main/nifi/src/app/pages/flow-designer/ui/canvas/items/flow/change-version-progress-dialog/change-version-progress-dialog.scss
nifi-nar-bundles/nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-frontend/src/main/nifi/src/app/pages/flow-designer/ui/canvas/items/flow/change-version-progress-dialog/change-version-progress-dialog.spec.ts
nifi-nar-bundles/nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-frontend/src/main/nifi/src/app/pages/flow-designer/ui/canvas/items/flow/change-version-progress-dialog/change-version-progress-dialog.ts
nifi-nar-bundles/nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-frontend/src/main/nifi/src/app/pages/flow-designer/ui/canvas/items/flow/local-changes-dialog/local-changes-dialog.html
nifi-nar-bundles/nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-frontend/src/main/nifi/src/app/pages/flow-designer/ui/canvas/items/flow/local-changes-dialog/local-changes-dialog.scss
nifi-nar-bundles/nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-frontend/src/main/nifi/src/app/pages/flow-designer/ui/canvas/items/flow/local-changes-dialog/local-changes-dialog.spec.ts
nifi-nar-bundles/nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-frontend/src/main/nifi/src/app/pages/flow-designer/ui/canvas/items/flow/local-changes-dialog/local-changes-dialog.ts
nifi-nar-bundles/nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-frontend/src/main/nifi/src/app/pages/flow-designer/ui/canvas/items/flow/local-changes-dialog/local-changes-table/local-changes-table.html
nifi-nar-bundles/nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-frontend/src/main/nifi/src/app/pages/flow-designer/ui/canvas/items/flow/local-changes-dialog/local-changes-table/local-changes-table.scss
nifi-nar-bundles/nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-frontend/src/main/nifi/src/app/pages/flow-designer/ui/canvas/items/flow/local-changes-dialog/local-changes-table/local-changes-table.spec.ts
nifi-nar-bundles/nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-frontend/src/main/nifi/src/app/pages/flow-designer/ui/canvas/items/flow/local-changes-dialog/local-changes-table/local-changes-table.ts
nifi-nar-bundles/nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-frontend/src/main/nifi/src/app/pages/flow-designer/ui/canvas/items/flow/save-version-dialog/save-version-dialog.component.html
nifi-nar-bundles/nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-frontend/src/main/nifi/src/app/service/nifi-common.service.ts

[NIFI-12995](https://issues.apache.org/jira/browse/NIFI-12995)
Also update the configuration around prettier so it will format html properly when it contains angular flow syntax.

[NIFI-12995]- Change Flow Version, Show Local Changes, Revert local changes

---

nifi-nar-bundles/nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-frontend/src/main/nifi/src/app/state/component-state/index.ts
nifi-nar-bundles/nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-frontend/src/main/nifi/src/app/ui/common/component-state/component-state.component.html
nifi-nar-bundles/nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-frontend/src/main/nifi/src/app/ui/common/component-state/component-state.component.ts

NIFI-13005:
- Adding support for showing cluster state in the component state dialog.

NIFI-13005: Cluster State in Component State Dialog

---

nifi-nar-bundles/nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-frontend/src/main/nifi/src/app/pages/flow-designer/service/canvas-context-menu.service.ts
nifi-nar-bundles/nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-frontend/src/main/nifi/src/app/pages/flow-designer/service/canvas-utils.service.ts
nifi-nar-bundles/nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-frontend/src/main/nifi/src/app/pages/flow-designer/service/flow.service.ts
nifi-nar-bundles/nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-frontend/src/main/nifi/src/app/pages/flow-designer/state/flow/flow.actions.ts
nifi-nar-bundles/nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-frontend/src/main/nifi/src/app/pages/flow-designer/state/flow/flow.effects.ts
nifi-nar-bundles/nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-frontend/src/main/nifi/src/app/pages/flow-designer/state/flow/index.ts

[NIFI-13029](https://issues.apache.org/jira/browse/NIFI-13029)

[NIFI-13029] download flow

---

nifi-nar-bundles/nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-frontend/src/main/nifi/src/app/pages/flow-designer/service/canvas-context-menu.service.ts
nifi-nar-bundles/nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-frontend/src/main/nifi/src/app/pages/flow-designer/service/canvas-utils.service.ts
nifi-nar-bundles/nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-frontend/src/main/nifi/src/app/pages/flow-designer/service/manager/connection-manager.service.ts
nifi-nar-bundles/nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-frontend/src/main/nifi/src/app/pages/flow-designer/service/manager/label-manager.service.ts
nifi-nar-bundles/nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-frontend/src/main/nifi/src/app/pages/flow-designer/state/flow/flow.actions.ts
nifi-nar-bundles/nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-frontend/src/main/nifi/src/app/pages/flow-designer/state/flow/flow.effects.ts
nifi-nar-bundles/nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-frontend/src/main/nifi/src/app/pages/flow-designer/state/flow/flow.selectors.ts
nifi-nar-bundles/nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-frontend/src/main/nifi/src/app/pages/flow-designer/state/flow/index.ts

NIFI-13044:
- Adding support to move to front.
- Fixing revisions sent in various payloads.

NIFI-13044: Adding support to move to front

---

nifi-nar-bundles/nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-frontend/src/main/nifi/src/app/pages/flow-designer/service/canvas-context-menu.service.ts
nifi-nar-bundles/nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-frontend/src/main/nifi/src/app/pages/flow-designer/service/canvas-utils.service.ts
nifi-nar-bundles/nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-frontend/src/main/nifi/src/app/pages/flow-designer/service/canvas-view.service.ts
nifi-nar-bundles/nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-frontend/src/main/nifi/src/app/pages/flow-designer/service/flow.service.ts
nifi-nar-bundles/nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-frontend/src/main/nifi/src/app/pages/flow-designer/service/snippet.service.ts
nifi-nar-bundles/nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-frontend/src/main/nifi/src/app/pages/flow-designer/state/flow/flow.actions.ts
nifi-nar-bundles/nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-frontend/src/main/nifi/src/app/pages/flow-designer/state/flow/flow.effects.ts
nifi-nar-bundles/nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-frontend/src/main/nifi/src/app/pages/flow-designer/state/flow/flow.reducer.ts
nifi-nar-bundles/nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-frontend/src/main/nifi/src/app/pages/flow-designer/state/flow/flow.selectors.ts
nifi-nar-bundles/nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-frontend/src/main/nifi/src/app/pages/flow-designer/state/flow/index.ts
nifi-nar-bundles/nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-frontend/src/main/nifi/src/app/pages/flow-designer/ui/canvas/graph-controls/operation-control/operation-control.component.html
nifi-nar-bundles/nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-frontend/src/main/nifi/src/app/pages/flow-designer/ui/canvas/graph-controls/operation-control/operation-control.component.ts
nifi-nar-bundles/nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-frontend/src/main/nifi/src/app/pages/flow-designer/ui/canvas/header/new-canvas-item/new-canvas-item.component.ts
nifi-nar-bundles/nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-frontend/src/main/nifi/src/app/ui/common/tooltips/property-tip/property-tip.component.html

NIFI-13059:
- Adding support for copying and pasting on the canvas.

NIFI-13059: Adding support for copying and pasting on the canvas

---

nifi-nar-bundles/nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-frontend/src/main/nifi/src/app/pages/flow-designer/service/behavior/connectable-behavior.service.ts
nifi-nar-bundles/nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-frontend/src/main/nifi/src/app/pages/flow-designer/service/behavior/draggable-behavior.service.ts
nifi-nar-bundles/nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-frontend/src/main/nifi/src/app/pages/flow-designer/service/manager/connection-manager.service.ts
nifi-nar-bundles/nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-frontend/src/main/nifi/src/app/pages/flow-designer/state/flow/flow.actions.ts
nifi-nar-bundles/nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-frontend/src/main/nifi/src/app/pages/flow-designer/state/flow/flow.effects.ts
nifi-nar-bundles/nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-frontend/src/main/nifi/src/app/pages/flow-designer/state/flow/index.ts
nifi-nar-bundles/nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-frontend/src/main/nifi/src/app/pages/flow-designer/ui/canvas/items/connection/create-connection/create-connection.component.ts

NIFI-13065:
- Adding initial bend points for self looping connections and connections that collide with existing connections.
- Merging two actions into one for opening the new connection dialog.

NIFI-13065: Adding initial bend points for self looping connections and connections that collide with existing connections

---

nifi-nar-bundles/nifi-opentelemetry-bundle/nifi-opentelemetry-processors/src/main/java/org/apache/nifi/processors/opentelemetry/server/HttpRequestHandler.java

[NIFI-13076](https://issues.apache.org/jira/browse/NIFI-13076)
reduce enum array allocation
cache enum .values() in a static variable
https://www.gamlor.info/wordpress/2017/08/javas-enum-values-hidden-allocations/
https://github.com/apache/pinot/pull/12579
https://github.com/apache/iceberg/pull/10126

NIFI-13076: reduce enum array allocation

---

nifi-nar-bundles/nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-frontend/src/main/nifi/src/app/pages/provenance/ui/provenance-event-listing/provenance-event-table/lineage/lineage.component.ts

NIFI-13074:
- Resetting the transform when navigating from the lineage to the event listing.

NIFI-13074: Resetting the transform when navigating from the lineage to the event listing

---

nifi-nar-bundles/nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-frontend/src/main/nifi/src/app/pages/provenance/service/provenance.service.ts
nifi-nar-bundles/nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-frontend/src/main/nifi/src/app/pages/queue/service/queue.service.ts
nifi-nar-bundles/nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-ui/src/main/webapp/js/nf/canvas/nf-queue-listing.js
nifi-nar-bundles/nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-ui/src/main/webapp/js/nf/provenance/nf-provenance-table.js

NIFI-13085:
- When viewing content, defaulting the Mode to 'Formatted'.

NIFI-13085: When viewing content, defaulting the Mode to 'Formatted'

---

.github/PULL_REQUEST_TEMPLATE.md
nifi-nar-bundles/nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-frontend/src/main/nifi/README.md
nifi-nar-bundles/nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-frontend/src/main/nifi/project.json

NIFI-13089:
- Updating PR Template and README for new UI.

NIFI-13089: Updating PR Template and README for new UI

---

nifi-nar-bundles/nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-frontend/src/main/nifi/src/app/pages/access-policies/feature/access-policies.component.ts
nifi-nar-bundles/nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-frontend/src/main/nifi/src/app/pages/access-policies/ui/component-access-policies/component-access-policies.component.ts
nifi-nar-bundles/nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-frontend/src/main/nifi/src/app/pages/access-policies/ui/global-access-policies/global-access-policies.component.ts
nifi-nar-bundles/nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-frontend/src/main/nifi/src/app/pages/bulletins/feature/bulletins.component.spec.ts
nifi-nar-bundles/nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-frontend/src/main/nifi/src/app/pages/bulletins/feature/bulletins.component.ts
nifi-nar-bundles/nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-frontend/src/main/nifi/src/app/pages/counters/feature/counters.component.ts
nifi-nar-bundles/nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-frontend/src/main/nifi/src/app/pages/flow-designer/feature/flow-designer.component.ts
nifi-nar-bundles/nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-frontend/src/main/nifi/src/app/pages/flow-designer/ui/canvas/canvas.component.ts
nifi-nar-bundles/nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-frontend/src/main/nifi/src/app/pages/flow-designer/ui/controller-service/controller-services.component.ts
nifi-nar-bundles/nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-frontend/src/main/nifi/src/app/pages/flow-designer/ui/manage-remote-ports/manage-remote-ports.component.ts
nifi-nar-bundles/nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-frontend/src/main/nifi/src/app/pages/parameter-contexts/feature/parameter-contexts.component.ts
nifi-nar-bundles/nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-frontend/src/main/nifi/src/app/pages/parameter-contexts/ui/parameter-context-listing/parameter-context-listing.component.ts
nifi-nar-bundles/nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-frontend/src/main/nifi/src/app/pages/provenance/feature/provenance.component.ts
nifi-nar-bundles/nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-frontend/src/main/nifi/src/app/pages/queue/feature/queue.component.ts
nifi-nar-bundles/nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-frontend/src/main/nifi/src/app/pages/settings/feature/settings.component.ts
nifi-nar-bundles/nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-frontend/src/main/nifi/src/app/pages/settings/ui/management-controller-services/management-controller-services.component.ts
nifi-nar-bundles/nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-frontend/src/main/nifi/src/app/pages/settings/ui/parameter-providers/parameter-providers.component.ts
nifi-nar-bundles/nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-frontend/src/main/nifi/src/app/pages/settings/ui/reporting-tasks/reporting-tasks.component.ts
nifi-nar-bundles/nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-frontend/src/main/nifi/src/app/pages/summary/feature/summary.component.ts
nifi-nar-bundles/nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-frontend/src/main/nifi/src/app/pages/users/feature/users.component.ts
nifi-nar-bundles/nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-frontend/src/main/nifi/src/app/pages/users/ui/user-listing/user-listing.component.ts
nifi-nar-bundles/nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-frontend/src/main/nifi/src/app/ui/common/navigation/navigation.component.ts

NIFI-13055:
- Moving the loading of flow configuration out of individual pages and into the navigation component which requires it for rendering the Users and Policies menu item.

NIFI-13055: Moving the loading of flow configuration out of individual pages and into the navigation component

---

nifi-docs/src/main/asciidoc/administration-guide.adoc
nifi-nar-bundles/nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-security/src/main/java/org/apache/nifi/web/security/configuration/AuthenticationSecurityConfiguration.java
nifi-nar-bundles/nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-security/src/main/java/org/apache/nifi/web/security/configuration/ClientRegistrationConfiguration.java
nifi-nar-bundles/nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-security/src/main/java/org/apache/nifi/web/security/configuration/JwtAuthenticationSecurityConfiguration.java
nifi-nar-bundles/nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-security/src/main/java/org/apache/nifi/web/security/configuration/JwtDecoderConfiguration.java
nifi-nar-bundles/nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-security/src/main/java/org/apache/nifi/web/security/configuration/OidcSecurityConfiguration.java
nifi-nar-bundles/nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-security/src/main/java/org/apache/nifi/web/security/jwt/converter/StandardIssuerJwtDecoder.java
nifi-nar-bundles/nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-security/src/main/java/org/apache/nifi/web/security/oidc/authentication/AccessTokenDecoderFactory.java
nifi-nar-bundles/nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-security/src/main/java/org/apache/nifi/web/security/oidc/authentication/StandardOidcIdTokenDecoderFactory.java
nifi-nar-bundles/nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-security/src/test/java/org/apache/nifi/web/security/jwt/converter/StandardIssuerJwtDecoderTest.java

[NIFI-5302](https://issues.apache.org/jira/browse/NIFI-5302) Adds supports for the [OAuth 2.0 Client Credentials Flow](https://www.oauth.com/oauth2-servers/access-tokens/client-credentials/) when NiFi is configured for [OpenID Connect](https://openid.net/specs/openid-connect-core-1_0.html) authentication.
The implementation changes maintain existing support for the [Authorization Code Grant Flow](https://www.oauth.com/oauth2-servers/server-side-apps/authorization-code/) as part of standard browser-based access, but enable machine-to-machine authentication using Client Credentials. Most of the code changes involve reorganizing the OIDC and JWT configuration objects for reuse between configuration classes.
The configuration changes support verifying Access Tokens based on the provided …

NIFI-5302 Add Support for Client Credentials Flow with OIDC

---

nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-frontend/src/main/nifi/src/app/pages/access-policies/state/access-policy/access-policy.actions.ts
nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-frontend/src/main/nifi/src/app/pages/access-policies/state/access-policy/access-policy.effects.ts
nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-frontend/src/main/nifi/src/app/pages/access-policies/state/access-policy/access-policy.reducer.ts
nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-frontend/src/main/nifi/src/app/pages/access-policies/state/access-policy/index.ts
nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-frontend/src/main/nifi/src/app/pages/access-policies/state/policy-component/index.ts
nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-frontend/src/main/nifi/src/app/pages/access-policies/state/policy-component/policy-component.actions.ts
nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-frontend/src/main/nifi/src/app/pages/access-policies/state/policy-component/policy-component.effects.ts
nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-frontend/src/main/nifi/src/app/pages/access-policies/state/policy-component/policy-component.reducer.ts
nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-frontend/src/main/nifi/src/app/pages/access-policies/state/tenants/index.ts
nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-frontend/src/main/nifi/src/app/pages/access-policies/state/tenants/tenants.actions.ts
nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-frontend/src/main/nifi/src/app/pages/access-policies/state/tenants/tenants.effects.ts
nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-frontend/src/main/nifi/src/app/pages/access-policies/state/tenants/tenants.reducer.ts
nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-frontend/src/main/nifi/src/app/pages/access-policies/ui/component-access-policies/component-access-policies.component.html
nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-frontend/src/main/nifi/src/app/pages/access-policies/ui/component-access-policies/component-access-policies.component.ts
nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-frontend/src/main/nifi/src/app/pages/access-policies/ui/component-access-policies/component-access-policies.module.ts
nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-frontend/src/main/nifi/src/app/pages/access-policies/ui/global-access-policies/global-access-policies.component.html
nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-frontend/src/main/nifi/src/app/pages/access-policies/ui/global-access-policies/global-access-policies.component.ts
nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-frontend/src/main/nifi/src/app/pages/access-policies/ui/global-access-policies/global-access-policies.module.ts

NIFI-13098:
- Updating error handling in Global and Component Policy pages.

NIFI-13098: Updating error handling in Global and Component Policy pages

---

nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-frontend/src/main/nifi/src/app/pages/flow-designer/service/behavior/draggable-behavior.service.ts
nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-frontend/src/main/nifi/src/app/pages/flow-designer/service/canvas-context-menu.service.ts
nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-frontend/src/main/nifi/src/app/pages/flow-designer/service/manager/connection-manager.service.ts
nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-frontend/src/main/nifi/src/app/pages/flow-designer/service/manager/label-manager.service.ts
nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-frontend/src/main/nifi/src/app/pages/flow-designer/state/flow/flow.actions.ts
nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-frontend/src/main/nifi/src/app/pages/flow-designer/state/flow/flow.effects.ts
nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-frontend/src/main/nifi/src/app/pages/flow-designer/state/flow/flow.reducer.ts
nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-frontend/src/main/nifi/src/app/pages/flow-designer/state/flow/flow.selectors.ts
nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-frontend/src/main/nifi/src/app/pages/flow-designer/state/flow/index.ts
nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-frontend/src/main/nifi/src/app/pages/flow-designer/ui/canvas/graph-controls/operation-control/operation-control.component.ts
nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-frontend/src/main/nifi/src/app/pages/flow-designer/ui/canvas/header/new-canvas-item/new-canvas-item.component.ts
nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-frontend/src/main/nifi/src/app/pages/flow-designer/ui/canvas/items/connection/create-connection/create-connection.component.html
nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-frontend/src/main/nifi/src/app/pages/flow-designer/ui/canvas/items/connection/create-connection/create-connection.component.ts
nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-frontend/src/main/nifi/src/app/pages/flow-designer/ui/canvas/items/connection/edit-connection/edit-connection.component.html
nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-frontend/src/main/nifi/src/app/pages/flow-designer/ui/canvas/items/connection/edit-connection/edit-connection.component.ts
nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-frontend/src/main/nifi/src/app/pages/flow-designer/ui/canvas/items/label/edit-label/edit-label.component.ts
nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-frontend/src/main/nifi/src/app/pages/flow-designer/ui/canvas/items/port/edit-port/edit-port.component.ts
nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-frontend/src/main/nifi/src/app/pages/flow-designer/ui/canvas/items/process-group/edit-process-group/edit-process-group.component.html
nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-frontend/src/main/nifi/src/app/pages/flow-designer/ui/canvas/items/process-group/edit-process-group/edit-process-group.component.spec.ts
nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-frontend/src/main/nifi/src/app/pages/flow-designer/ui/canvas/items/process-group/edit-process-group/edit-process-group.component.ts

NIFI-13100:
- Updating API response error handling for canvas based actions.

NIFI-13100: Updating API response error handling for canvas based actions

---

nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-frontend/src/main/nifi/src/app/pages/flow-designer/ui/canvas/items/connection/source/source-processor/source-processor.component.ts

NIFI-13110:
- Auto-selecting the relationship when the source processor only offers a single relationship.

NIFI-13110: Auto-selecting the relationship when the source processor only offers a single relationship

---

nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-frontend/src/main/nifi/src/app/pages/access-policies/state/access-policy/access-policy.effects.ts
nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-frontend/src/main/nifi/src/app/pages/access-policies/ui/component-access-policies/component-access-policies.component.ts

NIFI-12833:
- Reloading current user when any policy changes.
- Reloading the component for the policy whenever it's view permissions changes.

NIFI-12833: Ensuring permissions are updated when policies are changed

---

nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-frontend/src/main/nifi/src/app/pages/flow-designer/ui/canvas/header/search/search.component.html
nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-frontend/src/main/nifi/src/app/pages/flow-designer/ui/canvas/header/search/search.component.ts
nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-frontend/src/main/nifi/src/app/state/shared/index.ts
nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-frontend/src/main/nifi/src/app/ui/common/tooltips/search-match-tip/search-match-tip.component.html
nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-frontend/src/main/nifi/src/app/ui/common/tooltips/search-match-tip/search-match-tip.component.scss
nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-frontend/src/main/nifi/src/app/ui/common/tooltips/search-match-tip/search-match-tip.component.spec.ts
nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-frontend/src/main/nifi/src/app/ui/common/tooltips/search-match-tip/search-match-tip.component.ts

NIFI-13112:
- Fixing linking to non canvas items.
- Adding a tooltip to render search match details.

NIFI-13112: Fixing linking to non canvas items

---

nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-frontend/src/main/nifi/src/app/pages/flow-designer/service/manager/processor-manager.service.ts

NIFI-13114:
- Always show primary node indicator when configured

NIFI-13114: Always show primary node indicator when configured

---

nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-frontend/src/main/nifi/src/app/pages/flow-designer/service/canvas-context-menu.service.ts
nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-frontend/src/main/nifi/src/app/pages/flow-designer/ui/canvas/graph-controls/operation-control/operation-control.component.html
nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-frontend/src/main/nifi/src/app/pages/summary/ui/connection-status-listing/connection-status-table/connection-status-table.component.html
nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-frontend/src/main/nifi/src/app/pages/summary/ui/process-group-status-listing/process-group-status-table/process-group-status-table.component.html
nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-frontend/src/main/nifi/src/app/pages/summary/ui/processor-status-listing/processor-status-table/processor-status-table.component.html

NIFI-13111:
- Removing/Hiding unimplemented features in preparation for next milestone release.

NIFI-13111: Removing/Hiding unimplemented features in preparation for next milestone release

---

nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-frontend/src/main/nifi/src/app/pages/settings/ui/parameter-providers/fetch-parameter-provider-parameters/fetch-parameter-provider-parameters.component.html

[NIFI-13122] use accent color for checkbox on top of primary color

---

nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-frontend/src/main/nifi/src/app/pages/parameter-contexts/ui/parameter-context-listing/parameter-table/parameter-table.component.html
nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-frontend/src/main/nifi/src/app/pages/parameter-contexts/ui/parameter-context-listing/parameter-table/parameter-table.component.spec.ts
nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-frontend/src/main/nifi/src/app/pages/parameter-contexts/ui/parameter-context-listing/parameter-table/parameter-table.component.ts
nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-frontend/src/main/nifi/src/app/ui/common/edit-parameter-dialog/edit-parameter-dialog.component.ts

[NIFI-13134](https://issues.apache.org/jira/browse/NIFI-13134)
Also included in this PR:
[NIFI-13135](https://issues.apache.org/jira/browse/NIFI-13135) - Allow parameter table to be sortable by parameter name

[NIFI-13134] - Support No Value Set in Edit Parameter Context. 

---

nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-frontend/src/main/nifi/src/app/pages/flow-designer/ui/canvas/items/connection/prioritizers/prioritizers.component.ts

[NIFI-13129](https://issues.apache.org/jira/browse/NIFI-13129)

[NIFI-13129] - Fix: selected prioritizer order is not honored when displayed in the UI

---

nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-frontend/src/main/nifi/src/app/pages/flow-designer/ui/canvas/items/process-group/edit-process-group/edit-process-group.component.ts
nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-frontend/src/main/nifi/src/app/pages/flow-designer/ui/canvas/items/processor/edit-processor/edit-processor.component.spec.ts
nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-frontend/src/main/nifi/src/app/pages/parameter-contexts/ui/parameter-context-listing/edit-parameter-context/edit-parameter-context.component.spec.ts
nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-frontend/src/main/nifi/src/app/pages/settings/ui/flow-analysis-rules/edit-flow-analysis-rule/edit-flow-analysis-rule.component.spec.ts
nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-frontend/src/main/nifi/src/app/pages/settings/ui/registry-clients/edit-registry-client/edit-registry-client.component.spec.ts
nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-frontend/src/main/nifi/src/app/pages/settings/ui/reporting-tasks/edit-reporting-task/edit-reporting-task.component.spec.ts
nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-frontend/src/main/nifi/src/app/ui/common/controller-service/disable-controller-service/disable-controller-service.component.ts
nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-frontend/src/main/nifi/src/app/ui/common/controller-service/edit-controller-service/edit-controller-service.component.spec.ts
nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-frontend/src/main/nifi/src/app/ui/common/controller-service/enable-controller-service/enable-controller-service.component.ts
nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-frontend/src/main/nifi/src/app/ui/common/property-table/editors/nf-editor/_nf-editor.component-theme.scss
nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-frontend/src/main/nifi/src/app/ui/common/property-table/editors/nf-editor/modes/nfel.ts
nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-frontend/src/main/nifi/src/app/ui/common/property-table/editors/nf-editor/nf-editor.component.html
nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-frontend/src/main/nifi/src/app/ui/common/property-table/editors/nf-editor/nf-editor.component.scss
nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-frontend/src/main/nifi/src/app/ui/common/property-table/editors/nf-editor/nf-editor.component.spec.ts
nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-frontend/src/main/nifi/src/app/ui/common/property-table/editors/nf-editor/nf-editor.component.ts
nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-frontend/src/main/nifi/src/app/ui/common/property-table/property-table.component.spec.ts
nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-frontend/src/main/nifi/src/app/ui/common/property-table/property-table.component.ts
nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-frontend/src/main/nifi/src/main.ts

NIFI-13136:
- Allowing users to unset optional property values.
- Only selecting value and applying focus if it is not read only.

NIFI-13136: Allowing users to unset optional property values

---

nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-frontend/src/main/nifi/src/app/service/error-helper.service.ts
nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-frontend/src/main/nifi/src/app/service/guard/authorization.guard.ts
nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-frontend/src/main/nifi/src/app/service/guard/flow-configuration.guard.ts
nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-frontend/src/main/nifi/src/app/state/error/error.actions.ts
nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-frontend/src/main/nifi/src/app/state/error/error.effects.ts

NIFI-13140:
- Cleaning up error handling in guards.

NIFI-13140: Cleaning up error handling in guards

---

nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-frontend/src/main/nifi/src/app/pages/flow-designer/service/manager/connection-manager.service.ts
nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-frontend/src/main/nifi/src/app/pages/flow-designer/service/manager/label-manager.service.ts
nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-frontend/src/main/nifi/src/app/pages/flow-designer/ui/canvas/items/connection/source/source-processor/source-processor.component.html

NIFI-13141:
- Adding a dragging flag to not reset positioning for labels and connection bends if the user is currently performing an action.

NIFI-13141: Adding a dragging flag to not reset positioning for labels and connection bends if the user is currently performing an action

---

nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-frontend/src/main/nifi/README.md
nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-frontend/src/main/nifi/src/app/pages/flow-designer/service/canvas-actions.service.ts
nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-frontend/src/main/nifi/src/app/pages/flow-designer/service/canvas-context-menu.service.ts
nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-frontend/src/main/nifi/src/app/pages/flow-designer/service/canvas-utils.service.ts
nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-frontend/src/main/nifi/src/app/pages/flow-designer/state/flow/flow.effects.ts
nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-frontend/src/main/nifi/src/app/pages/flow-designer/ui/canvas/canvas.component.ts
nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-frontend/src/main/nifi/src/app/pages/flow-designer/ui/canvas/graph-controls/operation-control/operation-control.component.ts
nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-frontend/src/main/nifi/src/app/ui/common/context-menu/context-menu.component.html
nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-frontend/src/main/nifi/src/app/ui/common/context-menu/context-menu.component.ts

* removed aliasing of 'this' from canvas.component.ts
* removed aliasing of 'this' from canvas-utils.ts
* reuse common actions between operation and context menu
https://issues.apache.org/jira/browse/NIFI-13158

[NIFI-13158] support for keyboard shortcuts for canvas actions

---

nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-frontend/src/main/nifi/src/app/pages/flow-designer/service/behavior/draggable-behavior.service.ts
nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-frontend/src/main/nifi/src/app/pages/flow-designer/service/canvas-context-menu.service.ts
nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-frontend/src/main/nifi/src/app/pages/flow-designer/service/canvas-utils.service.ts
nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-frontend/src/main/nifi/src/app/pages/flow-designer/state/flow/flow.effects.ts

[NIFI-13162] horizontal and vertical canvas component alignment

---

nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-frontend/src/main/nifi/src/app/pages/flow-designer/ui/canvas/canvas.component.ts

[NIFI-13158](https://issues.apache.org/jira/browse/NIFI-13158)

[NIFI-13158] - Fix: need to prevent/disable keyboard hotkeys when a dialog is open or when typing in the search bar.

---

nifi-framework-bundle/nifi-framework/nifi-framework-cluster/src/main/java/org/apache/nifi/cluster/coordination/http/replication/ThreadPoolRequestReplicator.java

[NIFI-13195](https://issues.apache.org/jira/browse/NIFI-13195) Corrects HTTP header and cookie removal in the `ThreadPoolRequestReplicator` so that it works as expected regardless of HTTP protocol version.
Changes include a new method to find a matching header name regardless of case, which works with both HTTP/1.1 and HTTP/2 requests.

NIFI-13195 Correct Replicated Request Header Removal for HTTP/2

---

nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-frontend/src/main/nifi/src/app/pages/flow-designer/service/canvas-context-menu.service.ts
nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-frontend/src/main/nifi/src/app/pages/flow-designer/service/flow.service.ts
nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-frontend/src/main/nifi/src/app/pages/flow-designer/state/flow/flow.actions.ts
nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-frontend/src/main/nifi/src/app/pages/flow-designer/state/flow/flow.effects.ts
nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-frontend/src/main/nifi/src/app/pages/flow-designer/state/flow/index.ts

NIFI-13204:
- Adding the Enable/Disable All Controller Service context menu items.

NIFI-13204: Adding the Enable/Disable All Controller Service context menu items

---

nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-frontend/src/main/nifi/src/app/pages/flow-designer/ui/canvas/items/connection/create-connection/create-connection.component.html
nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-frontend/src/main/nifi/src/app/pages/flow-designer/ui/canvas/items/connection/destination/destination-funnel/destination-funnel.component.html
nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-frontend/src/main/nifi/src/app/pages/flow-designer/ui/canvas/items/connection/destination/destination-output-port/destination-output-port.component.html
nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-frontend/src/main/nifi/src/app/pages/flow-designer/ui/canvas/items/connection/destination/destination-process-group/destination-process-group.component.html
nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-frontend/src/main/nifi/src/app/pages/flow-designer/ui/canvas/items/connection/destination/destination-processor/destination-processor.component.html
nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-frontend/src/main/nifi/src/app/pages/flow-designer/ui/canvas/items/connection/destination/destination-remote-process-group/destination-remote-process-group.component.html
nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-frontend/src/main/nifi/src/app/pages/flow-designer/ui/canvas/items/connection/edit-connection/edit-connection.component.html
nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-frontend/src/main/nifi/src/app/pages/flow-designer/ui/canvas/items/connection/source/source-funnel/source-funnel.component.html
nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-frontend/src/main/nifi/src/app/pages/flow-designer/ui/canvas/items/connection/source/source-input-port/source-input-port.component.html
nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-frontend/src/main/nifi/src/app/pages/flow-designer/ui/canvas/items/connection/source/source-process-group/source-process-group.component.html
nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-frontend/src/main/nifi/src/app/pages/flow-designer/ui/canvas/items/connection/source/source-processor/source-processor.component.html
nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-frontend/src/main/nifi/src/app/pages/flow-designer/ui/canvas/items/connection/source/source-remote-process-group/source-remote-process-group.component.html
nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-frontend/src/main/nifi/src/app/ui/common/property-table/property-table.component.html
nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-frontend/src/main/nifi/src/app/ui/common/status-history/status-history.component.html

[NIFI-13153] use ellipsis for long component names in dialogs

---

nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-frontend/src/main/nifi/src/app/pages/flow-designer/ui/canvas/canvas.component.html
nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-frontend/src/main/nifi/src/app/pages/flow-designer/ui/canvas/canvas.component.scss
nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-frontend/src/main/nifi/src/app/pages/flow-designer/ui/canvas/footer/_footer.component-theme.scss
nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-frontend/src/main/nifi/src/app/pages/flow-designer/ui/canvas/graph-controls/graph-controls.component.scss
nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-frontend/src/main/nifi/src/app/pages/flow-designer/ui/canvas/header/new-canvas-item/new-canvas-item.component.scss

[NIFI-13212] handle canvas overflow on shorter screens

---

nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-frontend/src/main/nifi/src/app/pages/flow-designer/service/canvas-context-menu.service.ts
nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-frontend/src/main/nifi/src/app/ui/common/context-menu/context-menu.component.html
nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-frontend/src/main/nifi/src/app/ui/common/context-menu/context-menu.component.ts

[NIFI-13221](https://issues.apache.org/jira/browse/NIFI-13221)

[NIFI-13221] - display supported shortcut/hotkey combos in context menu

---

nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-frontend/src/main/nifi/src/app/pages/flow-designer/state/flow/flow.effects.ts
nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-frontend/src/main/nifi/src/app/state/shared/index.ts

[NIFI-13229](https://issues.apache.org/jira/browse/NIFI-13229)

[NIFI-13229] - Include branch when submitting to save version control endpoint

---

nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-frontend/src/main/nifi/src/app/pages/flow-designer/ui/canvas/items/connection/edit-connection/edit-connection.component.ts
nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-frontend/src/main/nifi/src/app/ui/common/close-on-escape-dialog/close-on-escape-dialog.component.ts

[NIFI-13243](https://issues.apache.org/jira/browse/NIFI-13243)

[NIFI-13243] - support cancel response in CloseOnEscapeDialog

---

nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-frontend/src/main/nifi/src/app/pages/flow-designer/ui/canvas/items/flow/change-version-dialog/change-version-dialog.html

[NIFI-13233](https://issues.apache.org/jira/browse/NIFI-13233)

[NIFI-13233] - Fix for overflow issues on change version dialog

---

nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-frontend/src/main/nifi/src/app/pages/flow-designer/service/canvas-actions.service.ts
nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-frontend/src/main/nifi/src/app/pages/flow-designer/service/canvas-context-menu.service.ts
nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-frontend/src/main/nifi/src/app/pages/flow-designer/service/canvas-utils.service.ts
nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-frontend/src/main/nifi/src/app/pages/flow-designer/service/manager/processor-manager.service.ts
nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-frontend/src/main/nifi/src/app/pages/flow-designer/state/flow/flow.actions.ts
nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-frontend/src/main/nifi/src/app/pages/flow-designer/state/flow/flow.effects.ts
nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-frontend/src/main/nifi/src/app/pages/flow-designer/state/flow/index.ts
nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-frontend/src/main/nifi/src/app/pages/flow-designer/ui/canvas/change-color-dialog/_change-color-dialog.component-theme.scss
nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-frontend/src/main/nifi/src/app/pages/flow-designer/ui/canvas/change-color-dialog/change-color-dialog.component.html
nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-frontend/src/main/nifi/src/app/pages/flow-designer/ui/canvas/change-color-dialog/change-color-dialog.component.scss
nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-frontend/src/main/nifi/src/app/pages/flow-designer/ui/canvas/change-color-dialog/change-color-dialog.component.spec.ts
nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-frontend/src/main/nifi/src/app/pages/flow-designer/ui/canvas/change-color-dialog/change-color-dialog.component.ts
nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-frontend/src/main/nifi/src/app/pages/flow-designer/ui/canvas/graph-controls/operation-control/operation-control.component.html
nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-frontend/src/main/nifi/src/app/pages/flow-designer/ui/canvas/graph-controls/operation-control/operation-control.component.ts
nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-frontend/src/main/nifi/src/app/pages/flow-designer/ui/canvas/items/remote-process-group/create-remote-process-group/create-remote-process-group.component.spec.ts
nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-frontend/src/main/nifi/src/app/pages/flow-designer/ui/canvas/items/remote-process-group/edit-remote-process-group/edit-remote-process-group.component.spec.ts
nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-frontend/src/main/nifi/src/styles.scss

[NIFI-13226](https://issues.apache.org/jira/browse/NIFI-13226)

[NIFI-13226] - Support changing color of processors and labels

---

nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-frontend/src/main/nifi/src/app/ui/common/property-table/editors/nf-editor/nf-editor.component.html
nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-frontend/src/main/nifi/src/app/ui/common/property-table/editors/nf-editor/nf-editor.component.scss
nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-frontend/src/main/nifi/src/app/ui/common/property-table/editors/nf-editor/nf-editor.component.ts
nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-frontend/src/main/nifi/src/app/ui/common/property-table/property-table.component.ts
nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-frontend/src/main/nifi/src/assets/styles/_codemirror-theme.scss

[NIFI-13276] improve property editor to handle large amounts of text

---

nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-frontend/src/main/nifi/src/app/pages/flow-designer/ui/canvas/items/connection/edit-connection/edit-connection.component.html
nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-frontend/src/main/nifi/src/app/pages/flow-designer/ui/canvas/items/connection/edit-connection/edit-connection.component.ts
nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-frontend/src/main/nifi/src/app/pages/flow-designer/ui/canvas/items/process-group/edit-process-group/edit-process-group.component.html
nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-frontend/src/main/nifi/src/app/pages/flow-designer/ui/canvas/items/process-group/edit-process-group/edit-process-group.component.ts
nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-frontend/src/main/nifi/src/app/pages/flow-designer/ui/canvas/items/processor/edit-processor/edit-processor.component.html
nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-frontend/src/main/nifi/src/app/pages/flow-designer/ui/canvas/items/processor/edit-processor/edit-processor.component.ts
nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-frontend/src/main/nifi/src/app/pages/parameter-contexts/ui/parameter-context-listing/edit-parameter-context/edit-parameter-context.component.html
nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-frontend/src/main/nifi/src/app/pages/parameter-contexts/ui/parameter-context-listing/edit-parameter-context/edit-parameter-context.component.ts
nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-frontend/src/main/nifi/src/app/pages/queue/ui/queue-listing/flowfile-dialog/flowfile-dialog.component.html
nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-frontend/src/main/nifi/src/app/pages/queue/ui/queue-listing/flowfile-dialog/flowfile-dialog.component.ts
nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-frontend/src/main/nifi/src/app/pages/settings/ui/flow-analysis-rules/edit-flow-analysis-rule/edit-flow-analysis-rule.component.html
nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-frontend/src/main/nifi/src/app/pages/settings/ui/flow-analysis-rules/edit-flow-analysis-rule/edit-flow-analysis-rule.component.ts
nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-frontend/src/main/nifi/src/app/pages/settings/ui/parameter-providers/edit-parameter-provider/edit-parameter-provider.component.html
nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-frontend/src/main/nifi/src/app/pages/settings/ui/parameter-providers/edit-parameter-provider/edit-parameter-provider.component.ts
nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-frontend/src/main/nifi/src/app/pages/settings/ui/registry-clients/edit-registry-client/edit-registry-client.component.html
nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-frontend/src/main/nifi/src/app/pages/settings/ui/registry-clients/edit-registry-client/edit-registry-client.component.ts
nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-frontend/src/main/nifi/src/app/pages/settings/ui/reporting-tasks/edit-reporting-task/edit-reporting-task.component.html
nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-frontend/src/main/nifi/src/app/pages/settings/ui/reporting-tasks/edit-reporting-task/edit-reporting-task.component.ts
nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-frontend/src/main/nifi/src/app/ui/common/controller-service/edit-controller-service/edit-controller-service.component.html
nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-frontend/src/main/nifi/src/app/ui/common/controller-service/edit-controller-service/edit-controller-service.component.ts
nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-frontend/src/main/nifi/src/app/ui/common/provenance-event-dialog/provenance-event-dialog.component.html
nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-frontend/src/main/nifi/src/app/ui/common/provenance-event-dialog/provenance-event-dialog.component.ts
nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-frontend/src/main/nifi/src/app/ui/common/system-diagnostics-dialog/system-diagnostics-dialog.component.html
nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-frontend/src/main/nifi/src/app/ui/common/system-diagnostics-dialog/system-diagnostics-dialog.component.ts
nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-frontend/src/main/nifi/src/app/ui/common/tabbed-dialog/tabbed-dialog.component.ts

NIFI-13270:
- Persisting the select tab index.

NIFI-13270: Persisting the select tab index

---

nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-frontend/src/main/nifi/src/app/pages/flow-designer/state/queue/queue.effects.ts

NIFI-13286:
- Conditionally reloading the child PG or current PG when emptying all queues based on the context of the request.

NIFI-13286: Conditionally reloading the child PG or current PG when emptying all queues

---

nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-frontend/src/main/nifi/src/app/ui/common/property-verification/property-verification.component.html

[NIFI-13303](https://issues.apache.org/jira/browse/NIFI-13303)

[NIFI-13303] - Remove text indicating property verification is disabled.

---

nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-frontend/src/main/nifi/src/app/app.component.ts
nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-frontend/src/main/nifi/src/app/ui/common/property-table/editors/combo-editor/combo-editor.component.ts
nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-frontend/src/main/nifi/src/app/ui/common/property-table/editors/nf-editor/modes/nfel.ts
nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-frontend/src/main/nifi/src/app/ui/common/property-table/editors/nf-editor/modes/nfpr.ts

[NIFI-13269](https://issues.apache.org/jira/browse/NIFI-13269)

[NIFI-13269] - Order parameter reference list alphabetically

---

nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-frontend/src/main/nifi/src/app/app.component.ts
nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-frontend/src/main/nifi/src/app/pages/flow-designer/ui/canvas/items/connection/create-connection/create-connection.component.html
nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-frontend/src/main/nifi/src/app/pages/flow-designer/ui/canvas/items/connection/create-connection/create-connection.component.ts
nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-frontend/src/main/nifi/src/app/pages/flow-designer/ui/canvas/items/connection/edit-connection/edit-connection.component.html
nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-frontend/src/main/nifi/src/app/pages/flow-designer/ui/canvas/items/connection/edit-connection/edit-connection.component.ts
nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-frontend/src/main/nifi/src/app/pages/flow-designer/ui/canvas/items/processor/edit-processor/edit-processor.component.html
nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-frontend/src/main/nifi/src/app/pages/flow-designer/ui/canvas/items/processor/edit-processor/edit-processor.component.ts
nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-frontend/src/main/nifi/src/app/pages/flow-designer/ui/canvas/items/processor/edit-processor/relationship-settings/relationship-settings.component.html

NIFI-13299:
- Adding min validators where appropriate.

NIFI-13299: Adding min validators where appropriate

---

nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-frontend/src/main/nifi/src/app/pages/flow-designer/ui/canvas/header/header.component.html
nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-frontend/src/main/nifi/src/app/pages/flow-designer/ui/canvas/header/new-canvas-item/new-canvas-item.component.html
nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-frontend/src/main/nifi/src/app/pages/flow-designer/ui/canvas/header/new-canvas-item/new-canvas-item.component.ts
nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-frontend/src/main/nifi/src/app/ui/common/tooltips/nifi-tooltip.directive.ts

[NIFI-13289](https://issues.apache.org/jira/browse/NIFI-13289)

NIFI-13289 Add tooltip to NewCanvas item

---

nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-frontend/src/main/nifi/apps/nifi/src/app/pages/flow-configuration-history/ui/flow-configuration-history-listing/flow-configuration-history-table/flow-configuration-history-table.component.html
nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-frontend/src/main/nifi/apps/nifi/src/app/pages/flow-configuration-history/ui/flow-configuration-history-listing/flow-configuration-history-table/flow-configuration-history-table.component.ts
nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-ui/src/main/webapp/js/nf/history/nf-history-table.js

[NIFI-11078](https://issues.apache.org/jira/browse/NIFI-11078)
Added Component UUID to flow configuration history table in old UI and new UI.

NIFI-11078: Adds Component UUID to Flow Configuration History Table

---

nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-frontend/src/main/nifi/apps/nifi/src/app/pages/flow-designer/service/manager/process-group-manager.service.ts
nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-frontend/src/main/nifi/apps/nifi/src/app/pages/flow-designer/state/controller-services/controller-services.effects.ts
nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-frontend/src/main/nifi/apps/nifi/src/app/pages/flow-designer/state/flow/flow.effects.ts
nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-frontend/src/main/nifi/apps/nifi/src/app/pages/parameter-contexts/state/parameter-context-listing/parameter-context-listing.effects.ts
nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-frontend/src/main/nifi/apps/nifi/src/app/pages/parameter-contexts/ui/parameter-context-listing/edit-parameter-context/edit-parameter-context.component.ts
nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-frontend/src/main/nifi/apps/nifi/src/app/service/nifi-common.service.ts

NIFI-13350:
- Allowing parameters to be edited in New Parameter Context dialog.
- Ensuring the proper tab is selected in the Parameter Context dialog based on the current usage.

NIFI-13350: Allowing parameters to be edited in New Parameter Context dialog

---

nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-frontend/src/main/nifi/apps/nifi/src/app/pages/queue/ui/queue-listing/flowfile-table/flowfile-table.component.scss

NIFI-13337:
- Adjust column widths of the queue listing table.

NIFI-13337: Adjust column widths of the queue listing table

---

nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-frontend/src/main/nifi/apps/nifi/src/app/pages/flow-designer/state/flow/flow.effects.ts
nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-frontend/src/main/nifi/apps/nifi/src/app/pages/flow-designer/ui/common/breadcrumbs/breadcrumbs.component.ts
nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-frontend/src/main/nifi/apps/nifi/src/app/pages/logout/feature/logout.module.ts

NIFI-13367:
- Updating the page title to align with the root Process Group.

NIFI-13367: Updating the page title to align with the root Process Group

---

nifi-nar-bundles/nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-ui/src/main/webapp/js/nf/canvas/header/components/nf-ng-group-component.js
nifi-nar-bundles/nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-ui/src/main/webapp/js/nf/canvas/nf-process-group-configuration.js
nifi-nar-bundles/nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-ui/src/main/webapp/js/nf/canvas/nf-settings.js

NIFI-13374:
- Fixing handling of description in tooltip.

NIFI-13374: Fixing handling of description in tooltip

---

nifi-frontend/src/main/frontend/apps/nifi/src/app/pages/summary/ui/common/summary-table-filter/summary-table-filter.component.html
nifi-frontend/src/main/frontend/apps/nifi/src/app/pages/summary/ui/common/summary-table-filter/summary-table-filter.component.ts
nifi-frontend/src/main/frontend/apps/nifi/src/app/pages/summary/ui/process-group-status-listing/process-group-status-table/process-group-status-table.component.html
nifi-frontend/src/main/frontend/apps/nifi/src/app/pages/summary/ui/process-group-status-listing/process-group-status-table/process-group-status-table.component.ts

[NIFI-13378](https://issues.apache.org/jira/browse/NIFI-13378)
Adds Version State as filterable option in Process Groups tab in Summary similar to Status filter.

NIFI-13378: Adds Version State as filterable option in Process Groups tab in Summary

---

nifi-frontend/pom.xml
nifi-frontend/src/main/frontend/.build.env
nifi-frontend/src/main/frontend/package-lock.json
nifi-frontend/src/main/frontend/package.json

NIFI-13385:
- Disabling nx daemon during builds.

NIFI-13385: Disabling nx daemon during builds

---

nifi-frontend/src/main/frontend/apps/nifi/src/app/service/interceptors/auth.interceptor.ts
nifi-frontend/src/main/frontend/apps/nifi/src/app/service/interceptors/polling.interceptor.ts

NIFI-13382:
- Showing a full page error when the front end can no longer communicate with the back end.

NIFI-13382: Showing a full page error when the front end can no longer communicate with the back end

---

nifi-frontend/src/main/frontend/apps/nifi/src/app/ui/common/map-table/map-table.component.ts

NIFI-13479:
- Remove unnecessary imports which was impacting the ability to use EL and Parameter autocomplete.

NIFI-13479: Remove imports to fix autocomplete issues

---

nifi-frontend/src/main/frontend/apps/nifi/src/app/pages/flow-designer/state/flow/flow.effects.ts

NIFI-13480:
- Taking the user to the Parameter Context dialog from the Parameters context menu on the canvas.

NIFI-13480: Taking the user to the Parameter Context dialog from the Parameters context menu on the canvas

---

nifi-frontend/src/main/frontend/apps/nifi/src/app/pages/provenance/state/lineage/lineage.effects.ts
nifi-frontend/src/main/frontend/apps/nifi/src/app/pages/provenance/state/provenance-event-listing/provenance-event-listing.effects.ts

NIFI-13552:
- Ensure errors from Provenance and Lineage queries are shown.

NIFI-13552: Ensure errors from Provenance and Lineage queries are shown

---

nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-security/src/main/java/org/apache/nifi/web/security/configuration/WebSecurityConfiguration.java

[NIFI-13558](https://issues.apache.org/jira/browse/NIFI-13558) Updates the framework `WebSecurityConfiguration` to ignore requests that do not require authentication.
The previous approach applied Spring Security filter processing to all requests, but permitted access without authentication to specific paths required for user interface configuration. This approach works for the majority of situations where the user interface makes initial requests without authentication. For certain edge cases, the client browser will continue to send a session cookie with an application bearer token that may be expired. In this situation, unauthenticated paths should continue to return the same results.
The implementation changes make use of the …

NIFI-13558 Configure Web Security to ignore unauthenticated requests

---

nifi-frontend/src/main/frontend/apps/nifi/src/app/pages/flow-designer/ui/common/breadcrumbs/breadcrumbs.component.html

[NIFI-13582](https://issues.apache.org/jira/browse/NIFI-13582)

[NIFI-13582] - Fix tracking expression warning from the breadcrumbs template

---

nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-api/src/main/java/org/apache/nifi/web/api/FlowResource.java

[NIFI-13602](https://issues.apache.org/jira/browse/NIFI-13602) Corrects the behavior of the `logoutSupported` property in the Current User REST API Response status when NiFi is running in a cluster.
Following changes for the new user interface in NiFi 2.0.0-M4, the Current User response includes a `logoutSupported` property that controls the visibility of the logout link. This is necessary as the REST API determines whether the client is presenting an Application Bearer Token or an X.509 Client Certificate for authentication.
When running in a cluster, a node replicates requests for the current user to all nodes, instead of using the local response status. With request replication using X.509 Client Certificates for cluster node requests, the `logoutSupported` property always returned …

NIFI-13602 Correct Logout Supported Status for Clustered User

---

nifi-frontend/src/main/frontend/apps/nifi/src/app/pages/flow-designer/service/canvas-context-menu.service.ts
nifi-frontend/src/main/frontend/apps/nifi/src/app/pages/flow-designer/service/canvas-utils.service.ts
nifi-frontend/src/main/frontend/apps/nifi/src/app/pages/flow-designer/ui/controller-service/controller-services.component.html
nifi-frontend/src/main/frontend/apps/nifi/src/app/pages/parameter-contexts/ui/parameter-context-listing/parameter-context-listing.component.html

NIFI-13610:
- Fix conditions controlling the availability of new Controller Service (in flow), new Parameter Context, and Move to Parent Group.

NIFI-13610: Fix conditions controlling the availability of new Controller Service (in flow), new Parameter Context, and Move to Parent Group

---

nifi-extension-bundles/nifi-standard-services/nifi-dbcp-service-bundle/nifi-hikari-dbcp-service/src/main/java/org/apache/nifi/dbcp/HikariCPConnectionPool.java
nifi-extension-bundles/nifi-standard-services/nifi-dbcp-service-bundle/nifi-hikari-dbcp-service/src/test/java/org/apache/nifi/dbcp/HikariCPConnectionPoolTest.java
nifi-mock/src/main/java/org/apache/nifi/util/MockControllerServiceLookup.java

[NIFI-13555](https://issues.apache.org/jira/browse/NIFI-13555) This PR adds verifiability to HikariDBCPConnectionPool for added capability and consistency with DBCPConnectionPool

NIFI-13555: Add verification to HikariDBCPConnectionPool

---

nifi-extension-bundles/nifi-opentelemetry-bundle/nifi-opentelemetry-processors/src/main/java/org/apache/nifi/processors/opentelemetry/server/HttpRequestHandler.java

[NIFI-13647](https://issues.apache.org/jira/browse/NIFI-13647) Improves the behavior of the `ListenOTLP` Processor when sending HTTP error responses the clients, removing the immediate server socket close listener. This behavior resulted intermittent unit test failures due to the server socket closing the connection before the test client completed reading the response. Removing the socket close step allows the server to follow the same handling steps as the completion of sending a successful response.

NIFI-13647 Remove Socket Close from ListenOTLP Error Responses

---

nifi-frontend/src/main/frontend/libs/shared/src/assets/themes/purple.scss

https://issues.apache.org/jira/browse/NIFI-13631

[NIFI-13631] update purple theme to reference M2 color palettes

---

nifi-frontend/src/main/frontend/apps/nifi-jolt-transform-ui/src/app/pages/jolt-transform-json-ui/feature/jolt-transform-json-ui.component.html

[NIFI-13637] add padding to Jolt UI expansion panels

---

nifi-frontend/src/main/frontend/apps/nifi-jolt-transform-ui/src/app/app.module.ts
nifi-frontend/src/main/frontend/apps/nifi-jolt-transform-ui/src/app/pages/jolt-transform-json-ui/feature/jolt-transform-json-ui.component.html
nifi-frontend/src/main/frontend/apps/nifi-jolt-transform-ui/src/app/pages/jolt-transform-json-ui/feature/jolt-transform-json-ui.component.ts
nifi-frontend/src/main/frontend/apps/nifi-jolt-transform-ui/src/app/pages/jolt-transform-json-ui/feature/jolt-transform-json-ui.module.ts
nifi-frontend/src/main/frontend/apps/nifi-jolt-transform-ui/src/app/pages/jolt-transform-json-ui/state/jolt-transform-json-processor-details/index.ts
nifi-frontend/src/main/frontend/apps/nifi-jolt-transform-ui/src/app/pages/jolt-transform-json-ui/state/jolt-transform-json-processor-details/jolt-transform-json-processor-details.actions.ts
nifi-frontend/src/main/frontend/apps/nifi-jolt-transform-ui/src/app/pages/jolt-transform-json-ui/state/jolt-transform-json-processor-details/jolt-transform-json-processor-details.effects.ts
nifi-frontend/src/main/frontend/apps/nifi-jolt-transform-ui/src/app/pages/jolt-transform-json-ui/state/jolt-transform-json-processor-details/jolt-transform-json-processor-details.reducer.ts
nifi-frontend/src/main/frontend/apps/nifi-jolt-transform-ui/src/app/pages/jolt-transform-json-ui/state/jolt-transform-json-processor-details/jolt-transform-json-processor-details.selectors.ts
nifi-frontend/src/main/frontend/apps/nifi-jolt-transform-ui/src/app/pages/jolt-transform-json-ui/state/jolt-transform-json-transform/index.ts
nifi-frontend/src/main/frontend/apps/nifi-jolt-transform-ui/src/app/pages/jolt-transform-json-ui/state/jolt-transform-json-transform/jolt-transform-json-transform.reducer.ts
nifi-frontend/src/main/frontend/apps/nifi-jolt-transform-ui/src/app/pages/jolt-transform-json-ui/state/jolt-transform-json-transform/jolt-transform-json-transform.selectors.ts
nifi-frontend/src/main/frontend/apps/nifi-jolt-transform-ui/src/app/pages/jolt-transform-json-ui/state/jolt-transform-json-validate/index.ts
nifi-frontend/src/main/frontend/apps/nifi-jolt-transform-ui/src/app/pages/jolt-transform-json-ui/state/jolt-transform-json-validate/jolt-transform-json-validate.reducer.ts
nifi-frontend/src/main/frontend/apps/nifi-jolt-transform-ui/src/app/pages/jolt-transform-json-ui/state/jolt-transform-json-validate/jolt-transform-json-validate.selectors.ts

[NIFI-13589] improve loading and error handling for jolt UI

---

nifi-nar-bundles/nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-ui/src/main/webapp/js/nf/canvas/nf-parameter-contexts.js

[NIFI-13675](https://issues.apache.org/jira/browse/NIFI-13675) - Fix tooltip for parameter description (NiFi 1.x)

NIFI-13675 - Fix tooltip for parameter description (NiFi 1.x)

---

nifi-docker/dockerhub/sh/start.sh

[NIFI-13681](https://issues.apache.org/jira/browse/NIFI-13681)
The Kubernetes-related coordination settings draw on environment variables that do not accurately reflect their property names, leading to confusion.

NIFI-13681 Fix Kubernetes coordination environment variable names

---

nifi-frontend/src/main/frontend/apps/nifi-jolt-transform-ui/setup-jest.ts
nifi-frontend/src/main/frontend/apps/nifi/setup-jest.ts
nifi-frontend/src/main/frontend/apps/nifi/src/app/service/client.service.ts
nifi-frontend/src/main/frontend/libs/shared/setup-jest.ts
nifi-frontend/src/main/frontend/package-lock.json
nifi-frontend/src/main/frontend/package.json

https://issues.apache.org/jira/browse/NIFI-13680

[NIFI-13680] Removing usage of crypto.randomUUID()

---

nifi-frontend/src/main/frontend/apps/nifi/src/app/ui/common/navigation/navigation.component.html

[NIFI-13693](https://issues.apache.org/jira/browse/NIFI-13693)

[NIFI-13693] - Remove System Diagnostics menu option when clustered

---

nifi-frontend/src/main/frontend/apps/nifi/src/app/pages/flow-designer/service/canvas-context-menu.service.ts
nifi-frontend/src/main/frontend/apps/nifi/src/app/pages/flow-designer/service/canvas-utils.service.ts
nifi-frontend/src/main/frontend/apps/nifi/src/app/pages/flow-designer/state/flow/flow.actions.ts
nifi-frontend/src/main/frontend/apps/nifi/src/app/pages/flow-designer/state/flow/flow.effects.ts
nifi-frontend/src/main/frontend/apps/nifi/src/app/pages/flow-designer/state/flow/flow.selectors.ts
nifi-frontend/src/main/frontend/apps/nifi/src/app/pages/flow-designer/ui/canvas/canvas-routing.module.ts
nifi-frontend/src/main/frontend/apps/nifi/src/app/pages/flow-designer/ui/canvas/canvas.component.ts

[NIFI-13624](https://issues.apache.org/jira/browse/NIFI-13624)
Added support in the context menu to view status history of the current process group.

[NIFI-13624] - Allow View Status History of the current process group.

---

nifi-extension-bundles/nifi-standard-bundle/nifi-standard-content-viewer/pom.xml
nifi-extension-bundles/nifi-standard-bundle/nifi-standard-content-viewer/src/main/java/org/apache/nifi/web/StandardContentViewerApplication.java

[NIFI-13725](https://issues.apache.org/jira/browse/NIFI-13725) Disables the Spring Boot [LoggingSystem](https://docs.spring.io/spring-boot/reference/features/logging.html#features.logging.custom-log-configuration) to avoid unnecessary initialization of Logback in the Standard Content Viewer application.

NIFI-13725 Disable Spring Logging System in Content Viewer

---

nifi-extension-bundles/nifi-update-attribute-bundle/nifi-update-attribute-processor/src/test/java/org/apache/nifi/update/attributes/TestUpdateAttribute.java

[NIFI-13730](https://issues.apache.org/jira/browse/NIFI-13730)

NIFI-13730 Refactor TestUpdateAttribute using current API methods

---

nifi-frontend/src/main/frontend/apps/standard-content-viewer/project.json

NIFI-13740: Fixing default build profile.

---

nifi-extension-bundles/nifi-gcp-bundle/pom.xml

[NIFI-13758](https://issues.apache.org/jira/browse/NIFI-13758)

NIFI-13758 Upgraded Google Cloud Libraries to 26.46.0

---

nifi-frontend/src/main/frontend/apps/nifi/src/app/pages/flow-configuration-history/state/flow-configuration-history-listing/flow-configuration-history-listing.effects.ts
nifi-frontend/src/main/frontend/apps/nifi/src/app/pages/flow-configuration-history/ui/flow-configuration-history-listing/purge-history/purge-history.component.html
nifi-frontend/src/main/frontend/apps/nifi/src/app/pages/flow-configuration-history/ui/flow-configuration-history-listing/purge-history/purge-history.component.ts

[NIFI-13749](https://issues.apache.org/jira/browse/NIFI-13749)

[NIFI-13749] - Improve the UX for purging flow configuation history

---

nifi-frontend/src/main/frontend/apps/nifi/src/app/pages/flow-designer/service/canvas-utils.service.ts
nifi-frontend/src/main/frontend/libs/shared/src/directives/nifi-tooltip.directive.ts
nifi-frontend/src/main/frontend/libs/shared/src/services/nifi-common.service.ts

[NIFI-13747](https://issues.apache.org/jira/browse/NIFI-13747)

[NIFI-13747] - Add a delay before displaying tooltips

---

nifi-frontend/src/main/frontend/apps/nifi/src/app/pages/provenance/ui/provenance-event-listing/provenance-search-dialog/provenance-search-dialog.component.html
nifi-frontend/src/main/frontend/apps/nifi/src/app/pages/provenance/ui/provenance-event-listing/provenance-search-dialog/provenance-search-dialog.component.ts

NIFI-13774: Accessed form controls using array notation in case the search field contains a dot.

NIFI-13766: Fixed spacing of checkboxes in Prov Search Dialog.

---

nifi-framework-bundle/nifi-framework-extensions/nifi-py4j-framework-bundle/nifi-python-extension-api/src/main/python/src/nifiapi/recordtransform.py
nifi-system-tests/nifi-system-test-suite/src/test/java/org/apache/nifi/tests/system/python/PythonProcessorIT.java

[NIFI-13714](https://issues.apache.org/jira/browse/NIFI-13714)

NIFI-13714 Fix RecordTransform python processor partition handling

---

nifi-frontend/src/main/frontend/apps/nifi/src/app/pages/flow-designer/service/canvas-utils.service.ts
nifi-frontend/src/main/frontend/apps/nifi/src/app/pages/flow-designer/ui/canvas/_canvas.component-theme.scss
nifi-frontend/src/main/frontend/apps/nifi/src/app/pages/flow-designer/ui/canvas/header/flow-status/_flow-status.component-theme.scss
nifi-frontend/src/main/frontend/apps/nifi/src/app/pages/flow-designer/ui/canvas/header/flow-status/flow-status.component.html
nifi-frontend/src/main/frontend/apps/nifi/src/app/pages/flow-designer/ui/canvas/header/flow-status/flow-status.component.ts
nifi-frontend/src/main/frontend/apps/nifi/src/app/ui/common/tooltips/bulletins-tip/bulletins-tip.component.scss

[NIFI-13772](https://issues.apache.org/jira/browse/NIFI-13772)

[NIFI-13772] - Color bulletin icons based on severity

---

nifi-commons/nifi-record/src/main/java/org/apache/nifi/serialization/record/util/DataTypeUtils.java

[NIFI-13781](https://issues.apache.org/jira/browse/NIFI-13781)

NIFI-13781 Updated DataTypeUtils with enhanced switch statements, pattern variables and some other minor formatting changes.

---

nifi-framework-bundle/nifi-framework/nifi-framework-cluster/src/main/java/org/apache/nifi/cluster/coordination/http/replication/ThreadPoolRequestReplicator.java
nifi-framework-bundle/nifi-framework/nifi-framework-cluster/src/main/java/org/apache/nifi/cluster/coordination/http/replication/client/StandardHttpReplicationClient.java
nifi-framework-bundle/nifi-framework/nifi-framework-cluster/src/main/java/org/apache/nifi/cluster/coordination/http/replication/io/ReplicatedResponse.java

[NIFI-13799](https://issues.apache.org/jira/browse/NIFI-13799) Improves replicated HTTP response handling for requests to cluster nodes, avoiding potential heap exhaustion when downloading large FlowFiles.
Instead of buffering the entire response body, the updated approach buffers responses with known content length values that are less than 1 MB. For streamed responses with an unknown content length, or large responses, the replication client returns the HTTP response stream. The changes also include a close callback to ensure that the replicated response stream is closed.

NIFI-13799 Improve Replicated Cluster Response Handling

---

nifi-frontend/src/main/frontend/apps/nifi/src/app/pages/settings/ui/parameter-providers/fetch-parameter-provider-parameters/fetch-parameter-provider-parameters.component.ts

[NIFI-13533](https://issues.apache.org/jira/browse/NIFI-13533)
This is tested/verified the easiest by setting up a DatabaseParameterProvider. I set up one that talks to a postgres db running in docker.
```bash
docker run --name my-pg -p 5432:5432 -it -e POSTGRES_PASSWORD=password -d postgres
```
then i seeded it with some data
```sql
drop table if exists public.parameters;
create table public.parameters(
groupName varchar(50) not null,
parameterName varchar(50) not null,
parameterValue varchar(2000)
);
insert into public.parameters (groupName, parameterName, parameterValue)
values ('group1', 'g1.param1', 'one');
insert into public.parameters (groupName, parameterName, parameterValue)
values ('group1', 'g1.param2', 'two');
insert into public.parameters (groupName, parameterName, …
```

[NIFI-13533] - Support dots in parameter names - parameter provider

---

nifi-frontend/src/main/frontend/apps/nifi/src/app/pages/login/ui/login-form/login-form.component.html

[NIFI-13820](https://issues.apache.org/jira/browse/NIFI-13820)
On the username/password Login Form, autofocus the Username field when the page loads.
If the approach in this MR isn't acceptable, an alternate approach also worked, but caused test failures in "npx nx test".  This approach used Renderer2 to focus the username field in ngOnInit().

NIFI-13820 autofocus Username field on Login Form

---

nifi-frontend/src/main/frontend/apps/nifi/src/app/pages/flow-designer/state/flow/flow.reducer.ts
nifi-frontend/src/main/frontend/apps/nifi/src/app/pages/flow-designer/state/flow/index.ts
nifi-frontend/src/main/frontend/apps/nifi/src/app/pages/flow-designer/ui/canvas/canvas.component.ts

[NIFI-13830](https://issues.apache.org/jira/browse/NIFI-13830)
_FYI: package-lock and edit-process-group.component were modified when running prettier. those changes have no bearing on the issue/change_

[NIFI-13830] - Wait for canvas to complete loading before attempting to restore view or center

---

nifi-nar-bundles/nifi-aws-bundle/nifi-aws-abstract-processors/src/main/java/org/apache/nifi/processors/aws/v2/AbstractAwsProcessor.java
nifi-nar-bundles/nifi-aws-bundle/nifi-aws-processors/src/main/java/org/apache/nifi/processors/aws/credentials/provider/factory/strategies/AssumeRoleCredentialsStrategy.java
nifi-nar-bundles/nifi-aws-bundle/nifi-aws-schema-registry-service/src/main/java/org/apache/nifi/aws/schemaregistry/AmazonGlueSchemaRegistry.java

[NIFI-13840](https://issues.apache.org/jira/browse/NIFI-13840)

NIFI-13840 Backport: Fixed proxy setup in AWS v2 components

---

nifi-nar-bundles/nifi-aws-bundle/nifi-aws-abstract-processors/src/main/java/org/apache/nifi/processors/aws/v2/AbstractAwsProcessor.java
nifi-nar-bundles/nifi-aws-bundle/nifi-aws-schema-registry-service/src/main/java/org/apache/nifi/aws/schemaregistry/AmazonGlueSchemaRegistry.java

[NIFI-13842](https://issues.apache.org/jira/browse/NIFI-13842)

NIFI-13842 Backport: Fixed truststore/keystore setup in AWS v2 components

---

nifi-frontend/src/main/frontend/apps/nifi/project.json
nifi-frontend/src/main/frontend/apps/nifi/src/app/app.module.ts
nifi-frontend/src/main/frontend/apps/nifi/src/app/pages/documentation/ui/common/additional-details/additional-details.component.html
nifi-frontend/src/main/frontend/libs/shared/src/assets/styles/_app.scss
nifi-frontend/src/main/frontend/libs/shared/src/assets/styles/_prism-theme.scss
nifi-frontend/src/main/frontend/libs/shared/src/components/copy-button/copy-button.component.ts
nifi-frontend/src/main/frontend/package-lock.json
nifi-frontend/src/main/frontend/package.json

[NIFI-13844] add copy button to markdown code syntax highlighting

---

nifi-frontend/src/main/frontend/apps/nifi/src/app/app.component.html
nifi-frontend/src/main/frontend/apps/nifi/src/app/pages/login/feature/login.component.html
nifi-frontend/src/main/frontend/libs/shared/src/assets/styles/_app.scss

[NIFI-13859] use tertiary color for spinners

---

nifi-extension-bundles/nifi-standard-services/nifi-lookup-services-bundle/nifi-lookup-services/pom.xml
nifi-extension-bundles/nifi-standard-services/nifi-lookup-services-bundle/nifi-lookup-services/src/main/java/org/apache/nifi/lookup/maxmind/IPLookupService.java
nifi-extension-bundles/nifi-standard-services/nifi-lookup-services-bundle/nifi-lookup-services/src/test/java/org/apache/nifi/lookup/maxmind/TestIPLookupService.java

[NIFI-13860](https://issues.apache.org/jira/browse/NIFI-13860)

NIFI-13860 Fix in IPLookupService: Don't throw exception when IP lookup fails, return Optional.empty instead.

---

nifi-assembly/pom.xml
nifi-extension-bundles/nifi-extension-utils/nifi-git-flow-registry/pom.xml
nifi-extension-bundles/nifi-extension-utils/nifi-git-flow-registry/src/main/java/org/apache/nifi/registry/flow/git/AbstractGitFlowRegistryClient.java
nifi-extension-bundles/nifi-extension-utils/nifi-git-flow-registry/src/main/java/org/apache/nifi/registry/flow/git/client/GitCommit.java
nifi-extension-bundles/nifi-extension-utils/nifi-git-flow-registry/src/main/java/org/apache/nifi/registry/flow/git/client/GitCreateContentRequest.java
nifi-extension-bundles/nifi-extension-utils/nifi-git-flow-registry/src/main/java/org/apache/nifi/registry/flow/git/client/GitRepositoryClient.java
nifi-extension-bundles/nifi-extension-utils/nifi-git-flow-registry/src/main/java/org/apache/nifi/registry/flow/git/serialize/FlowSnapshotSerializer.java
nifi-extension-bundles/nifi-extension-utils/nifi-git-flow-registry/src/main/java/org/apache/nifi/registry/flow/git/serialize/JacksonFlowSnapshotSerializer.java
nifi-extension-bundles/nifi-extension-utils/nifi-git-flow-registry/src/main/java/org/apache/nifi/registry/flow/git/serialize/VersionedComponentModule.java
nifi-extension-bundles/nifi-github-bundle/nifi-github-extensions/src/main/java/org/apache/nifi/github/GitHubFlowRegistryClient.java
nifi-extension-bundles/nifi-github-bundle/nifi-github-extensions/src/main/java/org/apache/nifi/github/GitHubRepositoryClient.java
nifi-extension-bundles/nifi-github-bundle/nifi-github-extensions/src/test/java/org/apache/nifi/github/GitHubFlowRegistryClientTest.java
nifi-extension-bundles/nifi-gitlab-bundle/nifi-gitlab-extensions/pom.xml
nifi-extension-bundles/nifi-gitlab-bundle/nifi-gitlab-extensions/src/main/java/org/apache/nifi/gitlab/GitLabAuthenticationType.java
nifi-extension-bundles/nifi-gitlab-bundle/nifi-gitlab-extensions/src/main/java/org/apache/nifi/gitlab/GitLabFlowRegistryClient.java
nifi-extension-bundles/nifi-gitlab-bundle/nifi-gitlab-extensions/src/main/java/org/apache/nifi/gitlab/GitLabRepositoryClient.java
nifi-extension-bundles/nifi-gitlab-bundle/nifi-gitlab-extensions/src/main/java/org/apache/nifi/gitlab/PersonalAccessToken.java
nifi-extension-bundles/nifi-gitlab-bundle/nifi-gitlab-extensions/src/main/resources/META-INF/services/org.apache.nifi.registry.flow.FlowRegistryClient
nifi-extension-bundles/nifi-gitlab-bundle/nifi-gitlab-nar/pom.xml
nifi-extension-bundles/nifi-gitlab-bundle/pom.xml
nifi-extension-bundles/pom.xml
nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-api/src/main/java/org/apache/nifi/web/dao/impl/StandardFlowRegistryDAO.java

- Refactoring to create base class for other git-based flow registry clients
- Implement GitLabRepositoryClient
- Implement GitLabFlowRegistryClient
[NIFI-13644](https://issues.apache.org/jira/browse/NIFI-13644)

NIFI-13644 Add GitLab Flow Registry Client

---

nifi-commons/nifi-record/src/main/java/org/apache/nifi/serialization/record/field/ObjectLocalDateFieldConverter.java
nifi-commons/nifi-record/src/main/java/org/apache/nifi/serialization/record/field/ObjectLocalDateTimeFieldConverter.java
nifi-commons/nifi-record/src/main/java/org/apache/nifi/serialization/record/field/ObjectLocalTimeFieldConverter.java
nifi-commons/nifi-record/src/main/java/org/apache/nifi/serialization/record/field/ObjectOffsetDateTimeFieldConverter.java
nifi-commons/nifi-record/src/main/java/org/apache/nifi/serialization/record/field/ObjectStringFieldConverter.java

[NIFI-13880](https://issues.apache.org/jira/browse/NIFI-13880)

NIFI-13880 Replaced if statements in Object###FieldConverter classes with enhanced switch statements

---

nifi-frontend/src/main/frontend/libs/shared/src/assets/styles/_app.scss

[NIFI-12964] fix the alignment of the date picker icon

---

nifi-frontend/src/main/frontend/apps/nifi/src/app/pages/flow-designer/ui/canvas/header/new-canvas-item/_new-canvas-item.component-theme.scss
nifi-frontend/src/main/frontend/libs/shared/src/assets/styles/_app.scss
nifi-frontend/src/main/frontend/libs/shared/src/assets/themes/material.scss
nifi-frontend/src/main/frontend/libs/shared/src/assets/themes/purple.scss

[NIFI-13887] update styles of disabled drag/drop new canvas items

---

nifi-code-coverage/pom.xml
nifi-extension-bundles/nifi-azure-bundle/nifi-azure-processors/pom.xml
nifi-extension-bundles/nifi-azure-bundle/pom.xml
nifi-extension-bundles/nifi-box-bundle/pom.xml
nifi-extension-bundles/nifi-elasticsearch-bundle/pom.xml
nifi-extension-bundles/nifi-extension-utils/nifi-hadoop-utils/pom.xml
nifi-extension-bundles/nifi-gcp-bundle/nifi-gcp-processors/pom.xml
nifi-extension-bundles/nifi-gitlab-bundle/pom.xml
nifi-extension-bundles/nifi-graph-bundle/nifi-neo4j-cypher-service/pom.xml
nifi-extension-bundles/nifi-hadoop-bundle/nifi-hdfs-processors/pom.xml
nifi-extension-bundles/nifi-hadoop-libraries-bundle/pom.xml
nifi-extension-bundles/nifi-iceberg-bundle/pom.xml
nifi-extension-bundles/nifi-parquet-bundle/nifi-parquet-processors/pom.xml
nifi-extension-bundles/nifi-slack-bundle/nifi-slack-processors/pom.xml
nifi-extension-bundles/nifi-standard-services/nifi-hadoop-dbcp-service-bundle/nifi-hadoop-dbcp-service/pom.xml
nifi-framework-bundle/pom.xml
nifi-registry/nifi-registry-core/nifi-registry-test/pom.xml
nifi-registry/nifi-registry-core/pom.xml
nifi-registry/pom.xml
nifi-toolkit/nifi-toolkit-cli/pom.xml
pom.xml

com.amazonaws	1.12.774 1.12.775
com.box	4.11.1 4.12.0
com.nimbusds nimbus-jose-jwt 9.40 9.41.2
com.nimbusds oauth2-oidc-sdk 11.14 11.20.1
io.projectreactor.netty reactor-netty-heep 1.1.22 1.1.23 org.elasticsearch.client 8.15.1 8.15.3
software.amazon.awssdk 2.28.24 2.28.25
com.google.apis v3-rev20240903-2.0.0	 v3-rev20240914-2.0.0 com.mysql 9.0.0 9.1.0
com.slack.api bolt-socket-mode 1.42.1 1.44.0
io.projectreactor reactor-core/test 3.6.10 3.6.11
org.flywaydb 10.18.2 10.20.0
org.gitlab4j gitlab4j-api 6.0.0-rc.5 6.0.0-rc.6
org.jline 3.27.0 3.27.1
org.neo4j.driver 5.25.0 5.26.0
[NIFI-13895](https://issues.apache.org/jira/browse/NIFI-13895) …

NIFI-13895 bumping various dependencies

---

nifi-framework-bundle/nifi-framework/nifi-framework-components/src/main/java/org/apache/nifi/controller/service/StandardControllerServiceProvider.java
nifi-framework-bundle/nifi-framework/nifi-framework-core/src/test/java/org/apache/nifi/controller/service/StandardControllerServiceProviderTest.java
nifi-framework-bundle/nifi-framework/nifi-framework-core/src/test/java/org/apache/nifi/controller/service/TestStandardControllerServiceProvider.java

(meaning all the ones which are not dependent on another disabled service).
Only skip trying to re-enable a previously disabled controller service IF it depends on another service which is disabled.
[NIFI-13755](https://issues.apache.org/jira/browse/NIFI-13755)
1) I added and updated automated tests to exercise the new behavior
2) I tested with running NiFi server for several disabled and enabled state services/combinations and it worked as ticket describes it should.
No new dependencies
No documentation changes

NIFI-13755 On NiFi restart, re-enable as many previously enabled controller services as possible 

---

nifi-extension-bundles/nifi-standard-bundle/nifi-standard-processors/src/main/java/org/apache/nifi/processors/standard/TailFile.java
nifi-extension-bundles/nifi-standard-bundle/nifi-standard-processors/src/test/java/org/apache/nifi/processors/standard/TestTailFile.java

[NIFI-13896](https://issues.apache.org/jira/browse/NIFI-13896)
- Removed legacy state handling from **cleanup** and **recoverState**
- Removed unused parameters from private methods
- Improved code and performance based on additional Sonar rules:
- https://www.jetbrains.com.cn/en-us/help/inspectopedia/SlowAbstractSetRemoveAll.html
- https://cloud-ci.sgs.com/sonar/coding_rules?open=java%3AS2864&rule_key=java%3AS2864

NIFI-13896: Removed legacy state migration from TailFile

---

nifi-nar-bundles/nifi-standard-bundle/nifi-standard-processors/src/main/java/org/apache/nifi/processors/standard/TailFile.java

[NIFI-13896](https://issues.apache.org/jira/browse/NIFI-13896)
- Moved out legacy state handling from cleanup to @OnScheduled
- Removed unused parameters from private methods
- Improved code and performance based on additional Sonar rules:
- https://www.jetbrains.com.cn/en-us/help/inspectopedia/SlowAbstractSetRemoveAll.html
- https://cloud-ci.sgs.com/sonar/coding_rules?open=java%3AS2864&rule_key=java%3AS2864

NIFI-13896: Improve TailFile performance

---

nifi-extension-bundles/nifi-snmp-bundle/nifi-snmp-processors/src/main/java/org/apache/nifi/snmp/processors/properties/V3SecurityProperties.java

[NIFI-13966](https://issues.apache.org/jira/browse/NIFI-13966)

NIFI-13966 Removed unsupported security protocols from SNMP processors

---

nifi-extension-bundles/nifi-standard-bundle/nifi-standard-processors/src/test/java/org/apache/nifi/processors/standard/TestConvertRecord.java

[NIFI-13965](https://issues.apache.org/jira/browse/NIFI-13965)

NIFI-13965 Reduced duplicate code in TestConvertRecord and made use of Java 21 features.

---

nifi-frontend/src/main/frontend/apps/nifi/src/app/ui/common/status-history/status-history.component.html
nifi-frontend/src/main/frontend/apps/nifi/src/app/ui/common/status-history/status-history.component.scss
nifi-frontend/src/main/frontend/apps/nifi/src/app/ui/common/status-history/status-history.component.ts

[NIFI-13974](https://issues.apache.org/jira/browse/NIFI-13974)
Before:
After Changes:

[NIFI-13974] - Improve UX of Status History dialog (select all nodes, scrolling left panel)

---

nifi-nar-bundles/nifi-accumulo-bundle/pom.xml
nifi-nar-bundles/nifi-atlas-bundle/pom.xml
nifi-nar-bundles/nifi-azure-bundle/pom.xml
nifi-nar-bundles/nifi-framework-bundle/pom.xml
nifi-nar-bundles/nifi-hadoop-libraries-bundle/pom.xml
nifi-nar-bundles/nifi-hive-bundle/pom.xml
nifi-nar-bundles/nifi-iceberg-bundle/pom.xml
nifi-nar-bundles/nifi-ranger-bundle/pom.xml
nifi-nar-bundles/nifi-spark-bundle/pom.xml
nifi-nar-bundles/nifi-standard-services/nifi-hbase_2-client-service-bundle/pom.xml
nifi-registry/nifi-registry-core/pom.xml
nifi-registry/nifi-registry-extensions/nifi-registry-ranger/pom.xml
nifi-registry/pom.xml
nifi-toolkit/pom.xml
pom.xml

[NIFI-13994](https://issues.apache.org/jira/browse/NIFI-13994)

NIFI-13994 Dependency upgrades

---

nifi-commons/nifi-record/src/main/java/org/apache/nifi/serialization/RecordReader.java
nifi-commons/nifi-record/src/main/java/org/apache/nifi/serialization/record/MapRecord.java
nifi-nar-bundles/nifi-extension-utils/nifi-record-utils/nifi-json-record-utils/src/main/java/org/apache/nifi/json/AbstractJsonRowRecordReader.java
nifi-nar-bundles/nifi-extension-utils/nifi-record-utils/nifi-json-record-utils/src/main/java/org/apache/nifi/json/JsonTreeRowRecordReader.java
nifi-nar-bundles/nifi-standard-bundle/nifi-standard-processors/pom.xml
nifi-nar-bundles/nifi-standard-bundle/nifi-standard-processors/src/test/java/org/apache/nifi/processors/standard/TestConvertRecord.java
nifi-nar-bundles/nifi-standard-bundle/nifi-standard-processors/src/test/resources/TestConvertRecord/input/person_dropfield.json

[NIFI-13963](https://issues.apache.org/jira/browse/NIFI-13963)
This is a back port of  the fix made in #9347 for 2.x.

NIFI-13963 Ensured unknown fields are not included in outputted schema for 1.x.

---

nifi-toolkit/nifi-toolkit-cli/src/main/java/org/apache/nifi/toolkit/cli/impl/command/nifi/pg/cs/ControllerServiceUtil.java

[NIFI-13990](https://issues.apache.org/jira/browse/NIFI-13990) - CLI - pg-enable-services will fail if parent PG has disabled CS
Scenario:
- root process group
- has a disabled controller service
- has a process group PG1
- PG1
- has multiple controller services
If using pg-enable-services on PG1, it will always fail because it'll check the listed controller services at PG1 level which also includes controller services from parent process groups although the request to enable controller services will not enable controller services in parent process groups.
When checking controller service states, it should filter the list of controller services with the ones defined at the level of the specified process group. …

NIFI-13990 - CLI - pg-enable-services will fail if parent PG has disabled CS

---

nifi-frontend/src/main/frontend/apps/nifi/src/app/pages/flow-designer/ui/canvas/header/flow-analysis-drawer/flow-analysis-drawer.component.ts

[NIFI-13918](https://issues.apache.org/jira/browse/NIFI-13918) & [NIFI-14015](https://issues.apache.org/jira/browse/NIFI-14015)

[NIFI-13918][NIFI-14015] - Flow analysis unauthorized root group does not display group id in the PG details section

---

nifi-nar-bundles/nifi-amqp-bundle/nifi-amqp-processors/pom.xml
nifi-nar-bundles/nifi-azure-bundle/pom.xml
nifi-nar-bundles/nifi-elasticsearch-bundle/pom.xml
nifi-nar-bundles/nifi-framework-bundle/pom.xml
nifi-nar-bundles/nifi-graph-bundle/nifi-graph-test-clients/pom.xml
nifi-nar-bundles/nifi-graph-bundle/nifi-other-graph-services/pom.xml
nifi-nar-bundles/nifi-groovyx-bundle/nifi-groovyx-nar/pom.xml
nifi-nar-bundles/nifi-hive-bundle/nifi-hive3-processors/pom.xml
nifi-nar-bundles/nifi-hive-bundle/pom.xml
nifi-nar-bundles/nifi-mongodb-bundle/pom.xml
nifi-nar-bundles/nifi-protobuf-bundle/nifi-protobuf-services/pom.xml
nifi-nar-bundles/nifi-ranger-bundle/pom.xml
nifi-nar-bundles/nifi-scripting-bundle/nifi-scripting-nar/pom.xml
nifi-nar-bundles/nifi-solr-bundle/nifi-solr-processors/pom.xml
nifi-nar-bundles/nifi-spring-bundle/nifi-spring-processors/pom.xml
nifi-nar-bundles/nifi-standard-bundle/pom.xml
nifi-nar-bundles/nifi-windows-event-log-bundle/nifi-windows-event-log-processors/pom.xml
nifi-registry/nifi-registry-extensions/nifi-registry-ranger/nifi-registry-ranger-plugin/pom.xml
nifi-registry/pom.xml
nifi-toolkit/nifi-toolkit-cli/pom.xml
nifi-toolkit/nifi-toolkit-zookeeper-migrator/pom.xml
nifi-toolkit/pom.xml
pom.xml

[NIFI-14028](https://issues.apache.org/jira/browse/NIFI-14028)

NIFI-14028 Update Apache parent pom version to 33. Upgraded Netty to 4.1.115 final along with other dependencies

---

nifi-frontend/src/main/frontend/apps/nifi/src/app/pages/flow-designer/ui/canvas/header/flow-status/flow-status.component.html
nifi-frontend/src/main/frontend/apps/nifi/src/app/pages/settings/ui/flow-analysis-rules/flow-analysis-rule-table/flow-analysis-rule-table.component.html
nifi-frontend/src/main/frontend/apps/nifi/src/app/pages/settings/ui/registry-clients/registry-client-table/registry-client-table.component.html
nifi-frontend/src/main/frontend/apps/nifi/src/app/pages/settings/ui/reporting-tasks/reporting-task-table/reporting-task-table.component.html
nifi-frontend/src/main/frontend/apps/nifi/src/app/ui/common/controller-service/controller-service-references/controller-service-references.component.html
nifi-frontend/src/main/frontend/apps/nifi/src/app/ui/common/controller-service/controller-service-table/controller-service-table.component.html
nifi-frontend/src/main/frontend/apps/nifi/src/app/ui/common/parameter-references/parameter-references.component.html
nifi-frontend/src/main/frontend/apps/nifi/src/app/ui/common/tooltips/bulletins-tip/bulletins-tip.component.html
nifi-frontend/src/main/frontend/apps/nifi/src/app/ui/common/tooltips/bulletins-tip/bulletins-tip.component.ts

* Added severity coloring to the bulletin tooltip text.
* Added copy support of the bulletin text using the copy directive.
[NIFI-14024](https://issues.apache.org/jira/browse/NIFI-14024)

[NIFI-14024] - Improve Bulletin ToolTip

---

nifi-frontend/src/main/frontend/apps/nifi/src/app/pages/flow-designer/service/canvas-context-menu.service.ts
nifi-frontend/src/main/frontend/apps/nifi/src/app/ui/common/navigation/navigation.component.html

[NIFI-14030](https://issues.apache.org/jira/browse/NIFI-14030)

[NIFI-14030] - Add an icon for Parameters and Parameter Contexts menu items

---

nifi-frontend/src/main/frontend/apps/nifi/src/app/pages/cluster/ui/cluster-system-listing/cluster-system-table/cluster-system-table.component.html
nifi-frontend/src/main/frontend/apps/nifi/src/app/pages/cluster/ui/cluster-system-listing/cluster-system-table/cluster-system-table.component.ts

[NIFI-14032](https://issues.apache.org/jira/browse/NIFI-14032)

[NIFI-14032] - Format Core Load Average in Cluster system table to 2 decimal places.

---

nifi-frontend/src/main/frontend/apps/nifi/src/app/pages/cluster/ui/cluster-node-listing/cluster-node-detail-dialog/cluster-node-detail-dialog.component.html
nifi-frontend/src/main/frontend/apps/nifi/src/app/pages/cluster/ui/cluster-node-listing/cluster-node-detail-dialog/cluster-node-detail-dialog.component.ts
nifi-frontend/src/main/frontend/libs/shared/src/assets/styles/_app.scss
nifi-frontend/src/main/frontend/libs/shared/src/components/component-context/component-context.component.html
nifi-frontend/src/main/frontend/libs/shared/src/components/component-context/component-context.component.ts
nifi-frontend/src/main/frontend/package-lock.json

[NIFI-14038](https://issues.apache.org/jira/browse/NIFI-14038)

[NIFI-14038] - Add quick-copy to component-context component when it displays the id

---

nifi-frontend/src/main/frontend/apps/nifi/src/app/pages/parameter-contexts/state/parameter-context-listing/parameter-context-listing.reducer.ts
nifi-frontend/src/main/frontend/apps/nifi/src/app/pages/parameter-contexts/ui/parameter-context-listing/edit-parameter-context/edit-parameter-context.component.html
nifi-frontend/src/main/frontend/apps/nifi/src/app/pages/settings/ui/parameter-providers/fetch-parameter-provider-parameters/fetch-parameter-provider-parameters.component.html
nifi-frontend/src/main/frontend/apps/nifi/src/app/ui/common/controller-service/controller-service-references/controller-service-references.component.html
nifi-frontend/src/main/frontend/apps/nifi/src/app/ui/common/controller-service/controller-service-references/controller-service-references.component.ts
nifi-frontend/src/main/frontend/apps/nifi/src/app/ui/common/controller-service/disable-controller-service/disable-controller-service.component.html
nifi-frontend/src/main/frontend/apps/nifi/src/app/ui/common/controller-service/edit-controller-service/edit-controller-service.component.html
nifi-frontend/src/main/frontend/apps/nifi/src/app/ui/common/controller-service/enable-controller-service/enable-controller-service.component.html
nifi-frontend/src/main/frontend/apps/nifi/src/app/ui/common/parameter-references/parameter-references.component.html
nifi-frontend/src/main/frontend/apps/nifi/src/app/ui/common/parameter-references/parameter-references.component.ts

[NIFI-14033](https://issues.apache.org/jira/browse/NIFI-14033)

[NIFI-14033] - Disable links to referencing components while saving.

---

nifi-extension-bundles/nifi-poi-bundle/nifi-poi-services/src/main/java/org/apache/nifi/processors/excel/SplitExcel.java

[NIFI-14036](https://issues.apache.org/jira/browse/NIFI-14036)

NIFI-14036 Modified description to describe behavior with formulas and a single sheet spreadsheet.

---

nifi-extension-bundles/nifi-standard-services/nifi-ssl-context-bundle/nifi-ssl-context-service/src/main/java/org/apache/nifi/ssl/PEMEncodedSSLContextProvider.java
nifi-extension-bundles/nifi-standard-services/nifi-ssl-context-bundle/nifi-ssl-context-service/src/main/resources/META-INF/services/org.apache.nifi.controller.ControllerService
nifi-extension-bundles/nifi-standard-services/nifi-ssl-context-bundle/nifi-ssl-context-service/src/test/java/org/apache/nifi/ssl/PEMEncodedSSLContextProviderTest.java

[NIFI-14049](https://issues.apache.org/jira/browse/NIFI-14049) Adds a `PEMEncodedSSLContextProvider` Controller Service implementation of the `SSLContextProvider` interface added in [NIFI-14027](https://issues.apache.org/jira/browse/NIFI-14027). The new Provider Service supports Private Keys and Certificates encoded using the [PEM](https://en.wikipedia.org/wiki/Privacy-Enhanced_Mail) format as an alternative to the `StandardSSLContextService` implementation. The majority of extension components now support the `SSLContextProvider` interface for SSLContext Service properties following changes in [NIFI-14027](https://issues.apache.org/jira/browse/NIFI-14027).
The `PEMEncodedSSLContextProvider` builds on PEM private key and certificate handling implemented in …

NIFI-14049 Add PEM-Encoded SSLContextProvider

---

nifi-commons/nifi-data-provenance-utils/src/main/java/org/apache/nifi/provenance/StandardLineageResult.java
nifi-commons/nifi-flowfile-packager/src/main/java/org/apache/nifi/util/Unpackage.java
nifi-commons/nifi-record-path/src/main/java/org/apache/nifi/record/path/paths/RecordPathCompiler.java
nifi-extension-bundles/nifi-avro-bundle/nifi-avro-processors/src/main/java/org/apache/nifi/processors/avro/SplitAvro.java
nifi-extension-bundles/nifi-aws-bundle/nifi-aws-processors/src/main/java/org/apache/nifi/processors/aws/ml/translate/GetAwsTranslateJobStatus.java
nifi-extension-bundles/nifi-extension-utils/nifi-database-utils/src/main/java/org/apache/nifi/util/db/AvroUtil.java
nifi-extension-bundles/nifi-extension-utils/nifi-database-utils/src/main/java/org/apache/nifi/util/db/JdbcCommon.java
nifi-extension-bundles/nifi-extension-utils/nifi-database-utils/src/test/java/org/apache/nifi/util/db/TestJdbcCommonConvertToAvro.java
nifi-extension-bundles/nifi-extension-utils/nifi-hadoop-utils/src/main/java/org/apache/nifi/processors/hadoop/CompressionType.java
nifi-extension-bundles/nifi-extension-utils/nifi-listed-entity/src/main/java/org/apache/nifi/processor/util/list/ListedEntityTracker.java
nifi-extension-bundles/nifi-extension-utils/nifi-put-pattern/src/main/java/org/apache/nifi/processor/util/pattern/ExceptionHandler.java
nifi-extension-bundles/nifi-extension-utils/nifi-put-pattern/src/test/java/org/apache/nifi/processor/util/pattern/TestExceptionHandler.java
nifi-extension-bundles/nifi-geohash-bundle/nifi-geohash-processors/src/main/java/org/apache/nifi/processors/geohash/GeohashRecord.java
nifi-extension-bundles/nifi-hadoop-bundle/nifi-hdfs-processors/src/main/java/org/apache/nifi/processors/hadoop/CreateHadoopSequenceFile.java
nifi-extension-bundles/nifi-hadoop-bundle/nifi-hdfs-processors/src/main/java/org/apache/nifi/processors/hadoop/ListHDFS.java
nifi-extension-bundles/nifi-hadoop-bundle/nifi-hdfs-processors/src/main/java/org/apache/nifi/processors/hadoop/inotify/GetHDFSEvents.java
nifi-extension-bundles/nifi-iotdb-bundle/nifi-iotdb-processors/src/main/java/org/apache/nifi/processors/AbstractIoTDB.java
nifi-extension-bundles/nifi-jolt-bundle/nifi-jolt-utils/src/main/java/org/apache/nifi/jolt/util/TransformFactory.java
nifi-extension-bundles/nifi-mqtt-bundle/nifi-mqtt-processors/src/main/java/org/apache/nifi/processors/mqtt/common/MqttClientFactory.java
nifi-extension-bundles/nifi-salesforce-bundle/nifi-salesforce-processors/src/main/java/org/apache/nifi/processors/salesforce/schema/SalesforceToRecordSchemaConverter.java
nifi-extension-bundles/nifi-standard-bundle/nifi-standard-processors/src/main/java/org/apache/nifi/processors/standard/GenerateRecord.java
nifi-extension-bundles/nifi-standard-services/nifi-record-serialization-services-bundle/nifi-record-serialization-services/src/main/java/org/apache/nifi/avro/AvroRecordSetWriter.java
nifi-extension-bundles/nifi-standard-services/nifi-record-serialization-services-bundle/nifi-record-serialization-services/src/main/java/org/apache/nifi/csv/WriteCSVResult.java
nifi-extension-bundles/nifi-standard-services/nifi-record-serialization-services-bundle/nifi-record-serialization-services/src/main/java/org/apache/nifi/csv/WriteFastCSVResult.java
nifi-extension-bundles/nifi-standard-services/nifi-record-serialization-services-bundle/nifi-record-serialization-services/src/main/java/org/apache/nifi/windowsevent/WindowsEventLogRecordReader.java

[NIFI-14070](https://issues.apache.org/jira/browse/NIFI-14070)

NIFI-14070 Replaced where possible switch statements with enhanced switch statements.

---

nifi-extension-bundles/nifi-extension-utils/nifi-file-transfer/src/main/java/org/apache/nifi/processor/util/file/transfer/GetFileTransfer.java
nifi-extension-bundles/nifi-extension-utils/nifi-hadoop-utils/src/main/java/org/apache/nifi/processors/hadoop/AbstractHadoopProcessor.java
nifi-extension-bundles/nifi-extension-utils/nifi-put-pattern/src/main/java/org/apache/nifi/processor/util/pattern/RollbackOnFailure.java
nifi-extension-bundles/nifi-hadoop-bundle/nifi-hdfs-processors/src/main/java/org/apache/nifi/processors/hadoop/MoveHDFS.java
nifi-extension-bundles/nifi-hadoop-bundle/nifi-hdfs-processors/src/main/java/org/apache/nifi/processors/hadoop/SequenceFileWriterImpl.java
nifi-extension-bundles/nifi-site-to-site-reporting-bundle/nifi-site-to-site-reporting-task/src/main/java/org/apache/nifi/reporting/SiteToSiteProvenanceReportingTask.java
nifi-extension-bundles/nifi-site-to-site-reporting-bundle/nifi-site-to-site-reporting-task/src/main/java/org/apache/nifi/reporting/SiteToSiteStatusReportingTask.java
nifi-extension-bundles/nifi-splunk-bundle/nifi-splunk-processors/src/main/java/org/apache/nifi/processors/splunk/PutSplunkHTTP.java
nifi-extension-bundles/nifi-splunk-bundle/nifi-splunk-processors/src/main/java/org/apache/nifi/processors/splunk/QuerySplunkIndexingStatus.java
nifi-extension-bundles/nifi-standard-bundle/nifi-standard-processors/src/main/java/org/apache/nifi/processors/standard/AbstractQueryDatabaseTable.java
nifi-extension-bundles/nifi-standard-bundle/nifi-standard-processors/src/main/java/org/apache/nifi/processors/standard/ConvertCharacterSet.java
nifi-extension-bundles/nifi-standard-bundle/nifi-standard-processors/src/main/java/org/apache/nifi/processors/standard/DebugFlow.java
nifi-extension-bundles/nifi-standard-bundle/nifi-standard-processors/src/main/java/org/apache/nifi/processors/standard/FetchFile.java
nifi-extension-bundles/nifi-standard-bundle/nifi-standard-processors/src/main/java/org/apache/nifi/processors/standard/HandleHttpResponse.java
nifi-extension-bundles/nifi-standard-bundle/nifi-standard-processors/src/main/java/org/apache/nifi/processors/standard/ListFile.java
nifi-extension-bundles/nifi-standard-bundle/nifi-standard-processors/src/main/java/org/apache/nifi/processors/standard/MergeContent.java
nifi-extension-bundles/nifi-standard-bundle/nifi-standard-processors/src/main/java/org/apache/nifi/processors/standard/servlets/ContentAcknowledgmentServlet.java
nifi-extension-bundles/nifi-standard-services/nifi-http-context-map-bundle/nifi-http-context-map/src/main/java/org/apache/nifi/http/StandardHttpContextMap.java
nifi-extension-bundles/nifi-standard-services/nifi-lookup-services-bundle/nifi-lookup-services/src/main/java/org/apache/nifi/lookup/RestLookupService.java

[NIFI-14108](https://issues.apache.org/jira/browse/NIFI-14108)

NIFI-14108 Removed the instantiation of extraneous Object arrays vararg methods.

---

nifi-extension-bundles/nifi-aws-bundle/nifi-aws-processors/src/main/java/org/apache/nifi/processors/aws/cloudwatch/PutCloudWatchMetric.java
nifi-extension-bundles/nifi-aws-bundle/nifi-aws-processors/src/main/java/org/apache/nifi/processors/aws/ml/textract/GetAwsTextractJobStatus.java
nifi-extension-bundles/nifi-aws-bundle/nifi-aws-processors/src/main/java/org/apache/nifi/processors/aws/s3/ListS3.java
nifi-extension-bundles/nifi-confluent-platform-bundle/nifi-confluent-schema-registry-service/src/main/java/org/apache/nifi/confluent/schemaregistry/ConfluentSchemaRegistry.java
nifi-extension-bundles/nifi-hadoop-bundle/nifi-hdfs-processors/src/main/java/org/apache/nifi/processors/hadoop/GetHDFS.java
nifi-extension-bundles/nifi-hadoop-bundle/nifi-hdfs-processors/src/main/java/org/apache/nifi/processors/hadoop/MoveHDFS.java
nifi-extension-bundles/nifi-jms-bundle/nifi-jms-processors/src/main/java/org/apache/nifi/jms/cf/JndiJmsConnectionFactoryHandler.java
nifi-extension-bundles/nifi-jms-bundle/nifi-jms-processors/src/test/java/org/apache/nifi/jms/processors/JMSPublisherConsumerIT.java
nifi-extension-bundles/nifi-standard-bundle/nifi-standard-processors/src/main/java/org/apache/nifi/processors/standard/PutFile.java
nifi-framework-bundle/nifi-framework-extensions/nifi-provenance-repository-bundle/nifi-persistent-provenance-repository/src/main/java/org/apache/nifi/provenance/store/WriteAheadStorePartition.java
nifi-framework-bundle/nifi-framework/nifi-framework-core/src/main/java/org/apache/nifi/controller/queue/clustered/partition/RemoteQueuePartition.java
nifi-framework-bundle/nifi-framework/nifi-framework-core/src/main/java/org/apache/nifi/controller/repository/WriteAheadFlowFileRepository.java
nifi-framework-bundle/nifi-framework/nifi-framework-core/src/main/java/org/apache/nifi/controller/scheduling/StandardProcessScheduler.java
nifi-framework-bundle/nifi-framework/nifi-framework-core/src/test/java/org/apache/nifi/controller/queue/clustered/TestSwappablePriorityQueue.java
nifi-framework-bundle/nifi-framework/nifi-framework-core/src/test/java/org/apache/nifi/controller/repository/TestWriteAheadFlowFileRepository.java
nifi-framework-bundle/nifi-framework/nifi-nar-utils/src/main/java/org/apache/nifi/nar/NarClassLoader.java
nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-api/src/main/java/org/apache/nifi/web/api/DataTransferResource.java

[NIFI-14130](https://issues.apache.org/jira/browse/NIFI-14130)

NIFI-14130 Replaced more anonymous classes with lambdas.

---

nifi-extension-bom/pom.xml
nifi-extension-bundles/nifi-aws-bundle/nifi-aws-processors/pom.xml
nifi-extension-bundles/nifi-groovyx-bundle/nifi-groovyx-processors/pom.xml
nifi-extension-bundles/nifi-hl7-bundle/nifi-hl7-processors/pom.xml
nifi-extension-bundles/nifi-media-bundle/pom.xml
nifi-extension-bundles/nifi-parquet-bundle/pom.xml
nifi-extension-bundles/nifi-poi-bundle/pom.xml
nifi-extension-bundles/nifi-scripting-bundle/nifi-scripting-processors/pom.xml
nifi-extension-bundles/nifi-slack-bundle/nifi-slack-processors/pom.xml
nifi-extension-bundles/nifi-standard-services/nifi-lookup-services-bundle/nifi-lookup-services/pom.xml
nifi-extension-bundles/nifi-standard-shared-bundle/nifi-standard-shared-bom/pom.xml
nifi-framework-bundle/pom.xml
nifi-registry/pom.xml
pom.xml

[NIFI-14139](https://issues.apache.org/jira/browse/NIFI-14139) - Upgrade dependencies Jersey, POI, AWS, Flyway, Logback, etc
- Checkstyle from 10.21.0 to 10.21.1 - https://checkstyle.sourceforge.io/releasenotes.html
- PMD from 7.8.0 to 7.9.0 - https://github.com/pmd/pmd/releases/tag/pmd_releases%2F7.9.0
- Mockito from 5.14.2 to 5.15.2 - https://github.com/mockito/mockito/releases
- commons-beanutils from 1.9.4 to 1.10.0 - https://commons.apache.org/proper/commons-beanutils/changes-report.html#a1.10.0
- Apache Ivy from 2.5.2 to 2.5.3 - https://ant.apache.org/ivy/history/2.5.3/release-notes.html
- Apache POI from 5.3.0 to 5.4.0 - https://poi.apache.org/changes.html
- Slack Bolt from 1.44.2 to 1.45.0
- checker-qual from 3.48.1 to 3.48.4 - …

NIFI-14139 - Upgrade dependencies Jersey, POI, AWS, Flyway, Logback, etc

---

nifi-extension-bundles/nifi-workday-bundle/nifi-workday-processors/src/main/java/org/apache/nifi/processors/workday/GetWorkdayReport.java

[NIFI-14177](https://issues.apache.org/jira/browse/NIFI-14177) - Add unsuccessful API call logging to GetWorkdayReport

NIFI-14177 - Add unsuccessful API call logging to GetWorkdayReport

---

nifi-frontend/src/main/frontend/apps/nifi/src/app/pages/flow-designer/ui/canvas/canvas.component.spec.ts
nifi-frontend/src/main/frontend/apps/nifi/src/app/pages/flow-designer/ui/canvas/canvas.component.ts
nifi-frontend/src/main/frontend/apps/nifi/src/app/ui/common/extension-creation/filter-predicate/camel-case.search.ts

[NIFI-14172](https://issues.apache.org/jira/browse/NIFI-14172)
Support pasting a Flow Definition string on the canvas. The Flow Definition format is the same format you would get if you download a flow from the canvas as well as the same format saved into a flow registry. Both "flavors" should be verified when reviewing this PR.

[NIFI-14172] - Support pasting a Flow Definition string on the canvas

---

nifi-extension-bundles/nifi-extension-utils/nifi-record-utils/nifi-standard-record-utils/src/main/java/org/apache/nifi/csv/CSVUtils.java
nifi-extension-bundles/nifi-standard-services/nifi-lookup-services-bundle/nifi-lookup-services/src/main/java/org/apache/nifi/lookup/CSVRecordLookupService.java
nifi-extension-bundles/nifi-standard-services/nifi-lookup-services-bundle/nifi-lookup-services/src/main/java/org/apache/nifi/lookup/SimpleCsvFileLookupService.java
nifi-extension-bundles/nifi-standard-services/nifi-record-serialization-services-bundle/nifi-record-serialization-services/src/main/java/org/apache/nifi/csv/CSVHeaderSchemaStrategy.java
nifi-extension-bundles/nifi-standard-services/nifi-record-serialization-services-bundle/nifi-record-serialization-services/src/main/java/org/apache/nifi/csv/CSVRecordReader.java
nifi-extension-bundles/nifi-standard-services/nifi-record-serialization-services-bundle/nifi-record-serialization-services/src/main/java/org/apache/nifi/csv/CSVRecordSource.java
nifi-extension-bundles/nifi-standard-services/nifi-record-serialization-services-bundle/nifi-record-serialization-services/src/main/java/org/apache/nifi/csv/WriteCSVResult.java
nifi-extension-bundles/nifi-standard-services/nifi-record-serialization-services-bundle/nifi-record-serialization-services/src/test/java/org/apache/nifi/csv/ITApacheCSVRecordReader.java
nifi-extension-bundles/nifi-standard-services/nifi-record-serialization-services-bundle/nifi-record-serialization-services/src/test/java/org/apache/nifi/csv/ITJacksonCSVRecordReader.java
nifi-extension-bundles/nifi-standard-services/nifi-record-serialization-services-bundle/nifi-record-serialization-services/src/test/java/org/apache/nifi/csv/TestCSVRecordReader.java
nifi-extension-bundles/nifi-standard-services/nifi-record-serialization-services-bundle/nifi-record-serialization-services/src/test/java/org/apache/nifi/csv/TestFastCSVRecordReader.java
nifi-extension-bundles/nifi-standard-services/nifi-record-serialization-services-bundle/nifi-record-serialization-services/src/test/java/org/apache/nifi/csv/TestJacksonCSVRecordReader.java
nifi-extension-bundles/nifi-standard-services/nifi-record-serialization-services-bundle/nifi-record-serialization-services/src/test/java/org/apache/nifi/csv/TestWriteCSVResult.java
nifi-extension-bundles/nifi-standard-services/nifi-record-serialization-services-bundle/nifi-record-serialization-services/src/test/java/org/apache/nifi/csv/TestWriteFastCSVResult.java

[NIFI-14200](https://issues.apache.org/jira/browse/NIFI-14200)
Replaced all the deprecated methods and implemented Intellij suggestions to use Java 21 constructs such as `Set.of`, `String.repeat`, `List.copyOf` etc.

NIFI-14200 Replaced the use of deprecated org.apache.commons:commons-csv:1.13.0 constructs with suggested replacements.

---

nifi-commons/nifi-security-kerberos/src/main/java/org/apache/nifi/security/krb/AbstractKerberosUser.java
nifi-commons/nifi-security-kerberos/src/test/java/org/apache/nifi/security/krb/KerberosUserIT.java
nifi-extension-bundles/nifi-extension-utils/nifi-hadoop-utils/src/main/java/org/apache/nifi/hadoop/SecurityUtil.java

[NIFI-14202](https://issues.apache.org/jira/browse/NIFI-14202)

NIFI-14202 Replaced javax.security.auth.Subject doAs and getSubject methods with suggested equivalents.

---

nifi-extension-bundles/nifi-pgp-bundle/nifi-pgp-processors/src/main/java/org/apache/nifi/processors/pgp/SignContentPGP.java
nifi-extension-bundles/nifi-pgp-bundle/nifi-pgp-test-utils/src/main/java/org/apache/nifi/pgp/util/PGPOperationUtils.java
nifi-extension-bundles/nifi-pgp-bundle/nifi-pgp-test-utils/src/main/java/org/apache/nifi/pgp/util/PGPSecretKeyGenerator.java

[NIFI-14203](https://issues.apache.org/jira/browse/NIFI-14203)

NIFI-14203 Replaced deprecated bouncycastle features with suggested equivalents.

---

nifi-extension-bundles/nifi-kafka-bundle/nifi-kafka-3-integration/src/test/java/org/apache/nifi/kafka/processors/AbstractKafkaBaseIT.java
nifi-extension-bundles/nifi-kafka-bundle/nifi-kafka-3-integration/src/test/java/org/apache/nifi/kafka/processors/PublishKafkaAuthSaslPlaintextIT.java
nifi-extension-bundles/nifi-kafka-bundle/nifi-kafka-3-service/src/test/java/org/apache/nifi/kafka/service/Kafka3ConnectionServiceBaseIT.java
nifi-extension-bundles/nifi-kafka-bundle/nifi-kafka-3-service/src/test/java/org/apache/nifi/kafka/service/Kafka3ConnectionServiceSSLIT.java
nifi-extension-bundles/nifi-kafka-bundle/nifi-kafka-3-service/src/test/java/org/apache/nifi/kafka/service/Kafka3ConnectionServiceSaslPlaintextIT.java
nifi-extension-bundles/nifi-kafka-bundle/nifi-kafka-3-service/src/test/java/org/apache/nifi/kafka/service/KafkaConnectivityIT.java
nifi-extension-bundles/nifi-redis-bundle/nifi-redis-extensions/src/test/java/org/apache/nifi/redis/testcontainers/RedisContainer.java
nifi-extension-bundles/nifi-smb-bundle/nifi-smb-smbj-client/src/test/java/org/apache/nifi/services/smb/SmbjClientServiceIT.java

[NIFI-14225](https://issues.apache.org/jira/browse/NIFI-14225)

NIFI-14225 Replaced deprecated methods in testcontainers with suggested replacements.

---

nifi-commons/nifi-web-client-api/src/main/java/org/apache/nifi/web/client/api/StandardHttpRequestMethod.java
nifi-commons/nifi-web-client-api/src/main/java/org/apache/nifi/web/client/api/WebClientService.java
nifi-commons/nifi-web-client/src/main/java/org/apache/nifi/web/client/StandardWebClientService.java
nifi-commons/nifi-web-client/src/test/java/org/apache/nifi/web/client/StandardWebClientServiceTest.java

[NIFI-14248](https://issues.apache.org/jira/browse/NIFI-14248) - Add support for HEAD in NiFi web client

NIFI-14248 - Add support for HEAD in NiFi web client

---

nifi-extension-bundles/nifi-mongodb-bundle/nifi-mongodb-processors/src/test/java/org/apache/nifi/processors/mongodb/PutMongoIT.java
nifi-extension-bundles/nifi-mongodb-bundle/nifi-mongodb-services/src/main/java/org/apache/nifi/mongodb/MongoDBControllerService.java

[NIFI-14272](https://issues.apache.org/jira/browse/NIFI-14272) - Refactoring MongoDB client creation
Small refactor for the creation of the MongoDB client to better leverage the MongoClientSettings builder.

NIFI-14272 - Refactoring MongoDB client creation

---

nifi-toolkit/nifi-toolkit-cli/src/main/java/org/apache/nifi/toolkit/cli/impl/command/registry/tenant/TenantHelper.java
nifi-toolkit/nifi-toolkit-cli/src/test/java/org/apache/nifi/toolkit/cli/impl/command/registry/tenant/TestTenantHelper.java

[NIFI-14290](https://issues.apache.org/jira/browse/NIFI-14290)

NIFI-14290 Allow Toolkit CLI commands for NiFi Registry to include usernames with commas in the CSV string of the username list

---

nifi-extension-bundles/nifi-standard-bundle/nifi-standard-processors/src/test/java/org/apache/nifi/processors/standard/TestIdentifyMimeType.java

[NIFI-14312](https://issues.apache.org/jira/browse/NIFI-14312)

NIFI-14312 Made improvements to TestIdentifyMimeType by reducing duplicated code and introducing paramaterized tests.

---

nifi-assembly/README.md
nifi-registry/nifi-registry-assembly/README.md

[NIFI-14330](https://issues.apache.org/jira/browse/NIFI-14330)

NIFI-14330 fixing invite links to slack in all the readme files

---

nifi-frontend/src/main/frontend/apps/nifi/src/app/pages/queue/ui/queue-listing/flowfile-table/flowfile-table.component.html

When performing a 'list queue', certain conditions will prevent the kebab on the right from appearing. One such condition is a zero-byte FlowFile and lack of being in the global Access Policy, 'Query provenance'. The kebab should always be present because 'View details' will always be an option regardless of other conditions such as file size and access policies. (The 'view the data' component Access Policy was already checked in order to list the queue at all.)
[NIFI-14385](https://issues.apache.org/jira/browse/NIFI-14385)

NIFI-14385 allow button with underlying conditional options to be displayed for every FlowFile item on a list queue table

---

nifi-extension-bundles/nifi-aws-bundle/pom.xml
nifi-extension-bundles/nifi-box-bundle/pom.xml
nifi-extension-bundles/nifi-email-bundle/nifi-email-processors/pom.xml
nifi-extension-bundles/nifi-extension-utils/nifi-record-utils/nifi-standard-record-utils/pom.xml
nifi-extension-bundles/nifi-gcp-bundle/pom.xml
nifi-extension-bundles/nifi-graph-bundle/nifi-neo4j-cypher-service/pom.xml
nifi-extension-bundles/nifi-standard-bundle/nifi-standard-content-viewer/pom.xml
nifi-extension-bundles/nifi-standard-services/nifi-dbcp-service-bundle/nifi-hikari-dbcp-service/pom.xml
nifi-extension-bundles/nifi-standard-services/nifi-lookup-services-bundle/nifi-lookup-services/pom.xml
nifi-extension-bundles/nifi-standard-services/nifi-record-serialization-services-bundle/nifi-record-serialization-services/pom.xml
nifi-registry/pom.xml
pom.xml

[NIFI-14387](https://issues.apache.org/jira/browse/NIFI-14387) - Bump Spring to 6.2.5, Commons CSV to 1.14.0, Spring boot to 3.4.4, and others
- kinesis client from 2.6.1 to 2.7.0 - https://github.com/awslabs/amazon-kinesis-client/releases/tag/v2.7.0
- box from 4.15.2 to 4.15.3 - https://github.com/box/box-java-sdk/releases/tag/v4.15.3
- spring integration from 6.4.2 to 6.4.3 - https://github.com/spring-projects/spring-integration/releases/tag/v6.4.3
- commons csv from 1.13.0 to 1.14.0 - https://github.com/apache/commons-csv/blob/master/RELEASE-NOTES.txt
- gcp from 26.56.0 to 26.57.0 - https://github.com/googleapis/java-cloud-bom/releases/tag/v26.57.0
- neo4j driver from 5.28.3 to 5.28.4 - https://github.com/neo4j/neo4j-java-driver/releases/tag/5.28.4
- spring boot from 3.4.3 to 3.4.4 - …

NIFI-14387 - Bump Spring to 6.2.5, Commons CSV to 1.14.0, Spring boot to 3.4.4, and others

---

nifi-extension-bundles/nifi-standard-services/nifi-distributed-cache-services-bundle/nifi-distributed-cache-server/src/main/java/org/apache/nifi/distributed/cache/server/AbstractCacheServer.java

[NIFI-14340](https://issues.apache.org/jira/browse/NIFI-14340)

NIFI-14340 Removed finalize method from AbstractCacheServer as the shutdownServer method is already annotated appropriately.

---

nifi-commons/pom.xml
nifi-extension-bom/pom.xml
nifi-extension-bundles/nifi-aws-bundle/pom.xml
nifi-extension-bundles/nifi-azure-bundle/pom.xml
nifi-extension-bundles/nifi-elasticsearch-bundle/pom.xml
nifi-extension-bundles/nifi-evtx-bundle/nifi-evtx-processors/pom.xml
nifi-extension-bundles/nifi-gcp-bundle/pom.xml
nifi-extension-bundles/nifi-graph-bundle/nifi-graph-test-clients/pom.xml
nifi-extension-bundles/nifi-hadoop-libraries-bundle/pom.xml
nifi-extension-bundles/nifi-opentelemetry-bundle/pom.xml
nifi-extension-bundles/nifi-protobuf-bundle/nifi-protobuf-services/pom.xml
nifi-extension-bundles/nifi-protobuf-bundle/pom.xml
nifi-extension-bundles/nifi-salesforce-bundle/nifi-salesforce-processors/pom.xml
nifi-extension-bundles/nifi-snmp-bundle/nifi-snmp-processors/pom.xml
nifi-extension-bundles/nifi-sql-reporting-bundle/pom.xml
nifi-extension-bundles/nifi-standard-bundle/nifi-standard-processors/pom.xml
nifi-extension-bundles/nifi-standard-bundle/pom.xml
nifi-framework-bundle/pom.xml
nifi-registry/nifi-registry-core/nifi-registry-test/pom.xml
nifi-registry/nifi-registry-core/pom.xml
nifi-registry/pom.xml
pom.xml

[NIFI-14406](https://issues.apache.org/jira/browse/NIFI-14406) - Bump Azure to 1.2.33, GCP to 26.58.0, AWS to 2.31.11 and others
- Guava from 33.4.0-jre to 33.4.6-jre - https://github.com/google/guava/releases/tag/v33.4.6
- ASM from 9.7.1 to 9.8 - https://asm.ow2.io/versions.html
- Azure SDK BOM from 1.2.32 to 1.2.33 - https://github.com/Azure/azure-sdk-for-java/releases/tag/azure-sdk-bom_1.2.33
- MSAL4J from 1.19.0 to 1.19.1 - https://github.com/AzureAD/microsoft-authentication-library-for-java/releases/tag/v1.19.1
- Elasticsearch client from 8.17.3 to 8.17.4 - https://github.com/elastic/elasticsearch-java/releases/tag/v8.17.4
- GCP BOM from 26.57.0 to 26.58.0 - https://github.com/googleapis/java-cloud-bom/releases/tag/v26.58.0
- Camel Salesforce from 4.10.2 to 4.10.3 - …

NIFI-14406 - Bump Azure to 1.2.33, GCP to 26.58.0, AWS to 2.31.11 and others

---

nifi-registry/nifi-registry-core/nifi-registry-web-api/src/main/java/org/apache/nifi/registry/web/security/authentication/oidc/StandardOidcIdentityProvider.java

[NIFI-14408](https://issues.apache.org/jira/browse/NIFI-14408)

NIFI-14408 Replaced use of deprecated TokenRequest constructor with a constructor which is not deprecated.

---

nifi-mock/src/main/java/org/apache/nifi/util/StandardProcessorTestRunner.java
nifi-mock/src/main/java/org/apache/nifi/util/TestRunner.java

[NIFI-14425](https://issues.apache.org/jira/browse/NIFI-14425) - Expose validate and verify in TestRunner

NIFI-14425 - Expose validate and verify in TestRunner

---

nifi-extension-bundles/nifi-poi-bundle/nifi-poi-services/src/main/java/org/apache/nifi/processors/excel/SplitExcel.java
nifi-extension-bundles/nifi-poi-bundle/nifi-poi-services/src/test/java/org/apache/nifi/processors/excel/TestSplitExcel.java

[NIFI-14106](https://issues.apache.org/jira/browse/NIFI-14106)

NIFI-14106 Reverted CellCopyPolicy in SplitExcel to allow copying cell styles which now allows for preservation of  dates and times precision. 

---

nifi-extension-bundles/nifi-standard-services/nifi-oauth2-provider-api/src/main/java/org/apache/nifi/oauth2/AccessToken.java
nifi-extension-bundles/nifi-standard-services/nifi-oauth2-provider-bundle/nifi-oauth2-provider-service/src/test/java/org/apache/nifi/oauth2/StandardOauth2AccessTokenProviderTest.java

[NIFI-14468](https://issues.apache.org/jira/browse/NIFI-14468) - Fix scope in AccessToken

NIFI-14468 - Fix scope in AccessToken

---

nifi-frontend/src/main/frontend/apps/nifi/src/app/pages/flow-designer/service/flow.service.ts
nifi-frontend/src/main/frontend/apps/nifi/src/app/pages/flow-designer/state/flow/flow.effects.spec.ts
nifi-frontend/src/main/frontend/apps/nifi/src/app/pages/flow-designer/state/flow/flow.effects.ts
nifi-frontend/src/main/frontend/apps/nifi/src/app/pages/flow-designer/state/flow/flow.selectors.ts
nifi-frontend/src/main/frontend/apps/nifi/src/app/pages/flow-designer/state/flow/index.ts

[NIFI-14196](https://issues.apache.org/jira/browse/NIFI-14196)
[NIFI-14079](https://issues.apache.org/jira/browse/NIFI-14079)
Fix "move to front" for connections and labels.
Enhances z-index handling for flow components by:
- Ensuring new labels and connections are created with the current maximum z-index + 1
- Modifying the move-to-front behavior to handle components with equal z-indices
- Updating the default minimum z-index from -1 to 0 for both connections and labels

[NIFI-14079][NIFI-14196] fix bring to front

---

nifi-commons/pom.xml
nifi-extension-bundles/nifi-aws-bundle/pom.xml
nifi-extension-bundles/nifi-azure-bundle/pom.xml
nifi-extension-bundles/nifi-elasticsearch-bundle/pom.xml
nifi-extension-bundles/nifi-evtx-bundle/nifi-evtx-processors/pom.xml
nifi-extension-bundles/nifi-extension-utils/nifi-syslog-utils/pom.xml
nifi-extension-bundles/nifi-gcp-bundle/pom.xml
nifi-extension-bundles/nifi-graph-bundle/nifi-graph-test-clients/pom.xml
nifi-extension-bundles/nifi-hadoop-libraries-bundle/pom.xml
nifi-extension-bundles/nifi-opentelemetry-bundle/pom.xml
nifi-extension-bundles/nifi-protobuf-bundle/pom.xml
nifi-extension-bundles/nifi-sql-reporting-bundle/pom.xml
nifi-extension-bundles/nifi-standard-bundle/nifi-standard-processors/pom.xml
nifi-extension-bundles/nifi-standard-bundle/pom.xml
nifi-extension-bundles/nifi-standard-services/nifi-record-serialization-services-bundle/nifi-record-serialization-services/pom.xml
nifi-framework-bundle/pom.xml
nifi-registry/nifi-registry-core/pom.xml
nifi-registry/pom.xml
pom.xml

[NIFI-14487](https://issues.apache.org/jira/browse/NIFI-14487) - Bump Spring to 6.2.6, Spring Security to 6.4.5, GSON to 2.13.0, and others
- Guava from 33.4.6-jre to 33.4.8-jre - https://github.com/google/guava/releases/tag/v33.4.8
- Elasticsearch client from 8.17.4 to 8.18.0 - https://github.com/elastic/elasticsearch-java/releases/tag/v8.18.0
- simple-syslog-5424 from 0.0.16 to 0.0.18 - https://github.com/palindromicity/simple-syslog-5424/compare/simple-syslog-5424-0.0.16...simple-syslog-5424-0.0.18
- FlywayDB from 11.7.1 to 11.7.2 - https://github.com/flyway/flyway/releases/tag/flyway-11.7.2
- AWS SDK from 2.31.22 to 2.31.25 - https://github.com/aws/aws-sdk-java-v2/blob/master/CHANGELOG.md
- GSON from 2.12.1 to 2.13.0 - https://github.com/google/gson/releases/tag/gson-parent-2.13.0
- …

NIFI-14487 - Bump Spring to 6.2.6, Spring Security to 6.4.5, GSON to 2.13.0, and others

---

nifi-extension-bundles/nifi-standard-services/nifi-oauth2-provider-bundle/nifi-oauth2-provider-service/pom.xml
nifi-extension-bundles/nifi-standard-services/nifi-oauth2-provider-bundle/nifi-oauth2-provider-service/src/main/java/org/apache/nifi/oauth2/JWTBearerOAuth2AccessTokenProvider.java
nifi-extension-bundles/nifi-standard-services/nifi-oauth2-provider-bundle/nifi-oauth2-provider-service/src/main/java/org/apache/nifi/oauth2/key/Ed25519Signer.java
nifi-extension-bundles/nifi-standard-services/nifi-oauth2-provider-bundle/nifi-oauth2-provider-service/src/main/resources/META-INF/services/org.apache.nifi.controller.ControllerService
nifi-extension-bundles/nifi-standard-services/nifi-oauth2-provider-bundle/nifi-oauth2-provider-service/src/main/resources/docs/org.apache.nifi.oauth2.JWTBearerOAuth2AccessTokenProvider/additionalDetails.md
nifi-extension-bundles/nifi-standard-services/nifi-oauth2-provider-bundle/nifi-oauth2-provider-service/src/test/java/org/apache/nifi/oauth2/JWTBearerOAuth2AccessTokenProviderTest.java
nifi-extension-bundles/nifi-standard-services/nifi-oauth2-provider-bundle/pom.xml

[NIFI-14380](https://issues.apache.org/jira/browse/NIFI-14380) - OAuth 2.0 Controller Service to support JWT Bearer Flow
This feature has been tested against
- Microsoft Sharepoint & MSGraph APIs
- Box
- Salesforce
- Google Identity for Google Cloud
Configuration settings for each scenario can be found in the additional details documentation of the controller service.

NIFI-14380 - OAuth 2.0 Controller Service to support JWT Bearer Flow

---

nifi-frontend/src/main/frontend/libs/shared/src/assets/styles/_app.scss

[NIFI-14403](https://issues.apache.org/jira/browse/NIFI-14403) - add missing drop shadows to text editors
Manual

NIFI-14403 add drop shadow to text editors

---

nifi-frontend/src/main/frontend/apps/nifi/src/app/pages/flow-designer/ui/manage-remote-ports/manage-remote-ports.component.html

[NIFI-14402](https://issues.apache.org/jira/browse/NIFI-14402) - simply enable / disabling message for activating ports
Manual

NIFI-14402 manage remote ports -> action menu, update labels for enabling ports

---

nifi-code-coverage/pom.xml
nifi-commons/nifi-calcite-utils/pom.xml
nifi-commons/nifi-hashicorp-vault/pom.xml
nifi-extension-bundles/nifi-asana-bundle/pom.xml
nifi-extension-bundles/nifi-email-bundle/nifi-email-processors/pom.xml
nifi-extension-bundles/nifi-gcp-bundle/nifi-gcp-processors/pom.xml
nifi-extension-bundles/nifi-gitlab-bundle/pom.xml
nifi-extension-bundles/nifi-graph-bundle/nifi-neo4j-cypher-service/pom.xml
nifi-extension-bundles/nifi-opentelemetry-bundle/pom.xml
nifi-extension-bundles/nifi-protobuf-bundle/nifi-protobuf-services/pom.xml
nifi-extension-bundles/nifi-snmp-bundle/nifi-snmp-processors/pom.xml
nifi-extension-bundles/nifi-standard-bundle/nifi-standard-content-viewer/pom.xml
nifi-framework-bundle/pom.xml
nifi-registry/pom.xml
pom.xml

[NIFI-14500](https://issues.apache.org/jira/browse/NIFI-14500) - Bump Spring Vault to 3.1.3, Spring Boot to 3.4.5, and others
- Protobuf from 3.25.6 to 3.25.7 - https://github.com/protocolbuffers/protobuf/releases/tag/v25.7
- Spring Vault from 3.1.2 to 3.1.3 - https://github.com/spring-projects/spring-vault/releases/tag/3.1.3
- Spring Integration from 6.4.3 to 6.4.4 - https://github.com/spring-projects/spring-integration/releases/tag/v6.4.4
- Spring Boot from 3.4.4 to 3.4.5 - https://github.com/spring-projects/spring-boot/releases/tag/v3.4.5
- Apache Commons Collections4 from 4.4 to 4.5.0 - https://github.com/apache/commons-collections/blob/master/RELEASE-NOTES.txt
- Google API Services Drive from v3-rev20250220-2.0.0 to v3-rev20250329-2.0.0 - …

NIFI-14500 - Bump Spring Vault to 3.1.3, Spring Boot to 3.4.5, and others

---

nifi-extension-bundles/nifi-azure-bundle/nifi-azure-processors/pom.xml
nifi-extension-bundles/nifi-azure-bundle/nifi-azure-processors/src/main/java/org/apache/nifi/services/azure/data/explorer/StandardKustoIngestService.java
nifi-extension-bundles/nifi-azure-bundle/nifi-azure-processors/src/main/java/org/apache/nifi/services/azure/data/explorer/StandardKustoQueryService.java
nifi-extension-bundles/nifi-azure-bundle/pom.xml
nifi-extension-bundles/nifi-box-bundle/pom.xml
nifi-extension-bundles/nifi-gcp-bundle/nifi-gcp-processors/pom.xml
nifi-extension-bundles/nifi-parquet-bundle/nifi-parquet-processors/pom.xml
nifi-extension-bundles/nifi-redis-bundle/nifi-redis-utils/src/main/java/org/apache/nifi/redis/util/RedisUtils.java
nifi-extension-bundles/nifi-redis-bundle/pom.xml
nifi-extension-bundles/nifi-standard-services/nifi-oauth2-provider-bundle/nifi-oauth2-provider-service/pom.xml
nifi-framework-bundle/nifi-framework-extensions/nifi-provenance-repository-bundle/pom.xml
nifi-registry/nifi-registry-core/nifi-registry-test/pom.xml
pom.xml

[NIFI-14510](https://issues.apache.org/jira/browse/NIFI-14510) - Bump Azure SDK to 1.2.34, parquet to 1.15.2, commons config to 2.12.0, and others
- Microsoft Azure Kusto from 5.2.0 to 6.0.2 - https://github.com/Azure/azure-kusto-java/releases/tag/v6.0.2
- Azure SDK from 1.2.33 to 1.2.34 - https://github.com/Azure/azure-sdk-for-java/releases/tag/azure-sdk-bom_1.2.34
- Box SDK from 4.16.0 to 4.16.1 - https://github.com/box/box-java-sdk/releases/tag/v4.16.1
- Google Drive from v3-rev20250329-2.0.0 to v3-rev20250427-2.0.0 - https://github.com/googleapis/google-api-java-client-services/blob/main/clients/google-api-services-drive/v3/2.0.0/README.md
- parquet-avro from 1.15.1 to 1.15.2 - https://github.com/apache/parquet-java/releases/tag/apache-parquet-1.15.2
- Spring Data Redis from 3.4.1 to …

NIFI-14510 - Bump Azure SDK to 1.2.34, parquet to 1.15.2, commons config to 2.12.0, and others

---

nifi-extension-bundles/nifi-standard-services/nifi-record-serialization-services-bundle/nifi-record-serialization-services/pom.xml
nifi-extension-bundles/nifi-standard-services/nifi-record-serialization-services-bundle/nifi-record-serialization-services/src/main/java/org/apache/nifi/csv/FastCSVRecordReader.java
nifi-extension-bundles/nifi-standard-services/nifi-record-serialization-services-bundle/nifi-record-serialization-services/src/main/java/org/apache/nifi/csv/WriteFastCSVResult.java

[NIFI-14508](https://issues.apache.org/jira/browse/NIFI-14508) - Upgrade fastcsv from 2.2.2 to 3.6.0

NIFI-14508 - Upgrade fastcsv from 2.2.2 to 3.6.0

---

nifi-extension-bundles/nifi-aws-bundle/nifi-aws-processors/pom.xml
nifi-extension-bundles/nifi-kafka-bundle/nifi-kafka-3-service/pom.xml
nifi-extension-bundles/nifi-kafka-bundle/nifi-kafka-service-aws/pom.xml
nifi-extension-bundles/nifi-kafka-bundle/pom.xml

[NIFI-14482](https://issues.apache.org/jira/browse/NIFI-14482) - Bump kafka-client to 4.0.0

NIFI-14482 - Bump kafka-client to 4.0.0

---

nifi-extension-bundles/nifi-extension-utils/nifi-event-transport/src/main/java/org/apache/nifi/event/transport/netty/EventLoopGroupFactory.java
nifi-extension-bundles/nifi-extension-utils/nifi-event-transport/src/main/java/org/apache/nifi/event/transport/netty/NettyEventServerFactory.java
nifi-extension-bundles/nifi-standard-services/nifi-distributed-cache-services-bundle/nifi-distributed-cache-client-service/src/main/java/org/apache/nifi/distributed/cache/client/CacheClient.java
nifi-framework-bundle/nifi-framework/nifi-framework-core/src/test/java/org/apache/nifi/controller/queue/clustered/client/async/nio/TestPeerChannel.java

[NIFI-14506](https://issues.apache.org/jira/browse/NIFI-14506)
- mvn -Pcontrib-check clean install >../xxx
- cat ../xxx|grep deprecated|grep netty
- Expected: No lines found

NIFI-14506 replace deprecated netty classes

---

nifi-extension-bundles/nifi-gcp-bundle/nifi-gcp-processors/pom.xml
nifi-extension-bundles/nifi-gcp-bundle/pom.xml
nifi-extension-bundles/nifi-graph-bundle/nifi-graph-test-clients/pom.xml
nifi-extension-bundles/nifi-snmp-bundle/nifi-snmp-processors/pom.xml
nifi-extension-bundles/nifi-standard-services/nifi-oauth2-provider-bundle/nifi-oauth2-provider-service/pom.xml
nifi-extension-bundles/nifi-standard-services/nifi-record-serialization-services-bundle/nifi-record-serialization-services/pom.xml
nifi-toolkit/nifi-toolkit-cli/pom.xml
pom.xml

[NIFI-14558](https://issues.apache.org/jira/browse/NIFI-14558) - Bump GCP SDK to 26.60.0, fastcsv to 3.7.0, SNPM4J to 3.9.3, and others
- Google Drive from v3-rev20250427-2.0.0 to v3-rev20250506-2.0.0
- GCP SDK from 26.59.0 to 26.60.0 - https://github.com/googleapis/java-cloud-bom/releases/tag/v26.60.0
- Janus Graph from 1.2.0-20250219-143145.6c030f7 to 1.2.0-20250509-104313.02c1bcb
- SNMP4J from 3.9.2 to 3.9.3 - https://www.snmp4j.org/CHANGES.txt
- nimbus-jose-jwt from 10.2 to 10.3 - https://bitbucket.org/connect2id/nimbus-jose-jwt/src/master/CHANGELOG.txt
- fastcsv from 3.6.0 to 3.7.0 - https://github.com/osiegmar/FastCSV/blob/main/CHANGELOG.md#370---2025-05-11
- jline from 3.29.0 to 3.30.0 - https://github.com/jline/jline3/releases/tag/jline-3.30.0
- AWS SDK v2 from 2.31.37 to 2.31.40 …

NIFI-14558 - Bump GCP SDK to 26.60.0, fastcsv to 3.7.0, SNPM4J to 3.9.3, and others

---

nifi-extension-bundles/nifi-extension-utils/nifi-git-flow-registry/src/main/java/org/apache/nifi/registry/flow/git/serialize/VersionedComponentCollectionSerializer.java
nifi-extension-bundles/nifi-extension-utils/nifi-git-flow-registry/src/main/java/org/apache/nifi/registry/flow/git/serialize/VersionedComponentModule.java

[NIFI-14556](https://issues.apache.org/jira/browse/NIFI-14556) - normalizing JSON git-registered flows via custom module

NIFI-14556 - normalizing JSON git-registered flows via custom module

---

nifi-extension-bundles/nifi-email-bundle/nifi-email-processors/pom.xml
nifi-extension-bundles/nifi-iotdb-bundle/pom.xml
nifi-extension-bundles/nifi-standard-bundle/nifi-standard-content-viewer/pom.xml
nifi-framework-bundle/pom.xml
nifi-registry/nifi-registry-core/pom.xml
nifi-registry/pom.xml
nifi-toolkit/nifi-toolkit-cli/pom.xml
pom.xml

[NIFI-14594](https://issues.apache.org/jira/browse/NIFI-14594) - Bump Mockito to 5.18.0, Spring Integration to 6.5.0, Spring Boot to 3.4.6 and others
- Spring Integration from 6.4.4 to 6.5.0 - https://github.com/spring-projects/spring-integration/releases/tag/v6.5.0
- Spring Boot from 3.4.5 to 3.4.6 - https://github.com/spring-projects/spring-boot/releases/tag/v3.4.6
- IoTDB from 2.0.2 to 2.0.2-1 - https://github.com/apache/iotdb/releases/tag/v2.0.2-1
- oauth2-oidc-sdk from 11.24 to 11.25 - https://bitbucket.org/connect2id/oauth-2.0-sdk-with-openid-connect-extensions/src/master/CHANGELOG.txt
- JLine from 3.30.2 to 3.30.3 - https://github.com/jline/jline3/releases/tag/jline-3.30.3
- AWS SDK v2 from 2.31.46 to 2.31.48 - https://github.com/aws/aws-sdk-java-v2/blob/master/CHANGELOG.md
- …

NIFI-14594 - Bump Mockito to 5.18.0, Spring Integration to 6.5.0, Spring Boot to 3.4.6 and others

---

nifi-extension-bundles/nifi-azure-bundle/pom.xml
nifi-extension-bundles/nifi-box-bundle/pom.xml
nifi-extension-bundles/nifi-iotdb-bundle/pom.xml
nifi-extension-bundles/nifi-salesforce-bundle/nifi-salesforce-processors/pom.xml
nifi-extension-bundles/nifi-scripting-bundle/nifi-scripting-processors/pom.xml
nifi-extension-bundles/nifi-standard-shared-bundle/nifi-standard-shared-bom/pom.xml
nifi-registry/pom.xml
nifi-toolkit/nifi-toolkit-cli/pom.xml
pom.xml

[NIFI-14623](https://issues.apache.org/jira/browse/NIFI-14623) - Bump Azure SDK to 1.2.35, Box SDK to 4.16.2, Flyway to 11.9.0 and others
- Azure SDK BOM from 1.2.34 to 1.2.35 - https://github.com/Azure/azure-sdk-for-java/releases/tag/azure-sdk-bom_1.2.35
- MSAL4J from 1.19.1 to 1.20.1 - https://github.com/AzureAD/microsoft-authentication-library-for-java/releases/tag/v1.20.1
- Box SDK from 4.16.1 to 4.16.2 - https://github.com/box/box-java-sdk/releases/tag/v4.16.2
- IoTDB SDK from 2.0.2-1 to 2.0.3 - https://github.com/apache/iotdb/releases/tag/v2.0.3
- Camel Salesforce from 4.11.0 to 4.12.0 - https://github.com/apache/camel/releases/tag/camel-4.12.0
- Clojure from 1.12.0 to 1.12.1 - https://github.com/clojure/clojure/blob/master/changes.md#changes-to-clojure-in-version-1121
- …

NIFI-14623 - Bump Azure SDK to 1.2.35, Box SDK to 4.16.2, Flyway to 11.9.0 and others

---

nifi-extension-bundles/nifi-elasticsearch-bundle/nifi-elasticsearch-client-service/pom.xml
nifi-extension-bundles/nifi-elasticsearch-bundle/pom.xml
nifi-extension-bundles/nifi-gitlab-bundle/pom.xml
nifi-extension-bundles/nifi-graph-bundle/nifi-graph-test-clients/pom.xml
nifi-extension-bundles/nifi-mqtt-bundle/nifi-mqtt-processors/pom.xml
nifi-extension-bundles/nifi-protobuf-bundle/nifi-protobuf-services/pom.xml
nifi-registry/pom.xml
pom.xml

[NIFI-14642](https://issues.apache.org/jira/browse/NIFI-14642) - Bump Jetty to 12.0.22, Netty to 4.2.2.Final, Bouncycastle to 1.81 and others
- Maven Artifact from 3.9.9 to 3.9.10 - https://maven.apache.org/ref/3.9.10/
- Elasticsearch Client from 8.18.1 to 8.18.2 - https://github.com/elastic/elasticsearch-java/releases/tag/v8.18.2
- Gitlab4J from 6.0.0-rc.10 to 6.0.0 - https://github.com/gitlab4j/gitlab4j-api/releases/tag/6.0.0
- Janusgraph from 1.2.0-20250509-104313.02c1bcb to 1.2.0-20250608-090535.869f248 - https://github.com/JanusGraph/janusgraph/pkgs/container/janusgraph/433377497?tag=1.2.0-20250608-090535.869f248
- HiveMQ MQTT Client from 1.3.5 to 1.3.6 - https://github.com/hivemq/hivemq-mqtt-client/releases/tag/v1.3.6
- Wire Java from 5.3.1 to 5.3.3 - …

NIFI-14642 - Bump Jetty to 12.0.22, Netty to 4.2.2.Final, Bouncycastle to 1.81 and others

---

nifi-toolkit/nifi-toolkit-cli/src/main/java/org/apache/nifi/toolkit/cli/impl/command/nifi/pg/PGChangeAllVersions.java
nifi-toolkit/nifi-toolkit-cli/src/main/java/org/apache/nifi/toolkit/cli/impl/command/nifi/pg/PGChangeVersion.java
nifi-toolkit/nifi-toolkit-cli/src/main/java/org/apache/nifi/toolkit/cli/impl/command/nifi/pg/PGList.java
nifi-toolkit/nifi-toolkit-cli/src/main/java/org/apache/nifi/toolkit/cli/impl/command/registry/extension/UploadBundles.java
nifi-toolkit/nifi-toolkit-cli/src/main/java/org/apache/nifi/toolkit/cli/impl/result/nifi/ProcessGroupsResult.java
nifi-toolkit/nifi-toolkit-cli/src/main/java/org/apache/nifi/toolkit/cli/impl/result/nifi/ProcessGroupsVersionChangeResult.java
nifi-toolkit/nifi-toolkit-cli/src/main/java/org/apache/nifi/toolkit/cli/impl/result/nifi/VersionControlInfoResult.java

[NIFI-14645](https://issues.apache.org/jira/browse/NIFI-14645) - Toolkit CLI - improve change version for versioned PG and PG listing
_(I'm happy to break down the below into multiple issues/PRs if preferred but given the very limited amount of code changes, I put everything together)_
- Add recursive flag support to PG List command
- Fix PG Change Version to account for the branch feature
- Made optional the Flow ID in PG Change All Versions so that it is possible to upgrade all versioned flows to the latest available version
- Fix Upload Bundles command when recursive flag is set
- Add version control state to Process Groups Result to show if a process group is versioned and if yes, what's the associated state
- Add branch name to Version Control Info Result to show the branch name, if …

NIFI-14645 - Toolkit CLI - improve change version for versioned PG and PG listing

---

nifi-toolkit/nifi-toolkit-client/src/main/java/org/apache/nifi/toolkit/client/impl/request/OIDCClientCredentialsRequestConfig.java
nifi-toolkit/nifi-toolkit-client/src/main/java/org/apache/nifi/toolkit/client/impl/request/util/AccessToken.java

[NIFI-14650](https://issues.apache.org/jira/browse/NIFI-14650) - Toolkit CLI - handle OIDC access token expiration

NIFI-14650 - Toolkit CLI - handle OIDC access token expiration

---

nifi-extension-bundles/nifi-standard-services/nifi-record-serialization-services-bundle/nifi-record-serialization-services/pom.xml
nifi-extension-bundles/nifi-standard-services/nifi-record-serialization-services-bundle/nifi-record-serialization-services/src/main/java/org/apache/nifi/csv/FastCSVRecordReader.java
nifi-extension-bundles/nifi-standard-services/nifi-record-serialization-services-bundle/nifi-record-serialization-services/src/main/java/org/apache/nifi/csv/WriteFastCSVResult.java

[NIFI-14692](https://issues.apache.org/jira/browse/NIFI-14692) - Upgrade FastCSV to 4.0.0
Important information is here:
https://github.com/osiegmar/FastCSV/blob/main/docs/src/content/docs/guides/upgrading.md

NIFI-14692 - Upgrade FastCSV to 4.0.0

---

nifi-frontend/src/main/frontend/apps/nifi/src/app/pages/documentation/ui/controller-service-definition/controller-service-definition.component.html
nifi-frontend/src/main/frontend/apps/nifi/src/app/pages/documentation/ui/controller-service-definition/controller-service-definition.component.ts

[NIFI-14694](https://issues.apache.org/jira/browse/NIFI-14694)

[NIFI-14694] - Display SeeAlso annotations for controller services in documentation

---

nifi-registry/nifi-registry-core/nifi-registry-resources/src/main/resources/conf/nifi-registry.properties

Added additional scopes and identifying user to properties
[NIFI-14701](https://issues.apache.org/jira/browse/NIFI-14701)

NIFI-14701 Add OIDC properties to nifi-registry.properties

---

nifi-commons/nifi-content-viewer-utils/src/main/java/org/apache/nifi/web/HttpServletContentRequestContext.java
nifi-commons/nifi-record/src/main/java/org/apache/nifi/serialization/record/ResultSetRecordSet.java
nifi-extension-bundles/nifi-mongodb-bundle/nifi-mongodb-processors/src/test/java/org/apache/nifi/processors/mongodb/PutMongoIT.java
nifi-extension-bundles/nifi-standard-bundle/nifi-standard-processors/src/main/java/org/apache/nifi/processors/standard/db/impl/MySQLDatabaseAdapter.java
nifi-extension-bundles/nifi-standard-services/nifi-record-serialization-services-bundle/nifi-record-serialization-services/src/test/java/org/apache/nifi/avro/TestWriteAvroResult.java
nifi-framework-bundle/nifi-framework-extensions/nifi-provenance-repository-bundle/nifi-persistent-provenance-repository/src/main/java/org/apache/nifi/provenance/index/lucene/IndexDirectoryManager.java
nifi-framework-bundle/nifi-framework/nifi-framework-core/src/main/java/org/apache/nifi/controller/status/history/MetricRollingBuffer.java
nifi-framework-bundle/nifi-framework/nifi-framework-core/src/main/java/org/apache/nifi/controller/status/history/VolatileComponentStatusRepository.java
nifi-framework-bundle/nifi-framework/nifi-site-to-site/src/test/java/org/apache/nifi/remote/TestStandardRemoteGroupPort.java
nifi-framework-bundle/nifi-framework/nifi-site-to-site/src/test/java/org/apache/nifi/remote/protocol/socket/TestSocketFlowFileServerProtocol.java
nifi-toolkit/nifi-toolkit-cli/src/main/java/org/apache/nifi/toolkit/cli/impl/result/registry/ExtensionMetadataResult.java
nifi-toolkit/nifi-toolkit-cli/src/main/java/org/apache/nifi/toolkit/cli/impl/result/registry/TagCountResult.java
pmd-ruleset.xml

[NIFI-14194](https://issues.apache.org/jira/browse/NIFI-14194)
This PR involved introducing the PMD rule `ForLoopCanBeForeach` and fixing all those places in the code which violated this rule. For most of the cases it was an easy refactoring except for two for loops in
`MetricRollingBuffer` which I was not sure if it was possible to refactor hence I just placed the `SuppressWarnings` annotation over the methods with these for loops.

NIFI-14194 Added PMD rule ForLoopCanBeForeach to ensure where possible, a for each loop is used instead of a regular for loop.

---

nifi-toolkit/nifi-toolkit-cli/src/main/java/org/apache/nifi/toolkit/cli/impl/command/nifi/pg/PGImport.java

[NIFI-14706](https://issues.apache.org/jira/browse/NIFI-14706) - NiFi CLI - flow version should be optional in PG Import command

NIFI-14706 - NiFi CLI - flow version should be optional in PG Import command

---

nifi-extension-bundles/nifi-standard-bundle/nifi-standard-processors/src/main/java/org/apache/nifi/processors/standard/calcite/RecordResultSetOutputStreamCallback.java
nifi-framework-bundle/nifi-framework/nifi-web/nifi-jetty/src/main/java/org/apache/nifi/web/server/connector/FrameworkServerConnectorFactory.java
nifi-registry/nifi-registry-core/nifi-registry-jetty/src/main/java/org/apache/nifi/registry/jetty/connector/ApplicationServerConnectorFactory.java

[NIFI-14762](https://issues.apache.org/jira/browse/NIFI-14762)

NIFI-14762 Replaced deprecated method defaultIfNull of org.apache.commons.lang3.ObjectUtils with getIfNull.

---

nifi-extension-bundles/nifi-extension-utils/nifi-git-flow-registry/src/main/java/org/apache/nifi/registry/flow/git/AbstractGitFlowRegistryClient.java

[NIFI-14774](https://issues.apache.org/jira/browse/NIFI-14774) - Fix NPE with Parameters Strategies in Git Registry Clients

NIFI-14774 - Fix NPE with Parameters Strategies in Git Registry Clients

---

nifi-extension-bundles/nifi-standard-bundle/nifi-standard-processors/src/main/java/org/apache/nifi/processors/standard/ControlRate.java
nifi-extension-bundles/nifi-standard-bundle/nifi-standard-processors/src/main/java/org/apache/nifi/processors/standard/TailFile.java
nifi-framework-bundle/nifi-framework/nifi-framework-core/src/main/java/org/apache/nifi/controller/serialization/AffectedComponentSet.java
nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-api/src/main/java/org/apache/nifi/authorization/StandardAuthorizableLookup.java

[NIFI-14787](https://issues.apache.org/jira/browse/NIFI-14787)
This PR involved adding the suggestions made in PR #10107 which are
- org.apache.nifi.controller.serialization.AffectedComponentSet after line 550 added a break statement.
- org.apache.nifi.processors.standard.ControlRate after line 280 added a comment why there is no break statement.
org.apache.nifi.processors.standard.TailFile after line 1034 added a comment why there is no break statement.
org.apache.nifi.authorization.StandardAuthorizableLookup refactored to remove the nested switch statement into its own method in order to make the outer switch easier to read and thereby avoiding any violation of the  PMD ImplicitSwitchFallThrough rule.
Please …

NIFI-14787 Implemented code improvements to avoid PMD's ImplicitSwitchFallThrough rule.

---

nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-api/src/main/java/org/apache/nifi/web/api/AccessPolicyResource.java

[NIFI-14807](https://issues.apache.org/jira/browse/NIFI-14807) - Policy deletion - Skip parent authorization if no parent

NIFI-14807 - Policy deletion - Skip parent authorization if no parent

---

nifi-docker/dockerhub/README.md

[NIFI-14828](https://issues.apache.org/jira/browse/NIFI-14828)
N/A

NIFI-14828 Update the NiFi Docker README

---

nifi-extension-bundles/nifi-snowflake-bundle/nifi-snowflake-processors/src/main/java/org/apache/nifi/processors/snowflake/PutSnowflakeInternalStage.java

NIFI-14833 - Add FlowFile attribute support to PutSnowflakeInternalStage
Tested with both named and table internal stage.
````sql
-- Create database
CREATE DATABASE IF NOT EXISTS NIFI_TEST_DATABASE;
-- Use the database
USE DATABASE NIFI_TEST_DATABASE;
-- Create schema
CREATE SCHEMA IF NOT EXISTS NIFI_TEST_SCHEMA;
-- Use the schema
USE SCHEMA NIFI_TEST_SCHEMA;
-- Create table
CREATE TABLE IF NOT EXISTS NIFI_TEST_TABLE (
id INTEGER,
value STRING
);
-- Create internal stage
CREATE STAGE IF NOT EXISTS NIFI_CSV_STAGE
FILE_FORMAT = (
TYPE = 'CSV'
FIELD_DELIMITER = ','
SKIP_HEADER = 1
FIELD_OPTIONALLY_ENCLOSED_BY = '"'
ESCAPE_UNENCLOSED_FIELD = NONE
);
-- Create pipe to automatically ingest files from the stage
CREATE PIPE IF NOT EXISTS NIFI_CSV_PIPE
AUTO_INGEST = TRUE
AS
COPY INTO …
```

NIFI-14833 - Add FlowFile attribute support to PutSnowflakeInternalStage

---

nifi-framework-bundle/nifi-framework/nifi-client-dto/src/main/java/org/apache/nifi/web/api/dto/ConnectionDTO.java
nifi-framework-bundle/nifi-framework/nifi-client-dto/src/main/java/org/apache/nifi/web/api/dto/ProcessorConfigDTO.java
nifi-framework-bundle/nifi-framework/nifi-client-dto/src/main/java/org/apache/nifi/web/api/dto/provenance/lineage/LineageRequestDTO.java
nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-api/src/main/java/org/apache/nifi/web/api/FlowResource.java

NIFI-14850 - Fix OpenAPI Enum inconsistencies

NIFI-14850 - Fix OpenAPI Enum inconsistencies

---

nifi-extension-bundles/nifi-elasticsearch-bundle/nifi-elasticsearch-test-utils/pom.xml
nifi-extension-bundles/nifi-github-bundle/nifi-github-extensions/pom.xml
nifi-extension-bundles/nifi-iotdb-bundle/pom.xml
nifi-extension-bundles/nifi-mqtt-bundle/nifi-mqtt-processors/pom.xml
nifi-extension-bundles/nifi-protobuf-bundle/nifi-protobuf-services/pom.xml
nifi-extension-bundles/nifi-salesforce-bundle/nifi-salesforce-processors/pom.xml
nifi-extension-bundles/nifi-slack-bundle/nifi-slack-processors/pom.xml
nifi-extension-bundles/nifi-standard-services/nifi-dbcp-service-bundle/nifi-hikari-dbcp-service/pom.xml
nifi-registry/nifi-registry-core/nifi-registry-web-api/pom.xml
pom.xml

NIFI-14885 - Bump AWS SDK v2 to 2.32.27, Spring Security to 6.5.3, and others
- Docker Java API from 3.5.3 to 3.6.0 - https://github.com/docker-java/docker-java/releases/tag/3.6.0
- jjwt from 0.12.7 to 0.13.0 - https://github.com/jwtk/jjwt/releases/tag/0.13.0
- IoTDB from 2.0.4 to 2.0.5 - https://github.com/apache/iotdb/releases/tag/v2.0.5
- HiveMQ MQTT Client from 1.3.7 to 1.3.8 - https://github.com/hivemq/hivemq-mqtt-client/releases/tag/v1.3.8
- Wire from 5.3.10 to 5.3.11 - https://github.com/square/wire/blob/master/CHANGELOG.md
- Camel Salesforce from 4.13.0 to 4.14.0 - https://github.com/apache/camel/releases/tag/camel-4.14.0
- Slack Bolt Socket Mode from 1.45.3 to 1.45.4 - https://github.com/slackapi/java-slack-sdk/releases/tag/v1.45.4
- HikariCP from 7.0.1 to 7.0.2 - …

NIFI-14885 - Bump AWS SDK v2 to 2.32.27, Spring Security to 6.5.3, and others

---

nifi-code-coverage/pom.xml
nifi-commons/nifi-metrics/pom.xml
nifi-extension-bundles/nifi-gcp-bundle/nifi-gcp-processors/pom.xml
nifi-extension-bundles/nifi-scripting-bundle/nifi-scripting-processors/src/test/resources/groovy/test_lookup_inline.groovy
nifi-extension-bundles/nifi-scripting-bundle/nifi-scripting-processors/src/test/resources/groovy/test_simple_lookup_inline.groovy
nifi-extension-bundles/nifi-standard-bundle/pom.xml
nifi-framework-bundle/pom.xml
nifi-registry/pom.xml
pom.xml

NIFI-14901 - Bump Apache MINA sshd to 2.16.0, Apache Groovy to 5.0.0, and others
- io.dropwizard.metrics metrics core and 4.2.33 to 4.2.34 - https://github.com/dropwizard/metrics/releases/tag/v4.2.34
- Google Drive Service API from v3-rev20250723-2.0.0 to v3-rev20250819-2.0.0 - https://github.com/googleapis/google-api-java-client-services/blob/main/clients/google-api-services-drive/v3/2.0.0/README.md
- Apache SSHD from 2.15.0 to 2.16.0 - https://github.com/apache/mina-sshd/releases/tag/sshd-2.16.0
- Spring Boot from 3.5.4 to 3.5.5 - https://github.com/spring-projects/spring-boot/releases/tag/v3.5.5
- FlywayDB from 11.11.1 to 11.11.2 - https://github.com/flyway/flyway/releases/tag/flyway-11.11.2
- AWS SDK v2 from 2.32.27 to 2.32.29 - …

NIFI-14901 - Bump Apache MINA sshd to 2.16.0, Apache Groovy to 5.0.0, and others

---

nifi-extension-bundles/nifi-aws-bundle/nifi-aws-processors/src/main/java/org/apache/nifi/processors/aws/lambda/PutLambda.java

[NIFI-14898](https://issues.apache.org/jira/browse/NIFI-14898)
PutLambda - Add SSL Context Service

NIFI-14898 PutLambda - Add SSL Context Service

---

nifi-extension-bundles/nifi-gitlab-bundle/nifi-gitlab-extensions/src/main/java/org/apache/nifi/gitlab/GitLabRepositoryClient.java

NIFI-14886 - GitLab Registry Client - switch from Repository File API to Commit API
I have reproduced the issue mentioned in the JIRA where the error starts when a flow to be versioned is around 2.5MB. It looks like the Repository File API is using a PUT where the payload is URL encoded as query params. The Commit API on the other hand is doing a POST where the flow content is part of a larger JSON payload. I confirmed that I was able to commit versioned flows well over 10MB+ (the limit would likely be a timeout or some limits on the GitLab side now).

NIFI-14886 - GitLab Registry Client - switch from Repository File API to Commit API

---

nifi-framework-bundle/nifi-framework/nifi-framework-components/src/main/java/org/apache/nifi/registry/flow/mapping/NiFiRegistryFlowMapper.java
nifi-framework-bundle/nifi-framework/nifi-framework-core/src/test/java/org/apache/nifi/registry/flow/mapping/NiFiRegistryFlowMapperTest.java

NIFI-14411 - Add Parameter Context descriptions in Versioned Flows

NIFI-14411 - Add Parameter Context descriptions in Versioned Flows

---

nifi-framework-bundle/nifi-framework/nifi-framework-cluster/src/main/java/org/apache/nifi/cluster/coordination/http/endpoints/ParameterProviderMerger.java

NIFI-14023 - Fix NPE listing Parameter Providers when some are unreadable

NIFI-14023 - Fix NPE listing Parameter Providers when some are unreadable

---

nifi-extension-bundles/nifi-mongodb-bundle/nifi-mongodb-services/src/main/java/org/apache/nifi/mongodb/MongoDBControllerService.java
nifi-extension-bundles/nifi-mongodb-bundle/nifi-mongodb-services/src/test/java/org/apache/nifi/mongodb/MongoDBControllerServiceTest.java

NIFI-14933 - Improve MongoDB authentication handling
Added tests to confirm the different scenarios when information is provided through the URI property, or as a combination of properties.

NIFI-14933 - Improve MongoDB authentication handling

---

nifi-framework-bundle/nifi-framework/nifi-framework-components/src/main/java/org/apache/nifi/registry/flow/mapping/NiFiRegistryFlowMapper.java
nifi-framework-bundle/nifi-framework/nifi-framework-core/src/test/java/org/apache/nifi/registry/flow/mapping/NiFiRegistryFlowMapperTest.java

NIFI-14935 - Improve handling of a parameter referencing a controller service

NIFI-14935 - Improve handling of a parameter referencing a controller service

---

nifi-extension-bundles/nifi-azure-bundle/nifi-azure-registry-clients/pom.xml
nifi-extension-bundles/nifi-azure-bundle/nifi-azure-registry-clients/src/main/java/org/apache/nifi/azure/devops/AzureDevOpsAuthenticationStrategy.java
nifi-extension-bundles/nifi-azure-bundle/nifi-azure-registry-clients/src/main/java/org/apache/nifi/azure/devops/AzureDevOpsFlowRegistryClient.java
nifi-extension-bundles/nifi-azure-bundle/nifi-azure-registry-clients/src/main/java/org/apache/nifi/azure/devops/AzureDevOpsRepositoryClient.java
nifi-extension-bundles/nifi-azure-bundle/nifi-azure-registry-clients/src/main/java/org/apache/nifi/azure/devops/AzureGitDevOpsFlowRegistryClient.java
nifi-extension-bundles/nifi-azure-bundle/nifi-azure-registry-clients/src/main/resources/META-INF/services/org.apache.nifi.registry.flow.FlowRegistryClient
nifi-extension-bundles/nifi-azure-bundle/pom.xml

NIFI-14816 - Add Azure Git DevOps Flow Registry Client
We currently have support for Github, Gitlab and Bitbucket. This Jira is for adding a new implementation for Azure Git DevOps. The initial implementation will support only one authentication method with service principals and the client credentials OAuth2 flow.

NIFI-14816 - Add Azure Git DevOps Flow Registry Client

---

nifi-extension-bundles/nifi-azure-bundle/nifi-azure-processors/src/main/java/org/apache/nifi/processors/azure/eventhub/ConsumeAzureEventHub.java
nifi-extension-bundles/nifi-azure-bundle/nifi-azure-processors/src/main/java/org/apache/nifi/processors/azure/eventhub/GetAzureEventHub.java
nifi-extension-bundles/nifi-azure-bundle/nifi-azure-processors/src/main/java/org/apache/nifi/processors/azure/eventhub/checkpoint/ComponentStateCheckpointStoreUtils.java
nifi-extension-bundles/nifi-azure-bundle/nifi-azure-processors/src/test/java/org/apache/nifi/processors/azure/eventhub/GetAzureEventHubTest.java
nifi-extension-bundles/nifi-azure-bundle/nifi-azure-processors/src/test/java/org/apache/nifi/processors/azure/eventhub/checkpoint/AbstractCheckpointStoreTest.java
nifi-extension-bundles/nifi-azure-bundle/nifi-azure-processors/src/test/java/org/apache/nifi/processors/azure/eventhub/checkpoint/ComponentStateCheckpointStoreTest.java
nifi-extension-bundles/nifi-azure-bundle/nifi-azure-processors/src/test/java/org/apache/nifi/processors/azure/eventhub/checkpoint/ComponentStateCheckpointStoreUtilsTest.java

[NIFI-14941](https://issues.apache.org/jira/browse/NIFI-14941)

NIFI-14941 Updated the Azure code which use methods from Azure dependencies which have been deprecated

---

nifi-commons/nifi-metrics/pom.xml
nifi-commons/nifi-xml-processing/pom.xml
nifi-extension-bundles/nifi-azure-bundle/nifi-azure-processors/pom.xml
nifi-extension-bundles/nifi-email-bundle/nifi-email-processors/pom.xml
nifi-extension-bundles/nifi-standard-bundle/nifi-standard-processors/pom.xml
nifi-extension-bundles/nifi-standard-bundle/pom.xml
nifi-registry/pom.xml
pom.xml

NIFI-14983 - Bump Bouncycastle to 1.82, Swagger to 2.2.37, datafaker to 2.5.0, and others
- metrics-core and metrics-jvm from 4.2.36 to 4.2.37 - https://github.com/dropwizard/metrics/releases/tag/v4.2.37
- Microsoft Kusto from 7.0.2 to 7.0.3 - https://github.com/Azure/azure-kusto-java/releases/tag/v7.0.3
- Spring Integration from 6.5.1 to 6.5.2 - https://github.com/spring-projects/spring-integration/releases/tag/v6.5.2
- datafaker from 2.4.4 to 2.5.0 - https://github.com/datafaker-net/datafaker/releases/tag/2.5.0
- Jakarta Activation API from 2.1.3 to 2.1.4 - https://github.com/jakartaee/jaf-api/releases/tag/2.1.4
- FlywayDB from 11.12.0 to 11.13.0 - https://github.com/flyway/flyway/releases/tag/flyway-11.13.0
- AWS SDK v2 from 2.33.9 to 2.33.11 - …

NIFI-14983 - Bump Bouncycastle to 1.82, Swagger to 2.2.37, datafaker to 2.5.0, and others

---

nifi-framework-bundle/nifi-framework/nifi-framework-components/src/test/java/org/apache/nifi/logging/TestStandardLoggingContext.java

[NIFI-14997](https://issues.apache.org/jira/browse/NIFI-14997)

NIFI-14997 Placed cast before null to avoid warning message.

---

nifi-frontend/src/main/frontend/apps/nifi-registry/src/app/app.module.ts
nifi-frontend/src/main/frontend/apps/nifi-registry/src/app/service/about.service.ts
nifi-frontend/src/main/frontend/apps/nifi-registry/src/app/state/about/about.actions.ts
nifi-frontend/src/main/frontend/apps/nifi-registry/src/app/state/about/about.effects.ts
nifi-frontend/src/main/frontend/apps/nifi-registry/src/app/state/about/about.reducer.ts
nifi-frontend/src/main/frontend/apps/nifi-registry/src/app/state/about/about.selectors.ts
nifi-frontend/src/main/frontend/apps/nifi-registry/src/app/state/about/index.ts
nifi-frontend/src/main/frontend/apps/nifi-registry/src/app/state/error/error.effects.ts
nifi-frontend/src/main/frontend/apps/nifi-registry/src/app/state/error/index.ts
nifi-frontend/src/main/frontend/apps/nifi-registry/src/app/state/index.ts
nifi-frontend/src/main/frontend/apps/nifi-registry/src/app/ui/common/about-dialog/about-dialog.component.html
nifi-frontend/src/main/frontend/apps/nifi-registry/src/app/ui/common/about-dialog/about-dialog.component.scss
nifi-frontend/src/main/frontend/apps/nifi-registry/src/app/ui/common/about-dialog/about-dialog.component.ts
nifi-frontend/src/main/frontend/apps/nifi-registry/src/app/ui/header/header.component.html
nifi-frontend/src/main/frontend/apps/nifi-registry/src/app/ui/header/header.component.spec.ts
nifi-frontend/src/main/frontend/apps/nifi-registry/src/app/ui/header/header.component.ts
nifi-frontend/src/main/frontend/apps/nifi/src/app/ui/common/navigation/navigation.component.html
nifi-frontend/src/main/frontend/apps/nifi/src/app/ui/common/navigation/navigation.component.ts

[NIFI-15004](https://issues.apache.org/jira/browse/NIFI-15004)

NIFI-15004 nifi registry about dialog

---

nifi-frontend/src/main/frontend/apps/nifi-registry/src/app/app-routing.module.ts
nifi-frontend/src/main/frontend/apps/nifi-registry/src/app/app.component.html
nifi-frontend/src/main/frontend/apps/nifi-registry/src/app/app.module.ts
nifi-frontend/src/main/frontend/apps/nifi-registry/src/app/pages/buckets/feature/buckets.component.html
nifi-frontend/src/main/frontend/apps/nifi-registry/src/app/pages/buckets/feature/buckets.module.ts
nifi-frontend/src/main/frontend/apps/nifi-registry/src/app/pages/resources/feature/resources.component.html
nifi-frontend/src/main/frontend/apps/nifi-registry/src/app/pages/resources/feature/resources.module.ts
nifi-frontend/src/main/frontend/apps/nifi-registry/src/app/pages/route-not-found/feature/route-not-found.component.html
nifi-frontend/src/main/frontend/apps/nifi-registry/src/app/pages/route-not-found/feature/route-not-found.component.scss
nifi-frontend/src/main/frontend/apps/nifi-registry/src/app/pages/route-not-found/feature/route-not-found.component.ts
nifi-frontend/src/main/frontend/apps/nifi-registry/src/app/ui/common/page-content/page-content.component.html
nifi-frontend/src/main/frontend/apps/nifi-registry/src/app/ui/common/page-content/page-content.component.scss
nifi-frontend/src/main/frontend/apps/nifi-registry/src/app/ui/common/page-content/page-content.component.ts

[NIFI-15005](https://issues.apache.org/jira/browse/NIFI-15005)

NIFI-15005 route not found

---

nifi-frontend/src/main/frontend/apps/nifi/src/app/ui/common/controller-service/controller-service-table/controller-service-table.component.ts

[NIFI-14653](https://issues.apache.org/jira/browse/NIFI-14653)
Before:
After:

NIFI-14653 close menu after delete clicked

---

nifi-frontend/src/main/frontend/apps/nifi/src/app/ui/common/parameter-context/parameter-context-inheritance/parameter-context-inheritance.component.html

[NIFI-14401](https://issues.apache.org/jira/browse/NIFI-14401)

NIFI-14401 update paramater context inheritance X

---

nifi-framework-bundle/nifi-framework-extensions/nifi-framework-kubernetes-bundle/nifi-framework-kubernetes-state-provider/src/main/java/org/apache/nifi/kubernetes/state/provider/KubernetesConfigMapStateProvider.java
nifi-framework-bundle/nifi-framework-extensions/nifi-framework-kubernetes-bundle/nifi-framework-kubernetes-state-provider/src/test/java/org/apache/nifi/kubernetes/state/provider/KubernetesConfigMapStateProviderTest.java

NIFI-15050 - Handle 409 HTTP Conflict in KubernetesConfigMapStateProvider

NIFI-15050 - Handle 409 HTTP Conflict in KubernetesConfigMapStateProvider

---

nifi-extension-bundles/nifi-standard-bundle/nifi-standard-processors/src/main/java/org/apache/nifi/processors/standard/ExecuteSQL.java

[NIFI-15049](https://issues.apache.org/jira/browse/NIFI-15049)

NIFI-15049 Made list of property descriptors and set of relationships in ExecuteSQL static.
