apache/nifi

nar-bundles/standard-bundle/standard-processors/src/main/java/org/apache/nifi/processors/standard/ListenHTTP.java, nar-bundles/standard-bundle/standard-processors/src/main/java/org/apache/nifi/processors/standard/servlets/ListenHTTPServlet.java
=> NIFI-201: Supporting arbitrary HTTP headers as flow file attributes in ListenHTTP

nifi/nifi-nar-bundles/nifi-standard-bundle/nifi-standard-processors/src/main/java/org/apache/nifi/processors/standard/BinFiles.java, nifi/nifi-nar-bundles/nifi-standard-bundle/nifi-standard-processors/src/main/java/org/apache/nifi/processors/standard/MergeContent.java
Pulled out the binning logic from MergeContent into a superclass for binning processors.  Basically all of the min/max properties were moved to BinFiles.  Mostly focused on ensuring that the functionality was preserved from MergeContent, but there is certainly room for improvement in producing a more elegantly extensible class.
=> NIFI-305: Refactoring base class from MergeContent to allow more binning processors

nifi/nifi-docs/src/main/asciidoc/developer-guide.adoc
Corrected casing of JIRA and fixed NoClassDefFoundError typo.
Adding AsciiDoc as a technology used and then providing a link to tooling to aid in the documentation generation process.
=> Documentation contributing

nifi/nifi-nar-bundles/nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-api/src/main/java/org/apache/nifi/web/api/RemoteProcessGroupResource.java, nifi/nifi-nar-bundles/nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-ui/src/main/webapp/WEB-INF/partials/canvas/new-remote-process-group-dialog.jsp
On the front end, providing a placeHolder hint as to what the expected value looks like
On the back end validating that the user specified url(on create or update) is http://something or https://something
=> NIFI-344 - Remote processor group lets you specify protocols other than http/https

nifi/nifi-nar-bundles/nifi-standard-bundle/nifi-standard-processors/src/main/resources/docs/org.apache.nifi.processors.standard.EvaluateJsonPath/index.html
I did not make a JIRA issue, if one is needed, let me know and I can update this PR to include it.
This simply corrects a reference to Xpath from using the EvaluateXpath usage guide as a template for  EvaluateJsonPath.
=> Correcting improper reference to Xpath in EvaluateJsonPath usage documentation

nifi/nifi-nar-bundles/nifi-standard-bundle/nifi-standard-processors/src/main/java/org/apache/nifi/processors/standard/PutEmail.java
Fairly simple change to allow username and password as part of the SMTP settings. Both are not required. In addition, password is sensitive.
I've tested this against an SMTP server that requires authentication (AWS SES, Simple Email Service) and it works as expected.
=> NIFI-414 Add SMTP Username and Password Support to PutEmail Processor

nifi/nifi-api/src/main/java/org/apache/nifi/processor/ProcessSession.java, nifi/nifi-nar-bundles/nifi-framework-bundle/nifi-framework/nifi-framework-core/src/main/java/org/apache/nifi/controller/repository/StandardProcessSession.java, nifi/nifi-nar-bundles/nifi-framework-bundle/nifi-framework/nifi-framework-core/src/main/java/org/apache/nifi/controller/repository/io/DisableOnCloseInputStream.java, nifi/nifi-nar-bundles/nifi-framework-bundle/nifi-framework/nifi-framework-core/src/test/java/org/apache/nifi/controller/repository/TestStandardProcessSession.java
Contains fix to prevent clients of the ProcessSession from accessing the Input/Output Streams it provides once callbacks complete their execution:
- Created a DisableOnCloseInputStream and modified StandardProcessSession to utilize it
- Updated ProcessSession's javadoc
- Added tests
=> NIFI-396: StandardProcessSession allows InputStream to be accessed after returning from callback

nifi/nifi-commons/nifi-processor-utilities/src/main/java/org/apache/nifi/processor/util/StandardValidators.java, nifi/nifi-nar-bundles/nifi-standard-bundle/nifi-standard-processors/src/main/java/org/apache/nifi/processors/standard/InvokeHTTP.java
modified InvokeHTTP to use the new mechanism for connecting to ControllerServices.
deprecating StandardValidators.createControllerServiceExistsValidator()
=> NIFI-460 deprecating createControllerServiceExistsValidator

nifi/nifi-commons/nifi-socket-utils/src/main/java/org/apache/nifi/io/nio/ChannelDispatcher.java, nifi/nifi-commons/nifi-socket-utils/src/main/java/org/apache/nifi/io/nio/ChannelListener.java, nifi/nifi-commons/nifi-socket-utils/src/main/java/org/apache/nifi/io/nio/DatagramChannelReader.java, nifi/nifi-commons/nifi-socket-utils/src/test/java/org/apache/nifi/io/nio/example/ServerMain.java, nifi/nifi-nar-bundles/nifi-standard-bundle/nifi-standard-processors/src/main/java/org/apache/nifi/processors/standard/ListenUDP.java, nifi/nifi-nar-bundles/nifi-standard-bundle/nifi-standard-processors/src/main/java/org/apache/nifi/processors/standard/util/UDPStreamConsumer.java
This pull request shows a possible approach to support "FlowFile per Datagram" for NIFI-548.
Most of the changes are for passing down a flag from the processor all the way to the DatagramChannelReader which requires passing through a few levels of classes.
The important change to the logic is:
* DatagramChannelReader - break out of the receive loop if null, or if we only want one datagram
* UDPConsumerCallback - break out of writing to the FlowFile OutputStream if we hit the totalBytes, or if we only want one datagram
=> NIFI-548 - Listen UDP should support generation of a flowfile per datagram

nifi/nifi-nar-bundles/nifi-standard-bundle/nifi-standard-processors/src/main/java/org/apache/nifi/processors/standard/MergeContent.java, nifi/nifi-nar-bundles/nifi-standard-bundle/nifi-standard-processors/src/test/java/org/apache/nifi/processors/standard/TestMergeContent.java
Adds a "Delimiter Strategy" property which allows specifying the Header, Footer, and Demarcator as filenames, or as text values.
=> NIFI-446 Adding a Delimiter Strategy to MergeContent

nifi-nar-bundles/nifi-hadoop-bundle/nifi-hdfs-processors/src/main/java/org/apache/nifi/processors/hadoop/AbstractHadoopProcessor.java, nifi-nar-bundles/nifi-hadoop-bundle/nifi-hdfs-processors/src/main/java/org/apache/nifi/processors/hadoop/CreateHadoopSequenceFile.java, nifi-nar-bundles/nifi-hadoop-bundle/nifi-hdfs-processors/src/main/java/org/apache/nifi/processors/hadoop/GetHDFS.java, nifi-nar-bundles/nifi-hadoop-bundle/nifi-hdfs-processors/src/main/java/org/apache/nifi/processors/hadoop/PutHDFS.java, nifi-nar-bundles/nifi-hadoop-bundle/nifi-hdfs-processors/src/test/java/org/apache/nifi/processors/hadoop/GetHDFSTest.java
- Three main types of compression options:
NONE 		: no compression
AUTOMATIC 	: infers codec by extension
SPECIFIED	: specified codec (e.g. snappy, gzip, bzip, or lz4)
Added a CompressionType enum to the AbstractHadoopProcessor to make things a bit cleaner. Added two options (NONE [default] and AUTOMATIC).
=> NIFI-713: Infer Hadoop Compression Automatically

nifi-commons/nifi-processor-utilities/src/main/java/org/apache/nifi/processor/util/StandardValidators.java, nifi-nar-bundles/nifi-standard-bundle/nifi-standard-processors/src/main/java/org/apache/nifi/processors/standard/ExecuteProcess.java, nifi-nar-bundles/nifi-standard-bundle/nifi-standard-processors/src/main/java/org/apache/nifi/processors/standard/ExecuteStreamCommand.java, nifi-nar-bundles/nifi-standard-bundle/nifi-standard-processors/src/main/java/org/apache/nifi/processors/standard/util/ArgumentUtils.java, nifi-nar-bundles/nifi-standard-bundle/nifi-standard-processors/src/test/java/org/apache/nifi/processors/standard/TestExecuteProcess.java, nifi-nar-bundles/nifi-standard-bundle/nifi-standard-processors/src/test/java/org/apache/nifi/processors/standard/TestExecuteStreamCommand.java
- Unified the way ExecuteStreamCommand and ExecuteProcess handle arguments. This enables
the ExecuteStreamCommand to use semicolons as part of arguments. 
- Argument delimiters can now be specified. Their default being what they were using before (ExecuteStreamCommand -> ';' , ExecuteProcess -> ' ')
=> NIFI-604: Custom Argument Delimiters ExecuteStreamCommand / ExecuteProcess

nifi-nar-bundles/nifi-aws-bundle/nifi-aws-processors/src/main/java/org/apache/nifi/processors/aws/AbstractAWSProcessor.java, nifi-nar-bundles/nifi-aws-bundle/nifi-aws-processors/src/main/java/org/apache/nifi/processors/aws/s3/DeleteS3Object.java, nifi-nar-bundles/nifi-aws-bundle/nifi-aws-processors/src/main/resources/META-INF/services/org.apache.nifi.processor.Processor, nifi-nar-bundles/nifi-aws-bundle/nifi-aws-processors/src/test/java/org/apache/nifi/processors/aws/s3/TestDeleteS3Object.java
I'm sorry for the delay of my sending a new PR again. @danbress could you review it?
[[NIFI-774] Create a DeleteS3Object Processor - ASF JIRA](https://issues.apache.org/jira/browse/NIFI-774)
#72
=> [NIFI-774] Create a DeleteS3Object Processor

nifi-nar-bundles/nifi-standard-bundle/nifi-standard-processors/src/main/java/org/apache/nifi/processors/standard/PutDistributedMapCache.java, nifi-nar-bundles/nifi-standard-bundle/nifi-standard-processors/src/main/resources/META-INF/services/org.apache.nifi.processor.Processor, nifi-nar-bundles/nifi-standard-bundle/nifi-standard-processors/src/test/java/org/apache/nifi/processors/standard/TestPutDistributedMapCache.java
There is a standard controller service, called DistributedMapCacheServer, which provides a distributed cache, and an associated DistributedMapCacheClientService to interact with the cache. But there is not any standard processor, which puts data into the cache, and helps the user to leverage the distributed cache capabilities.
The purpose of PutDistributedMapCache is very similar to the egress processors: it gets the content of a FlowFile and puts it to a distributed map cache, using a cache key computed from FlowFile attributes. If the cache already contains the entry and the cache update strategy is 'keep original' the entry is not replaced.
=> NIFI-988: PutDistributedMapCache processor

nifi-nar-bundles/nifi-framework-bundle/nifi-framework/nifi-framework-core/src/main/java/org/apache/nifi/controller/repository/FileSystemRepository.java, nifi-nar-bundles/nifi-framework-bundle/nifi-framework/nifi-framework-core/src/test/java/org/apache/nifi/controller/repository/TestFileSystemRepository.java
The exception was caused due to basic file permissions. This fix overrides
'visitFileFailed' method of SimpleFileVisitor to log WARN message and allow
FileSystemRepository to continue.
=> NIFI-1051 Allowed FileSystemRepository to skip un-readable entries.

nifi-nar-bundles/nifi-framework-bundle/nifi-framework/nifi-framework-core/src/main/java/org/apache/nifi/controller/scheduling/StandardProcessScheduler.java, nifi-nar-bundles/nifi-standard-services/nifi-dbcp-service-bundle/nifi-dbcp-service/src/main/java/org/apache/nifi/dbcp/DBCPConnectionPool.java
Current implementation of DBCPConnectionPool was attempting to test if connection could be obtained via dataSource.getConnection().
Such call is naturally a blocking call and the duration of the block is dependent on driver implementation. Some drivers (e.g., Phoenix - https://phoenix.apache.org/installation.html)
attempts numerous retries before failing creating a deadlock when attempt was made to disable DBCPConnectionPool which was still being enabled.
This fix removes the connection test from DBCPConnectionPool.onConfigured() operation returning successfully upon creation of DataSource.
For more details see comments in https://issues.apache.org/jira/browse/NIFI-1061
=> NIFI-1061 fixed deadlock caused by DBCPConnectionPool.onConfigured()

nifi-api/src/main/java/org/apache/nifi/components/PropertyDescriptor.java, nifi-nar-bundles/nifi-framework-bundle/nifi-framework/nifi-framework-core/src/test/java/org/apache/nifi/controller/service/TestStandardControllerServiceProvider.java
Fixed the order of service state check in PropertyDescriptor
Encapsulated the check into private method for readability
Modified and documented test to validate correct behavior.
For more details please see comment in https://issues.apache.org/jira/browse/NIFI-1143
=> NIFI-1143 Fixed race condition which caused intermittent failures

nifi-nar-bundles/nifi-kafka-bundle/nifi-kafka-processors/pom.xml, nifi-nar-bundles/nifi-kafka-bundle/nifi-kafka-processors/src/main/java/org/apache/nifi/processors/kafka/GetKafka.java, nifi-nar-bundles/nifi-kafka-bundle/nifi-kafka-processors/src/main/java/org/apache/nifi/processors/kafka/KafkaUtils.java, nifi-nar-bundles/nifi-kafka-bundle/nifi-kafka-processors/src/main/java/org/apache/nifi/processors/kafka/PutKafka.java
Due to the fact that current component uses artificial names for properties set via UI and then maps those properties to the actual names used by Kafka, we can not rely on NiFi UI to display an error if user attempts to set a dynamic property which will eventually map to the same Kafka property. So, I’ve decided that any dynamic property will simply override an existing property with WARNING message displayed. It is actually consistent with how Kafka does it and displayed the overrides in the console. Updated the relevant annotation description.
It is also worth to mentioned that current code was using an old property from Kafka 0.7 (“zk.connectiontimeout.ms”) which is no longer present in Kafka 0.8 (WARN Timer-Driven Process Thread-7 utils.VerifiableProperties:83 - Property …
=> NIFI-1192 added support for dynamic properties to GetKafka

nifi-nar-bundles/nifi-aws-bundle/nifi-aws-processors/src/main/java/org/apache/nifi/processors/aws/sqs/GetSQS.java
This adds long polling support to the GetSQS processor.
By default, it sets the Receive Message Wait Time to zero, which is the same as the current behavior. Setting the Receive Message Wait Time to 1 second or greater causes the request to long poll for that period of time before returning.
=> NIFI-1103: Add support for long polling in GetSQS processor

nifi-assembly/pom.xml, nifi-nar-bundles/nifi-riemann-bundle/nifi-riemann-nar/pom.xml, nifi-nar-bundles/nifi-riemann-bundle/nifi-riemann-nar/src/main/resources/META-INF/NOTICE, nifi-nar-bundles/nifi-riemann-bundle/nifi-riemann-processors/pom.xml, nifi-nar-bundles/nifi-riemann-bundle/nifi-riemann-processors/src/main/java/org/apache/nifi/processors/riemann/PutRiemann.java, nifi-nar-bundles/nifi-riemann-bundle/nifi-riemann-processors/src/main/resources/META-INF/services/org.apache.nifi.processor.Processor, nifi-nar-bundles/nifi-riemann-bundle/nifi-riemann-processors/src/test/java/org/apache/nifi/processors/riemann/TestPutRiemann.java, nifi-nar-bundles/nifi-riemann-bundle/pom.xml, nifi-nar-bundles/pom.xml, pom.xml
- Introduced nifi-riemann-bundle for future Riemann backed monitoring
- Added initial PutRiemann processor for writing events to Riemann
using the Riemann batch client.
- Values for events are provided using the NiFi expression language
e.g. Metric -> ${latency.milliseconds:divide(1000)}
=> [NIFI-987] Added Processor For Writing Events to Riemann

nifi-nar-bundles/nifi-framework-bundle/nifi-framework/nifi-framework-core-api/src/main/java/org/apache/nifi/controller/service/ControllerServiceNode.java, nifi-nar-bundles/nifi-framework-bundle/nifi-framework/nifi-framework-core/src/main/java/org/apache/nifi/controller/scheduling/StandardProcessScheduler.java, nifi-nar-bundles/nifi-framework-bundle/nifi-framework/nifi-framework-core/src/main/java/org/apache/nifi/controller/service/StandardControllerServiceNode.java, nifi-nar-bundles/nifi-framework-bundle/nifi-framework/nifi-framework-core/src/main/java/org/apache/nifi/controller/service/StandardControllerServiceProvider.java, nifi-nar-bundles/nifi-framework-bundle/nifi-framework/nifi-framework-core/src/main/java/org/apache/nifi/controller/service/StandardControllerServiceReference.java, nifi-nar-bundles/nifi-framework-bundle/nifi-framework/nifi-framework-core/src/test/java/org/apache/nifi/controller/scheduling/TestStandardProcessScheduler.java, nifi-nar-bundles/nifi-framework-bundle/nifi-framework/nifi-framework-core/src/test/java/org/apache/nifi/controller/service/TestStandardControllerServiceProvider.java
Changed ControllerServiceNode by adding enable(..), disable(..) and isActive() operations. See javadocs for more details in both ControllerServiceNode and StandardControllerServiceNode
Refactored service enable/disable logic in StandardProcessScheduler and StandardControllerServiceNode . Below are some of the notes:
- No need for resetting class loader since its going to derive from the class loader of the service. In other words any classes that aren’t loaded and will be loaded within the scope of the already loaded service will be loaded by the class lower of that service
- No need to control 'scheduleState.isScheduled()’ since the logic has changed to use CAS operation on state update and the service state change is now atomic.
- Removed Thread.sleep(..) and while(true) loop in favor …
=> NIFI-1164 Fixed race condition and refactored

nifi-nar-bundles/nifi-standard-bundle/nifi-standard-reporting-tasks/src/main/java/org/apache/nifi/controller/ControllerStatusReportingTask.java
ControllerStatusReportingTask was using an abbreviated class name to prefix its loggers, "ControllerStatusReportingTask", instead of the fully-qualified name "org.apache.nifi.controller.ControllerStatusReportingTask", as specified in the documentation and standard across reporting tasks in the same package.
=> NIFI-1283 Fixing ControllerStatusReportingTask logger name

nifi-nar-bundles/nifi-standard-bundle/nifi-standard-processors/src/main/java/org/apache/nifi/processors/standard/SplitXml.java
Potential fix for Travis-CI test failure.
I'm using a TreeMap for the namespace prefixes, this will guarantee the order that the namespaces are written out in the split file.
=> NIFI-1421 Make namespace ordering deterministic in SplitXML

nifi-nar-bundles/nifi-standard-bundle/nifi-standard-processors/src/main/java/org/apache/nifi/processors/standard/util/JdbcCommon.java, nifi-nar-bundles/nifi-standard-bundle/nifi-standard-processors/src/test/java/org/apache/nifi/processors/standard/util/TestJdbcCommon.java
Changes the logic so no exception is thrown when meta.getColumnCount() returns 0, instead an empty Avro schema is produced.
=> NIFI-1412: Fix error during Avro conversion where no fields are present

nifi-nar-bundles/nifi-scripting-bundle/nifi-scripting-processors/src/main/java/org/apache/nifi/processors/script/AbstractScriptProcessor.java, nifi-nar-bundles/nifi-scripting-bundle/nifi-scripting-processors/src/main/java/org/apache/nifi/processors/script/ExecuteScript.java, nifi-nar-bundles/nifi-scripting-bundle/nifi-scripting-processors/src/main/java/org/apache/nifi/processors/script/InvokeScriptedProcessor.java, nifi-nar-bundles/nifi-scripting-bundle/nifi-scripting-processors/src/main/java/org/apache/nifi/processors/script/ScriptEngineConfigurator.java, nifi-nar-bundles/nifi-scripting-bundle/nifi-scripting-processors/src/main/java/org/apache/nifi/processors/script/impl/AbstractModuleClassloaderConfigurator.java, nifi-nar-bundles/nifi-scripting-bundle/nifi-scripting-processors/src/main/java/org/apache/nifi/processors/script/impl/GroovyScriptEngineConfigurator.java, nifi-nar-bundles/nifi-scripting-bundle/nifi-scripting-processors/src/main/java/org/apache/nifi/processors/script/impl/JavascriptScriptEngineConfigurator.java, nifi-nar-bundles/nifi-scripting-bundle/nifi-scripting-processors/src/main/resources/META-INF/services/org.apache.nifi.processors.script.ScriptEngineConfigurator, nifi-nar-bundles/nifi-scripting-bundle/nifi-scripting-processors/src/test/java/org/apache/nifi/processors/script/TestExecuteGroovy.java
This allows more than one module path to be set for scripts to use. Each language that has a specific configurator can deal with the module paths as they see fit. For example, the Groovy configurator can use a list of paths and look for JARs in any folders specified (rather than having to enumerate each JAR).
=> NIFI-210: Add support for multiple module paths for scripting

nifi-api/src/main/java/org/apache/nifi/processor/ProcessContext.java, nifi-mock/src/main/java/org/apache/nifi/util/MockProcessContext.java, nifi-nar-bundles/nifi-framework-bundle/nifi-framework/nifi-documentation/src/main/java/org/apache/nifi/documentation/mock/MockProcessContext.java, nifi-nar-bundles/nifi-framework-bundle/nifi-framework/nifi-framework-core/src/main/java/org/apache/nifi/controller/scheduling/ConnectableProcessContext.java, nifi-nar-bundles/nifi-framework-bundle/nifi-framework/nifi-framework-core/src/main/java/org/apache/nifi/processor/StandardProcessContext.java, nifi-nar-bundles/nifi-framework-bundle/nifi-framework/nifi-framework-core/src/main/java/org/apache/nifi/processor/StandardSchedulingContext.java
I've added a `getName()` method to `ProcessContext` which means that a `Processor` can access the name that was configured in the UI.
=> NIFI-1573 Allow programmatic access to a Processor's name

nifi-nar-bundles/nifi-framework-bundle/nifi-framework/nifi-framework-core/src/main/java/org/apache/nifi/controller/StandardProcessorNode.java
Need to ensure that processor state is STOPPED, not STOPPING
=> NIFI-1676: Do not allow Processor to be started if state is STOPPING

nifi-nar-bundles/nifi-standard-bundle/nifi-standard-processors/src/test/java/org/apache/nifi/processors/standard/TestPutUDP.java
TestPutUDP#testUnknownHostname.
=> NIFI-1795 Temporarily ignored incorrectly failing test

nifi-nar-bundles/nifi-framework-bundle/nifi-framework/nifi-resources/src/main/resources/bin/nifi.sh
Respecting when run.as is commented out by ensuring the chosen line starts with run.as optionally preceded by whitespace
=> NIFI-1817 Respecting when run.as is commented out

nifi-api/src/main/java/org/apache/nifi/controller/AbstractControllerService.java
This commit removes the unused import statement which is added at [this commit](https://github.com/apache/nifi/commit/46f8693bc6e906d66326e48233e139924648b904), in order to make build process succeed.
I was not sure if this is the right action to fix the problem since original JIRA issue [NIFI-1773](https://issues.apache.org/jira/browse/NIFI-1773) is already marked as resolved. Please let me know if there's a better way to do. I hope this helps.
=> NIFI-1773 Removed unused import statement.

nifi-nar-bundles/nifi-framework-bundle/nifi-framework/nifi-framework-core/src/test/java/org/apache/nifi/controller/state/providers/zookeeper/TestZooKeeperStateProvider.java
Since it is on master it's best to ignore, since the problem appears to be the lifecycle of the unit test
=> NIFI-1872: Ignore failing unit test for now until we can properly address

nifi-nar-bundles/nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-api/src/main/java/org/apache/nifi/web/api/dto/DtoFactory.java, nifi-nar-bundles/nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-api/src/main/java/org/apache/nifi/web/dao/impl/StandardProcessGroupDAO.java
- Ensuring child group contents are included in exported templates.
=> NIFI-1941: Child group contents in exported templates

nifi-nar-bundles/nifi-kafka-bundle/nifi-kafka-processors/src/main/java/org/apache/nifi/processors/kafka/KafkaPublisher.java, nifi-nar-bundles/nifi-kafka-bundle/nifi-kafka-processors/src/main/java/org/apache/nifi/processors/kafka/PutKafka.java, nifi-nar-bundles/nifi-kafka-bundle/nifi-kafka-processors/src/test/java/org/apache/nifi/processors/kafka/KafkaPublisherTest.java, nifi-nar-bundles/nifi-kafka-bundle/nifi-kafka-pubsub-processors/src/main/java/org/apache/nifi/processors/kafka/pubsub/KafkaPublisher.java, nifi-nar-bundles/nifi-kafka-bundle/nifi-kafka-pubsub-processors/src/main/java/org/apache/nifi/processors/kafka/pubsub/PublishKafka.java, nifi-nar-bundles/nifi-kafka-bundle/nifi-kafka-pubsub-processors/src/test/java/org/apache/nifi/processors/kafka/pubsub/KafkaPublisherTest.java, nifi-nar-bundles/nifi-kafka-bundle/nifi-kafka-pubsub-processors/src/test/java/org/apache/nifi/processors/kafka/pubsub/PublishKafkaTest.java, nifi-nar-bundles/nifi-kafka-bundle/nifi-kafka-pubsub-processors/src/test/java/org/apache/nifi/processors/kafka/pubsub/StubPublishKafka.java
- fixed the logging issue NIFI-2444 by ensuring the ProcessLog is added to KafkaPublisher
- fixed KafkaPublisher's isAllAcked operation to ensure that it properly reports that the flow file has failed.
- added additional test
=> NIFI-2444 NIFI-2445 fixed PublishKafka

nifi-docker/dockermaven/pom.xml, nifi-docker/pom.xml
NIFI-4193 Converting to use the dockerfile-maven plugin to replace deprecated plugin.
=> NIFI-4193 Converting to use the dockerfile-maven plugin 

nifi-toolkit/nifi-toolkit-assembly/docker/Dockerfile, nifi-toolkit/nifi-toolkit-assembly/docker/Dockerfile.hub, nifi-toolkit/nifi-toolkit-assembly/docker/sh/docker-entrypoint.sh, nifi-toolkit/nifi-toolkit-assembly/pom.xml
NIFI-4333: 
Providing Docker support of the NiFi Toolkit via Maven build and Docker
Hub.
=> NIFI-4333: Providing Docker support of the NiFi Toolkit

nifi-nar-bundles/nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-api/src/main/java/org/apache/nifi/web/api/ProcessGroupResource.java
NIFI-4733:
- Resolving logic issue in two phase commit when updating variable registry.
=> NIFI-4733: Addressing two phase commit logic issue in variable registry

nifi-mock/src/main/java/org/apache/nifi/util/MockProcessSession.java, nifi-nar-bundles/nifi-couchbase-bundle/nifi-couchbase-processors/src/test/java/org/apache/nifi/processors/couchbase/TestPutCouchbaseKey.java, nifi-nar-bundles/nifi-scripting-bundle/nifi-scripting-processors/src/main/java/org/apache/nifi/script/ScriptingComponentHelper.java, nifi-nar-bundles/nifi-standard-bundle/nifi-standard-processors/src/test/java/org/apache/nifi/processors/standard/TestWait.java
=> NIFI-5871 ignore UUID attribute when copying flow file attributes

nifi-nar-bundles/nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-ui/src/main/webapp/js/nf/canvas/nf-queue-listing.js
NIFI-6221 Adding 'Download' and 'View' content icon buttons to slick grid actions column to improve end user navigation.
=> NIFI-6221 Adding 'Download' and 'View' content buttons to List Queue

nifi-nar-bundles/nifi-prometheus-bundle/nifi-prometheus-reporting-task/src/main/java/org/apache/nifi/reporting/prometheus/api/PrometheusMetricsUtil.java, nifi-nar-bundles/nifi-site-to-site-reporting-bundle/nifi-site-to-site-reporting-task/src/main/java/org/apache/nifi/reporting/SiteToSiteStatusReportingTask.java, nifi-nar-bundles/nifi-site-to-site-reporting-bundle/nifi-site-to-site-reporting-task/src/main/resources/docs/org.apache.nifi.reporting.SiteToSiteStatusReportingTask/additionalDetails.html, nifi-nar-bundles/nifi-site-to-site-reporting-bundle/nifi-site-to-site-reporting-task/src/main/resources/schema-status.avsc, nifi-nar-bundles/nifi-site-to-site-reporting-bundle/nifi-site-to-site-reporting-task/src/test/java/org/apache/nifi/reporting/TestSiteToSiteStatusReportingTask.java
Adds missing status fields (run status, e.g.) and metrics (terminated thread count, e.g.) to SiteToSiteStatusReportingTask and PrometheusReportingTask. `PrometheusMetricsUtil` had CRLF line endings so I removed them, please ignore whitespace while reviewing, thanks!
=> NIFI-5417: Add missing component status and metrics to S2SStatusReportingTask and PrometheusReportingTask

nifi-nar-bundles/nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-ui/src/main/webapp/js/nf/canvas/nf-connection.js, nifi-nar-bundles/nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-ui/src/main/webapp/js/nf/summary/nf-summary-table.js
* Updated the Connection summary table to only show the prediction column if predictions are available 
* Updated back pressure tooltips to indicate a distinction between Queue Prediction not being configured and not able to make a prediction just yet.
=> NIFI-6510 - Support enable disable of prediction in ui

nifi-mock/src/main/java/org/apache/nifi/util/MockProcessSession.java, nifi-mock/src/test/java/org/apache/nifi/util/TestMockProcessSession.java, nifi-nar-bundles/nifi-elasticsearch-bundle/nifi-elasticsearch-processors/src/main/java/org/apache/nifi/processors/elasticsearch/PutElasticsearchHttpRecord.java, nifi-nar-bundles/nifi-hive-bundle/nifi-hive3-processors/src/main/java/org/apache/nifi/processors/hive/PutHive3Streaming.java, nifi-nar-bundles/nifi-jolt-record-bundle/nifi-jolt-record-processors/src/main/java/org/apache/nifi/processors/jolt/record/JoltTransformRecord.java, nifi-nar-bundles/nifi-jolt-record-bundle/nifi-jolt-record-processors/src/test/java/org/apache/nifi/processors/jolt/record/TestJoltTransformRecord.java
For RecordReader implementations that don't close the underlying input stream when nextRecord() returns no records, JoltTransformRecord fails the flowfile instead of sending the input flowfile to the "original" relationship. Unit tests didn't catch it because MockProcessSession wasn't keeping track of the open stream counts.
=> NIFI-6925: Fixed JoltTransformRecord for RecordReaders, improved MockProcessSession

nifi-commons/nifi-properties/src/main/java/org/apache/nifi/util/NiFiProperties.java, nifi-commons/nifi-properties/src/test/java/org/apache/nifi/util/NiFiPropertiesTest.java
Added code to catch port value when it is 0. Added unit tests to validate port values.
=> NIFI-6336 Added code to catch port value when it is 0.

nifi-nar-bundles/nifi-extension-utils/nifi-record-utils/nifi-mock-record-utils/src/main/java/org/apache/nifi/serialization/record/ArrayListRecordReader.java, nifi-nar-bundles/nifi-extension-utils/nifi-record-utils/nifi-mock-record-utils/src/main/java/org/apache/nifi/serialization/record/ArrayListRecordWriter.java
ArrayListRecordReader (nifi-mock-record-utils) obtain inputStream in own constructor but don't close this. 
ArrayListRecordWriter has the same problem with outputStream.
So if in custom processor i use 
InputStream in = session.read(flowfile)
reader = factory.createRecordReader(flowfile, in, logger)
reader.close() 
Tests fail and complain that file didn't close.
Add streams and close them in close()
=> NIFI-6955 close streams in Reader/writer mock

nifi-nar-bundles/nifi-jms-bundle/nifi-jms-processors/src/main/java/org/apache/nifi/jms/processors/AbstractJMSProcessor.java, nifi-nar-bundles/nifi-jms-bundle/nifi-jms-processors/src/main/java/org/apache/nifi/jms/processors/ConsumeJMS.java, nifi-nar-bundles/nifi-jms-bundle/nifi-jms-processors/src/main/java/org/apache/nifi/jms/processors/JMSConsumer.java, nifi-nar-bundles/nifi-jms-bundle/nifi-jms-processors/src/main/java/org/apache/nifi/jms/processors/MessageBodyToBytesConverter.java, nifi-nar-bundles/nifi-jms-bundle/nifi-jms-processors/src/test/java/org/apache/nifi/jms/processors/ConsumeJMSIT.java, nifi-nar-bundles/nifi-jms-bundle/nifi-jms-processors/src/test/java/org/apache/nifi/jms/processors/ConsumeJMSManualTest.java, nifi-nar-bundles/nifi-jms-bundle/nifi-jms-processors/src/test/java/org/apache/nifi/jms/processors/JMSPublisherConsumerIT.java
https://issues.apache.org/jira/browse/NIFI-7015
ConsumeJMS now supports ObjectMessage, MapMessage and StreamMessage types as well. Added optional ERROR_QUEUE property. Result flowfiles get a 'jms.messagetype' attribute that contains the incoming message type (TextMessage, BytesMessage, ObjectMessage, MapMessage or StreamMessage).
=> NIFI-7015 - ConsumeJMS supports additional message types

nifi-commons/nifi-security-utils/pom.xml, nifi-commons/nifi-security-utils/src/main/java/org/apache/nifi/security/util/crypto/Argon2SecureHasher.java, nifi-commons/nifi-security-utils/src/main/java/org/apache/nifi/security/util/crypto/SecureHasher.java, nifi-commons/nifi-security-utils/src/test/groovy/org/apache/nifi/security/util/crypto/Argon2SecureHasherTest.groovy, nifi-commons/nifi-security-utils/src/test/resources/logback-test.xml, nifi-nar-bundles/nifi-framework-bundle/nifi-framework/nifi-framework-core/src/main/java/org/apache/nifi/fingerprint/FingerprintFactory.java, nifi-nar-bundles/nifi-framework-bundle/nifi-framework/nifi-framework-core/src/test/groovy/org/apache/nifi/fingerprint/FingerprintFactoryGroovyTest.groovy, nifi-nar-bundles/nifi-framework-bundle/nifi-framework/nifi-framework-core/src/test/java/org/apache/nifi/fingerprint/FingerprintFactoryTest.java, nifi-nar-bundles/nifi-framework-bundle/nifi-framework/nifi-framework-core/src/test/resources/nifi/fingerprint/initial.xml, nifi-nar-bundles/nifi-framework-bundle/nifi-framework/nifi-framework-core/src/test/resources/nifi/fingerprint/modified.xml, nifi-nar-bundles/nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-security/src/test/java/org/apache/nifi/web/security/jwt/JwtServiceTest.java
_Changes the flow fingerprinting implementation._
=> NIFI-7079 Changed flow fingerprinting implementation

nifi-assembly/pom.xml, nifi-nar-bundles/nifi-standard-services/nifi-record-sink-service-bundle/nifi-record-sink-service-nar/pom.xml, nifi-nar-bundles/nifi-standard-services/nifi-record-sink-service-bundle/nifi-record-sink-service-nar/src/main/resources/META-INF/LICENSE, nifi-nar-bundles/nifi-standard-services/nifi-record-sink-service-bundle/nifi-record-sink-service/pom.xml, nifi-nar-bundles/nifi-standard-services/nifi-record-sink-service-bundle/nifi-record-sink-service/src/main/java/org/apache/nifi/record/sink/lookup/RecordSinkServiceLookup.java, nifi-nar-bundles/nifi-standard-services/nifi-record-sink-service-bundle/nifi-record-sink-service/src/main/resources/META-INF/services/org.apache.nifi.controller.ControllerService, nifi-nar-bundles/nifi-standard-services/nifi-record-sink-service-bundle/nifi-record-sink-service/src/test/java/org/apache/nifi/record/sink/lookup/MockRecordSinkService.java, nifi-nar-bundles/nifi-standard-services/nifi-record-sink-service-bundle/nifi-record-sink-service/src/test/java/org/apache/nifi/record/sink/lookup/TestProcessor.java, nifi-nar-bundles/nifi-standard-services/nifi-record-sink-service-bundle/nifi-record-sink-service/src/test/java/org/apache/nifi/record/sink/lookup/TestRecordSinkServiceLookup.java, nifi-nar-bundles/nifi-standard-services/nifi-record-sink-service-bundle/pom.xml, nifi-nar-bundles/nifi-standard-services/pom.xml
=> NIFI-7054: Add RecordSinkServiceLookup for dynamic sink routing

nifi-nar-bundles/nifi-framework-bundle/nifi-framework/nifi-framework-core/src/main/java/org/apache/nifi/groups/StandardProcessGroup.java
NIFI-6958:
- Addressing issue causing errors preventing version changes when there is a processor to enable or disable in a sub process group.
=> NIFI-6958: Fixing issue enabling/disabling processors in sub groups when changing versions

nifi-nar-bundles/nifi-standard-bundle/nifi-standard-processors/src/main/java/org/apache/nifi/processors/standard/ListenTCPRecord.java, nifi-nar-bundles/nifi-standard-bundle/nifi-standard-processors/src/test/java/org/apache/nifi/processors/standard/TestListenTCPRecord.java
https://issues.apache.org/jira/browse/NIFI-7286
ListenTCPRecord cleanup changed from @OnStopped to @OnUnschedulededuled
=> NIFI-7286 Fix: ListenTCPRecord doesn't release port when stopping + terminating while running

nifi-nar-bundles/nifi-framework-bundle/nifi-framework/nifi-framework-core/src/test/java/org/apache/nifi/controller/service/TestStandardControllerServiceInvocationHandler.java, nifi-system-tests/nifi-system-test-suite/src/test/java/org/apache/nifi/tests/system/NiFiSystemIT.java
This PR resets the classloader after running `TestStandardControllerServiceInvocationHandler` in nifi-framework-core and fixes a checkstyle violation on `NiFiSystemIT`. The classloader reset is to correct build failures on Java 11 that occur depending on the order the tests run in. See the JIRA for the details.
=> NIFI-7508: Reset classloader after running TestStandardControllerServiceInvocationHandler

nifi-nar-bundles/nifi-framework-bundle/nifi-framework/nifi-framework-core/src/main/java/org/apache/nifi/controller/status/analytics/models/OrdinaryLeastSquares.java, nifi-nar-bundles/nifi-framework-bundle/nifi-framework/nifi-framework-core/src/test/java/org/apache/nifi/controller/status/analytics/models/TestOrdinaryLeastSquares.java
Rather than propagate a SingularMatrixException all the way up the stack, instead just log it at debug level. Also I cleaned up some of the stream code and renamed the test class as it was misspelled so IDEs can't find it from the unit under test.
=> NIFI-7516: Catch and log SingularMatrixExceptions in OrdinaryLeastSquares model

nifi-nar-bundles/nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-api/src/main/java/org/apache/nifi/web/api/FlowResource.java, nifi-nar-bundles/nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-api/src/main/java/org/apache/nifi/web/api/ParameterContextResource.java, nifi-nar-bundles/nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-api/src/main/java/org/apache/nifi/web/api/ProcessGroupResource.java, nifi-nar-bundles/nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-api/src/main/java/org/apache/nifi/web/api/VersionsResource.java
Validate request object to be not null to fix NullPointerException fixes bug NIFI-7691.
=> NIFI-7691: Validate request object to be not null.

nifi-nar-bundles/nifi-standard-services/nifi-record-serialization-services-bundle/nifi-record-serialization-services/src/main/java/org/apache/nifi/csv/CSVReader.java, nifi-nar-bundles/nifi-standard-services/nifi-record-serialization-services-bundle/nifi-record-serialization-services/src/main/java/org/apache/nifi/csv/JacksonCSVRecordReader.java, nifi-nar-bundles/nifi-standard-services/nifi-record-serialization-services-bundle/nifi-record-serialization-services/src/test/java/org/apache/nifi/csv/TestJacksonCSVRecordReader.java
The `Record Separator` property for CSV components is available but not exposed in CSVReader as it is in other components. As a result the property is not set and returns `null` for its value. For the Jackson CSV parser (an option in CSVReader), this causes a NullPointerException. The property is now exposed and the Jackson parser configuration code is more defensive (with a unit test to verify)
=> NIFI-7734: Added Record Separator property to CSVReader

nifi-nar-bundles/nifi-hadoop-libraries-bundle/nifi-hadoop-libraries-nar/pom.xml, nifi-nar-bundles/nifi-hive-bundle/nifi-hive3-nar/pom.xml, nifi-nar-bundles/nifi-ranger-bundle/nifi-ranger-plugin/pom.xml, pom.xml
=> NIFI-7833 - Add Ozone support in Hadoop components where appropriate

nifi-nar-bundles/nifi-hadoop-bundle/nifi-hdfs-processors/src/main/java/org/apache/nifi/processors/hadoop/DeleteHDFS.java
=> NIFI-7984 Use UGI doAs in DeleteHDFS

nifi-nar-bundles/nifi-standard-bundle/nifi-standard-processors/src/main/java/org/apache/nifi/processors/standard/ReplaceText.java
Moving RegexReplace.additionalAttrs field to local variable in replace() method.
Concurrent usage of the additionalAttrs map caused data corruption.
https://issues.apache.org/jira/browse/NIFI-7994
=> NIFI-7994: Fixed ReplaceText concurrency issue

nifi-nar-bundles/nifi-framework-bundle/nifi-framework/nifi-framework-core/src/main/java/org/apache/nifi/controller/repository/crypto/EncryptedFileSystemRepository.java, nifi-nar-bundles/nifi-framework-bundle/nifi-framework/nifi-framework-core/src/test/groovy/org/apache/nifi/controller/repository/crypto/EncryptedFileSystemRepositoryTest.groovy
NIFI-8024 Added check for null ContentClaim in EncryptedFileSystemRepository.read() to avoid EOFException in following method implementation.  The standard FileSystemRepository.read() handles null ContentClaims, but the Encrypted implementation attempts to decrypt the contents.  This update brings the encrypted implementation in line with the standard implementation and adds a unit test for verification.
=> NIFI-8024 Added null claim check to EncryptedFileSystemRepository.read()

nifi-nar-bundles/nifi-framework-bundle/nifi-framework/nifi-documentation/src/main/java/org/apache/nifi/documentation/html/HtmlDocumentationWriter.java
Before this PR, the machine-friendly name was being shown in the documentation for dependent properties, which can make it difficult to map to the other property's name/doc. This minor change shows the display name instead.
=> NIFI-1121: Use display name for dependent property documentation

nifi-api/src/main/java/org/apache/nifi/components/RequiredPermission.java, nifi-nar-bundles/nifi-hadoop-bundle/nifi-hdfs-processors/src/main/java/org/apache/nifi/processors/hadoop/DeleteHDFS.java, nifi-nar-bundles/nifi-hadoop-bundle/nifi-hdfs-processors/src/main/java/org/apache/nifi/processors/hadoop/FetchHDFS.java, nifi-nar-bundles/nifi-hadoop-bundle/nifi-hdfs-processors/src/main/java/org/apache/nifi/processors/hadoop/GetHDFS.java, nifi-nar-bundles/nifi-hadoop-bundle/nifi-hdfs-processors/src/main/java/org/apache/nifi/processors/hadoop/MoveHDFS.java, nifi-nar-bundles/nifi-hadoop-bundle/nifi-hdfs-processors/src/main/java/org/apache/nifi/processors/hadoop/PutHDFS.java, nifi-nar-bundles/nifi-hive-bundle/nifi-hive3-processors/src/main/java/org/apache/nifi/processors/orc/PutORC.java, nifi-nar-bundles/nifi-parquet-bundle/nifi-parquet-processors/src/main/java/org/apache/nifi/processors/parquet/FetchParquet.java, nifi-nar-bundles/nifi-parquet-bundle/nifi-parquet-processors/src/main/java/org/apache/nifi/processors/parquet/PutParquet.java
NIFI-7884 Introduces READ_DISTRIBUTED_FILESYSTEM and WRITE_DISTRIBUTED_FILESYSTEM Required Permission values to distinguish annotated Processors from other Processors that are limited to accessing the local file system  As indicated in the existing annotation explanations, these permissions imply access to both distributed file systems as well as local file systems.  This update replaces permission definitions on the following Processors:
- DeleteHDFS
- FetchHDFS
- GetHDFS
- MoveHDFS
- PutHDFS
- PutORC
- FetchParquet
- PutParquet
Please ensure that once the PR is submitted, you check GitHub Actions CI for build issues and submit an update to your PR as …
=> NIFI-7884 Added and applied Distributed File System permissions

nifi-nar-bundles/nifi-extension-utils/nifi-hadoop-utils/src/main/java/org/apache/nifi/processors/hadoop/AbstractHadoopProcessor.java, nifi-nar-bundles/nifi-framework-bundle/nifi-framework/nifi-resources/src/main/resources/bin/nifi-env.sh, nifi-nar-bundles/nifi-hadoop-bundle/nifi-hdfs-processors/src/test/java/org/apache/nifi/processors/hadoop/AbstractHadoopTest.java, nifi-nar-bundles/nifi-hadoop-bundle/nifi-hdfs-processors/src/test/java/org/apache/nifi/processors/hadoop/SimpleHadoopProcessor.java
NIFI-7885 Introduces a Boolean environment variable named NIFI_HDFS_DENY_LOCAL_FILE_SYSTEM_ACCESS that be set to _true_ in order to deny access from HDFS Processors to the Local File System.  This change impacts all Processors that extend AbstractHadoopProcessor.  The evaluation occurs during Processor scheduling when retrieving the initial FileSystem object based on the provided Hadoop Configuration.  Setting the environment variable to _true_ will caused an AccessDeniedException to be thrown if an operator attempts to configure access to the Local File System.
Please ensure that once the PR is submitted, you check GitHub Actions CI for build issues and …
=> NIFI-7885 Added Environment Variable to deny LFS access using Hadoop

nifi-commons/nifi-utils/src/main/java/org/apache/nifi/flowfile/attributes/FlowFileMediaType.java, nifi-commons/nifi-utils/src/main/java/org/apache/nifi/flowfile/attributes/StandardFlowFileMediaType.java, nifi-nar-bundles/nifi-hadoop-bundle/nifi-hdfs-processors/src/main/java/org/apache/nifi/processors/hadoop/CreateHadoopSequenceFile.java, nifi-nar-bundles/nifi-hadoop-bundle/nifi-hdfs-processors/src/test/java/org/apache/nifi/processors/hadoop/TestCreateHadoopSequenceFile.java, nifi-nar-bundles/nifi-standard-bundle/nifi-standard-processors/src/main/java/org/apache/nifi/processors/standard/MergeContent.java, nifi-nar-bundles/nifi-standard-bundle/nifi-standard-processors/src/main/java/org/apache/nifi/processors/standard/PostHTTP.java, nifi-nar-bundles/nifi-standard-bundle/nifi-standard-processors/src/main/java/org/apache/nifi/processors/standard/UnpackContent.java, nifi-nar-bundles/nifi-standard-bundle/nifi-standard-processors/src/main/java/org/apache/nifi/processors/standard/servlets/ListenHTTPServlet.java, nifi-nar-bundles/nifi-standard-bundle/nifi-standard-processors/src/test/java/org/apache/nifi/processors/standard/CaptureServlet.java, nifi-nar-bundles/nifi-standard-bundle/nifi-standard-processors/src/test/java/org/apache/nifi/processors/standard/TestIdentifyMimeType.java, nifi-nar-bundles/nifi-standard-bundle/nifi-standard-processors/src/test/java/org/apache/nifi/processors/standard/TestMergeContent.java
NIFI-7937 Replaces multiple string references to FlowFile Media Types with a StandardFlowFileMediaType enum in nifi-utils.  The change replaces references in the following processors:
- CreateHadoopSequenceFile
- MergeContent
- PostHTTP
- UnpackContent
- ListenHTTP
- IdentityMimeType
The PostHTTP and ListenHTTP processors referenced _application/flowfile_ without a version number.  In order to provide backwards compatibility, StandardFlowFileMediaType includes both VERSION_1 and VERSION_UNSPECIFIED values to support these processors.
Please ensure that once the PR is submitted, you check GitHub Actions CI for build issues and submit an update to your PR as …
=> NIFI-7937 Added StandardFlowFileMediaType enum to replace string FlowFile Media Types

nifi-nar-bundles/nifi-standard-bundle/nifi-standard-processors/src/main/java/org/apache/nifi/processors/standard/PutFileTransfer.java, nifi-nar-bundles/nifi-standard-bundle/nifi-standard-processors/src/test/java/org/apache/nifi/processors/standard/TestFTP.java, nifi-nar-bundles/nifi-standard-bundle/nifi-standard-processors/src/test/java/org/apache/nifi/processors/standard/TestPutSFTP.java
Ensures tranfer hostnames are generated correctly in provenance messages; fixes bug NIFI-6242._
=> NIFI-6242 PutFileTransfer generation incorrect provenance event

nifi-nar-bundles/nifi-standard-bundle/nifi-standard-reporting-tasks/src/main/java/org/apache/nifi/controller/MonitorMemory.java
This clarifies some of the behavior of MonitorMemory, in particular for Memory Pools. It also includes a small change to the description for Usage Threshold to mention that Data Size is a valid configuration.
=> NIFI-8231 Clarify behavior of allowed values for Memory Pools in MonitorMemory

nifi-nar-bundles/nifi-single-user-iaa-providers-bundle/nifi-single-user-iaa-providers-nar/pom.xml, nifi-nar-bundles/nifi-single-user-iaa-providers-bundle/nifi-single-user-iaa-providers-nar/src/main/resources/META-INF/LICENSE, nifi-nar-bundles/nifi-single-user-iaa-providers-bundle/nifi-single-user-iaa-providers-nar/src/main/resources/META-INF/NOTICE, nifi-nar-bundles/nifi-single-user-iaa-providers-bundle/nifi-single-user-iaa-providers/pom.xml, nifi-nar-bundles/nifi-single-user-iaa-providers-bundle/nifi-single-user-iaa-providers/src/main/java/org/apache/nifi/authentication/single/user/SingleUserLoginIdentityProvider.java, nifi-nar-bundles/nifi-single-user-iaa-providers-bundle/nifi-single-user-iaa-providers/src/main/java/org/apache/nifi/authentication/single/user/encoder/BCryptPasswordEncoder.java, nifi-nar-bundles/nifi-single-user-iaa-providers-bundle/nifi-single-user-iaa-providers/src/main/java/org/apache/nifi/authentication/single/user/encoder/PasswordEncoder.java, nifi-nar-bundles/nifi-single-user-iaa-providers-bundle/nifi-single-user-iaa-providers/src/main/java/org/apache/nifi/authentication/single/user/writer/LoginCredentialsWriter.java, nifi-nar-bundles/nifi-single-user-iaa-providers-bundle/nifi-single-user-iaa-providers/src/main/java/org/apache/nifi/authentication/single/user/writer/StandardLoginCredentialsWriter.java, nifi-nar-bundles/nifi-single-user-iaa-providers-bundle/nifi-single-user-iaa-providers/src/main/java/org/apache/nifi/authorization/single/user/SingleUserAuthorizer.java, nifi-nar-bundles/nifi-single-user-iaa-providers-bundle/nifi-single-user-iaa-providers/src/main/resources/META-INF/services/org.apache.nifi.authentication.LoginIdentityProvider, nifi-nar-bundles/nifi-single-user-iaa-providers-bundle/nifi-single-user-iaa-providers/src/main/resources/META-INF/services/org.apache.nifi.authorization.Authorizer, nifi-nar-bundles/nifi-single-user-iaa-providers-bundle/nifi-single-user-iaa-providers/src/test/java/org/apache/nifi/authentication/single/user/SingleUserLoginIdentityProviderTest.java, nifi-nar-bundles/nifi-single-user-iaa-providers-bundle/nifi-single-user-iaa-providers/src/test/java/org/apache/nifi/authentication/single/user/encoder/BCryptPasswordEncoderTest.java, nifi-nar-bundles/nifi-single-user-iaa-providers-bundle/nifi-single-user-iaa-providers/src/test/java/org/apache/nifi/authentication/single/user/writer/StandardLoginCredentialsWriterTest.java, nifi-nar-bundles/nifi-single-user-iaa-providers-bundle/nifi-single-user-iaa-providers/src/test/java/org/apache/nifi/authorization/single/user/SingleUserAuthorizerTest.java, nifi-nar-bundles/nifi-single-user-iaa-providers-bundle/nifi-single-user-iaa-providers/src/test/resources/conf/login-identity-providers.xml, nifi-nar-bundles/nifi-single-user-iaa-providers-bundle/nifi-single-user-iaa-providers/src/test/resources/conf/populated-login-identity-providers.xml, nifi-nar-bundles/nifi-single-user-iaa-providers-bundle/nifi-single-user-iaa-providers/src/test/resources/conf/unsupported-login-identity-providers.xml, nifi-nar-bundles/nifi-single-user-iaa-providers-bundle/pom.xml, nifi-nar-bundles/pom.xml
NIFI-8363 Implements a Single User `LoginIdentityProvider` and `Authorizer` as an incremental step toward a default secure standalone installation of NiFi.  The `LoginIdentityProvider` class includes the following features:
- Reads and writes username and hashed password in `login-identity-providers.xml`
- Generates random username using `java.util.UUID.randomUUID()`
- Generates random password of using `java.security.SecureRandom` with Base64 encoding
- Writes generated password hash using bcrypt
The implementation is not intended for production use, but provides a basic level of security for standalone installations.  Future changes will incorporate updates to default configuration files so that this implementation can be reviewed independently.  Verifying runtime behavior requires the …
=> NIFI-8363 Added Single User Login Identity Provider and Authorizer

nifi-bootstrap/src/main/java/org/apache/nifi/bootstrap/RunNiFi.java, nifi-bootstrap/src/main/java/org/apache/nifi/bootstrap/util/SecureNiFiConfigUtil.java, nifi-bootstrap/src/test/java/org/apache/nifi/bootstrap/util/TestSecureNiFiConfigUtil.java, nifi-bootstrap/src/test/resources/nifi.properties.dns-sans, nifi-bootstrap/src/test/resources/nifi.properties.ip-sans, nifi-bootstrap/src/test/resources/nifi.properties.keystore-password, nifi-bootstrap/src/test/resources/nifi.properties.no-https, nifi-bootstrap/src/test/resources/nifi.properties.no-keystore-types, nifi-bootstrap/src/test/resources/nifi.properties.no-keystores, nifi-bootstrap/src/test/resources/nifi.properties.only-keystore, nifi-bootstrap/src/test/resources/nifi.properties.only-truststore, nifi-bootstrap/src/test/resources/nifi.properties.stores-exist, nifi-bootstrap/src/test/resources/nifi.properties.success, nifi-bootstrap/src/test/resources/nifi.properties.truststore-password, nifi-commons/nifi-security-utils/src/main/java/org/apache/nifi/security/util/CertificateUtils.java, nifi-commons/nifi-security-utils/src/main/java/org/apache/nifi/security/util/KeyStoreUtils.java, nifi-commons/nifi-security-utils/src/main/java/org/apache/nifi/security/util/StandardTlsConfiguration.java, nifi-nar-bundles/nifi-framework-bundle/nifi-framework/nifi-framework-components/src/main/java/org/apache/nifi/controller/state/manager/StandardStateManagerProvider.java, nifi-nar-bundles/nifi-framework-bundle/nifi-framework/nifi-resources/pom.xml
Adding autogeneration of self-signed certificate in a default keystore/truststore when applicable.  Conditions for autogeneration are as follows:
**nifi.properties contains the following configuration:**
```
nifi.web.https.port=<value> // Must be set
nifi.security.keystore=<value> // Recommend testing with ./conf/keystore.p12
nifi.security.truststore=<value> // Recommend testing with ./conf/truststore.p12
```
Additionally, the keystore and truststore files as configured must not exist on the file system at those locations in order for them to be autogenerated.  The code will not attempt to generate these files if one or both of them is present in the configured locations. 
**The results will be:**
- A self-signed certificate (CN=localhost) is generated with an expiration of 60 days.  The …
=> NIFI-8403: Generating Self-signed cert on startup when applicable

nifi-nar-bundles/nifi-standard-bundle/nifi-standard-processors/pom.xml
NIFI-8367 Removes joda-time direct dependency from `nifi-standard-processors`.  Recent changes to `InvokeHTTP` removed the last direct reference to Joda Time.  The `nifi-standard-content-viewer` module still relies on Joda Time for handling certain Avro fields and will remain necessary until the Avro dependency is upgraded.
=> NIFI-8367 Removed joda-time from nifi-standard-processors

nifi-nar-bundles/nifi-standard-bundle/nifi-standard-processors/src/main/java/org/apache/nifi/processors/standard/PutDatabaseRecord.java, nifi-nar-bundles/nifi-standard-bundle/nifi-standard-processors/src/test/groovy/org/apache/nifi/processors/standard/TestPutDatabaseRecord.groovy
If no columns are found for the specified table, call getTables() to see if the table exists at all, and return a more descriptive error message in that case. Otherwise, warn the user that the specified table has no columns
=> NIFI-8535: Better error message in PutDatabaseRecord when table does not exist

nifi-nar-bundles/nifi-framework-bundle/nifi-framework/nifi-framework-cluster/src/main/java/org/apache/nifi/cluster/spring/FileBasedClusterNodeFirewallFactoryBean.java, nifi-nar-bundles/nifi-framework-bundle/nifi-framework/nifi-framework-cluster/src/main/java/org/apache/nifi/cluster/spring/NodeClusterCoordinatorFactoryBean.java, nifi-nar-bundles/nifi-framework-bundle/nifi-framework/nifi-framework-cluster/src/test/java/org/apache/nifi/cluster/firewall/impl/FileBasedClusterNodeFirewallFactoryBeanTest.java
NIFI-8614 Updates `NodeClusterCoordinatorFactoryBean` to support a `null` instance of `ClusterNodeFirewall` as expected prior to upgrading from Spring Framework 4 to Spring Framework 5.  Changes include adjusting `FileBasedClusterNodeFirewallFactoryBean` to return `null` when the firewall configuration file is not found.  These changes are necessary to support existing system integration tests and clusters running without TLS configured.
=> NIFI-8614 Corrected Cluster Node Firewall for Spring 5

nifi-docker/dockerhub/README.md, nifi-docker/dockerhub/pom.xml, nifi-docker/dockerhub/sh/start.sh, nifi-docker/dockermaven/integration-test.sh, nifi-docker/dockermaven/sh/start.sh
NIFI-8725 Adds support for specifying Single User authentication credentials using environment variables in NiFi Docker images.  Additional updates include an example command and links to the Administration Guide section in the Docker README.
=> NIFI-8725 Added Single User Environment Variables for Docker

nifi-nar-bundles/nifi-kudu-bundle/nifi-kudu-processors/src/main/java/org/apache/nifi/processors/kudu/AbstractKuduProcessor.java, nifi-nar-bundles/nifi-kudu-bundle/nifi-kudu-processors/src/main/java/org/apache/nifi/processors/kudu/PutKudu.java, nifi-nar-bundles/nifi-kudu-bundle/nifi-kudu-processors/src/test/java/org/apache/nifi/processors/kudu/ITPutKudu.java, nifi-nar-bundles/nifi-kudu-bundle/pom.xml
As of KUDU-1884, Kudu supports custom Kerberos principals on server-side
and custom SASL protocol (service) names on client-side which must match
the SPN base, i.e. if the SPN is kudu/_HOST, SASL protocol name *must*
be "kudu" in the client to be able to connect to the cluster.
This patch adds the ability to configure this in the PutKudu processor.
=> NIFI-8463: Support custom SASL protocol name in PutKudu

nifi-nar-bundles/nifi-hadoop-bundle/nifi-hdfs-processors/src/main/java/org/apache/nifi/processors/hadoop/GetHDFS.java, nifi-nar-bundles/nifi-hadoop-bundle/nifi-hdfs-processors/src/test/java/org/apache/nifi/processors/hadoop/GetHDFSTest.java
https://issues.apache.org/jira/browse/NIFI-8787
In GetHDFS processor, an hdfs.exists(directoryPath) call needed to be preceded with the getUGI() call because that is where Kerberos relogin is handled. Also hdfs.exists() is now wrapped in UGI.doAs().
=> NIFI-8787: Wrapped hdfs.exists() call in UGI.doAs() in GetHDFS processor

nifi-docs/src/main/asciidoc/administration-guide.adoc
NIFI-8964 Adds a `Cluster Firewall Configuration` section under the general `Clustering Configuration` heading in the NiFi System Adminstrator's Guide. The section includes an example configuration file showing supported file syntax.
=> NIFI-8964 Add Cluster Firewall Configuration to Admin Guide

nifi-nar-bundles/nifi-framework-bundle/nifi-framework/nifi-client-dto/src/main/java/org/apache/nifi/web/api/dto/ParameterDTO.java, nifi-nar-bundles/nifi-framework-bundle/nifi-framework/nifi-framework-components/src/main/java/org/apache/nifi/parameter/StandardParameterContext.java, nifi-nar-bundles/nifi-framework-bundle/nifi-framework/nifi-framework-core-api/src/main/java/org/apache/nifi/parameter/ParameterContext.java, nifi-nar-bundles/nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-api/src/main/java/org/apache/nifi/web/StandardNiFiServiceFacade.java, nifi-nar-bundles/nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-api/src/main/java/org/apache/nifi/web/api/dto/EntityFactory.java, nifi-nar-bundles/nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-api/src/main/java/org/apache/nifi/web/dao/ParameterContextDAO.java, nifi-nar-bundles/nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-api/src/main/java/org/apache/nifi/web/dao/impl/StandardParameterContextDAO.java, nifi-nar-bundles/nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-ui/src/main/webapp/WEB-INF/partials/canvas/new-parameter-context-dialog.jsp, nifi-nar-bundles/nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-ui/src/main/webapp/css/dialog.css, nifi-nar-bundles/nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-ui/src/main/webapp/css/new-parameter-context-dialog.css, nifi-nar-bundles/nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-ui/src/main/webapp/js/nf/canvas/nf-parameter-contexts.js
NIFI-8491:
- Adding support for configuring parameter context inheritance.
=> NIFI-8491: Adding support for configuring parameter context inheritance

nifi-nar-bundles/nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-ui/src/main/webapp/js/jquery/propertytable/jquery.propertytable.js, nifi-nar-bundles/nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-ui/src/main/webapp/js/nf/nf-common.js
Jira: https://issues.apache.org/jira/browse/NIFI-9336
When configuring processors and controller services in the UI, if a user enters a property value that has leading or trailing whitespace, it's not always obvious and may not be desired. To indicate when a value contains leading/trailing whitespace, an icon with a tooltip will show next to the value in processor and controller services configurations.
To test:
- go to configurations in a processor or controller service
- enter a property value with leading and/or trailing whitespace
- you should see an info icon and tooltip show to the right of the value
to ensure the …
=> NIFI-9336 - Show icon for property values with leading or trailing whitespace

nifi-nar-bundles/nifi-framework-bundle/nifi-framework/nifi-framework-core/src/main/java/org/apache/nifi/controller/state/server/ZooKeeperStateServer.java
Observed a NullPointerException in embedded ZooKeeper shutdown while running system tests.  This was causing FlowController shutdown to fail, which resulted in lingering threads and cluster node shutdown hang.  Catch and log the exception, which will allow the process to shutdown cleanly.
Also adjusted order of object cleanup to match that of initialization. 
In order to streamline the review of the contribution we ask you to ensure the following steps have been taken:
=> NIFI-9233 - Improve reliability of system integration tests

nifi-nar-bundles/nifi-extension-utils/nifi-event-listen/src/main/java/org/apache/nifi/processor/util/listen/AbstractListenEventProcessor.java, nifi-nar-bundles/nifi-extension-utils/nifi-event-listen/src/main/java/org/apache/nifi/processor/util/listen/queue/TrackingLinkedBlockingQueue.java, nifi-nar-bundles/nifi-extension-utils/nifi-event-listen/src/test/java/org/apache/nifi/processor/util/listen/queue/TrackingLinkedBlockingQueueTest.java
NIFI-9655 Adds queue size debug logging to `ListenUDP` and `ListenUDPRecord` through updates to the `AbstractListenEventProcessor`.
The debug logging occurs at most once per minute. The implementation uses an `AtomicLong` to track the minimum next timestamp in milliseconds for logging, and relies on processor scheduling for logging invocation. This approach avoids running an additional thread for background logging, and expects that the processor will be scheduled more often than 60 second intervals. The implementation leverages a custom `TrackingLinkedBlockingQueue` to maintain the largest queue size over the lifecycle of the processor.  Restarting the processor resets the queue and associated largest queue size tracking. …
=> NIFI-9655 Add Queue Logging to ListenUDP

nifi-nar-bundles/nifi-standard-bundle/nifi-standard-processors/src/main/java/org/apache/nifi/processors/standard/util/SFTPTransfer.java, nifi-nar-bundles/nifi-standard-bundle/nifi-standard-processors/src/test/java/org/apache/nifi/processors/standard/util/TestServerSFTPTransfer.java
NIFI-6699 Corrects handling of symbolic links for `GetSFTP` and `ListSFTP` processors, which both use the `SFTPTransfer.getListing()` method to retrieve a listing of remote file information.
The current behavior evaluates the `FileMode.Type` property of each remote file and handles all symbolic links as directories when the the calling processor has the `Follow symlink` property is enabled.  With this approach, `SFTPTransfer` adds all remote symbolic links to a list of directories selected for recursion, including symbolic links to files. The results in a `FileNotFoundException` when `SFTPTransfer` attempts to read a symbolic link file as a directory.
To resolve this problem, the remote resource filter now performs a remote `stat()` request when evaluating a symbolic link for potential …
=> NIFI-6699 Correct SFTP symbolic link handling

nifi-nar-bundles/nifi-framework-bundle/nifi-framework/nifi-resources/src/main/resources/bin/nifi-env.sh, nifi-nar-bundles/nifi-framework-bundle/nifi-framework/nifi-resources/src/main/resources/conf/logback.xml, nifi-nar-bundles/nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-api/src/main/java/org/apache/nifi/web/contextlistener/ApplicationStartupContextListener.java, nifi-system-tests/nifi-system-test-suite/src/test/resources/conf/clustered/node1/bootstrap.conf, nifi-system-tests/nifi-system-test-suite/src/test/resources/conf/clustered/node1/logback.xml, nifi-system-tests/nifi-system-test-suite/src/test/resources/conf/clustered/node2/bootstrap.conf, nifi-system-tests/nifi-system-test-suite/src/test/resources/conf/clustered/node2/logback.xml, nifi-system-tests/nifi-system-test-suite/src/test/resources/conf/default/bootstrap.conf, nifi-system-tests/nifi-system-test-suite/src/test/resources/conf/default/logback.xml
NIFI-9688 Improves Logback shutdown handling, avoiding premature closure of the Logback context during application shutdown, and enabling log messages to be written during application termination.
The default [LogbackServletContainerInitializer](https://github.com/qos-ch/logback/blob/v_1.2.10/logback-classic/src/main/java/ch/qos/logback/classic/servlet/LogbackServletContainerInitializer.java) registers a `LogbackServletContainerListener` that closes the Logback context on web application shutdown. When Jetty registers NiFi web applications, it configures the Logback initializer using the standard Java ServiceLoader. With this behavior, Jetty calls `contextDestroyed` on the Logback Listener before NiFi termination has completed. This results is missing a number of log messages when …
=> NIFI-9688 Improve Logback shutdown handling

nifi-api/src/main/java/org/apache/nifi/flow/VersionedLabel.java, nifi-nar-bundles/nifi-framework-bundle/nifi-framework/nifi-client-dto/src/main/java/org/apache/nifi/web/api/dto/LabelDTO.java, nifi-nar-bundles/nifi-framework-bundle/nifi-framework/nifi-client-dto/src/main/java/org/apache/nifi/web/api/entity/LabelEntity.java, nifi-nar-bundles/nifi-framework-bundle/nifi-framework/nifi-framework-components/src/main/java/org/apache/nifi/connectable/StandardConnection.java, nifi-nar-bundles/nifi-framework-bundle/nifi-framework/nifi-framework-components/src/main/java/org/apache/nifi/controller/label/StandardLabel.java, nifi-nar-bundles/nifi-framework-bundle/nifi-framework/nifi-framework-components/src/main/java/org/apache/nifi/groups/StandardProcessGroupSynchronizer.java, nifi-nar-bundles/nifi-framework-bundle/nifi-framework/nifi-framework-components/src/main/java/org/apache/nifi/registry/flow/mapping/NiFiRegistryFlowMapper.java, nifi-nar-bundles/nifi-framework-bundle/nifi-framework/nifi-framework-components/src/main/java/org/apache/nifi/util/FlowDifferenceFilters.java, nifi-nar-bundles/nifi-framework-bundle/nifi-framework/nifi-framework-core-api/src/main/java/org/apache/nifi/controller/label/Label.java, nifi-nar-bundles/nifi-framework-bundle/nifi-framework/nifi-framework-core/src/main/java/org/apache/nifi/controller/StandardFlowSnippet.java, nifi-nar-bundles/nifi-framework-bundle/nifi-framework/nifi-framework-core/src/main/java/org/apache/nifi/controller/XmlFlowSynchronizer.java, nifi-nar-bundles/nifi-framework-bundle/nifi-framework/nifi-framework-core/src/main/java/org/apache/nifi/controller/serialization/FlowFromDOMFactory.java, nifi-nar-bundles/nifi-framework-bundle/nifi-framework/nifi-framework-core/src/main/java/org/apache/nifi/controller/serialization/StandardFlowSerializer.java, nifi-nar-bundles/nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-api/src/main/java/org/apache/nifi/web/api/dto/DtoFactory.java, nifi-nar-bundles/nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-api/src/main/java/org/apache/nifi/web/api/dto/EntityFactory.java, nifi-nar-bundles/nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-api/src/main/java/org/apache/nifi/web/dao/impl/StandardLabelDAO.java, nifi-nar-bundles/nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-ui/src/main/webapp/js/nf/canvas/nf-actions.js, nifi-nar-bundles/nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-ui/src/main/webapp/js/nf/canvas/nf-context-menu.js, nifi-nar-bundles/nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-ui/src/main/webapp/js/nf/canvas/nf-label.js, nifi-registry/nifi-registry-core/nifi-registry-flow-diff/src/main/java/org/apache/nifi/registry/flow/diff/DifferenceType.java, nifi-registry/nifi-registry-core/nifi-registry-flow-diff/src/main/java/org/apache/nifi/registry/flow/diff/StandardFlowComparator.java
Link to Jira: https://issues.apache.org/jira/browse/NIFI-9543
This PR adds bring-to-front functionality to labels on the canvas. To test, add multiple overlapping labels on the canvas, right click on a label below the others to open the context menu and choose `Bring to Front`. The label should now be at the top of the other overlapping labels. This label that's now at the front should be persisted even after shutting down and restarting NiFi.
Please ensure that once the PR is submitted, you check GitHub Actions CI for build issues and submit an …
=> NIFI-9543: Add bring-to-front functionality to labels

nifi-nar-bundles/nifi-framework-bundle/nifi-framework/nifi-framework-core/pom.xml, nifi-nar-bundles/nifi-framework-bundle/nifi-framework/nifi-framework-core/src/main/java/org/apache/nifi/controller/queue/clustered/client/async/nio/PeerChannel.java, nifi-nar-bundles/nifi-framework-bundle/nifi-framework/nifi-framework-core/src/test/java/org/apache/nifi/controller/queue/clustered/client/async/nio/TestPeerChannel.java
NIFI-9761 Corrects `PeerChannel` handling of TLS 1.3 post-handshake messages, avoiding unexpected behavior when attempting to read from the underlying `SocketChannel` after previous calls have already put data in the stream buffer. This resolves a latent issue with Load-Balanced Connections and TLS 1.3 communication.
The new `TestPeerChannel` leverages a simple socket server based on Netty to confirm expected behavior for both TLS 1.2 and TLS 1.3.
=> NIFI-9761 Correct PeerChannel processing for TLS 1.3

nifi-nar-bundles/nifi-standard-services/nifi-record-serialization-services-bundle/nifi-record-serialization-services/src/main/java/org/apache/nifi/grok/GrokReader.java, nifi-nar-bundles/nifi-standard-services/nifi-record-serialization-services-bundle/nifi-record-serialization-services/src/main/java/org/apache/nifi/grok/GrokRecordReader.java, nifi-nar-bundles/nifi-standard-services/nifi-record-serialization-services-bundle/nifi-record-serialization-services/src/test/java/org/apache/nifi/grok/TestGrokReader.java, nifi-nar-bundles/nifi-standard-services/nifi-record-serialization-services-bundle/nifi-record-serialization-services/src/test/java/org/apache/nifi/grok/TestGrokRecordReader.java
NIFI-9850 Adds support for multiple expressions to `GrokReader`.
The implementation updates the existing `Grok Expression` property with a new display name of `Grok Expressions` and enhances the property descriptor to support reading multiple expressions from a resource reference. The resource reference enables reading Grok Expressions from the property value itself as well as an external file path or URL. This approach maintains compatibility with existing property values that define a single Grok Expression.
The updated `Grok Expressions` property descriptor enables `GrokReader` to load multiple expressions, separated by newlines. The `GrokRecordReader` iterates over the configured expressions and returns on the first match found.
Changes include unit test optimization as well as a new …
=> NIFI-9850 Add support for multiple expressions to GrokReader

nifi-nar-bundles/nifi-framework-bundle/nifi-framework/nifi-framework-components/src/main/java/org/apache/nifi/processor/SimpleProcessLogger.java, nifi-nar-bundles/nifi-framework-bundle/nifi-framework/nifi-framework-components/src/test/java/org/apache/nifi/processor/TestSimpleProcessLogger.java, nifi-nar-bundles/nifi-framework-bundle/nifi-framework/nifi-framework-core/src/main/java/org/apache/nifi/controller/tasks/ConnectableTask.java
NIFI-9871 Corrects stack trace logging for extension components to avoid sending summarized stack trace causes to the SLF4J Logger. This change preserves the stack trace summary in bulletin messages and avoids writing duplicate information to application log files.
The `ConnectableTask` includes log wording adjustments to indicate the difference between termination, failure, and halted because of an uncaught exception.
The updated `TestSimpleProcessLogger` includes several new test methods to improve coverage and ensure consistent formatting.
The updated `SimpleProcessLogger` implementation of `ComponentLog` behaves as follows when logging an error:
1. Bulletin Messages contain a simple message with a summary of causes:
```
ListSFTP[id=d4ee5196-b059-3bab-4416-9f59a45cd7b0] Processing …
```
=> NIFI-9871 Correct Component Stack Trace Logging

nifi-nar-bundles/nifi-kafka-bundle/nifi-kafka-2-6-processors/src/main/java/org/apache/nifi/processors/kafka/pubsub/InFlightMessageTracker.java
Error reporting  statement has been changed such that it will write flowfile UUID attribute to bulletin
=> NIFI-9938  Error Reporting message has been Fixed for Kafka Bundle 

nifi-nar-bundles/nifi-ranger-bundle/nifi-ranger-plugin/pom.xml, nifi-registry/nifi-registry-extensions/nifi-registry-ranger/nifi-registry-ranger-plugin/pom.xml, pom.xml
[NIFI-9997](https://issues.apache.org/jira/browse/NIFI-9997) Upgrades Apache Ranger dependencies from 2.1.0 to 2.2.0 for both NiFi and NiFi Registry Ranger Plugins.
Ranger 2.2.0 depends on Hadoop 3.3.0, so the upgrade also includes updating the Hadoop version from 3.1.1 to the latest patch version of 3.3.2.
=> NIFI-9997 Upgrade Ranger from 2.1.0 to 2.2.0

.github/workflows/system-tests.yml
[NIFI-10038](https://issues.apache.org/jira/browse/NIFI-10038) Adds Ubuntu Java 17 as an additional platform to the GitHub system-tests workflow.
=> NIFI-10038 Add Java 17 to system-tests workflow

nifi-nar-bundles/nifi-framework-bundle/nifi-framework/nifi-framework-core-api/src/main/java/org/apache/nifi/controller/AbstractComponentNode.java, nifi-nar-bundles/nifi-framework-bundle/nifi-framework/nifi-framework-core-api/src/main/java/org/apache/nifi/controller/ComponentNode.java, nifi-nar-bundles/nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-api/src/main/java/org/apache/nifi/web/NiFiServiceFacade.java, nifi-nar-bundles/nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-api/src/main/java/org/apache/nifi/web/StandardNiFiServiceFacade.java, nifi-nar-bundles/nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-api/src/main/java/org/apache/nifi/web/api/ControllerServiceResource.java, nifi-nar-bundles/nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-api/src/main/java/org/apache/nifi/web/api/ProcessorResource.java, nifi-nar-bundles/nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-api/src/main/java/org/apache/nifi/web/api/ReportingTaskResource.java, nifi-nar-bundles/nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-ui/src/main/webapp/js/jquery/modal/jquery.modal.css, nifi-nar-bundles/nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-ui/src/main/webapp/js/jquery/propertytable/jquery.propertytable.js, nifi-nar-bundles/nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-ui/src/main/webapp/js/nf/canvas/nf-controller-service.js, nifi-nar-bundles/nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-ui/src/main/webapp/js/nf/canvas/nf-processor-configuration.js, nifi-nar-bundles/nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-ui/src/main/webapp/js/nf/canvas/nf-reporting-task.js, nifi-nar-bundles/nifi-scripting-bundle/nifi-scripting-processors/src/main/java/org/apache/nifi/reporting/script/ScriptedReportingTask.java, nifi-nar-bundles/nifi-standard-services/nifi-dbcp-service-bundle/nifi-dbcp-service/src/main/java/org/apache/nifi/dbcp/DBCPConnectionPool.java
[NIFI-9959](https://issues.apache.org/jira/browse/NIFI-9959) Adds web user interface support for Sensitive Dynamic Properties in Processors, Controller Services, and Reporting Tasks based on framework support implemented in #6057 for NIFI-9958.
The implementation applies the `SupportsSensitiveDynamicProperties` annotation to `DBCPConnectionPool` and `ScriptedReportingTask` to enable evaluation of component types in addition to `InvokeHTTP`.
The UI implementation adds a new `Sensitive Value` field to the New Property dialog with radio button selections for `Yes` and `No`. The implementation follows the same approach as the `Sensitive Value` field in Parameter definitions. The internal processing collects sensitive dynamic property names for sending to the REST API on each invocation. …
=> NIFI-9959 Add UI Support for Sensitive Dynamic Properties

nifi-api/src/main/java/org/apache/nifi/controller/status/ConnectionStatus.java, nifi-api/src/main/java/org/apache/nifi/controller/status/LoadBalanceStatus.java, nifi-api/src/main/java/org/apache/nifi/controller/status/ProcessGroupStatus.java, nifi-nar-bundles/nifi-framework-bundle/nifi-framework/nifi-framework-components/src/main/java/org/apache/nifi/reporting/AbstractEventAccess.java
[NIFI-10072](https://issues.apache.org/jira/browse/NIFI-10072)
=> NIFI-10072: Adding LoadBalanceStatus to ConnectionStatus

nifi-nar-bundles/nifi-smb-bundle/nifi-smb-processors/src/main/java/org/apache/nifi/processors/smb/PutSmbFile.java
[NIFI-10074](https://issues.apache.org/jira/browse/NIFI-10074)
In ```PutSmbFile.customValidate``` replace ```Collections.emptySet()``` to ```new ArrayList<>()``` to hold ```ValidationResults``` objects.
=> NIFI-10074 Fix potential UnsupportedOperationException in PutSmbFile customValidate.

nifi-nar-bundles/nifi-framework-bundle/nifi-framework/nifi-framework-cluster-protocol/src/main/java/org/apache/nifi/cluster/protocol/jaxb/JaxbProtocolContext.java, nifi-nar-bundles/nifi-framework-bundle/nifi-framework/nifi-framework-cluster-protocol/src/test/java/org/apache/nifi/cluster/protocol/impl/SocketProtocolListenerTest.java
[NIFI-10093](https://issues.apache.org/jira/browse/NIFI-10093) Updates `SocketProtocolListenerTest` to use 5 seconds instead of 1 second for socket timeout configuration. This change should make test methods more reliable in resource-constrained automated build environments. Additional changes include upgrading the test to JUnit 5 and including the missing generic type on `JaxbProtocolContext`.
=> NIFI-10093 Set timeout to 5 seconds on SocketProtocolListenerTest

nifi-nar-bundles/nifi-standard-services/nifi-record-serialization-services-bundle/nifi-record-serialization-services/src/main/java/org/apache/nifi/json/WriteJsonResult.java
[NIFI-10141](https://issues.apache.org/jira/browse/NIFI-10141) The current error logging when a field cannot be written out uses the record's (i.e the record reader's) schema, which is not an accurate depiction of why the field cannot be written. Instead the record writer's schema should be used in the logging statement to show the schema used to write the record.
=> NIFI-10141: Fix WriteJsonResult logging to show writer's schema

nifi-commons/nifi-record/src/main/java/org/apache/nifi/serialization/record/MapRecord.java, nifi-nar-bundles/nifi-standard-services/nifi-record-serialization-services-bundle/nifi-record-serialization-services/src/main/java/org/apache/nifi/json/JsonTreeRowRecordReader.java, nifi-nar-bundles/nifi-standard-services/nifi-record-serialization-services-bundle/nifi-record-serialization-services/src/test/java/org/apache/nifi/json/TestJsonTreeRowRecordReader.java
[NIFI-10109](https://issues.apache.org/jira/browse/NIFI-10109) Replaces usage of `HashMap` with `LinkedHashMap` in `JsonTreeRowRecordReader` and `MapRecord` to preserve input field order read from input JSON Objects nodes. This approach maintains a deterministic internal representation of objects.
=> NIFI-10109 Preserve Field Order in JsonTreeReader

nifi-nar-bundles/nifi-standard-bundle/nifi-standard-processors/src/main/java/org/apache/nifi/processors/standard/LookupRecord.java, nifi-nar-bundles/nifi-standard-bundle/nifi-standard-processors/src/test/java/org/apache/nifi/processors/standard/TestLookupRecord.java
[NIFI-10106](https://issues.apache.org/jira/browse/NIFI-10106)
=> NIFI-10106 Avoid NPE in LookupRecord.createLookupCoordinates

pom.xml
[NIFI-10395](https://issues.apache.org/jira/browse/NIFI-10395) Adds Apache Xalan to the list of banned dependencies. The last version 2.7.2 was released in April 2014 and CVE-2022-34169 highlights the fact that the project is dormant, with no future releases expected. The dependency is not currently used and should not be necessary as standard Java distributions include a repackaged version.
=> NIFI-10395 Add Apache Xalan to banned dependencies

nifi-api/src/main/java/org/apache/nifi/annotation/behavior/DefaultRunDuration.java, nifi-api/src/main/java/org/apache/nifi/annotation/behavior/RunDuration.java, nifi-api/src/main/java/org/apache/nifi/annotation/behavior/SupportsBatching.java, nifi-nar-bundles/nifi-framework-bundle/nifi-framework/nifi-framework-core/src/main/java/org/apache/nifi/controller/ExtensionBuilder.java
[NIFI-10366](https://issues.apache.org/jira/browse/NIFI-10366)
=> NIFI-10366: Make Default Run Duration configurable

nifi-toolkit/nifi-toolkit-cli/src/main/java/org/apache/nifi/toolkit/cli/impl/command/nifi/params/SetParam.java
[NIFI-10488](https://issues.apache.org/jira/browse/NIFI-10488)
CLI throws an error when we are trying to set an empty property:
```
ERROR: Error executing command 'set-param' : null 
```
Command to test with:
```
./cli.sh nifi set-param -u http://localhost:8080/ -pcid 32d572a1-0183-1000-a811-ab916612b4af -pn emptyParam -pv newvalue
```
=> NIFI-10488 Fix NullPointerException on updating empty ParameterContext property with NiFi Toolkit

nifi-nar-bundles/nifi-smb-bundle/nifi-smb-client-api/src/main/java/org/apache/nifi/services/smb/SmbListableEntity.java
=> NIFI-10507 removed absolute.path

nifi-assembly/src/main/assembly/ranger.xml
[NIFI-10549](https://issues.apache.org/jira/browse/NIFI-10549)
=> NIFI-10549: Remove group name wildcard from assembly for nifi-ranger-resources

nifi-nar-bundles/nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-ui/src/main/webapp/js/nf/canvas/nf-parameter-provider.js
[NIFI-10542](https://issues.apache.org/jira/browse/NIFI-10542)
Additional UI improvements for Parameter Providers.
=> NIFI-10542: set sensitivity for new parameters in a synced parameter context

nifi-manifest/nifi-runtime-manifest-core/src/main/java/org/apache/nifi/runtime/manifest/impl/StandardRuntimeManifestBuilder.java
NIFI-10584:
- Only including dependent values in manifest when they are non-null.
=> NIFI-10584: Only including dependent values in manifest when they are non-null

nifi-api/src/main/java/org/apache/nifi/flow/VersionedPort.java
- Add missing getter to class VersionedPort
=> NIFI-10627 - VersionedPort missing getter

nifi-nar-bundles/nifi-framework-bundle/nifi-framework/nifi-framework-core/src/main/java/org/apache/nifi/controller/XmlFlowSynchronizer.java, nifi-nar-bundles/nifi-framework-bundle/nifi-framework/nifi-framework-core/src/main/java/org/apache/nifi/controller/service/ControllerServiceLoader.java
[NIFI-10567](https://issues.apache.org/jira/browse/NIFI-10567) Corrects the parsing of Sensitive Dynamic Properties read from the XML version of the flow configuration, in absence of the JSON version.
The issue surfaces when upgrading to NiFi 1.17.0 or 1.18.0 from a version older than 1.16.0. The issue also requires the presence of a Parameter Context with a Sensitive value assigned to a component with a Sensitive Property. Upgrading from 1.16.0 and following is not a problem. Deleting the `flow.json.gz` configuration also triggers the problematic behavior.
The following steps can be used to reproduce the problem on NiFi 1.18.0:
1. Create a new Process Group
2. Create and assign a new Parameter Context
3. Create a Sensitive Parameter Value in the Parameter Context
4. Create a Processor …
=> NIFI-10567 Correct Sensitive Dynamic Property handling for flow.xml

nifi-nar-bundles/nifi-elasticsearch-bundle/nifi-elasticsearch-client-service/src/main/java/org/apache/nifi/elasticsearch/ElasticSearchLookupService.java, nifi-nar-bundles/nifi-email-bundle/nifi-email-processors/src/main/java/org/apache/nifi/processors/email/ConsumeEWS.java, nifi-nar-bundles/nifi-standard-bundle/nifi-standard-processors/src/main/java/org/apache/nifi/processors/standard/CalculateRecordStats.java, nifi-nar-bundles/nifi-standard-bundle/nifi-standard-processors/src/main/java/org/apache/nifi/processors/standard/ForkRecord.java, nifi-nar-bundles/nifi-standard-bundle/nifi-standard-processors/src/main/java/org/apache/nifi/processors/standard/PutDatabaseRecord.java, nifi-nar-bundles/nifi-standard-services/nifi-lookup-services-bundle/nifi-lookup-services/src/main/java/org/apache/nifi/lookup/DistributedMapCacheLookupService.java, nifi-nar-bundles/nifi-tcp-bundle/nifi-tcp-processors/src/main/java/org/apache/nifi/processors/gettcp/GetTCP.java
[NIFI-10617](https://issues.apache.org/jira/browse/NIFI-10617)
=> NIFI-10617: Add missing DynamicProperty annotation to processors that use them

nifi-api/src/main/java/org/apache/nifi/flow/VersionedProcessGroup.java, nifi-api/src/main/java/org/apache/nifi/flow/VersionedRemoteProcessGroup.java, nifi-nar-bundles/nifi-framework-bundle/nifi-framework/nifi-framework-components/src/main/java/org/apache/nifi/flow/synchronization/StandardVersionedComponentSynchronizer.java, nifi-nar-bundles/nifi-framework-bundle/nifi-framework/nifi-framework-components/src/main/java/org/apache/nifi/registry/flow/mapping/NiFiRegistryFlowMapper.java
[NIFI-10668](https://issues.apache.org/jira/browse/NIFI-10668)
=> NIFI-10668 Persist proxy password in remote process group

nifi-nar-bundles/nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-ui/src/main/webapp/js/nf/canvas/nf-parameter-provider.js
[NIFI-10603](https://issues.apache.org/jira/browse/NIFI-10603)
In the Fetch Parameters dialog, sometimes the referencing components border shows when there is no content. The referencing components should only be populated and update the border for the currently selected parameter.
=> NIFI-10603: fix showing the referencing components border in the fetch parameters dialog

nifi-nar-bundles/nifi-extension-utils/nifi-event-transport/src/main/java/org/apache/nifi/event/transport/netty/ByteArrayMessageNettyEventServerFactory.java, nifi-nar-bundles/nifi-extension-utils/nifi-event-transport/src/main/java/org/apache/nifi/event/transport/netty/FilteringStrategy.java, nifi-nar-bundles/nifi-extension-utils/nifi-event-transport/src/main/java/org/apache/nifi/event/transport/netty/channel/FilteringByteArrayMessageChannelHandler.java, nifi-nar-bundles/nifi-standard-bundle/nifi-standard-processors/src/main/java/org/apache/nifi/processors/standard/ListenSyslog.java, nifi-nar-bundles/nifi-standard-bundle/nifi-standard-processors/src/test/java/org/apache/nifi/processors/standard/TestListenSyslog.java
[NIFI-10768](https://issues.apache.org/jira/browse/NIFI-10768) Updates the `ListenSyslog` Processor to discard incoming messages consisting of zero bytes.
This behavior can occur when the `Parse Messages` property is disabled. Changes include a new test method to send a batch of messages with an empty message to confirm expected behavior. The implementation adds a `FilteringStrategy` argument to the generic Server Factory to support the potential for other components to implement similar behavior.
=> NIFI-10768 Filter empty messages in ListenSyslog

nifi-nar-bundles/nifi-kafka-bundle/nifi-kafka-2-6-processors/pom.xml, nifi-nar-bundles/nifi-kafka-bundle/nifi-kafka-2-6-processors/src/main/java/org/apache/nifi/processors/kafka/pubsub/ConsumeKafkaRecord_2_6.java, nifi-nar-bundles/nifi-kafka-bundle/nifi-kafka-2-6-processors/src/main/java/org/apache/nifi/processors/kafka/pubsub/ConsumerLease.java, nifi-nar-bundles/nifi-kafka-bundle/nifi-kafka-2-6-processors/src/main/java/org/apache/nifi/processors/kafka/pubsub/ConsumerPool.java, nifi-nar-bundles/nifi-kafka-bundle/nifi-kafka-2-6-processors/src/main/java/org/apache/nifi/processors/kafka/pubsub/KafkaProcessorUtils.java, nifi-nar-bundles/nifi-kafka-bundle/nifi-kafka-2-6-processors/src/main/java/org/apache/nifi/processors/kafka/pubsub/OutputStrategy.java, nifi-nar-bundles/nifi-kafka-bundle/nifi-kafka-2-6-processors/src/main/java/org/apache/nifi/processors/kafka/pubsub/PublishKafkaRecord_2_6.java, nifi-nar-bundles/nifi-kafka-bundle/nifi-kafka-2-6-processors/src/main/java/org/apache/nifi/processors/kafka/pubsub/PublishKafka_2_6.java, nifi-nar-bundles/nifi-kafka-bundle/nifi-kafka-2-6-processors/src/main/java/org/apache/nifi/processors/kafka/pubsub/PublishMetadataStrategy.java, nifi-nar-bundles/nifi-kafka-bundle/nifi-kafka-2-6-processors/src/main/java/org/apache/nifi/processors/kafka/pubsub/PublishStrategy.java, nifi-nar-bundles/nifi-kafka-bundle/nifi-kafka-2-6-processors/src/main/java/org/apache/nifi/processors/kafka/pubsub/PublisherLease.java, nifi-nar-bundles/nifi-kafka-bundle/nifi-kafka-2-6-processors/src/main/java/org/apache/nifi/processors/kafka/pubsub/PublisherPool.java, nifi-nar-bundles/nifi-kafka-bundle/nifi-kafka-2-6-processors/src/main/resources/docs/org.apache.nifi.processors.kafka.pubsub.ConsumeKafkaRecord_2_6/additionalDetails.html, nifi-nar-bundles/nifi-kafka-bundle/nifi-kafka-2-6-processors/src/main/resources/docs/org.apache.nifi.processors.kafka.pubsub.PublishKafkaRecord_2_6/additionalDetails.html, nifi-nar-bundles/nifi-kafka-bundle/nifi-kafka-2-6-processors/src/test/java/org/apache/nifi/processors/kafka/pubsub/TestConsumeKafkaMock.java, nifi-nar-bundles/nifi-kafka-bundle/nifi-kafka-2-6-processors/src/test/java/org/apache/nifi/processors/kafka/pubsub/TestConsumeKafkaRecordKey_2_6.java, nifi-nar-bundles/nifi-kafka-bundle/nifi-kafka-2-6-processors/src/test/java/org/apache/nifi/processors/kafka/pubsub/TestPublishKafkaMock.java, nifi-nar-bundles/nifi-kafka-bundle/nifi-kafka-2-6-processors/src/test/java/org/apache/nifi/processors/kafka/pubsub/TestPublishKafkaMockParameterized.java, nifi-nar-bundles/nifi-kafka-bundle/nifi-kafka-2-6-processors/src/test/java/org/apache/nifi/processors/kafka/pubsub/TestPublishKafkaRecordKey_2_6.java, nifi-nar-bundles/nifi-kafka-bundle/nifi-kafka-2-6-processors/src/test/java/org/apache/nifi/processors/kafka/pubsub/TestPublishKafkaRecord_2_6.java, nifi-nar-bundles/nifi-kafka-bundle/nifi-kafka-2-6-processors/src/test/java/org/apache/nifi/processors/kafka/pubsub/TestPublisherLease.java, nifi-nar-bundles/nifi-kafka-bundle/nifi-kafka-2-6-processors/src/test/java/org/apache/nifi/processors/kafka/pubsub/TestPublisherPool.java, nifi-nar-bundles/nifi-kafka-bundle/nifi-kafka-2-6-processors/src/test/resources/PublishRecord/parameterized/flowfileInput1.json, nifi-nar-bundles/nifi-kafka-bundle/nifi-kafka-2-6-processors/src/test/resources/PublishRecord/parameterized/flowfileInputA.json, nifi-nar-bundles/nifi-kafka-bundle/nifi-kafka-2-6-processors/src/test/resources/PublishRecord/parameterized/kafkaOutput1V.json, nifi-nar-bundles/nifi-kafka-bundle/nifi-kafka-2-6-processors/src/test/resources/PublishRecord/parameterized/kafkaOutput1W.json, nifi-nar-bundles/nifi-kafka-bundle/nifi-kafka-2-6-processors/src/test/resources/PublishRecord/parameterized/kafkaOutputAV.json, nifi-nar-bundles/nifi-kafka-bundle/nifi-kafka-2-6-processors/src/test/resources/PublishRecord/parameterized/kafkaOutputAW.json
[NIFI-9822](https://issues.apache.org/jira/browse/NIFI-9822)
=> NIFI-9822 - ConsumeKafkaRecord allows writing out Kafka record key

nifi-nar-bundles/nifi-standard-bundle/nifi-standard-processors/src/main/java/org/apache/nifi/processors/standard/ListenHTTP.java
=> NIFI-10833 - Fix grammar error in ListenHTTP log msg

nifi-nar-bundles/nifi-framework-bundle/nifi-framework/nifi-framework-components/src/main/java/org/apache/nifi/flow/synchronization/StandardVersionedComponentSynchronizer.java, nifi-nar-bundles/nifi-framework-bundle/nifi-framework/nifi-framework-components/src/main/java/org/apache/nifi/groups/StandardProcessGroup.java, nifi-nar-bundles/nifi-framework-bundle/nifi-framework/nifi-framework-components/src/main/java/org/apache/nifi/registry/flow/StandardVersionControlInformation.java, nifi-nar-bundles/nifi-framework-bundle/nifi-framework/nifi-framework-core/src/main/java/org/apache/nifi/controller/serialization/VersionedFlowSynchronizer.java, nifi-nar-bundles/nifi-framework-bundle/nifi-framework/nifi-framework-core/src/test/java/org/apache/nifi/integration/versioned/ImportFlowIT.java, nifi-nar-bundles/nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-api/src/main/java/org/apache/nifi/web/StandardNiFiServiceFacade.java, nifi-nar-bundles/nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-api/src/main/java/org/apache/nifi/web/api/VersionsResource.java, nifi-registry/nifi-registry-core/nifi-registry-flow-diff/src/main/java/org/apache/nifi/registry/flow/diff/FlowComparatorVersionedStrategy.java, nifi-registry/nifi-registry-core/nifi-registry-flow-diff/src/main/java/org/apache/nifi/registry/flow/diff/StandardFlowComparator.java, nifi-registry/nifi-registry-core/nifi-registry-flow-diff/src/test/java/org/apache/nifi/registry/flow/diff/TestStandardFlowComparator.java, nifi-registry/nifi-registry-core/nifi-registry-framework/src/main/java/org/apache/nifi/registry/service/RegistryService.java
Comparison of the flows is used for multiple purposes, including synchronisation and to inform users. In some cases we want to include actual changes of the embedded versioned flows, in other cases we do not want to. In order to server every purpose properly, some differentiation was introduced. This shoud fix the issue mentioned in NIFI-10973 and also keep the benefits of NIFI-10939.
[NIFI-10973](https://issues.apache.org/jira/browse/NIFI-10973)
=> NIFI-10973 Introduce differention of comparing embedded versioned flows for UI and synchronisation purposes

nifi-nar-bundles/nifi-standard-services/nifi-dbcp-service-bundle/nifi-hikari-dbcp-service/pom.xml, nifi-nar-bundles/nifi-standard-services/nifi-dbcp-service-bundle/nifi-hikari-dbcp-service/src/test/java/org/apache/nifi/dbcp/HikariCPConnectionPoolTest.java, nifi-nar-bundles/nifi-standard-services/nifi-dbcp-service-bundle/nifi-hikari-dbcp-service/src/test/java/org/apache/nifi/dbcp/MockDriver.java
[NIFI-11191](https://issues.apache.org/jira/browse/NIFI-11191) Refactors the `HikariCPConnectionPoolTest` class using a `MockDriver` class to avoid intermittent failures related to concurrency and file locking when using Apache Derby.
The existing test class attempted to work around locking issues using specialized temporary file handling for the Derby database and associated the logs. The `MockDriver` approach avoids these issues and focuses the test on confirming whether the Controller Service returns a Connection.
=> NIFI-11191 Refactored HikariCPConnectionPoolTest with Mock Driver

.github/workflows/ci-workflow.yml
[NIFI-11257](https://issues.apache.org/jira/browse/NIFI-11257) Updates the Maven Wagon HTTP configuration for GitHub automated builds to enable connection pooling with additional retries.
Earlier Maven configurations disabled HTTP connection pooling attempting to improve stability, but more recent versions of Maven Wagon support a number of [HTTP configuration options](https://maven.apache.org/wagon/wagon-providers/wagon-http/).
The configuration updates switch to the default setting of HTTP connection pooling enabled, but set a time-to-live of 30 seconds for pooled connections. The configuration lowers the maximum connections per route from the default of 20 to 5, in order to reduce the number of simultaneous connections to the Maven Central repository.
Additional changes include setting …
=> NIFI-11257 Enable Maven HTTP pooling and additional retries

nifi-nar-bundles/nifi-cdc/nifi-cdc-mysql-bundle/nifi-cdc-mysql-processors/src/main/java/org/apache/nifi/cdc/mysql/processors/CaptureChangeMySQL.java, nifi-nar-bundles/nifi-cdc/nifi-cdc-mysql-bundle/nifi-cdc-mysql-processors/src/test/groovy/org/apache/nifi/cdc/mysql/processors/CaptureChangeMySQLTest.groovy, nifi-nar-bundles/nifi-framework-bundle/nifi-framework/nifi-framework-components/src/main/java/org/apache/nifi/controller/repository/StandardProcessSession.java
[NIFI-11279](https://issues.apache.org/jira/browse/NIFI-11279)
=> NIFI-11279: Allow event stream processing to continue in CaptureChangeMySQL after sync issue

nifi-nar-bundles/nifi-framework-bundle/nifi-framework/nifi-framework-components/src/main/java/org/apache/nifi/util/FlowDifferenceFilters.java, nifi-registry/nifi-registry-core/nifi-registry-flow-diff/src/main/java/org/apache/nifi/registry/flow/diff/ConciseEvolvingDifferenceDescriptor.java, nifi-registry/nifi-registry-core/nifi-registry-flow-diff/src/main/java/org/apache/nifi/registry/flow/diff/FlowDifferenceUtil.java
Contained versioned flows using registryUri to localize flows vere not handled properly when checking for local changes in the flow. This PR aims to solve this issue.
[NIFI-11213](https://issues.apache.org/jira/browse/NIFI-11213)
=> NIFI-11213 Showing version change in older (pre 1.18.0) contained version flows properly

nifi-nar-bundles/nifi-standard-bundle/nifi-standard-processors/src/main/java/org/apache/nifi/processors/standard/PutDatabaseRecord.java
[NIFI-11337](https://issues.apache.org/jira/browse/NIFI-11337) This PR removes the`dependsOn` from the definition of the Maximum Batch Size property as the dependency is not honored in the code. The documentation is updated to reflect the actual behavior, and the default value is changed to 1000 to avoid memory usage issues for large incoming FlowFiles. No unit tests were added as the existing tests show there is no regression.
=> NIFI-11337: Update PutDatabaseRecord's Max Batch Size property documentation to reflect actual behavior

nifi-nar-bundles/nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-security/src/main/java/org/apache/nifi/web/security/configuration/OidcSecurityConfiguration.java, nifi-nar-bundles/nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-security/src/main/java/org/apache/nifi/web/security/oidc/client/web/StandardOAuth2AuthorizationRequestResolver.java, nifi-nar-bundles/nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-security/src/test/java/org/apache/nifi/web/security/oidc/client/web/StandardOAuth2AuthorizationRequestResolverTest.java
[NIFI-11365](https://issues.apache.org/jira/browse/NIFI-11365) Corrects OpenID Connect Redirect URI resolution for NiFi deployments running behind a reverse proxy server. This fixes a regression introduced as a result of refactoring implemented for [NIFI-4890](https://issues.apache.org/jira/browse/NIFI-4890).
Changes include introducing an Authorization Request Resolver that delegates to the standard framework `RequestUriBuilder` for building a Redirect URI that considers allowed `X-Proxy` headers.
=> NIFI-11365 Correct OIDC Redirect URI resolution for reverse proxies

nifi-nar-bundles/nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-security/src/main/java/org/apache/nifi/web/security/configuration/OidcSecurityConfiguration.java, nifi-nar-bundles/nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-security/src/main/java/org/apache/nifi/web/security/oidc/authentication/StandardOidcIdTokenDecoderFactory.java, nifi-nar-bundles/nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-security/src/test/java/org/apache/nifi/web/security/oidc/authentication/StandardOidcIdTokenDecoderFactoryTest.java
[NIFI-11370](https://issues.apache.org/jira/browse/NIFI-11370) Corrects JSON Web Key Set retrieval when using the `NIFI` Trust Store Strategy.
The `NIFI` trust store strategy can be configured using `nifi.security.user.oidc.truststore.strategy` in application properties for integrating with Identity Providers that do not use certificates issued from public authorities.
The standard Spring Security [OidcIdTokenDecoderFactory](https://github.com/spring-projects/spring-security/blob/main/oauth2/oauth2-client/src/main/java/org/springframework/security/oauth2/client/oidc/authentication/OidcIdTokenDecoderFactory.java) implementation does not support providing an instance of `RestOperations` to the `NimbusJwtDecoder` builder, which results in using the default Java trust store instead of the …
=> NIFI-11370 Correct JWK Set retrieval for NIFI Trust Strategy

nifi-nar-bundles/nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-api/src/main/java/org/apache/nifi/web/NiFiServiceFacade.java, nifi-nar-bundles/nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-api/src/main/java/org/apache/nifi/web/StandardNiFiServiceFacade.java, nifi-nar-bundles/nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-api/src/main/java/org/apache/nifi/web/api/TenantsResource.java, nifi-nar-bundles/nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-api/src/test/java/org/apache/nifi/web/StandardNiFiServiceFacadeTest.java, nifi-nar-bundles/nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-ui/src/main/webapp/js/nf/canvas/nf-policy-management.js
[NIFI-11461](https://issues.apache.org/jira/browse/NIFI-11461) Improves the performance of the User and Group Tenants Search REST Resource method with the addition of a `searchTenants` method to the `NiFiServiceFacade`.
The previous implementation called `getUsers()` and `getUserGroups()` in the Tenants Resource, which requires retrieving all users and all group members before evaluating the query.
The new implementation passes the query string to the `NiFiServiceFacade.searchTenants()` method and applies the filtering criteria prior to additional object creation. This approach reduces the number of method calls significantly for large numbers of users and groups.
Additional changes include adjusting the user interface autocomplete delay from the default 300 ms to 500 ms, minimizing the …
=> NIFI-11461 Improve User and Group Tenants Search

nifi-nar-bundles/nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-ui/src/main/webapp/js/nf/canvas/nf-controller-service.js, nifi-nar-bundles/nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-ui/src/main/webapp/js/nf/canvas/nf-controller-services.js, nifi-nar-bundles/nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-ui/src/main/webapp/js/nf/canvas/nf-settings.js
=> NIFI-11433 - use .add() for set instead of .push()

nifi-commons/nifi-properties/src/main/java/org/apache/nifi/util/NiFiProperties.java, nifi-docs/src/main/asciidoc/administration-guide.adoc, nifi-framework-api/src/main/java/org/apache/nifi/components/state/StateProvider.java, nifi-nar-bundles/nifi-framework-bundle/nifi-framework/nifi-framework-components/src/main/java/org/apache/nifi/controller/state/manager/StandardStateManagerProvider.java, nifi-nar-bundles/nifi-framework-bundle/nifi-framework/nifi-framework-core/src/main/java/org/apache/nifi/controller/state/providers/local/WriteAheadLocalStateProvider.java, nifi-nar-bundles/nifi-framework-bundle/nifi-framework/nifi-framework-core/src/main/java/org/apache/nifi/controller/state/providers/zookeeper/ZooKeeperStateProvider.java, nifi-nar-bundles/nifi-framework-bundle/nifi-framework/nifi-framework-core/src/test/java/org/apache/nifi/controller/state/providers/AbstractTestStateProvider.java, nifi-nar-bundles/nifi-framework-bundle/nifi-framework/nifi-framework-kubernetes-bundle/nifi-framework-kubernetes-state-provider/src/main/java/org/apache/nifi/kubernetes/state/provider/KubernetesConfigMapStateProvider.java, nifi-nar-bundles/nifi-framework-bundle/nifi-framework/nifi-framework-kubernetes-bundle/nifi-framework-kubernetes-state-provider/src/test/java/org/apache/nifi/kubernetes/state/provider/KubernetesConfigMapStateProviderTest.java, nifi-nar-bundles/nifi-framework-bundle/nifi-framework/nifi-resources/pom.xml, nifi-nar-bundles/nifi-framework-bundle/nifi-framework/nifi-resources/src/main/resources/conf/nifi.properties, nifi-nar-bundles/nifi-redis-bundle/nifi-redis-extensions/src/main/java/org/apache/nifi/redis/state/RedisStateProvider.java, nifi-nar-bundles/nifi-redis-bundle/nifi-redis-extensions/src/test/java/org/apache/nifi/redis/state/ITRedisStateProvider.java, nifi-stateless/nifi-stateless-bundle/nifi-stateless-engine/src/main/java/org/apache/nifi/components/state/HashMapStateProvider.java
[NIFI-10976](https://issues.apache.org/jira/browse/NIFI-10976) Adds a Previous Cluster State Provider to support migrating from one Cluster State Provider implementation to another.
The new Previous Cluster Provider property enables conditional transfer of Cluster State from a previous Cluster State Provider to the configured Cluster State Provider. This approaches supports migration scenarios such as moving from ZooKeeper to Kubernetes ConfigMaps or Redis. The implementation is a one-way operation that copies from the Previous Provider to the Current Provider when the Current Provider does not have any state information. After the initial state transfer, the framework ignores the Previous Provider when the Current Provider contains stored informaiton.
Changes include new methods on the …
=> NIFI-10976 Add Previous Cluster State Provider configuration

nifi-nar-bundles/nifi-framework-bundle/nifi-framework/nifi-framework-core/src/main/java/org/apache/nifi/controller/ExtensionBuilder.java
[NIFI-11109](https://issues.apache.org/jira/browse/NIFI-11109)
If nifi registry client comes up in "ghost" mode.  It can never be restored.   This resolves this situation.
To verify fix:
Start nifi
configure registry client (i.e. Global Menu -> Controller Settings -> Registry Clients)
Verify there are no warnings associated with registry client
Stop nifi
move  nifi-flow-registry-client-nar (found in lib directory) to another directory
Start nifi
Verify registry client (at above mentioned location) does not work (i.e. it will have a warning as it is now in ghost mode)
Restore  nifi-flow-registry-client-nar to lib directory
Restart nifi
Verify earlier warning is gone and registry client is restored
Please indicate …
=> NIFI-11109 Allow registry client's class in flow.xml/json to not change when underlying nar for nifi-flow-registry-client-nar is missing

nifi-nar-bundles/nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-ui/src/main/webapp/js/nf/canvas/nf-policy-management.js, nifi-nar-bundles/nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-ui/src/main/webapp/js/nf/canvas/nf-settings.js
[NIFI-11560](https://issues.apache.org/jira/browse/NIFI-11560)
=> [NIFI-11560] call forEach on Map

nifi-nar-bundles/nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-ui/src/main/webapp/js/jquery/propertytable/jquery.propertytable.js
[NIFI-11593](https://issues.apache.org/jira/browse/NIFI-11593)
=> NIFI-11593: Fix hiding logic for properties

.github/workflows/ci-workflow.yml, .github/workflows/system-tests.yml, .mvn/wrapper/maven-wrapper.properties, README.md, mvnw, mvnw.cmd
[NIFI-11689](https://issues.apache.org/jira/browse/NIFI-11689) Adds the [Apache Maven Wrapper](https://maven.apache.org/wrapper/) scripts with Maven 3.9.2 for consistent Maven versioning across build platforms.
Changes include updating GitHub workflows to use Maven Wrapper instead of the available Maven version to ensure the same version of Maven for all platforms.
The Maven Wrapper scripts use the `only-script` option as described in the documentation, which relies on platform commands to download the configured Maven version.
The addition of Maven Wrapper does not interfere with standard Maven installations, but provides the recommended approach for consistent builds.
Please indicate the verification steps …
=> NIFI-11689 Add Maven Wrapper with Maven 3.9.2

nifi-nar-bundles/nifi-framework-bundle/nifi-framework/nifi-resources/src/main/resources/conf/state-management.xml, nifi-nar-bundles/nifi-redis-bundle/nifi-redis-extensions/src/main/java/org/apache/nifi/redis/state/RedisStateProvider.java, nifi-nar-bundles/nifi-redis-bundle/nifi-redis-extensions/src/test/java/org/apache/nifi/redis/state/TestRedisStateProvider.java
[NIFI-11794](https://issues.apache.org/jira/browse/NIFI-11794) - Fix NPE + configure max attempts for Redis State Provider
=> NIFI-11794 - Fix NPE + configure max attempts for Redis State Provider

nifi-registry/pom.xml
[NIFI-11927](https://issues.apache.org/jira/browse/NIFI-11927) Downgrades SSHD from 2.10.0 to 2.9.2 for Registry on the version 1 support branch to correct [compatibility issues](https://github.com/apache/mina-sshd/blob/master/docs/changes/2.10.0.md#potential-compatibility-issues) with SSHD 2.10.0 and JGit 5.13.
The current main branch includes JGit 6, but requires Java 11 or higher, so this change is specific to the support branch for version 1.
=> NIFI-11927 Downgrade SSHD from 2.10.0 to 2.9.2 for Registry

nifi-nar-bundles/nifi-framework-bundle/nifi-framework/nifi-framework-components/src/main/java/org/apache/nifi/logging/repository/StandardLogRepository.java, nifi-nar-bundles/nifi-framework-bundle/nifi-framework/nifi-framework-components/src/test/java/org/apache/nifi/logging/TestStandardLogRepository.java
[NIFI-12025](https://issues.apache.org/jira/browse/NIFI-12025)
=> NIFI-12025: Fixed duplicated bulletin messages

nifi-nar-bundles/nifi-framework-bundle/nifi-framework/nifi-framework-core/src/test/java/org/apache/nifi/controller/state/server/TestZooKeeperStateServer.java
=> NIFI-11903 disable if windows

nifi-docker/dockerhub/DockerRun.sh, nifi-docker/dockerhub/Dockerfile, nifi-docker/dockerhub/README.md, nifi-docker/dockerhub/sh/start.sh, nifi-docker/dockermaven/Dockerfile, nifi-docker/dockermaven/integration-test.sh, nifi-docker/dockermaven/pom.xml, nifi-docker/pom.xml
=> NIFI-12074 updated images to base on Java 21 and added Python3

nifi-mock/src/main/java/org/apache/nifi/util/MockProcessSession.java, nifi-mock/src/test/java/org/apache/nifi/util/TestMockProcessSession.java
[NIFI-12158](https://issues.apache.org/jira/browse/NIFI-12158)
The mock process session wrote the passed in flowfile as the current version when session.write was called. This could negate previous changes to the flowfiles attributes and behaves differently from the regular process sessions.
~~- New dependencies are compatible with the [Apache License 2.0](https://apache.org/licenses/LICENSE-2.0) according to the [License Policy](https://www.apache.org/legal/resolved.html)~~
~~- New dependencies are documented in applicable `LICENSE` and `NOTICE` files~~
~~- Documentation formatting appears as expected in rendered files~~
=> NIFI-12158 MockProcessSession write methods preserves attributes

nifi-mock/src/main/java/org/apache/nifi/util/MockProcessSession.java, nifi-mock/src/test/java/org/apache/nifi/util/TestMockProcessSession.java
[NIFI-12067](https://issues.apache.org/jira/browse/NIFI-12067)
Flowfiles created or within a process session are removed on rollback rather than being put on the inbound queue. This behaviour is now in line with the StandardProcessSession.
~~- [ ] New dependencies are compatible with the [Apache License 2.0](https://apache.org/licenses/LICENSE-2.0) according to the [License Policy](https://www.apache.org/legal/resolved.html)~~
~~- [ ] New dependencies are documented in applicable `LICENSE` and `NOTICE` files~~
~~- [ ] Documentation formatting appears as expected in rendered files~~
=> NIFI-12067 MockProcessSession Removes Created FF on Rollback

nifi-api/src/main/java/org/apache/nifi/flow/VersionedReportingTaskSnapshot.java, nifi-nar-bundles/nifi-framework-bundle/nifi-framework/nifi-framework-components/src/main/java/org/apache/nifi/registry/flow/mapping/NiFiRegistryFlowMapper.java, nifi-nar-bundles/nifi-framework-bundle/nifi-framework/nifi-framework-core/src/main/java/org/apache/nifi/controller/serialization/VersionedReportingTaskSnapshotMapper.java, nifi-nar-bundles/nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-api/src/main/java/org/apache/nifi/web/NiFiServiceFacade.java, nifi-nar-bundles/nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-api/src/main/java/org/apache/nifi/web/StandardNiFiServiceFacade.java, nifi-nar-bundles/nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-api/src/main/java/org/apache/nifi/web/api/FlowResource.java, nifi-toolkit/nifi-toolkit-cli/src/main/java/org/apache/nifi/toolkit/cli/impl/client/nifi/FlowClient.java, nifi-toolkit/nifi-toolkit-cli/src/main/java/org/apache/nifi/toolkit/cli/impl/client/nifi/impl/JerseyFlowClient.java, nifi-toolkit/nifi-toolkit-cli/src/main/java/org/apache/nifi/toolkit/cli/impl/command/nifi/NiFiCommandGroup.java, nifi-toolkit/nifi-toolkit-cli/src/main/java/org/apache/nifi/toolkit/cli/impl/command/nifi/flow/ExportReportingTask.java, nifi-toolkit/nifi-toolkit-cli/src/main/java/org/apache/nifi/toolkit/cli/impl/command/nifi/flow/ExportReportingTasks.java, nifi-toolkit/nifi-toolkit-cli/src/main/java/org/apache/nifi/toolkit/cli/impl/result/nifi/VersionedReportingTaskSnapshotResult.java
- Add CLI commands and optional query param to specify specific reporting task
[NIFI-12186](https://issues.apache.org/jira/browse/NIFI-12186)
- Create some reporting tasks with at least one that also uses a controller service
- Test CLI commands for `nifi export-reporting-tasks` and `nifi export-reporting-task -rtId your-id`
=> NIFI-12186 Add ability to export a versioned reporting task snapshot

nifi-nar-bundles/nifi-standard-bundle/nifi-standard-processors/src/main/java/org/apache/nifi/processors/standard/SplitText.java, nifi-nar-bundles/nifi-standard-bundle/nifi-standard-processors/src/test/java/org/apache/nifi/processors/standard/TestSplitText.java
[NIFI-12238](https://issues.apache.org/jira/browse/NIFI-12238)
=> NIFI-12238 Fix SplitText endline trimming with max fragment size

nifi-nar-bundles/nifi-standard-bundle/nifi-standard-processors/src/main/java/org/apache/nifi/processors/standard/UpdateRecord.java
[NIFI-12244](https://issues.apache.org/jira/browse/NIFI-12244) - UpdateRecord invalid because of migrateProperties
=> NIFI-12244 - UpdateRecord invalid because of migrateProperties

nifi-nar-bundles/nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-ui/src/main/webapp/js/jquery/propertytable/jquery.propertytable.js
NIFI-12247:
- Reverting to the initial value if there is no selected parameter in the combo editor.
=> NIFI-12247: Reverting to the initial value if there is no selected parameter in the combo editor

nifi-nar-bundles/nifi-framework-bundle/nifi-framework/nifi-client-dto/src/main/java/org/apache/nifi/web/api/entity/VersionedReportingTaskImportRequestEntity.java, nifi-nar-bundles/nifi-framework-bundle/nifi-framework/nifi-client-dto/src/main/java/org/apache/nifi/web/api/entity/VersionedReportingTaskImportResponseEntity.java, nifi-nar-bundles/nifi-framework-bundle/nifi-framework/nifi-framework-components/src/main/java/org/apache/nifi/util/BundleUtils.java, nifi-nar-bundles/nifi-framework-bundle/nifi-framework/nifi-framework-core-api/src/main/java/org/apache/nifi/controller/reporting/ReportingTaskProvider.java, nifi-nar-bundles/nifi-framework-bundle/nifi-framework/nifi-framework-core/src/main/java/org/apache/nifi/controller/FlowController.java, nifi-nar-bundles/nifi-framework-bundle/nifi-framework/nifi-framework-core/src/main/java/org/apache/nifi/controller/serialization/FlowSynchronizationUtils.java, nifi-nar-bundles/nifi-framework-bundle/nifi-framework/nifi-framework-core/src/main/java/org/apache/nifi/controller/serialization/StandardVersionedReportingTaskImporter.java, nifi-nar-bundles/nifi-framework-bundle/nifi-framework/nifi-framework-core/src/main/java/org/apache/nifi/controller/serialization/VersionedFlowSynchronizer.java, nifi-nar-bundles/nifi-framework-bundle/nifi-framework/nifi-framework-core/src/main/java/org/apache/nifi/controller/serialization/VersionedReportingTaskImportResult.java, nifi-nar-bundles/nifi-framework-bundle/nifi-framework/nifi-framework-core/src/main/java/org/apache/nifi/controller/serialization/VersionedReportingTaskImporter.java, nifi-nar-bundles/nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-api/src/main/java/org/apache/nifi/registry/flow/FlowRegistryUtils.java, nifi-nar-bundles/nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-api/src/main/java/org/apache/nifi/web/NiFiServiceFacade.java, nifi-nar-bundles/nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-api/src/main/java/org/apache/nifi/web/StandardNiFiServiceFacade.java, nifi-nar-bundles/nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-api/src/main/java/org/apache/nifi/web/api/ControllerResource.java, nifi-nar-bundles/nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-api/src/main/java/org/apache/nifi/web/controller/ControllerFacade.java, nifi-nar-bundles/nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-api/src/main/java/org/apache/nifi/web/dao/impl/StandardReportingTaskDAO.java, nifi-nar-bundles/nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-api/src/test/java/org/apache/nifi/web/StandardNiFiServiceFacadeTest.java, nifi-toolkit/nifi-toolkit-cli/src/main/java/org/apache/nifi/toolkit/cli/impl/client/nifi/ControllerClient.java, nifi-toolkit/nifi-toolkit-cli/src/main/java/org/apache/nifi/toolkit/cli/impl/client/nifi/impl/JerseyControllerClient.java, nifi-toolkit/nifi-toolkit-cli/src/main/java/org/apache/nifi/toolkit/cli/impl/command/nifi/NiFiCommandGroup.java, nifi-toolkit/nifi-toolkit-cli/src/main/java/org/apache/nifi/toolkit/cli/impl/command/nifi/flow/ImportReportingTasks.java, nifi-toolkit/nifi-toolkit-cli/src/main/java/org/apache/nifi/toolkit/cli/impl/result/nifi/ImportReportingTasksResult.java
[NIFI-12198](https://issues.apache.org/jira/browse/NIFI-12198)
Use CLI commands to export reporting tasks and then use that as input to the new command:
```
nifi export-reporting-tasks -o /tmp/reporting-tasks.json
nifi import-reporting-tasks -i /tmp/reporting-tasks.json
```
=> NIFI-12198 Add API and CLI commands to import reporting task snapshots

pom.xml
[NIFI-12269](https://issues.apache.org/jira/browse/NIFI-12269) Resolves Maven build warnings for several plugin versions by setting the plugin version in the plugin management section of the root Maven configuration.
=> NIFI-12269 Resolve Maven Build Warnings for Plugins

nifi-nar-bundles/nifi-framework-bundle/nifi-framework/nifi-framework-nar-utils/src/test/java/org/apache/nifi/nar/NarUnpackerTest.java, nifi-nar-bundles/nifi-framework-bundle/nifi-framework/nifi-nar-utils/src/main/java/org/apache/nifi/nar/NarUnpacker.java
[NIFI-12294](https://issues.apache.org/jira/browse/NIFI-12294) Updates the `NarUnpacker` to standardize loading of entries for NAR files, reducing duplicative naming normalization. Additional changes include updating the associated test class to reduce unnecessary parameter passing and method calls.
=> NIFI-12294 Standardize NAR Entry Loading

minifi/minifi-bootstrap/src/main/java/org/apache/nifi/minifi/bootstrap/configuration/ListenerHandleResult.java, nifi-nar-bundles/nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-api/src/main/java/org/apache/nifi/web/filter/ExceptionFilter.java, nifi-nar-bundles/nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-security/src/main/java/org/apache/nifi/web/security/NiFiAuthenticationFilter.java
[NIFI-12293](https://issues.apache.org/jira/browse/NIFI-12293) Updates exception handling in several web application filters to write standard messages based on the type of exception being processed.
Changes include adjusting applicable filters to write standard messages to the HTTP response stream. Existing log methods continue to include the full message and stack trace details.
=> NIFI-12293 Standardize HTTP error response messages

nifi-registry/nifi-registry-core/nifi-registry-framework/src/main/java/org/apache/nifi/registry/provider/extension/FileSystemBundlePersistenceProvider.java, nifi-registry/nifi-registry-core/nifi-registry-framework/src/main/java/org/apache/nifi/registry/provider/flow/FileSystemFlowPersistenceProvider.java, nifi-registry/nifi-registry-core/nifi-registry-framework/src/test/java/org/apache/nifi/registry/provider/extension/TestFileSystemBundlePersistenceProvider.java, nifi-registry/nifi-registry-core/nifi-registry-framework/src/test/java/org/apache/nifi/registry/provider/flow/TestFileSystemFlowPersistenceProvider.java, nifi-system-tests/nifi-system-test-extensions-bundle/nifi-system-test-extensions/src/main/java/org/apache/nifi/flow/registry/FileSystemFlowRegistryClient.java, nifi-system-tests/nifi-system-test-suite/src/test/java/org/apache/nifi/tests/system/registry/RegistryClientIT.java, nifi-system-tests/nifi-system-test-suite/src/test/java/org/apache/nifi/tests/system/stateless/StatelessBasicsIT.java
[NIFI-12297](https://issues.apache.org/jira/browse/NIFI-12297) Standardizes file path resolution in the NiFi Registry File System Bundle and Flow Persistence Providers, as well as the file-backed Registry client for system tests.
These changes replace string concatenation and related strategies with a standard approach using Java NIO Paths. Using Paths ensures consistent directory separator handling and path normalization.
Additional changes include updating related unit tests to reuse shared identifier values.
=> NIFI-12297 Standardize File Path resolution in Persistence Providers

nifi-nar-bundles/nifi-py4j-bundle/nifi-py4j-bridge/src/main/java/org/apache/nifi/py4j/StandardPythonBridge.java
[NIFI-12310](https://issues.apache.org/jira/browse/NIFI-12310) Updates the `StandardPythonBridge` to validate the request Component Type and Version against available Python Processors when starting new Python processes.
=> NIFI-12310 Validate Python Component Type for Processes

.github/workflows/system-tests.yml, nifi-nar-bundles/nifi-py4j-bundle/nifi-py4j-bridge/src/main/java/org/apache/nifi/py4j/StandardPythonBridge.java
[NIFI-12321](https://issues.apache.org/jira/browse/NIFI-12321) Updates the `StandardPythonBridge.onProcessorRemoved()` method to avoid throwing exceptions when called with a Processor Type and Version that is not registered.
=> NIFI-12321 Avoid Exceptions when removing Python Processors

nifi-nar-bundles/nifi-framework-bundle/nifi-framework/nifi-framework-components/src/main/java/org/apache/nifi/flow/synchronization/StandardVersionedComponentSynchronizer.java, nifi-nar-bundles/nifi-framework-bundle/nifi-framework/nifi-framework-components/src/test/java/org/apache/nifi/flow/synchronization/StandardVersionedComponentSynchronizerTest.java, nifi-nar-bundles/nifi-framework-bundle/nifi-framework/nifi-framework-core-api/src/main/java/org/apache/nifi/controller/AbstractComponentNode.java
[NIFI-12339](https://issues.apache.org/jira/browse/NIFI-12339) Resolves recursive sensitive property encryption issues on the main branch, introduced with changes for handling migration of properties in [NIFI-12301](https://issues.apache.org/jira/browse/NIFI-12301). The problem was the result of passing encrypted property values to migration methods, which subsequently resulted in encrypting a value that was already encrypted.
The resolution decrypts original property values prior to registering created extensions so that subsequent property migration methods have access to the decrypted property values.
The resolution can be verified using the `InvokeHTTP` Processor and creating a sensitive dynamic property named `Authorization`. After creating the property with an arbitrary value, …
=> NIFI-12339 Fix Property Decryption for Migrated Components

nifi-nar-bundles/nifi-standard-bundle/nifi-jolt-transform-json-ui/src/main/webapp/app/transformjson/transformjson.controller.js
[NIFI-12403](https://issues.apache.org/jira/browse/NIFI-12403) Improves the `JoltTransformJSON` Processor custom user interface parameter initialization parsing. The JavaScript controller sets Boolean properties based on initial state parameters, which are passed as strings. Adjusting the processing to use a simple string comparison avoids unnecessary additional parsing.
=> NIFI-12403 Improve Jolt UI Parameter Processing

nifi-nar-bundles/nifi-framework-bundle/nifi-framework/nifi-web/pom.xml
NIFI-12419:
- Applying a copy of the nifi-web-frontend rat config in the parent module when the new ui profile is not activated. Previously, if the new ui profile was not activated, the rat check would fail.
=> NIFI-12419: Applying a copy of the nifi-web-frontend rat config in the parent module when the new ui profile is not activated

nifi-nar-bundles/nifi-jms-bundle/nifi-jms-processors/src/main/java/org/apache/nifi/jms/processors/JMSConsumer.java, nifi-nar-bundles/nifi-jms-bundle/nifi-jms-processors/src/main/java/org/apache/nifi/jms/processors/MessageBodyToBytesConverter.java, nifi-nar-bundles/nifi-jms-bundle/nifi-jms-processors/src/test/java/org/apache/nifi/jms/processors/JMSPublisherConsumerIT.java, pom.xml
[NIFI-12478](https://issues.apache.org/jira/browse/NIFI-12478) Updates supporting utilities for the `ConsumeJMS` Processor to return the Message Type as the body when receiving JMS [ObjectMessage](https://docs.oracle.com/javaee/7/api/javax/jms/ObjectMessage.html) types. This approach avoids various problems with attempting to serialize a wrapped opaque `Object` from a JMS `ObjectMessage`. Java Object serialization is not suitable for inter-operation with subsequent Processors, and the wrapped Object may reference classes that are not available on a given Java Virtual Machine. Rather than writing the message as an error, this approach allows NiFi flows to continue receiving `ObjectMessage` types and handling the associated metadata, while using a standard value of `ObjectMessage` as the …
=> NIFI-12478 Return Message Type as body for JMS Object Messages

nifi-nar-bundles/nifi-hadoop-bundle/nifi-hdfs-processors/src/main/java/org/apache/nifi/processors/hadoop/DeleteHDFS.java
[NIFI-12474](https://issues.apache.org/jira/browse/NIFI-12474)
- Added back `context.yield()` to DeleteHDFS in order to make processor yield when there is no incoming flowfiles in an incoming connection. To alleviate the high task count, I removed `@TriggerWhenEmpty` since the Kerberos login/ticket renewal has been handled properly in the following `getUserGroupInformation()` call in `onTrigger`
=> NIFI-12474: remove TriggerWhenEmpty for DeleteHDFS

nifi-nar-bundles/nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-api/src/main/java/org/apache/nifi/web/api/AccessResource.java, nifi-nar-bundles/nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-security/src/main/java/org/apache/nifi/web/security/configuration/JwtAuthenticationSecurityConfiguration.java, nifi-nar-bundles/nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-security/src/main/java/org/apache/nifi/web/security/configuration/SamlAuthenticationSecurityConfiguration.java, nifi-nar-bundles/nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-security/src/main/java/org/apache/nifi/web/security/jwt/provider/IssuerProvider.java, nifi-nar-bundles/nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-security/src/main/java/org/apache/nifi/web/security/jwt/provider/StandardBearerTokenProvider.java, nifi-nar-bundles/nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-security/src/main/java/org/apache/nifi/web/security/jwt/provider/StandardIssuerProvider.java, nifi-nar-bundles/nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-security/src/main/java/org/apache/nifi/web/security/oidc/client/web/OidcBearerTokenRefreshFilter.java, nifi-nar-bundles/nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-security/src/main/java/org/apache/nifi/web/security/oidc/web/authentication/OidcAuthenticationSuccessHandler.java, nifi-nar-bundles/nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-security/src/main/java/org/apache/nifi/web/security/saml2/web/authentication/Saml2AuthenticationSuccessHandler.java, nifi-nar-bundles/nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-security/src/main/java/org/apache/nifi/web/security/token/LoginAuthenticationToken.java, nifi-nar-bundles/nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-security/src/test/java/org/apache/nifi/web/security/jwt/provider/StandardBearerTokenProviderTest.java, nifi-nar-bundles/nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-security/src/test/java/org/apache/nifi/web/security/jwt/provider/StandardIssuerProviderTest.java, nifi-nar-bundles/nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-security/src/test/java/org/apache/nifi/web/security/oidc/client/web/OidcBearerTokenRefreshFilterTest.java, nifi-nar-bundles/nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-security/src/test/java/org/apache/nifi/web/security/oidc/web/authentication/OidcAuthenticationSuccessHandlerTest.java, nifi-nar-bundles/nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-security/src/test/java/org/apache/nifi/web/security/saml2/web/authentication/Saml2AuthenticationSuccessHandlerTest.java
[NIFI-12418](https://issues.apache.org/jira/browse/NIFI-12418) Corrects OpenID Connect Bearer Token refresh processing, preserving Identity Provider Group information after a token refresh occurs.
Following refactoring in NiFi 1.24.0 to pass Identity Provider Group membership in the `groups` claim of Application Bearer Tokens, the group membership is lost when an automatic Bearer Token refresh occurs. This applies only to OpenID Connect integration, and only impacts users with Identity Provider Group membership that is not supplied through a User Group Provider.
The correction streamlines the `LoginAuthenticationToken` class, removing unnecessary constructors to avoid ambiguity. It also introduces an Issuer Provider to return a standard application Bearer Token Issuer based on the …
=> NIFI-12418 Correct Provider Groups Missing in Refreshed Tokens

nifi-registry/nifi-registry-core/nifi-registry-web-api/src/main/java/org/apache/nifi/registry/web/security/NiFiRegistrySecurityConfig.java, nifi-registry/nifi-registry-core/nifi-registry-web-api/src/main/java/org/apache/nifi/registry/web/security/authentication/csrf/CsrfCookieFilter.java, nifi-registry/nifi-registry-core/nifi-registry-web-api/src/main/java/org/apache/nifi/registry/web/security/authentication/csrf/CsrfCookieName.java, nifi-registry/nifi-registry-core/nifi-registry-web-api/src/main/java/org/apache/nifi/registry/web/security/authentication/csrf/CsrfRequestMatcher.java, nifi-registry/nifi-registry-core/nifi-registry-web-api/src/main/java/org/apache/nifi/registry/web/security/authentication/csrf/StandardCookieCsrfTokenRepository.java, nifi-registry/nifi-registry-core/nifi-registry-web-api/src/main/java/org/apache/nifi/registry/web/security/authentication/csrf/StandardCsrfTokenRequestAttributeHandler.java, nifi-registry/nifi-registry-core/nifi-registry-web-ui/src/main/webapp/services/nf-registry.token.interceptor.js
[NIFI-12487](https://issues.apache.org/jira/browse/NIFI-12487) Adds Cross-Site Request Forgery protection to NiFi Registry using the Spring Security CSRF Filter and several components that follow the same approach currently implemented for NiFi CSRF protection.
NiFi Registry does not use cookies for passing Application Bearer Tokens, and instead relies on the HTTP Authorization header to be populated using a custom JavaScript request interceptor. This approach mitigates a number of potential threats. Introducing the CSRF Filter provides an additional layer of protection. Following a strategy similar to NiFi, the CSRF Request Matcher is based on the default Spring Security HTTP Method matching plus the presence of the Request Token cookie. This enables programmatic clients to continue …
=> NIFI-12487 Add CSRF Protection to Registry

minifi/minifi-assembly/README.md, minifi/minifi-c2/minifi-c2-assembly/README.md, minifi/minifi-docs/src/main/markdown/System_Admin_Guide.md, minifi/minifi-nar-bundles/minifi-framework-bundle/minifi-framework/minifi-resources/src/main/resources/bin/minifi-env.bat, minifi/minifi-nar-bundles/minifi-framework-bundle/minifi-framework/minifi-resources/src/main/resources/bin/minifi-env.sh, nifi-assembly/README.md, nifi-commons/nifi-metrics/src/main/java/org/apache/nifi/metrics/jvm/JvmMetrics.java, nifi-docs/src/main/asciidoc/administration-guide.adoc, nifi-docs/src/main/asciidoc/expression-language-guide.adoc, nifi-docs/src/main/asciidoc/nifi-in-depth.adoc, nifi-nar-bundles/nifi-framework-bundle/nifi-framework/nifi-resources/src/main/resources/bin/nifi-env.bat, nifi-nar-bundles/nifi-framework-bundle/nifi-framework/nifi-resources/src/main/resources/bin/nifi-env.cmd, nifi-nar-bundles/nifi-framework-bundle/nifi-framework/nifi-resources/src/main/resources/bin/nifi-env.sh, nifi-nar-bundles/nifi-framework-bundle/nifi-framework/nifi-resources/src/main/resources/conf/bootstrap.conf, nifi-nar-bundles/nifi-mongodb-bundle/nifi-mongodb-processors/src/main/java/org/apache/nifi/processors/mongodb/AbstractMongoProcessor.java, nifi-registry/nifi-registry-assembly/README.md, nifi-registry/nifi-registry-core/nifi-registry-docs/src/main/asciidoc/administration-guide.adoc, nifi-registry/nifi-registry-core/nifi-registry-resources/src/main/resources/bin/nifi-registry-env.sh, nifi-registry/nifi-registry-core/nifi-registry-web-api/src/test/resources/keys/README.md, nifi-stateless/nifi-stateless-resources/src/main/resources/bin/nifi-stateless-env.sh
[NIFI-12493](https://issues.apache.org/jira/browse/NIFI-12493) Updates documentation references to indicate that Java 21 is the minimum required version. Additional changes include removing the need to download Apache Maven and instead referencing the Apache Maven Wrapper command.
=> NIFI-12493 Update Documentation References to Java 21

nifi-nar-bundles/nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-frontend/src/main/nifi/src/app/pages/counters/feature/counters.component.ts, nifi-nar-bundles/nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-frontend/src/main/nifi/src/app/pages/counters/state/counter-listing/counter-listing.actions.ts, nifi-nar-bundles/nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-frontend/src/main/nifi/src/app/pages/counters/state/counter-listing/counter-listing.reducer.ts, nifi-nar-bundles/nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-frontend/src/main/nifi/src/app/pages/flow-designer/state/controller-services/controller-services.effects.ts, nifi-nar-bundles/nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-frontend/src/main/nifi/src/app/pages/flow-designer/state/flow/flow.effects.ts, nifi-nar-bundles/nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-frontend/src/main/nifi/src/app/pages/parameter-contexts/ui/parameter-context-listing/parameter-references/parameter-references.component.ts, nifi-nar-bundles/nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-frontend/src/main/nifi/src/app/pages/parameter-contexts/ui/parameter-context-listing/parameter-table/parameter-table.component.ts, nifi-nar-bundles/nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-frontend/src/main/nifi/src/app/pages/settings/state/management-controller-services/management-controller-services.effects.ts, nifi-nar-bundles/nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-frontend/src/main/nifi/src/app/pages/summary/feature/summary.component.ts, nifi-nar-bundles/nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-frontend/src/main/nifi/src/app/pages/summary/state/summary-listing/summary-listing.actions.ts, nifi-nar-bundles/nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-frontend/src/main/nifi/src/app/pages/summary/state/summary-listing/summary-listing.reducer.ts, nifi-nar-bundles/nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-frontend/src/main/nifi/src/app/ui/common/controller-service/controller-service-references/controller-service-references.component.html, nifi-nar-bundles/nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-frontend/src/main/nifi/src/app/ui/common/controller-service/controller-service-references/controller-service-references.component.ts, nifi-nar-bundles/nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-frontend/src/main/nifi/src/app/ui/common/controller-service/edit-controller-service/edit-controller-service.component.html, nifi-nar-bundles/nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-frontend/src/main/nifi/src/app/ui/common/controller-service/edit-controller-service/edit-controller-service.component.ts
[NIFI-12519](https://issues.apache.org/jira/browse/NIFI-12519)
* deselect parameter when it is deleted so it no longer shows its referencing components.
* also, fixed a minor bug preventing goto controller service linking from parameter reference.
=> [NIFI-12519] - deselect parameter when it is deleted.

nifi-nar-bundles/nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-frontend/src/main/nifi/src/app/pages/parameter-contexts/ui/parameter-context-listing/parameter-table/parameter-table.component.scss, nifi-nar-bundles/nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-frontend/src/main/nifi/src/app/ui/common/property-table/editors/combo-editor/combo-editor.component.html, nifi-nar-bundles/nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-frontend/src/main/nifi/src/app/ui/common/property-table/editors/combo-editor/combo-editor.component.scss, nifi-nar-bundles/nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-frontend/src/main/nifi/src/app/ui/common/property-table/editors/combo-editor/combo-editor.component.spec.ts, nifi-nar-bundles/nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-frontend/src/main/nifi/src/app/ui/common/property-table/editors/combo-editor/combo-editor.component.ts, nifi-nar-bundles/nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-frontend/src/main/nifi/src/app/ui/common/property-table/editors/nf-editor/nf-editor.component.html, nifi-nar-bundles/nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-frontend/src/main/nifi/src/app/ui/common/property-table/editors/nf-editor/nf-editor.component.ts, nifi-nar-bundles/nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-frontend/src/main/nifi/src/app/ui/common/property-table/property-table.component.html, nifi-nar-bundles/nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-frontend/src/main/nifi/src/app/ui/common/property-table/property-table.component.scss, nifi-nar-bundles/nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-frontend/src/main/nifi/src/app/ui/common/property-table/property-table.component.ts
- Set the width of the Property editor. This ensures the width looks correct and the overflow scroll policy works as expected.
- Fixed table layout issues where width: 100% from listing table wasn't correct.
=> NIFI-12547: Set the width of the Property editor.

nifi-nar-bundles/nifi-provenance-repository-bundle/nifi-persistent-provenance-repository/src/main/java/org/apache/nifi/provenance/EncryptedWriteAheadProvenanceRepository.java, nifi-nar-bundles/nifi-provenance-repository-bundle/nifi-persistent-provenance-repository/src/main/java/org/apache/nifi/provenance/WriteAheadProvenanceRepository.java
Fixed race condition between "Timer-Driven" threads when running SiteToSiteProvenanceReportingTask.onTrigger and "Compress Provenance Log" threads running EventFileCompressos.run that can cause the SiteToSiteProvenanceReportingTask.onTrigger to pair an already compressed .prov.gz file with a .toc file that corresponds to the uncompressed .prov file.
[NIFI-9464](https://issues.apache.org/jira/browse/NIFI-9464)
=> NIFI-9464 Provenance Events files corrupted

nifi-nar-bundles/nifi-framework-bundle/nifi-framework/nifi-framework-kubernetes-bundle/nifi-framework-kubernetes-leader-election/src/main/java/org/apache/nifi/kubernetes/leader/election/KubernetesLeaderElectionManager.java, nifi-nar-bundles/nifi-framework-bundle/nifi-framework/nifi-framework-kubernetes-bundle/nifi-framework-kubernetes-leader-election/src/test/java/org/apache/nifi/kubernetes/leader/election/KubernetesLeaderElectionManagerTest.java, nifi-nar-bundles/nifi-framework-bundle/nifi-framework/nifi-framework-kubernetes-bundle/nifi-framework-kubernetes-state-provider/pom.xml, nifi-nar-bundles/nifi-framework-bundle/nifi-framework/nifi-framework-kubernetes-bundle/nifi-framework-kubernetes-state-provider/src/main/java/org/apache/nifi/kubernetes/state/provider/KubernetesConfigMapStateProvider.java, nifi-nar-bundles/nifi-framework-bundle/nifi-framework/nifi-framework-kubernetes-bundle/nifi-framework-kubernetes-state-provider/src/test/java/org/apache/nifi/kubernetes/state/provider/KubernetesConfigMapStateProviderTest.java
[NIFI-12634](https://issues.apache.org/jira/browse/NIFI-12634) Updates `KubernetesConfigMapStateProvider` and `KubernetesLeaderElectionManager` to ignore blank prefix values as provided in default configuration files.
=> NIFI-12634 Ignore Blank Prefix Values in Kubernetes Components

nifi-registry/nifi-registry-core/nifi-registry-framework/src/main/java/org/apache/nifi/registry/db/DataSourceFactory.java, nifi-registry/nifi-registry-core/nifi-registry-framework/src/test/java/org/apache/nifi/registry/db/DatabaseTestApplication.java, nifi-registry/nifi-registry-core/nifi-registry-web-api/src/test/java/org/apache/nifi/registry/NiFiRegistryTestApiApplication.java, nifi-registry/nifi-registry-core/nifi-registry-web-api/src/test/java/org/apache/nifi/registry/SecureLdapTestApiApplication.java
[NIFI-12666](https://issues.apache.org/jira/browse/NIFI-12666) Corrects the NiFi Registry Data Source Configuration, which inadvertently defaulted to H2 memory-backed storage following an upgrade to Spring Framework 6.1. This change is present on the main branch, but does not impact any released versions.
The changes remove the `ConditionalOnProperty` annotation, which did not function as intended based on NiFi Registry property loading. The new annotation supports overriding the Data Source in test classes, but otherwise uses standard NiFi Registry properties.
=> NIFI-12666 Correct Registry Data Source Configuration

nifi-nar-bundles/nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-frontend/src/main/nifi/src/app/app.module.ts, nifi-nar-bundles/nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-frontend/src/main/nifi/src/app/pages/flow-designer/service/canvas-context-menu.service.ts, nifi-nar-bundles/nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-frontend/src/main/nifi/src/app/pages/flow-designer/service/canvas-utils.service.ts, nifi-nar-bundles/nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-frontend/src/main/nifi/src/app/pages/flow-designer/ui/controller-service/controller-services.component.html, nifi-nar-bundles/nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-frontend/src/main/nifi/src/app/pages/flow-designer/ui/controller-service/controller-services.component.ts, nifi-nar-bundles/nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-frontend/src/main/nifi/src/app/pages/settings/ui/flow-analysis-rules/flow-analysis-rule-table/flow-analysis-rule-table.component.html, nifi-nar-bundles/nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-frontend/src/main/nifi/src/app/pages/settings/ui/flow-analysis-rules/flow-analysis-rule-table/flow-analysis-rule-table.component.ts, nifi-nar-bundles/nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-frontend/src/main/nifi/src/app/pages/settings/ui/flow-analysis-rules/flow-analysis-rules.component.html, nifi-nar-bundles/nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-frontend/src/main/nifi/src/app/pages/settings/ui/flow-analysis-rules/flow-analysis-rules.component.ts, nifi-nar-bundles/nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-frontend/src/main/nifi/src/app/pages/settings/ui/management-controller-services/management-controller-services.component.html, nifi-nar-bundles/nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-frontend/src/main/nifi/src/app/pages/settings/ui/management-controller-services/management-controller-services.component.ts, nifi-nar-bundles/nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-frontend/src/main/nifi/src/app/pages/settings/ui/reporting-tasks/reporting-task-table/reporting-task-table.component.html, nifi-nar-bundles/nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-frontend/src/main/nifi/src/app/pages/settings/ui/reporting-tasks/reporting-task-table/reporting-task-table.component.ts, nifi-nar-bundles/nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-frontend/src/main/nifi/src/app/pages/settings/ui/reporting-tasks/reporting-tasks.component.html, nifi-nar-bundles/nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-frontend/src/main/nifi/src/app/pages/settings/ui/reporting-tasks/reporting-tasks.component.ts, nifi-nar-bundles/nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-frontend/src/main/nifi/src/app/service/component-state.service.ts, nifi-nar-bundles/nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-frontend/src/main/nifi/src/app/state/component-state/component-state.actions.ts, nifi-nar-bundles/nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-frontend/src/main/nifi/src/app/state/component-state/component-state.effects.ts, nifi-nar-bundles/nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-frontend/src/main/nifi/src/app/state/component-state/component-state.reducer.ts, nifi-nar-bundles/nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-frontend/src/main/nifi/src/app/state/component-state/component-state.selectors.ts, nifi-nar-bundles/nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-frontend/src/main/nifi/src/app/state/component-state/index.ts, nifi-nar-bundles/nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-frontend/src/main/nifi/src/app/state/index.ts, nifi-nar-bundles/nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-frontend/src/main/nifi/src/app/ui/common/component-state/component-state.component.html, nifi-nar-bundles/nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-frontend/src/main/nifi/src/app/ui/common/component-state/component-state.component.scss, nifi-nar-bundles/nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-frontend/src/main/nifi/src/app/ui/common/component-state/component-state.component.spec.ts, nifi-nar-bundles/nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-frontend/src/main/nifi/src/app/ui/common/component-state/component-state.component.ts, nifi-nar-bundles/nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-frontend/src/main/nifi/src/app/ui/common/controller-service/controller-service-table/controller-service-table.component.html, nifi-nar-bundles/nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-frontend/src/main/nifi/src/app/ui/common/controller-service/controller-service-table/controller-service-table.component.ts, nifi-nar-bundles/nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-frontend/src/main/nifi/src/app/ui/common/extension-creation/extension-creation.component.html
NIFI-12611:
- Component State.
To verify this capability run a Stateful processor (like ListFile) and access the View State menu item. Since not all components are stateful, there is no new route for the component state dialog. Rather, the dialog is simply shown over the existing view.
=> NIFI-12611: Component State

nifi-nar-bundles/nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-frontend/src/main/nifi/src/app/ui/common/property-table/editors/nf-editor/nf-editor.component.ts, nifi-nar-bundles/nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-frontend/src/main/nifi/src/app/ui/common/property-table/property-table.component.ts
NIFI-12743: 
- Updating property editing so that Shift-Enter inserts a new line and Enter commits the edit.
- Fixing bug that prevented deleting a Property and then re-adding a new Property with the same name.
=> NIFI-12743: Property Table Fixes

nifi-commons/nifi-security-utils/pom.xml, nifi-commons/nifi-security-utils/src/main/java/org/apache/nifi/security/util/KeyStoreUtils.java, nifi-commons/nifi-security-utils/src/main/java/org/apache/nifi/security/util/StandardTlsConfiguration.java, nifi-commons/nifi-security-utils/src/main/java/org/apache/nifi/security/util/crypto/HashAlgorithm.java, nifi-commons/nifi-security-utils/src/main/java/org/apache/nifi/security/util/crypto/HashService.java, nifi-commons/nifi-security-utils/src/test/java/org/apache/nifi/security/util/KeyStoreUtilsTest.java, nifi-commons/nifi-security-utils/src/test/java/org/apache/nifi/security/util/SslSocketFactoryTest.java, nifi-commons/nifi-security-utils/src/test/java/org/apache/nifi/security/util/crypto/HashServiceTest.java, nifi-nar-bundles/nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-security/pom.xml, nifi-system-tests/nifi-system-test-suite/pom.xml
[NIFI-12764](https://issues.apache.org/jira/browse/NIFI-12764) Removes `commons-codec` and `commons-lang3` dependencies from `nifi-security-utils` to reduce the transitive dependencies inherited in other referencing modules.
Changes include replacing Commons Codec Hex with Java [HexFormat](https://docs.oracle.com/en/java/javase/17/docs/api/java.base/java/util/HexFormat.html) and replacing `StringUtils` references with simple checks.
Commons Codec is a runtime dependency of OpenSAML, so it is now declared explicitly in `nifi-web-security`, and Commons Lang3 is a runtime dependency of the `nifi-system-test-suite` for dynamic class loading tests. …
=> NIFI-12764 Removed Commons Codec and Lang3 from security-utils

nifi-nar-bundles/nifi-standard-bundle/nifi-standard-processors/src/test/java/org/apache/nifi/processors/standard/TestListFile.java
[NIFI-12768](https://issues.apache.org/jira/browse/NIFI-12768) Removes an unstable filename assertion from the `TestListFile.testFilterAge()` method.
The test method uses calculated timestamps to update multiple files and then runs the `ListFile` Processor to return a filtered number of files. The `testFilterAge()` method fails intermittently when checking for which file matched, but the previous assertion succeeds, confirming that only one file matched the filter.
This change is intentionally narrow, so additional changes may be necessary to revisit the larger file modification time approach if this continues to be a problem.
=> NIFI-12768 Remove unstable filename assertion in TestListFile

nifi-nar-bundles/nifi-py4j-bundle/nifi-python-framework/src/main/python/framework/Controller.py
Python 3.0 incorrectly raises an exception in multi-threaded applications (https://bugs.python.org/issue42647).
This applies a fix for importing ProcessPoolExecutor that is similar to a previous fix for importing ThreadPoolExecutor.
[NIFI-12739](https://issues.apache.org/jira/browse/NIFI-12739)
NiFi was recompiled and manually deployed and tested to verify that the `RuntimeError: can't register atexit after shutdown` is no longer thrown when importing `ProcessPoolExecutor`
=> NIFI-12739 - Import ProcessPoolExecutor to fix bug in python 3.9+

nifi-nar-bundles/nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-frontend/src/main/nifi/src/app/pages/flow-designer/service/canvas-context-menu.service.ts, nifi-nar-bundles/nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-frontend/src/main/nifi/src/app/pages/flow-designer/state/flow/flow.actions.ts, nifi-nar-bundles/nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-frontend/src/main/nifi/src/app/pages/flow-designer/state/flow/flow.effects.ts, nifi-nar-bundles/nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-frontend/src/main/nifi/src/app/pages/flow-designer/state/flow/flow.reducer.ts, nifi-nar-bundles/nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-frontend/src/main/nifi/src/app/pages/flow-designer/state/flow/flow.selectors.ts, nifi-nar-bundles/nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-frontend/src/main/nifi/src/app/pages/flow-designer/state/flow/index.ts
=> [NIFI-12761] refresh RPG

nifi-docs/src/main/asciidoc/user-guide.adoc
As outlined in [NIFI-12498](https://issues.apache.org/jira/browse/NIFI-12498),
the documentation falsely claims that `OldestFlowFileFirstPrioritizer` is used whenever no `FlowFilePrioritizer` is specified explicitly.
The PR adjusts the documentation to remove the long standing claim.
- [] Build completed using `mvn clean install -P contrib-check`
- [] JDK 21
=> NIFI-12498 Adjust docs on default behaviour of prioritizers

nifi-commons/nifi-properties/src/main/java/org/apache/nifi/util/NiFiProperties.java, nifi-docs/src/main/asciidoc/administration-guide.adoc, nifi-nar-bundles/nifi-framework-bundle/nifi-framework/nifi-framework-core/src/main/java/org/apache/nifi/controller/FlowController.java, nifi-nar-bundles/nifi-framework-bundle/nifi-framework/nifi-resources/pom.xml, nifi-nar-bundles/nifi-framework-bundle/nifi-framework/nifi-resources/src/main/resources/conf/logback.xml, nifi-nar-bundles/nifi-framework-bundle/nifi-framework/nifi-resources/src/main/resources/conf/nifi.properties, nifi-nar-bundles/nifi-py4j-bundle/nifi-py4j-bridge/pom.xml, nifi-nar-bundles/nifi-py4j-bundle/nifi-py4j-bridge/src/main/java/org/apache/nifi/py4j/PythonProcess.java, nifi-nar-bundles/nifi-py4j-bundle/nifi-py4j-bridge/src/main/java/org/apache/nifi/py4j/PythonProcessLogReader.java, nifi-nar-bundles/nifi-py4j-bundle/nifi-py4j-bridge/src/main/java/org/apache/nifi/py4j/StandardPythonBridge.java, nifi-nar-bundles/nifi-py4j-bundle/nifi-py4j-bridge/src/main/java/org/apache/nifi/py4j/logback/LevelChangeListener.java, nifi-nar-bundles/nifi-py4j-bundle/nifi-py4j-bridge/src/main/java/org/apache/nifi/py4j/logging/LogLevelChangeHandler.java, nifi-nar-bundles/nifi-py4j-bundle/nifi-py4j-bridge/src/main/java/org/apache/nifi/py4j/logging/LogLevelChangeListener.java, nifi-nar-bundles/nifi-py4j-bundle/nifi-py4j-bridge/src/main/java/org/apache/nifi/py4j/logging/PythonLogLevel.java, nifi-nar-bundles/nifi-py4j-bundle/nifi-py4j-bridge/src/main/java/org/apache/nifi/py4j/logging/StandardLogLevelChangeHandler.java, nifi-nar-bundles/nifi-py4j-bundle/nifi-py4j-bridge/src/test/java/org/apache/nifi/py4j/PythonProcessLogReaderTest.java, nifi-nar-bundles/nifi-py4j-bundle/nifi-py4j-bridge/src/test/java/org/apache/nifi/py4j/logback/LevelChangeListenerTest.java, nifi-nar-bundles/nifi-py4j-bundle/nifi-py4j-integration-tests/src/test/java/org.apache.nifi.py4j/PythonControllerInteractionIT.java, nifi-nar-bundles/nifi-py4j-bundle/nifi-python-framework-api/src/main/java/org/apache/nifi/python/PythonController.java, nifi-nar-bundles/nifi-py4j-bundle/nifi-python-framework-api/src/main/java/org/apache/nifi/python/PythonProcessConfig.java, nifi-nar-bundles/nifi-py4j-bundle/nifi-python-framework/src/main/python/framework/Controller.py, nifi-system-tests/nifi-system-test-suite/src/test/resources/conf/clustered/node1/nifi.properties, nifi-system-tests/nifi-system-test-suite/src/test/resources/conf/clustered/node2/nifi.properties, nifi-system-tests/nifi-system-test-suite/src/test/resources/conf/default/nifi.properties, nifi-system-tests/nifi-system-test-suite/src/test/resources/conf/pythonic/logback.xml, nifi-system-tests/nifi-system-test-suite/src/test/resources/conf/pythonic/nifi.properties
[NIFI-11443](https://issues.apache.org/jira/browse/NIFI-11443) Updates Python Process log handling to route messages to SLF4J so that logging levels and appenders can be managed using Logback.
These changes remove the need for separate Python log settings in `nifi.properties` and support translating Python log levels and logger names to Logback.
The implementation changes the Python logging format to use the Python [level numbers](https://docs.python.org/3/library/logging.html#levels) for optimized parsing. The implementation changes Python logging to write messages to the standard output stream, and the `PythonProcess` builder creates a Java Virtual Thread to read lines from the `BufferedReader` containing process output stream messages.
These changes eliminate the dedicated …
=> NIFI-11443 Route Python Framework Logging to SLF4J

nifi-nar-bundles/nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-frontend/src/main/nifi/src/app/pages/flow-designer/ui/canvas/items/processor/edit-processor/relationship-settings/relationship-settings.component.html
Updated all the checkboxes to use color="primary" to keep them consistent.
As you can see in the below image, the checkboxes don't match. This PR changes all checkboxes to use the primary theme color.
[NIFI-12865](https://issues.apache.org/jira/browse/NIFI-12865)
=> NIFI-12865 BUG - Checkboxes are inconsistently styled with primary or accent

nifi-nar-bundles/nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-frontend/src/main/nifi/src/styles.scss
Set an explicit background color for the skeleton-loader element so there is sufficient contrast to show the animation in both light and dark themes.
[NIFI-12720](https://issues.apache.org/jira/browse/NIFI-12720) BUG - Dark mode skeleton loader styles
=> NIFI-12720 BUG - Dark mode skeleton loader styles

nifi-nar-bundles/nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-frontend/pom.xml
NIFI-12902:
- Updating packaging to account for new build output.
=> NIFI-12902: Updating packaging to account for new build output

nifi-nar-bundles/nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-ui/src/main/webapp/WEB-INF/partials/connection-details.jsp, nifi-nar-bundles/nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-ui/src/main/webapp/js/nf/nf-connection-details.js
[NIFI-12972](https://issues.apache.org/jira/browse/NIFI-12972) - Only show selected relationships in read-only connection details
=> NIFI-12972 - Only show selected relationships in read-only connection details

nifi-nar-bundles/nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-frontend/src/main/nifi/src/app/pages/flow-designer/ui/canvas/canvas.component.html, nifi-nar-bundles/nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-frontend/src/main/nifi/src/app/pages/flow-designer/ui/canvas/header/flow-status/flow-status.component.html, nifi-nar-bundles/nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-frontend/src/main/nifi/src/app/pages/flow-designer/ui/canvas/header/header.component.scss, nifi-nar-bundles/nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-frontend/src/main/nifi/src/app/pages/flow-designer/ui/canvas/header/new-canvas-item/new-canvas-item.component.scss, nifi-nar-bundles/nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-frontend/src/main/nifi/src/app/pages/flow-designer/ui/canvas/header/search/search.component.html, nifi-nar-bundles/nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-frontend/src/main/nifi/src/app/pages/flow-designer/ui/canvas/header/search/search.component.ts, nifi-nar-bundles/nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-frontend/src/main/nifi/src/app/pages/flow-designer/ui/canvas/items/flow/change-version-progress-dialog/change-version-progress-dialog.html, nifi-nar-bundles/nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-frontend/src/main/nifi/src/app/pages/parameter-contexts/ui/parameter-context-listing/edit-parameter-context/edit-parameter-context.component.html, nifi-nar-bundles/nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-frontend/src/main/nifi/src/app/pages/queue/ui/queue-listing/flowfile-table/flowfile-table.component.html, nifi-nar-bundles/nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-frontend/src/main/nifi/src/app/pages/settings/ui/parameter-providers/fetch-parameter-provider-parameters/parameter-groups-table/parameter-groups-table.component.html, nifi-nar-bundles/nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-frontend/src/main/nifi/src/app/pages/settings/ui/parameter-providers/parameter-providers-table/parameter-providers-table.component.html, nifi-nar-bundles/nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-frontend/src/main/nifi/src/app/state/status-history/status-history.effects.ts, nifi-nar-bundles/nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-frontend/src/main/nifi/src/app/ui/common/component-state/component-state.component.html, nifi-nar-bundles/nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-frontend/src/main/nifi/src/app/ui/common/controller-service/controller-service-references/controller-service-references.component.html, nifi-nar-bundles/nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-frontend/src/main/nifi/src/app/ui/common/controller-service/disable-controller-service/disable-controller-service.component.html, nifi-nar-bundles/nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-frontend/src/main/nifi/src/app/ui/common/controller-service/enable-controller-service/enable-controller-service.component.html, nifi-nar-bundles/nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-frontend/src/main/nifi/src/app/ui/common/extension-creation/extension-creation.component.html, nifi-nar-bundles/nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-frontend/src/main/nifi/src/app/ui/common/extension-creation/extension-creation.component.ts, nifi-nar-bundles/nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-frontend/src/main/nifi/src/app/ui/common/navigation/navigation.component.html, nifi-nar-bundles/nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-frontend/src/main/nifi/src/app/ui/common/parameter-references/parameter-references.component.html, nifi-nar-bundles/nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-frontend/src/main/nifi/src/app/ui/common/status-history/status-history-chart/status-history-chart.component.html, nifi-nar-bundles/nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-frontend/src/main/nifi/src/app/ui/common/status-history/status-history.component.scss
* [NIFI-13000](https://issues.apache.org/jira/browse/NIFI-13000) - Improvement - Prevent text selection in header, flow status, canvas, extension creation dialog table.
* [NIFI-13024](https://issues.apache.org/jira/browse/NIFI-13024) - Improvement - Support Enter to create selected extension type
* [NIFI-13023](https://issues.apache.org/jira/browse/NIFI-13023) - Fix - Right click on canvas while search results open shows browser right-click menu
* [NIFI-13018](https://issues.apache.org/jira/browse/NIFI-13018) - Fix - Refreshing Node Status History when open for the cluster, makes the incorrect backend call
* [NIFI-13021](https://issues.apache.org/jira/browse/NIFI-13021) - Fix - Status History dialog changes size when switching selected metric
=> General improvements

nifi-nar-bundles/nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-frontend/src/main/nifi/src/app/pages/flow-designer/state/controller-services/controller-services.effects.ts, nifi-nar-bundles/nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-frontend/src/main/nifi/src/app/pages/flow-designer/state/flow/flow.effects.ts, nifi-nar-bundles/nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-frontend/src/main/nifi/src/app/pages/flow-designer/state/flow/index.ts, nifi-nar-bundles/nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-frontend/src/main/nifi/src/app/pages/flow-designer/ui/canvas/items/processor/edit-processor/edit-processor.component.html, nifi-nar-bundles/nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-frontend/src/main/nifi/src/app/pages/settings/state/flow-analysis-rules/flow-analysis-rules.effects.ts, nifi-nar-bundles/nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-frontend/src/main/nifi/src/app/pages/settings/state/flow-analysis-rules/index.ts, nifi-nar-bundles/nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-frontend/src/main/nifi/src/app/pages/settings/state/management-controller-services/management-controller-services.effects.ts, nifi-nar-bundles/nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-frontend/src/main/nifi/src/app/pages/settings/state/parameter-providers/index.ts, nifi-nar-bundles/nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-frontend/src/main/nifi/src/app/pages/settings/state/parameter-providers/parameter-providers.effects.ts, nifi-nar-bundles/nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-frontend/src/main/nifi/src/app/pages/settings/state/reporting-tasks/index.ts, nifi-nar-bundles/nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-frontend/src/main/nifi/src/app/pages/settings/state/reporting-tasks/reporting-tasks.effects.ts, nifi-nar-bundles/nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-frontend/src/main/nifi/src/app/pages/settings/ui/flow-analysis-rules/edit-flow-analysis-rule/edit-flow-analysis-rule.component.html, nifi-nar-bundles/nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-frontend/src/main/nifi/src/app/pages/settings/ui/parameter-providers/edit-parameter-provider/edit-parameter-provider.component.html, nifi-nar-bundles/nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-frontend/src/main/nifi/src/app/pages/settings/ui/reporting-tasks/edit-reporting-task/edit-reporting-task.component.html, nifi-nar-bundles/nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-frontend/src/main/nifi/src/app/service/property-table-helper.service.ts, nifi-nar-bundles/nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-frontend/src/main/nifi/src/app/state/shared/index.ts, nifi-nar-bundles/nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-frontend/src/main/nifi/src/app/ui/common/controller-service/edit-controller-service/edit-controller-service.component.html, nifi-nar-bundles/nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-frontend/src/main/nifi/src/app/ui/common/property-table/property-table.component.html, nifi-nar-bundles/nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-frontend/src/main/nifi/src/app/ui/common/property-table/property-table.component.ts, nifi-nar-bundles/nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-frontend/src/main/nifi/src/app/ui/common/tooltips/property-tip/property-tip.component.html
NIFI-13047:
- Adding property history to the property tooltip in the Edit dialogs for Processors, Controller Services, Reporting Tasks, Parameter Providers, and Flow Analysis Rules.
=> NIFI-13047: Adding property history to the property tooltip

nifi-nar-bundles/nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-frontend/src/main/nifi/src/app/pages/flow-designer/service/canvas-context-menu.service.ts, nifi-nar-bundles/nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-frontend/src/main/nifi/src/app/pages/flow-designer/service/canvas-utils.service.ts, nifi-nar-bundles/nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-frontend/src/main/nifi/src/app/pages/flow-designer/state/flow/flow.actions.ts, nifi-nar-bundles/nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-frontend/src/main/nifi/src/app/pages/flow-designer/state/flow/flow.effects.ts, nifi-nar-bundles/nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-frontend/src/main/nifi/src/app/pages/flow-designer/state/flow/index.ts, nifi-nar-bundles/nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-frontend/src/main/nifi/src/app/pages/parameter-contexts/ui/parameter-context-listing/parameter-table/parameter-table.component.ts
NIFI-13083:
- Fixing import preventing the dialog from warning the user that they must apply changes before deleting/adding the same parameter with different sensitivities.
- Allowing the sensitivity to change when deleting/adding the same parameter as long as it hasn't been saved yet.
- Adding the Parameters context menu item for Process Groups.
=> NIFI-13083: Parameter sensitivity issue when deleting and re-adding

nifi-nar-bundles/nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-frontend/src/main/nifi/src/app/pages/flow-designer/service/canvas-context-menu.service.ts, nifi-nar-bundles/nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-frontend/src/main/nifi/src/app/pages/flow-designer/service/canvas-utils.service.ts, nifi-nar-bundles/nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-frontend/src/main/nifi/src/app/pages/flow-designer/service/flow.service.ts, nifi-nar-bundles/nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-frontend/src/main/nifi/src/app/pages/flow-designer/state/flow/flow.actions.ts, nifi-nar-bundles/nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-frontend/src/main/nifi/src/app/pages/flow-designer/state/flow/flow.effects.ts, nifi-nar-bundles/nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-frontend/src/main/nifi/src/app/pages/flow-designer/state/flow/flow.reducer.ts, nifi-nar-bundles/nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-frontend/src/main/nifi/src/app/pages/flow-designer/state/flow/index.ts, nifi-nar-bundles/nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-frontend/src/main/nifi/src/app/pages/flow-designer/ui/canvas/graph-controls/operation-control/operation-control.component.ts
NIFI-13078:
- Adding support to Enable and Disable through the context menu and operation control.
=> NIFI-13078: Adding support to Enable and Disable through the context menu and operation control

nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-frontend/src/main/nifi/README.md, nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-frontend/src/main/nifi/src/app/pages/flow-designer/state/flow/flow.effects.ts, nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-frontend/src/main/nifi/src/app/pages/flow-designer/state/flow/flow.reducer.ts, nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-frontend/src/main/nifi/src/app/pages/flow-designer/state/flow/index.ts, nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-frontend/src/main/nifi/src/app/state/cluster-summary/cluster-summary.actions.ts, nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-frontend/src/main/nifi/src/app/state/cluster-summary/cluster-summary.reducer.ts, nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-frontend/src/main/nifi/src/app/state/cluster-summary/cluster-summary.selectors.ts, nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-frontend/src/main/nifi/src/app/state/cluster-summary/index.ts
NIFI-13155: 
- Handling newer revisions in flow reducer to ensure that the appropriate version of the component is saved in case responses are received out of order.
This addresses an issue that occurs for slow connections and there are very large flows. Under these circumstances, a user would issue a request to add or remove a component between when the canvas polling starts and completes. This can be easily simulated by adding a `delay` to the `pipe` following the API call and before `loadProcessGroupSuccess` is dispatched.
This PR additionally adds an override to skip the revision check when a nodes cluster connection state changes. This is important because the basis for component revisions changes when the node is connected to the cluster from when it's disconnected.
=> NIFI-13155: Adding revision checking in flow reducer

nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-frontend/src/main/nifi/src/app/pages/flow-designer/service/canvas-view.service.ts
NIFI-13176: 
- Relaxing the scale that triggers when details for components on the canvas are not rendered.
=> NIFI-13176: Relaxing the scale that triggers when details for components on the canvas are not rendered

nifi-extension-bundles/nifi-slack-bundle/nifi-slack-processors/src/main/java/org/apache/nifi/processors/slack/ConsumeSlack.java, nifi-extension-bundles/nifi-slack-bundle/nifi-slack-processors/src/main/java/org/apache/nifi/processors/slack/consume/ConsumeSlackClient.java, nifi-extension-bundles/nifi-slack-bundle/nifi-slack-processors/src/test/java/org/apache/nifi/processors/slack/TestConsumeSlack.java
[NIFI-13146](https://issues.apache.org/jira/browse/NIFI-13146)
ConsumeSlack processor got stuck in initialization phase and reported rate limit error continuously when it was running in a Slack workplace with thousands of channels. 
As a mitigation for the problem I added a logic which checks if "Channels" property contains only IDs. In case no channel name is specified, another Slack API call ([conversations.info](https://api.slack.com/methods/conversations.info)) is used to fetch the channel names for the channel IDs and no need to fetch the whole conversation list.
- [x ] JDK 21
=> NIFI-13146 ConsumeSlack rate limit error mitigation

nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-frontend/src/main/nifi/src/app/ui/common/property-table/property-table.component.html
NIFI-13060:
- Using ellipsis and normal line height in the property table.
=> NIFI-13060: Using ellipsis and normal line height in the property table

nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-frontend/src/main/nifi/src/app/pages/access-policies/ui/component-access-policies/component-access-policies.component.html, nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-frontend/src/main/nifi/src/app/pages/access-policies/ui/component-access-policies/component-access-policies.component.scss, nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-frontend/src/main/nifi/src/app/pages/access-policies/ui/component-access-policies/component-access-policies.component.ts, nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-frontend/src/main/nifi/src/app/pages/access-policies/ui/component-access-policies/component-access-policies.module.ts, nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-frontend/src/main/nifi/src/app/pages/flow-designer/ui/canvas/graph-controls/operation-control/operation-control.component.html, nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-frontend/src/main/nifi/src/app/pages/flow-designer/ui/canvas/graph-controls/operation-control/operation-control.component.scss, nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-frontend/src/main/nifi/src/app/pages/flow-designer/ui/canvas/graph-controls/operation-control/operation-control.component.ts, nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-frontend/src/main/nifi/src/app/pages/flow-designer/ui/controller-service/controller-services.component.scss, nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-frontend/src/main/nifi/src/app/pages/flow-designer/ui/manage-remote-ports/manage-remote-ports.component.scss, nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-frontend/src/main/nifi/src/app/pages/settings/ui/management-controller-services/management-controller-services.component.scss, nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-frontend/src/main/nifi/src/app/pipes/component-type-name.pipe.ts, nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-frontend/src/main/nifi/src/app/ui/common/component-context/component-context.component.html, nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-frontend/src/main/nifi/src/app/ui/common/component-context/component-context.component.scss, nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-frontend/src/main/nifi/src/app/ui/common/component-context/component-context.component.ts, nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-frontend/src/main/nifi/src/app/ui/common/property-table/property-table.component.html, nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-frontend/src/main/nifi/src/assets/styles/_app.scss
=> [NIFI-13177] ensure consistent typography rendering

nifi-commons/nifi-record-path/src/main/java/org/apache/nifi/record/path/functions/UnescapeJson.java, nifi-commons/nifi-record-path/src/main/java/org/apache/nifi/record/path/paths/RecordPathCompiler.java, nifi-commons/nifi-record-path/src/test/java/org/apache/nifi/record/path/TestRecordPath.java, nifi-commons/nifi-record/src/main/java/org/apache/nifi/serialization/record/util/DataTypeUtils.java, nifi-docs/src/main/asciidoc/record-path-guide.adoc, nifi-extension-bundles/nifi-standard-bundle/nifi-standard-processors/pom.xml, nifi-extension-bundles/nifi-standard-bundle/nifi-standard-processors/src/test/java/org/apache/nifi/processors/standard/TestUpdateRecord.java, nifi-extension-bundles/nifi-standard-bundle/nifi-standard-processors/src/test/resources/TestUpdateRecord/input/organisation.json, nifi-extension-bundles/nifi-standard-bundle/nifi-standard-processors/src/test/resources/TestUpdateRecord/output/organisation.json, nifi-extension-bundles/nifi-standard-bundle/nifi-standard-processors/src/test/resources/TestUpdateRecord/schema/organisation-with-departments-string.avsc, nifi-extension-bundles/nifi-standard-bundle/nifi-standard-processors/src/test/resources/TestUpdateRecord/schema/organisation-with-departments.avsc
[NIFI-8134](https://issues.apache.org/jira/browse/NIFI-8134) allow unescapeJson Record Path function to recursively convert Maps to Records
- ~[ ] New dependencies are compatible with the [Apache License 2.0](https://apache.org/licenses/LICENSE-2.0) according to the [License Policy](https://www.apache.org/legal/resolved.html)~
- ~[ ] New dependencies are documented in applicable `LICENSE` and `NOTICE` files~
=> NIFI-8134 allow unescapeJson Record Path function to recursively convert Maps to Records

nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-frontend/src/main/nifi/src/app/pages/flow-designer/ui/canvas/items/label/edit-label/edit-label.component.ts, nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-frontend/src/main/nifi/src/app/pages/flow-designer/ui/canvas/items/port/create-port/create-port.component.ts, nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-frontend/src/main/nifi/src/app/pages/flow-designer/ui/canvas/items/port/edit-port/edit-port.component.ts, nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-frontend/src/main/nifi/src/app/pages/flow-designer/ui/canvas/items/process-group/create-process-group/create-process-group.component.ts, nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-frontend/src/main/nifi/src/app/pages/flow-designer/ui/canvas/items/remote-process-group/create-remote-process-group/create-remote-process-group.component.ts, nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-frontend/src/main/nifi/src/app/pages/users/ui/user-listing/user-access-policies/user-access-policies.component.ts, nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-frontend/src/main/nifi/src/app/ui/common/extension-creation/extension-creation.component.ts, nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-frontend/src/main/nifi/src/app/ui/common/status-history/status-history.component.ts, nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-frontend/src/main/nifi/src/app/ui/common/system-diagnostics-dialog/system-diagnostics-dialog.component.ts
[NIFI-13241](https://issues.apache.org/jira/browse/NIFI-13241)
There were a number of dialogs missed in the original pass at supporting escape to close them. This PR adds it to those dialogs.
=> [NIFI-13241] - extend CloseOnEscpaeDialog in dialogs previously missing it

nifi-framework-bundle/nifi-framework/nifi-client-dto/src/main/java/org/apache/nifi/web/api/dto/AuthenticationConfigurationDTO.java, nifi-framework-bundle/nifi-framework/nifi-client-dto/src/main/java/org/apache/nifi/web/api/entity/AuthenticationConfigurationEntity.java, nifi-framework-bundle/nifi-framework/nifi-client-dto/src/main/java/org/apache/nifi/web/api/entity/CurrentUserEntity.java, nifi-framework-bundle/nifi-framework/nifi-framework-authorization-providers/src/main/java/org/apache/nifi/authorization/user/NiFiUserUtils.java, nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-api/src/main/java/org/apache/nifi/web/NiFiWebApiConfiguration.java, nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-api/src/main/java/org/apache/nifi/web/NiFiWebApiResourceConfig.java, nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-api/src/main/java/org/apache/nifi/web/StandardNiFiServiceFacade.java, nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-api/src/main/java/org/apache/nifi/web/api/AuthenticationResource.java, nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-api/src/main/java/org/apache/nifi/web/configuration/AuthenticationConfiguration.java, nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-api/src/main/resources/nifi-web-api-context.xml, nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-security/src/main/java/org/apache/nifi/web/security/configuration/WebSecurityConfiguration.java, nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-security/src/main/java/org/apache/nifi/web/security/jwt/converter/StandardJwtAuthenticationConverter.java, nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-security/src/main/java/org/apache/nifi/web/security/token/NiFiAuthenticationToken.java, nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-security/src/main/java/org/apache/nifi/web/security/x509/X509AuthenticationProvider.java
[NIFI-13232](https://issues.apache.org/jira/browse/NIFI-13232) Adds a new REST API method for returning authentication configuration details.
The purpose of the new method is to provide sufficient details for the user interface to determine when to show the login screen and when to show the logout link.
The REST API method is designed to support current authentication strategies, including username and password authentication with a Login Identity Provider, as well as single sign-on with either OIDC or SAML. The method should also return correct status when the client makes a request using mutual TLS with a client certificate. The mutual TLS scenario may require an additional field because when NiFi is running behind a reverse proxy, the proxy itself will provide a client certificate, but …
=> NIFI-13232 Add Authentication Configuration REST API method

minifi/minifi-nar-bundles/minifi-standard-nar/src/main/resources/META-INF/NOTICE, nifi-assembly/NOTICE, nifi-extension-bundles/nifi-standard-bundle/nifi-standard-nar/src/main/resources/META-INF/NOTICE, nifi-extension-bundles/nifi-standard-bundle/pom.xml, nifi-extension-bundles/nifi-standard-services/nifi-record-serialization-services-bundle/nifi-record-serialization-services/pom.xml
[NIFI-13263](https://issues.apache.org/jira/browse/NIFI-13263)
=> NIFI-13263 - Bump ParCEFone version

nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-frontend/src/main/nifi/src/assets/styles/_app.scss
[NIFI-13277](https://issues.apache.org/jira/browse/NIFI-13277)
Before:
After:
With the changes, the menu (as of now) displays without the need for scrollbars until the displayable browser area gets below 570 pixels in height. Previously it needed more than 740px. I guess I'm running non-clustered... but in clustered mode there would be an extra menu item, so these numbers would be slightly bigger there.
=> [NIFI-13277] - Make the main menu more compact in terms of spacing.

nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-frontend/src/main/nifi/src/app/ui/common/property-table/editors/nf-editor/_nf-editor.component-theme.scss, nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-frontend/src/main/nifi/src/app/ui/common/property-table/editors/nf-editor/nf-editor.component.ts, nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-frontend/src/main/nifi/src/assets/styles/_codemirror-theme.scss, nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-frontend/src/main/nifi/src/styles.scss
General light mode and dark mode theme support (with proper color contrast ratios) for codemirror v5 editors:
=> [NIFI-13257] codemirror light and dark mode theme

nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-frontend/pom.xml
NIFI-13278:
- Ensure 3rdpartylicenses.txt is included in resulting build artifact.
=> NIFI-13278: Ensure 3rdpartylicenses.txt is included in resulting build artifact

nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-frontend/src/main/nifi/src/app/pages/flow-designer/service/canvas-view.service.ts, nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-frontend/src/main/nifi/src/app/pages/flow-designer/state/transform/transform.actions.ts, nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-frontend/src/main/nifi/src/app/pages/flow-designer/state/transform/transform.effects.ts, nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-frontend/src/main/nifi/src/app/pages/flow-designer/ui/canvas/canvas.component.scss, nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-frontend/src/main/nifi/src/app/pages/flow-designer/ui/canvas/graph-controls/navigation-control/navigation-control.component.ts
NIFI-13285:
- If there is no transform to restore for the current viewport, executing a zoom fit.
=> NIFI-13285: If there is no transform to restore for the current viewport, executing a zoom fit

nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-frontend/src/main/nifi/src/app/pages/flow-designer/ui/canvas/canvas.component.ts
NIFI-13284:
- Only saving canvas routes that are not edit or history.
=> NIFI-13284: Only saving canvas routes that are not edit or history

nifi-extension-bundles/nifi-github-bundle/nifi-github-extensions/src/main/java/org/apache/nifi/github/GitHubAuthenticationType.java, nifi-extension-bundles/nifi-github-bundle/nifi-github-extensions/src/main/java/org/apache/nifi/github/GitHubFlowRegistryClient.java, nifi-extension-bundles/nifi-github-bundle/nifi-github-extensions/src/main/java/org/apache/nifi/github/GitHubRepositoryClient.java
[NIFI-13357](https://issues.apache.org/jira/browse/NIFI-13357) Removes the `APP_INSTALLATION_TOKEN` Authentication option from the `GitHubFlowRegistryClient` in favor of the `APP_INSTALLATION` option implemented in 
[NIFI-13231](https://issues.apache.org/jira/browse/NIFI-13231).
The `APP_INSTALLATION_TOKEN` option required external token provision to produce and sign a JWT with a short expiration, which was not optimal for long-lived access to GitHub repositories. The new `APP_INSTALLATION` option integrates App Installation Token provision using a configured App ID and Private Key, supporting long-lived service-based access. As the initial version was released in NiFi 2.0.0-M3, this is a breaking change, but the impact should be minimal based on the expiration issues with external token …
=> NIFI-13357 Remove APP_INSTALLATION_TOKEN from GitHubFlowRegistryClient

nifi-extension-bundles/nifi-hazelcast-bundle/nifi-hazelcast-services/src/test/java/org/apache/nifi/hazelcast/services/cachemanager/ExternalHazelcastCacheManagerTest.java, nifi-framework-bundle/nifi-framework/nifi-framework-kubernetes-bundle/nifi-framework-kubernetes-state-provider/src/test/java/org/apache/nifi/kubernetes/state/provider/KubernetesConfigMapStateProviderTest.java
[NIFI-13365](https://issues.apache.org/jira/browse/NIFI-13365)
=> NIFI-13365 - Fix unit tests running in kubernetes pod

nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-frontend/src/main/nifi/apps/nifi/src/app/pages/flow-designer/service/canvas-utils.service.ts, nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-frontend/src/main/nifi/apps/nifi/src/app/pages/flow-designer/service/manager/port-manager.service.ts, nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-frontend/src/main/nifi/apps/nifi/src/app/pages/flow-designer/service/manager/process-group-manager.service.ts, nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-frontend/src/main/nifi/apps/nifi/src/app/pages/flow-designer/service/manager/processor-manager.service.ts, nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-frontend/src/main/nifi/apps/nifi/src/app/pages/flow-designer/service/manager/remote-process-group-manager.service.ts, nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-frontend/src/main/nifi/apps/nifi/src/app/pages/flow-designer/state/flow/flow.effects.ts
NIFI-13368:
- Allowing tooltip mouse listeners to be destroyed when necessary.
- Ensuring connection source/destination run status and validation errors are updated when deleted.
=> NIFI-13368: Allowing tooltip mouse listeners to be destroyed when necessary

nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-frontend/src/main/nifi/apps/nifi/src/assets/styles/_app.scss
[NIFI-13370](https://issues.apache.org/jira/browse/NIFI-13370)
=> [NIFI-13370] - dark-mode support for browser inputs

nifi-extension-bundles/nifi-standard-services/nifi-lookup-services-bundle/nifi-lookup-services/src/main/java/org/apache/nifi/lookup/configuration2/XXEValidator.java
[NIFI-13383](https://issues.apache.org/jira/browse/NIFI-13383)
Changes info log message to debug in XXEValidator
- [n/a] New dependencies are compatible with the [Apache License 2.0](https://apache.org/licenses/LICENSE-2.0) according to the [License Policy](https://www.apache.org/legal/resolved.html)
- [n/a] New dependencies are documented in applicable `LICENSE` and `NOTICE` files
- [n/a] Documentation formatting appears as expected in rendered files
=> NIFI-13383 change info log message to debug in XXEValidator

nifi-docs/src/main/asciidoc/administration-guide.adoc, nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-security/src/main/java/org/apache/nifi/web/security/configuration/JwtDecoderConfiguration.java, nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-security/src/main/java/org/apache/nifi/web/security/jwt/key/Ed25519Signer.java, nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-security/src/main/java/org/apache/nifi/web/security/jwt/key/Ed25519Verifier.java, nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-security/src/main/java/org/apache/nifi/web/security/jwt/key/Ed25519VerifierFactory.java, nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-security/src/main/java/org/apache/nifi/web/security/jwt/key/command/KeyGenerationCommand.java, nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-security/src/test/java/org/apache/nifi/web/security/jwt/key/command/KeyGenerationCommandTest.java, nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-security/src/test/java/org/apache/nifi/web/security/jwt/provider/StandardBearerTokenProviderTest.java
[NIFI-13424](https://issues.apache.org/jira/browse/NIFI-13424) Changes the Application Bearer Token signing algorithm from `PS512` to `EdDSA` based on `Ed25519` for Elliptic Curve Cryptography described in [RFC 8032](https://www.rfc-editor.org/rfc/rfc8032).
Changes replace RSA key pair generation with `Ed25519`, which has been support as a standard signing algorithm for Java since [JEP 339](https://openjdk.org/jeps/339) introduced support in Java 15.
The implementation includes `Ed25519Signer` and `Ed25519Verifier` classes, which implement the corresponding interfaces from the [Nimbus JOSE + JWT](https://connect2id.com/products/nimbus-jose-jwt) library. The Nimbus library includes `Ed25519` implementations, but requires [Google Tink](https://developers.google.com/tink) instead of using …
=> NIFI-13424 Switch to EdDSA for Application Bearer Tokens

nifi-framework-bundle/nifi-framework/nifi-framework-components/src/main/java/org/apache/nifi/reporting/AbstractEventAccess.java, nifi-framework-bundle/nifi-framework/nifi-framework-core/src/test/java/org/apache/nifi/reporting/AbstractEventAccessTest.java
[NIFI-13476](https://issues.apache.org/jira/browse/NIFI-13476) Optimizes authorization checking when computing Process Group Status. Changes include evaluating the current recursion depth for included component status and using that to decide whether to run full authorization checks or use a static denied response. For flow definitions with several process groups that have numbers of nested components, this improvement avoids numerous unnecessary calls to the configured Authorizer.
=> NIFI-13476 Optimize Authorization Checking in Process Group Status

nifi-frontend/src/main/frontend/apps/nifi/src/app/pages/flow-designer/state/controller-services/controller-services.effects.ts, nifi-frontend/src/main/frontend/apps/nifi/src/app/pages/settings/state/management-controller-services/management-controller-services.effects.ts
NIFI-13523:
- Refreshing the controller service listing after creation or deletion to ensure allowable values of other services is accurate.
=> NIFI-13523: Refreshing the controller service listing after creation or deletion

nifi-frontend/src/main/frontend/libs/shared/src/directives/nifi-tooltip.directive.ts
NIFI-13477:
- Refreshing the controller service listing after creation or deletion to ensure allowable values of other services is accurate.
=> NIFI-13477: Fix flickering tooltip

nifi-nar-bundles/nifi-poi-bundle/nifi-poi-services/src/main/java/org/apache/nifi/excel/ExcelHeaderSchemaStrategy.java, nifi-nar-bundles/nifi-poi-bundle/nifi-poi-services/src/main/java/org/apache/nifi/excel/ExcelReader.java, nifi-nar-bundles/nifi-poi-bundle/nifi-poi-services/src/main/java/org/apache/nifi/excel/ExcelSchemaInference.java, nifi-nar-bundles/nifi-poi-bundle/nifi-poi-services/src/main/java/org/apache/nifi/excel/ExcelUtils.java, nifi-nar-bundles/nifi-poi-bundle/nifi-poi-services/src/test/java/org/apache/nifi/excel/TestExcelHeaderSchemaStrategy.java, nifi-nar-bundles/nifi-poi-bundle/nifi-poi-services/src/test/java/org/apache/nifi/excel/TestExcelSchemaInference.java
[NIFI-12491](https://issues.apache.org/jira/browse/NIFI-12491)
This feature has been added for the 2.x branch with #9064. This PR is to have it added to the 1.x branch. Per the comments in [NIFI-11167](https://issues.apache.org/jira/browse/NIFI-11167)  and [NIFI-13304](https://issues.apache.org/jira/browse/NIFI-13304) it would seem this feature along with `SplitExcel` processor will help customers who had used `ConvertExcelToCSV` in 1.x be able to make a smoother transition from 1.x to  2.x.
=> NIFI-12491 Added Starting Row Schema Strategy to ExcelReader for 1.x branch

nifi-nar-bundles/nifi-extension-utils/nifi-record-utils/nifi-json-record-utils/src/main/java/org/apache/nifi/json/AbstractJsonRowRecordReader.java, nifi-nar-bundles/nifi-extension-utils/nifi-record-utils/nifi-json-record-utils/src/main/java/org/apache/nifi/json/JsonPathRowRecordReader.java, nifi-nar-bundles/nifi-extension-utils/nifi-record-utils/nifi-json-record-utils/src/main/java/org/apache/nifi/json/JsonRecordSource.java, nifi-nar-bundles/nifi-extension-utils/nifi-record-utils/nifi-yaml-record-utils/src/main/java/org/apache/nifi/yaml/YamlParserFactory.java, nifi-nar-bundles/nifi-extension-utils/nifi-record-utils/nifi-yaml-record-utils/src/main/java/org/apache/nifi/yaml/YamlRecordSource.java, nifi-nar-bundles/nifi-standard-services/nifi-record-serialization-services-bundle/nifi-record-serialization-services/src/main/java/org/apache/nifi/json/JsonPathReader.java, nifi-nar-bundles/nifi-standard-services/nifi-record-serialization-services-bundle/nifi-record-serialization-services/src/main/java/org/apache/nifi/json/JsonTreeReader.java, nifi-nar-bundles/nifi-standard-services/nifi-record-serialization-services-bundle/nifi-record-serialization-services/src/main/java/org/apache/nifi/yaml/YamlTreeReader.java, nifi-nar-bundles/nifi-standard-services/nifi-record-serialization-services-bundle/nifi-record-serialization-services/src/test/java/org/apache/nifi/json/TestInferJsonSchemaAccessStrategy.java, nifi-nar-bundles/nifi-standard-services/nifi-record-serialization-services-bundle/nifi-record-serialization-services/src/test/java/org/apache/nifi/json/TestJsonTreeRowRecordReader.java, nifi-nar-bundles/nifi-standard-services/nifi-record-serialization-services-bundle/nifi-record-serialization-services/src/test/java/org/apache/nifi/yaml/TestYamlTreeRowRecordReader.java
[NIFI-13542](https://issues.apache.org/jira/browse/NIFI-13542)
=> NIFI-13542 Added missing Max String Length property for JSON Readers (nifi-1.x)

.asf.yaml
[NIFI-13561](https://issues.apache.org/jira/browse/NIFI-13561) Enables [automatic linking](https://github.com/apache/infrastructure-asfyaml/blob/main/README.md#autolink) for commit messages in GitHub to the Apache Jira system.
=> NIFI-13561 Enable Jira Automatic Linking in GitHub

nifi-commons/nifi-utils/src/test/java/org/apache/nifi/util/text/TestRegexDateTimeMatcher.java
[NIFI-13569](https://issues.apache.org/jira/browse/NIFI-13569)
=> NIFI-13569 Converted TestRegexDateTimeMatcher.java to a JUnit 5 Parameterized Test.

nifi-framework-bundle/nifi-framework/nifi-framework-components/src/main/java/org/apache/nifi/controller/parameter/StandardParameterProviderNode.java, nifi-framework-bundle/nifi-framework/nifi-framework-components/src/main/java/org/apache/nifi/parameter/FilterSensitiveParameterValueMapper.java, nifi-framework-bundle/nifi-framework/nifi-framework-components/src/main/java/org/apache/nifi/parameter/ParameterValueMapper.java, nifi-framework-bundle/nifi-framework/nifi-framework-components/src/main/java/org/apache/nifi/parameter/StandardParameterValueMapper.java, nifi-framework-bundle/nifi-framework/nifi-framework-components/src/main/java/org/apache/nifi/registry/flow/mapping/NiFiRegistryFlowMapper.java, nifi-framework-bundle/nifi-framework/nifi-framework-components/src/test/java/org/apache/nifi/parameter/TestStandardParameterValueMapper.java, nifi-framework-bundle/nifi-framework/nifi-framework-core-api/src/main/java/org/apache/nifi/controller/ParameterProviderNode.java, nifi-framework-bundle/nifi-framework/nifi-framework-core/src/main/java/org/apache/nifi/controller/serialization/VersionedFlowSynchronizer.java
[NIFI-13560](https://issues.apache.org/jira/browse/NIFI-13560) Refactors Parameter Provider handling to avoid storing fetched Parameter Values in the persisted flow configuration.
The implementation change retains memory-based storage of fetched Parameter Values ,but stores a reference string in the serialized flow configuration. When the framework starts, the flow synchronization process fetches current values from referenced Parameter Providers.
This change requires configured Parameter Provider services to be accessible on startup, but otherwise retains existing behavior. This strategy restores centralized management of external Parameter Values to referenced external services. The nature of external vaults and secrets managers necessitates high availability, so the requirement for …
=> NIFI-13560 Change Parameter Provider handling to avoid storing values

nifi-framework-bundle/nifi-framework/nifi-framework-components/src/main/java/org/apache/nifi/parameter/StandardParameterValueMapper.java, nifi-framework-bundle/nifi-framework/nifi-framework-components/src/test/java/org/apache/nifi/parameter/TestStandardParameterValueMapper.java
[NIFI-13577](https://issues.apache.org/jira/browse/NIFI-13577) Corrects `null` value handling in the `StandardParameterValueMapper` used to serialize values prior to writing the flow configuration. This change ensures that the Mapper returns a `null` when the input value is `null` instead of passing the value the configured value encryptor. This correction is required for the main branch, following the changes merged but not yet released under [NIFI-13560](https://issues.apache.org/jira/browse/NIFI-13560)
=> NIFI-13577 Correct null handling in Parameter Value Mapper

nifi-frontend/src/main/frontend/apps/nifi/src/app/pages/flow-designer/service/registry.service.ts, nifi-frontend/src/main/frontend/apps/nifi/src/app/pages/flow-designer/ui/canvas/items/flow/import-from-registry/import-from-registry.component.ts
[NIFI-13535](https://issues.apache.org/jira/browse/NIFI-13535)
Properly include the branch query param in API calls to the backend registry API when provided.
=> [NIFI-13535] - Fix: Issues selecting GitHub branch on version control screens in new UI

pom.xml
[NIFI-13588](https://issues.apache.org/jira/browse/NIFI-13588)
=> NIFI-13588 bumped maven-dependency-check to 10.0.3

nifi-framework-bundle/nifi-framework/nifi-web/nifi-jetty/src/main/java/org/apache/nifi/web/server/JettyServer.java
[NIFI-13575](https://issues.apache.org/jira/browse/NIFI-13575) Enables the `throwUnavailableOnStartupException` property for configured Web Applications in the framework Jetty Server. This property instructs Jetty to throw exceptions caught when starting a configured Web Applications, instead of just capturing and storing the exception. This approach removes the need for iterating over configured Jetty Server Handlers, and avoids potential issues related to nested handlers, ensuring that a Web Application exception will cause the Jetty Server to shutdown instead of continuing the startup process.
=> NIFI-13575 Improve Jetty Server handling of Web App Exceptions

nifi-commons/nifi-property-encryptor/pom.xml, nifi-commons/nifi-property-encryptor/src/main/java/org/apache/nifi/encrypt/CipherPropertyEncryptor.java, nifi-commons/nifi-property-encryptor/src/test/java/org/apache/nifi/encrypt/KeyedCipherPropertyEncryptorTest.java
[NIFI-13599](https://issues.apache.org/jira/browse/NIFI-13599) Replaces the Apache Commons Codec `Hex` usage with Java [HexFormat](https://docs.oracle.com/en/java/javase/17/docs/api/java.base/java/util/HexFormat.html), introduced in Java 17. The change preserves existing behavior of encoding and decoding encrypted values in a hexadecimal format, but removes the need for the `commons-codec` dependency in `nifi-property-encryptor`.
=> NIFI-13599 Replace Commons Codec Hex with HexFormat for Encryptor

nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-api/src/main/java/org/apache/nifi/web/configuration/WebApplicationConfiguration.java, nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-api/src/main/java/org/apache/nifi/web/configuration/WebSearchConfiguration.java
[NIFI-13609](https://issues.apache.org/jira/browse/NIFI-13609) Corrects the Component Search configuration definitions to avoid failures when using the search field in the web user interface.
Changes include removing a duplicate Controller Search Service bean definition and wiring in the correct Controller Search Service to the Controller Facade bean definition.
This issue does not impact released versions and was a result of recent changes with Spring Framework configuration refactoring.
=> NIFI-13609 Correct Component Search Configuration

nifi-frontend/src/main/frontend/apps/nifi/src/app/pages/flow-designer/ui/canvas/header/search/search.component.html, nifi-frontend/src/main/frontend/apps/nifi/src/app/pages/flow-designer/ui/canvas/header/search/search.component.ts
[NIFI-13621](https://issues.apache.org/jira/browse/NIFI-13621)
If there is an error from the search API, handle it by showing the error in a snackbar or fullscreen depending on the type.
Also fixed an issue with escape closing the search results and then not being able to open them back up again.
=> [NIFI-13621] - UI - handle backend errors when hitting the search api

nifi-framework-bundle/nifi-framework/nifi-web/nifi-jetty/pom.xml, nifi-framework-bundle/nifi-framework/nifi-web/nifi-jetty/src/main/java/org/apache/nifi/web/server/JettyServer.java, nifi-framework-bundle/nifi-framework/nifi-web/nifi-jetty/src/main/java/org/apache/nifi/web/server/filter/LogoutCompleteRedirectFilter.java, nifi-framework-bundle/nifi-framework/nifi-web/nifi-jetty/src/test/java/org/apache/nifi/web/server/filter/LogoutCompleteRedirectFilterTest.java
[NIFI-13622](https://issues.apache.org/jira/browse/NIFI-13622) Corrects core framework redirect handling for logout completion requests when NiFi is deployed behind a reverse proxy server with an alternative context path.
The initial implementation works as expected when the context path is unchanged, but the Jetty Redirect Pattern Rule does not account for the custom forwarded context path headers. Refactoring the approach to use a Servlet Filter based on the shared `RedirectUriHandler` from `nifi-web-servlet-shared` ensures correct redirect URI construction.
=> NIFI-13622 Correct Logout Complete Redirect for Proxies

nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-api/src/main/java/org/apache/nifi/web/api/FlowResource.java
[NIFI-13646](https://issues.apache.org/jira/browse/NIFI-13646) Corrects REST Resource handling of requests for the Current User when processing a response from a replicated request to other cluster members. The impact of failing behavior is limited to the current branch based on recent changes. Updated handling inspects the response type returned to either return the expected object or parse a streaming output according to node response handling.
=> NIFI-13646 Correct Current User Replicated Response Handling

nifi-extension-bundles/nifi-standard-bundle/nifi-standard-processors/src/main/java/org/apache/nifi/processors/standard/PutEmail.java
[NIFI-11977](https://issues.apache.org/jira/browse/NIFI-11977)
=> NIFI-11977 Set UTF-8 Character Set in Subject for PutEmail

nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-api/src/main/java/org/apache/nifi/web/NiFiWebApiResourceConfig.java, nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-api/src/main/java/org/apache/nifi/web/api/FlowFileQueueResource.java, nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-api/src/main/java/org/apache/nifi/web/api/ProvenanceEventResource.java, nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-api/src/main/java/org/apache/nifi/web/api/config/RangeNotSatisfiableExceptionMapper.java, nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-api/src/main/java/org/apache/nifi/web/api/streaming/ByteRange.java, nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-api/src/main/java/org/apache/nifi/web/api/streaming/ByteRangeFormatException.java, nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-api/src/main/java/org/apache/nifi/web/api/streaming/ByteRangeParser.java, nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-api/src/main/java/org/apache/nifi/web/api/streaming/ByteRangeStreamingOutput.java, nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-api/src/main/java/org/apache/nifi/web/api/streaming/InputStreamingOutput.java, nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-api/src/main/java/org/apache/nifi/web/api/streaming/RangeNotSatisfiableException.java, nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-api/src/main/java/org/apache/nifi/web/api/streaming/StandardByteRangeParser.java, nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-api/src/main/java/org/apache/nifi/web/api/streaming/StreamingOutputResponseBuilder.java, nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-api/src/test/java/org/apache/nifi/web/api/streaming/ByteRangeStreamingOutputTest.java, nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-api/src/test/java/org/apache/nifi/web/api/streaming/StandardByteRangeParserTest.java, nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-api/src/test/java/org/apache/nifi/web/api/streaming/StreamingOutputResponseBuilderTest.java
[NIFI-13652](https://issues.apache.org/jira/browse/NIFI-13652) Adds handling for the HTTP `Range` request header in content download REST resource methods.
[RFC 9110 Section 14](https://httpwg.org/specs/rfc9110.html#range.requests) describes range requests where clients can send the `Range` header with a specified number of bytes. The range request specification allows for multiple ranges, but the current implementation supports requesting a single range with either a first and last position, or a last position, which indicates the last number of bytes.
The implementation includes a `StreamingOutputResponseBuilder` that encapsulates `Range` header parsing, sets appropriate `Content-Range` response headers, and builds a `StreamingOutput` wrapper around the content stream that skips and …
=> NIFI-13652 Add Range Header Handling for Content Download

nifi-bootstrap/src/main/java/org/apache/nifi/bootstrap/command/ManagementServerBootstrapCommand.java, nifi-bootstrap/src/test/java/org/apache/nifi/bootstrap/command/ManagementServerBootstrapCommandTest.java, nifi-framework-bundle/nifi-framework/nifi-runtime/src/main/java/org/apache/nifi/runtime/HealthClusterHttpHandler.java, nifi-framework-bundle/nifi-framework/nifi-runtime/src/test/java/org/apache/nifi/runtime/StandardManagementServerTest.java
[NIFI-13684](https://issues.apache.org/jira/browse/NIFI-13684) Updates the `nifi-runtime` Management Server `/health/cluster` HTTP response to return HTTP 503 when the cluster connection state is not `CONNECTED` or `CONNECTING`. This change preserves the current behavior of the `nifi.sh cluster-status` command to return the information to the console, but provides an HTTP response code that corresponds to the content of the connection state.
=> NIFI-13684 Set Cluster Status HTTP Code based on Connection

nifi-registry/pom.xml, pom.xml
[NIFI-13685](https://issues.apache.org/jira/browse/NIFI-13685) Upgrades Spring Framework dependencies from 6.1.11 to [6.1.12](https://github.com/spring-projects/spring-framework/releases/tag/v6.1.12) and Spring Security dependencies from 6.3.1 to [6.3.3](https://github.com/spring-projects/spring-security/releases/tag/6.3.3). Also upgraded Spring Boot from 3.3.2 to [3.3.3](https://github.com/spring-projects/spring-boot/releases/tag/v3.3.3) for NiFi Registry.
=> NIFI-13685 Upgrade Spring from 6.1.11 to 6.1.12

nifi-nar-bundles/nifi-media-bundle/nifi-media-processors/src/main/java/org/apache/nifi/processors/image/ResizeImage.java
=> NIFI-13692 (1.X) Widened the exception handling in ResizeImage

nifi-bootstrap/src/main/java/org/apache/nifi/bootstrap/command/StandardBootstrapCommandProvider.java, nifi-bootstrap/src/main/java/org/apache/nifi/bootstrap/command/StartBootstrapCommand.java, nifi-bootstrap/src/test/java/org/apache/nifi/bootstrap/command/StartBootstrapCommandTest.java
[NIFI-13689](https://issues.apache.org/jira/browse/NIFI-13689) Adds a watch delay of 60 seconds to the NiFi Bootstrap Start Command to avoid launching the monitoring command when the application process fails on initial launch. This approach is similar to the previous implementation that waited up to 60 seconds for a successful launch. The implementation expects that application configuration problems will cause the application launch failures before the watch delay expires.
=> NIFI-13689 Add Watch Delay to Bootstrap Start Command

nifi-framework-bundle/nifi-framework/nifi-framework-core/src/main/java/org/apache/nifi/controller/serialization/VersionedFlowSynchronizer.java
[NIFI-13706](https://issues.apache.org/jira/browse/NIFI-13706) Updates the flow synchronization process to catch exceptions when fetching Parameters from Parameter Providers.
The framework logs a warning when catching exceptions from a Parameter Provider, and already handles logging warnings when a Parameter Provider does not return values for a configured Parameter.
This change in the startup process allows NiFi to start even when a Parameter Provider has configuration or connectivity issues. Missing Parameter values may result in flow configuration problems, which an authorized user can correct after fixing the referenced Parameter Provider. …
=> NIFI-13706 Handle Exceptions Fetching Parameters on Startup

nifi-commons/nifi-kubernetes-client/pom.xml, nifi-framework-bundle/nifi-framework-extensions/nifi-framework-kubernetes-bundle/nifi-framework-kubernetes-nar/pom.xml
[NIFI-13707](https://issues.apache.org/jira/browse/NIFI-13707) Changes the Fabric8 Kubernetes HTTP client implementation library from the default [kubernetes-httpclient-okhttp](https://central.sonatype.com/artifact/io.fabric8/kubernetes-httpclient-okhttp) to the [kubernetes-httpclient-jdk](https://central.sonatype.com/artifact/io.fabric8/kubernetes-httpclient-jdk) library, removing the dependency on OkHttp and Kotlin from the Kubernetes Framework bundle NAR.
=> NIFI-13707 Switch Kubernetes HTTP Client from OkHttp to JDK

nifi-stateless/nifi-stateless-bundle/nifi-stateless-engine/pom.xml, nifi-stateless/nifi-stateless-bundle/nifi-stateless-engine/src/main/java/org/apache/nifi/extensions/NexusExtensionClient.java, nifi-stateless/nifi-stateless-bundle/nifi-stateless-engine/src/main/java/org/apache/nifi/stateless/config/PropertiesFileFlowDefinitionParser.java, nifi-stateless/nifi-stateless-bundle/nifi-stateless-engine/src/main/java/org/apache/nifi/stateless/config/SslConfigurationUtil.java
[NIFI-13705](https://issues.apache.org/jira/browse/NIFI-13705) Refactors the NiFi Stateless Engine module to use the `nifi-web-client-api` module instead of the OkHttp library for retrieving flow definitions and extensions.
=> NIFI-13705 Refactor Stateless Engine using Web Client Service API

nifi-nar-bundles/nifi-cassandra-bundle/nifi-cassandra-processors/src/main/java/org/apache/nifi/processors/cassandra/QueryCassandra.java, nifi-nar-bundles/nifi-cassandra-bundle/nifi-cassandra-processors/src/test/java/org/apache/nifi/processors/cassandra/QueryCassandraTest.java
- Resolved the problem where QueryCassandra was not respecting the configured Max Wait Time.
- Updated the logic to ensure that the Max Wait Time is correctly applied to all query executions.
=> NIFI-13620: Resolved MaxWaitTime Issue in QueryCassandra

nifi-nar-bundles/nifi-standard-bundle/nifi-standard-processors/src/main/java/org/apache/nifi/processors/standard/ValidateXml.java, nifi-nar-bundles/nifi-standard-bundle/nifi-standard-processors/src/test/java/org/apache/nifi/processors/standard/TestValidateXml.java
[NIFI-13709](https://issues.apache.org/jira/browse/NIFI-13709)
The same fix was done for 2.x in #9229 and this fix is for 1.x
=> For 1.x added more meaningful message when validation fails with non-compliant XML and no schema is provided.

nifi-extension-bundles/nifi-elasticsearch-bundle/nifi-elasticsearch-client-service/src/test/java/org/apache/nifi/elasticsearch/integration/ElasticSearchClientService_IT.java
[NIFI-13734](https://issues.apache.org/jira/browse/NIFI-13734) Removes assertions for values of `getTook()` from the Elasticsearch Client Integration Test, which can fail intermittently based on development environment behavior.
=> NIFI-13734 Remove getTook assertions from Elasticsearch Test

nifi-extension-bundles/nifi-standard-bundle/nifi-standard-processors/src/test/java/org/apache/nifi/processors/standard/util/TestSFTPTransfer.java, nifi-extension-bundles/nifi-standard-bundle/pom.xml
[NIFI-13751](https://issues.apache.org/jira/browse/NIFI-13751)
=> NIFI-13751 Update com.hierynomus:sshj to v0.39.0

nifi-docs/src/main/asciidoc/administration-guide.adoc, nifi-docs/src/main/asciidoc/user-guide.adoc
[NIFI-7583](https://issues.apache.org/jira/browse/NIFI-7583) Add documentation on the user guide and admin guide about how swapping queued flowfiles to disk impacts prioritization.
- N/A New dependencies are compatible with the [Apache License 2.0](https://apache.org/licenses/LICENSE-2.0) according to the [License Policy](https://www.apache.org/legal/resolved.html)
- N/A New dependencies are documented in applicable `LICENSE` and `NOTICE` files
=> NIFI-7583 Document queue prioritizer issue with swapping

nifi-docs/src/main/asciidoc/expression-language-guide.adoc
Minor fix to the expected results of an Expression Language use of the `join` function. Update to Expression Language Guide. Documentation update only.
[NIFI-13736](https://issues.apache.org/jira/browse/NIFI-13736)
=> NIFI-13736 update Expression Language Guide, join function

nifi-extension-bundles/nifi-standard-bundle/nifi-standard-processors/src/main/java/org/apache/nifi/processors/standard/util/SFTPTransfer.java, nifi-extension-bundles/nifi-standard-bundle/nifi-standard-processors/src/test/java/org/apache/nifi/processors/standard/util/TestSFTPTransfer.java
[NIFI-13750](https://issues.apache.org/jira/browse/NIFI-13750)
=> NIFI-13750 Abort SFTP listing once maxResults is reached

nifi-framework-bundle/nifi-framework-extensions/nifi-py4j-framework-bundle/nifi-python-framework-api/src/main/java/org/apache/nifi/python/processor/PythonProcessorBridge.java, nifi-framework-bundle/nifi-framework/nifi-framework-core/src/main/java/org/apache/nifi/controller/ExtensionBuilder.java, nifi-framework-bundle/nifi-framework/nifi-framework-core/src/main/java/org/apache/nifi/nar/ComponentNodeDefinitionPredicate.java, nifi-framework-bundle/nifi-framework/nifi-framework-core/src/test/java/org/apache/nifi/nar/ComponentNodeDefinitionPredicateTest.java, nifi-framework-bundle/nifi-framework/nifi-framework-nar-utils/src/main/java/org/apache/nifi/nar/StandardExtensionDiscoveringManager.java, nifi-frontend/src/main/frontend/apps/nifi/src/app/pages/flow-designer/ui/canvas/items/connection/prioritizers/prioritizers.component.ts, nifi-frontend/src/main/frontend/apps/nifi/src/app/pages/settings/ui/registry-clients/create-registry-client/create-registry-client.component.ts, nifi-frontend/src/main/frontend/apps/nifi/src/app/ui/common/change-component-version-dialog/change-component-version-dialog.ts, nifi-frontend/src/main/frontend/apps/nifi/src/app/ui/common/extension-creation/extension-creation.component.ts, nifi-frontend/src/main/frontend/libs/shared/src/services/nifi-common.service.ts, nifi-system-tests/nifi-system-test-suite/src/test/java/org/apache/nifi/tests/system/NiFiClientUtil.java, nifi-system-tests/nifi-system-test-suite/src/test/java/org/apache/nifi/tests/system/nar/NarUploadPythonIT.java
[NIFI-13770](https://issues.apache.org/jira/browse/NIFI-13770) Removes the `python.` placeholder prefix from Python Processors added when loading extensions, and corrects the user interface behavior to display the component type.
The original implementation of support for Python Processors included the prefix as a workaround for UI rendering that expected a package name along with the simple class name. The updated UI function handles simple names for Python Processors as well as standard Java classes.
=> NIFI-13770 Remove Placeholder Prefix from Python Component Types

nifi-extension-bundles/nifi-slack-bundle/nifi-slack-processors/src/main/java/org/apache/nifi/processors/slack/ListenSlack.java
[NIFI-13712](https://issues.apache.org/jira/browse/NIFI-13712) - Improve ListenSlack to catch channel join events
=> NIFI-13712 - Improve ListenSlack to catch channel join events

nifi-framework-api/src/main/java/org/apache/nifi/nar/NarPersistenceInfo.java, nifi-framework-bundle/nifi-framework/nifi-framework-core-api/src/main/java/org/apache/nifi/nar/NarManager.java, nifi-framework-bundle/nifi-framework/nifi-framework-core/src/main/java/org/apache/nifi/controller/ExtensionBuilder.java, nifi-framework-bundle/nifi-framework/nifi-framework-core/src/main/java/org/apache/nifi/nar/NarInstallTask.java, nifi-framework-bundle/nifi-framework/nifi-framework-core/src/main/java/org/apache/nifi/nar/StandardNarManager.java, nifi-framework-bundle/nifi-framework/nifi-framework-nar-loading-utils/src/main/java/org/apache/nifi/nar/ExtensionUiLoader.java, nifi-framework-bundle/nifi-framework/nifi-framework-nar-loading-utils/src/main/java/org/apache/nifi/nar/NarLoader.java, nifi-framework-bundle/nifi-framework/nifi-framework-nar-loading-utils/src/main/java/org/apache/nifi/nar/StandardNarLoader.java, nifi-framework-bundle/nifi-framework/nifi-framework-nar-loading-utils/src/test/java/org/apache/nifi/nar/AbstractTestNarLoader.java, nifi-framework-bundle/nifi-framework/nifi-framework-nar-utils/src/main/java/org/apache/nifi/nar/ExtensionManager.java, nifi-framework-bundle/nifi-framework/nifi-framework-nar-utils/src/main/java/org/apache/nifi/nar/StandardExtensionDiscoveringManager.java, nifi-framework-bundle/nifi-framework/nifi-web/nifi-jetty/src/main/java/org/apache/nifi/web/server/JettyServer.java, nifi-system-tests/nifi-system-test-suite/src/test/java/org/apache/nifi/tests/system/nar/NarUploadStandaloneIT.java
- Ensure NARs are loaded in parent-first order during restart
- Allow replacing a NAR when other NARs are dependent on it
- Improvements to catch `Throwable` in several places to handle `NoClassDefFoundError`
[NIFI-13795](https://issues.apache.org/jira/browse/NIFI-13795)
=> NIFI-13795 Improve NAR Manager handling of dependent NARs

nifi-extension-bundles/nifi-py4j-extension-bundle/nifi-py4j-bridge/src/main/java/org/apache/nifi/python/processor/FlowFileTransformProxy.java, nifi-extension-bundles/nifi-py4j-extension-bundle/nifi-py4j-integration-tests/src/test/java/org.apache.nifi.py4j/PythonControllerInteractionIT.java
* Use cloned flow file as original
* Transform inbound flow file to ensure it gets picked up in Provenance Events
[NIFI-13779](https://issues.apache.org/jira/browse/NIFI-13779)
=> NIFI-13779: Missing Some Data Provenance Events from Python

nifi-frontend/src/main/frontend/libs/shared/src/assets/themes/material.scss
The secondary darker color for both light and dark mode has been updated to use the appropriate hue. 
The primary palette in dark mode has been update to match the secondary palette. 
Shared palettes have been encapsulated to ensure these colors do not get update in either light or dark mode. Only the neutral and neutral variants should be the only real differences between light and dark mode palettes.
=> [NIFI-13806] finalize color hues

nifi-extension-bundles/nifi-standard-bundle/nifi-standard-processors/src/main/java/org/apache/nifi/processors/standard/PutEmail.java, nifi-extension-bundles/nifi-standard-bundle/nifi-standard-processors/src/test/java/org/apache/nifi/processors/standard/TestPutEmail.java
[NIFI-13827](https://issues.apache.org/jira/browse/NIFI-13827)
This commit introduces: one new property descriptor for setting the reply-to address; checks and sets the file mime for the attached file. In case the mime type is null, the standard `application/octect-stream` is used.
=> NIFI-13827: support for the reply-to fuctionality and honor attached file mime type

nifi-extension-bundles/nifi-standard-services/nifi-record-serialization-services-bundle/nifi-record-serialization-services/src/test/java/org/apache/nifi/xml/TestXMLReader.java
[NIFI-13850](https://issues.apache.org/jira/browse/NIFI-13850)
=> NIFI-13850 Simplified TestXMLReader with Java 21 constructs, JUnit constructs and NIFI MockFlowFile methods.

nifi-nar-bundles/nifi-standard-services/nifi-record-serialization-services-bundle/nifi-record-serialization-services/pom.xml, nifi-nar-bundles/nifi-standard-services/nifi-record-serialization-services-bundle/nifi-record-serialization-services/src/main/java/org/apache/nifi/xml/XMLRecordReader.java, nifi-nar-bundles/nifi-standard-services/nifi-record-serialization-services-bundle/nifi-record-serialization-services/src/test/java/org/apache/nifi/xml/TestXMLReader.java, nifi-nar-bundles/nifi-standard-services/nifi-record-serialization-services-bundle/nifi-record-serialization-services/src/test/java/org/apache/nifi/xml/TestXMLReaderProcessor.java, nifi-nar-bundles/nifi-standard-services/nifi-record-serialization-services-bundle/nifi-record-serialization-services/src/test/resources/xml/dataWithArrayOfDifferentTypes.xml
[NIFI-13335](https://issues.apache.org/jira/browse/NIFI-13335)
This is a backport of the fix made in #9356
=> NIFI-13335 1.x Added ability for the XMLRecordReader to handle where an array of data has different types.

nifi-extension-bundles/nifi-standard-bundle/nifi-standard-processors/src/main/java/org/apache/nifi/processors/standard/ListenHTTP.java
[NIFI-12304](https://issues.apache.org/jira/browse/NIFI-12304)
Added ListenHTTP FlowFileV3 unpack behavior UseCase to its documentation
=> NIFI-12304 added ListenHTTP FlowFileV3 unpack behavior UseCase

nifi-extension-bundles/nifi-standard-bundle/nifi-standard-processors/src/main/java/org/apache/nifi/processors/standard/MergeRecord.java, nifi-extension-bundles/nifi-standard-bundle/nifi-standard-processors/src/main/java/org/apache/nifi/processors/standard/merge/RecordBin.java, nifi-extension-bundles/nifi-standard-bundle/nifi-standard-processors/src/test/java/org/apache/nifi/processors/standard/TestMergeRecord.java
[NIFI-13674](https://issues.apache.org/jira/browse/NIFI-13674)
I copied the description of the `WritesAttribute`  annotation from `MergeContent` `merge.reason`. Please confirm whether that is okay.
=> NIFI-13674 Added merge.reason attribute for MergeRecord.

nifi-commons/nifi-parameter/src/main/java/org/apache/nifi/parameter/AbstractParameterParser.java, nifi-commons/nifi-parameter/src/test/java/org/apache/nifi/parameter/TestExpressionLanguageAgnosticParameterParser.java
[NIFI-13890](https://issues.apache.org/jira/browse/NIFI-13890) - No referencing component for quoted parameter
=> NIFI-13890 - fix referencing components for quoted parameters

nifi-registry/nifi-registry-core/nifi-registry-framework/src/main/java/org/apache/nifi/registry/event/EventFactory.java, nifi-registry/nifi-registry-core/nifi-registry-framework/src/test/java/org/apache/nifi/registry/event/TestEventFactory.java, nifi-registry/nifi-registry-core/nifi-registry-framework/src/test/java/org/apache/nifi/registry/event/TestEventService.java, nifi-registry/nifi-registry-core/nifi-registry-provider-api/src/main/java/org/apache/nifi/registry/hook/EventFieldName.java, nifi-registry/nifi-registry-core/nifi-registry-provider-api/src/main/java/org/apache/nifi/registry/hook/EventType.java
[NIFI-13724](https://issues.apache.org/jira/browse/NIFI-13724)
- [ X] [Apache NiFi Jira](https://issues.apache.org/jira/browse/NIFI) issue created
- [ X] Pull Request title starts with Apache NiFi Jira issue number, such as `NIFI-00000`
- [ X] Pull Request commit message starts with Apache NiFi Jira issue number, as such `NIFI-00000`
- [X ] Pull Request based on current revision of the `main` branch
- [X ] Pull Request refers to a feature branch with one commit containing changes
- [ X] Build completed using `mvn clean install -P contrib-check`
- [ X] JDK 21
- [ n/a] New dependencies are compatible with the [Apache License …
=> NIFI-13724 Add additional metadata to Registry events

nifi-extension-bundles/nifi-update-attribute-bundle/nifi-update-attribute-ui/src/main/webapp/js/application.js
[NIFI-13853](https://issues.apache.org/jira/browse/NIFI-13853)
Added the ability to filter on text anywhere in the UpdateAttribute advanced rules. Currently you can filter by matching text in Rule name, the Conditions, Comments, and the Actions. So I added an option to filter "Anywhere", if the search string matches anywhere in a rule, that rule will be displayed.
=> NIFI-13853: Added the ability to filter by all to the Advanced Rules page

nifi-frontend/src/main/frontend/libs/shared/src/assets/styles/_app.scss, nifi-frontend/src/main/frontend/libs/shared/src/assets/styles/_codemirror-theme.scss
Prior to this PR:
After updates included with this PR:
=> [NIFI-13925] update codemirror cursor and matching brackets

nifi-frontend/src/main/frontend/apps/nifi/src/app/pages/flow-designer/ui/canvas/header/new-canvas-item/_new-canvas-item.component-theme.scss
=> [NIFI-13920] fix draggable icon color while dragging

nifi-frontend/src/main/frontend/libs/shared/src/assets/styles/_app.scss
Previously:
With this change applied:
Now the font color of the PG name matches the operation palette.
=> [NIFI-13917] update sidenav font color to match applicaiton font color

nifi-toolkit/nifi-toolkit-cli/src/main/java/org/apache/nifi/toolkit/cli/impl/command/nifi/params/DeleteParam.java
[NIFI-13924](https://issues.apache.org/jira/browse/NIFI-13924) - NiFi CLI - delete-param has no effect
While doing some testing for [NIFI-13904](https://issues.apache.org/jira/browse/NIFI-13904), I noticed that the delete-param CLI command has no effect. After some digging, this is due to [NIFI-12898](https://issues.apache.org/jira/browse/NIFI-12898) and the addition of asset support. In the CLI, the referenced asset needs to set to null to let the backend know that this is a deletion request.
See: https://github.com/apache/nifi/blame/main/nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-api/src/main/java/org/apache/nifi/web/dao/impl/StandardParameterContextDAO.java#L209
Please indicate the verification …
=> NIFI-13924 - Fix NiFi CLI delete-param command

nifi-toolkit/nifi-toolkit-cli/src/main/java/org/apache/nifi/toolkit/cli/impl/command/nifi/params/FetchParams.java, nifi-toolkit/nifi-toolkit-cli/src/main/java/org/apache/nifi/toolkit/cli/impl/command/nifi/params/GetParamProvider.java, nifi-toolkit/nifi-toolkit-cli/src/main/java/org/apache/nifi/toolkit/cli/impl/command/nifi/params/RemoveInheritedParamContexts.java, nifi-toolkit/nifi-toolkit-cli/src/main/java/org/apache/nifi/toolkit/cli/impl/command/nifi/params/SetInheritedParamContexts.java, nifi-toolkit/nifi-toolkit-cli/src/main/java/org/apache/nifi/toolkit/cli/impl/result/nifi/ParamProviderResult.java
[NIFI-13904](https://issues.apache.org/jira/browse/NIFI-13904) - Linking Parameter Contexts using NiFi Toolkit causes sensitive parameters to become invalid
The current implementation of the CLI for setting / removing the parameter context inheritance is broken when the parameter context to update contains sensitive parameters. The reason is that, currently, the update parameter request is adding all of the parameter entities in the request. However, when we retrieve sensitive parameters, we never really retrieve the sensitive values on the client side, we only get `*****` strings. Because of this, the current update request is actually updating the values of the sensitive parameters to this  `*****` value and this is what makes referencing components invalid. The update request needs to …
=> NIFI-13904 - Fix CLI commands to set/remove parameter context inheritance

nifi-registry/nifi-registry-core/nifi-registry-framework/src/main/java/org/apache/nifi/registry/event/EventFactory.java, nifi-registry/nifi-registry-core/nifi-registry-framework/src/test/java/org/apache/nifi/registry/event/TestEventFactory.java, nifi-registry/nifi-registry-core/nifi-registry-framework/src/test/java/org/apache/nifi/registry/event/TestEventService.java, nifi-registry/nifi-registry-core/nifi-registry-provider-api/src/main/java/org/apache/nifi/registry/hook/EventFieldName.java, nifi-registry/nifi-registry-core/nifi-registry-provider-api/src/main/java/org/apache/nifi/registry/hook/EventType.java
[NIFI-13724](https://issues.apache.org/jira/browse/NIFI-13724)
- [ X] [Apache NiFi Jira](https://issues.apache.org/jira/browse/NIFI) issue created
- [ X] Pull Request title starts with Apache NiFi Jira issue number, such as `NIFI-00000`
- [ X] Pull Request commit message starts with Apache NiFi Jira issue number, as such `NIFI-00000`
- [X ] Pull Request based on current revision of the `main` branch
- [X ] Pull Request refers to a feature branch with one commit containing changes
- [ X] Build completed using `mvn clean install -P contrib-check`
- [ X] JDK 21
- [ n/a] New dependencies are compatible with the [Apache License …
=> NIFI-13724 - Added additional metadata to events (#9239) on 1.x branch

nifi-extension-bundles/nifi-gcp-bundle/nifi-gcp-processors/src/main/java/org/apache/nifi/processors/gcp/pubsub/PublishGCPubSub.java
[NIFI-13927](https://issues.apache.org/jira/browse/NIFI-13927) - PublishGCPPubSub processor stop working and is stucked when using Record Oriented mode
See #9445 for more details
=> NIFI-13927 - Use synchronized lists in PublishGCPubSub

nifi-extension-bundles/nifi-gcp-bundle/nifi-gcp-processors/src/main/java/org/apache/nifi/processors/gcp/pubsub/PublishGCPubSub.java
[NIFI-13544](https://issues.apache.org/jira/browse/NIFI-13544) - Align number of executors with concurrent tasks in PublishGCPubSub
See #9405
=> NIFI-13544 Align number of executors with concurrent tasks in PublishGCPubSub

nifi-toolkit/nifi-toolkit-cli/src/main/java/org/apache/nifi/toolkit/cli/impl/client/nifi/ProcessGroupClient.java, nifi-toolkit/nifi-toolkit-cli/src/main/java/org/apache/nifi/toolkit/cli/impl/client/nifi/impl/JerseyProcessGroupClient.java, nifi-toolkit/nifi-toolkit-cli/src/main/java/org/apache/nifi/toolkit/cli/impl/command/nifi/NiFiCommandGroup.java, nifi-toolkit/nifi-toolkit-cli/src/main/java/org/apache/nifi/toolkit/cli/impl/command/nifi/pg/PGEmptyQueues.java
[NIFI-13937](https://issues.apache.org/jira/browse/NIFI-13937) - NiFi CLI - Add command pg-empty-queues
````
./bin/cli.sh nifi pg-empty-queues -p nifi-cli.properties -pgid 9a70ab3e-0192-1000-af96-cd5914b70181
````
````
./bin/cli.sh nifi pg-empty-queues -p nifi-cli.properties -pgid b5e0eb3a-0192-1000-6996-53ab1c85211b --verbose
Emptying queues, currently at 0% (1 of 20)...
Emptying queues, currently at 23% (2 of 20)...
Emptying queues, currently at 50% (3 of 20)...
Emptying queues, currently at 79% (4 of 20)...
Drop request completed. Deleted: 484,282 / 0 bytes
````
=> NIFI-13937 - NiFi CLI - Add command pg-empty-queues

nifi-docs/src/main/asciidoc/toolkit-guide.adoc, nifi-toolkit/nifi-toolkit-cli/src/main/java/org/apache/nifi/toolkit/cli/impl/command/nifi/NiFiCommandGroup.java, nifi-toolkit/nifi-toolkit-cli/src/main/java/org/apache/nifi/toolkit/cli/impl/command/nifi/pg/PGDelete.java
[NIFI-13868](https://issues.apache.org/jira/browse/NIFI-13868)
Adding `pg-delete` command to Nifi Toolkit. The command works the same way as deleting a process group via UI. If there are messages in PG queue, deletion will fail. I ported this change from [Anetac's Nifi fork](https://github.com/Eng-Anetac/nifi) where I made it a while ago. We have been using this feature in production at Anetac for months now.
The code change to `main` branch is smaller than the one to support/nifi-1.x branch, because @markap14 has already added some of the functionality under NIFI-12898
Related PR for support/nifi-1.x branch: https://github.com/apache/nifi/pull/9387
Please indicate the verification steps performed prior to pull …
=> NIFI-13868: add pg-delete command to Nifi Toolkit

nifi-bootstrap/src/main/java/org/apache/nifi/bootstrap/property/SecurityApplicationPropertyHandler.java, nifi-bootstrap/src/test/java/org/apache/nifi/bootstrap/property/SecurityApplicationPropertyHandlerTest.java
[NIFI-13941](https://issues.apache.org/jira/browse/NIFI-13941) Corrects DNS Subject Alternative Name handling for generated certificates derived from the `nifi.web.proxy.host` property. Recent changes reduced the maximum length to 64 characters, instead of the 255 allowed according to [RFC 1035 Section 2.3.4](https://www.rfc-editor.org/rfc/rfc1035#section-2.3.4). The adjusted regular expression and unit test verify names longer than 64 characters are allowed.
=> NIFI-13941 Fix Maximum Length for DNS Certificate SAN from Proxy Hosts

nifi-docs/src/main/asciidoc/toolkit-guide.adoc, nifi-toolkit/nifi-toolkit-cli/src/main/java/org/apache/nifi/toolkit/cli/impl/client/nifi/ProcessGroupClient.java, nifi-toolkit/nifi-toolkit-cli/src/main/java/org/apache/nifi/toolkit/cli/impl/client/nifi/impl/JerseyProcessGroupClient.java, nifi-toolkit/nifi-toolkit-cli/src/main/java/org/apache/nifi/toolkit/cli/impl/command/nifi/NiFiCommandGroup.java, nifi-toolkit/nifi-toolkit-cli/src/main/java/org/apache/nifi/toolkit/cli/impl/command/nifi/pg/PGDelete.java
[NIFI-13868](https://issues.apache.org/jira/browse/NIFI-13868)
Adding `pg-delete` command to Nifi Toolkit. The command works the same way as deleting a process group via UI. If there are messages in PG queue, deletion will fail. I ported this change from [Anetac's Nifi fork](https://github.com/Eng-Anetac/nifi) where I made it a while ago. We have been using this feature in production at Anetac for months now.
PR with the same feature for `main` branch: https://github.com/apache/nifi/pull/9388
The change for support/nifi-1.x branch is larger than for main, because the support branch does not have changes for NIFI-12898
=> NIFI-13868: add `pg-delete` command to Nifi Toolkit

nifi-extension-bundles/nifi-dropbox-bundle/pom.xml, nifi-extension-bundles/nifi-salesforce-bundle/nifi-salesforce-processors/pom.xml, nifi-extension-bundles/nifi-snmp-bundle/nifi-snmp-processors/pom.xml, nifi-extension-bundles/nifi-snmp-bundle/nifi-snmp-processors/src/main/java/org/apache/nifi/snmp/operations/SNMPTrapReceiverHandler.java, nifi-extension-bundles/nifi-snmp-bundle/nifi-snmp-processors/src/main/java/org/apache/nifi/snmp/utils/SNMPUtils.java, nifi-extension-bundles/nifi-snmp-bundle/nifi-snmp-processors/src/test/java/org/apache/nifi/snmp/factory/trap/V2TrapPDUFactoryTest.java, nifi-framework-bundle/nifi-framework-extensions/nifi-questdb-bundle/nifi-questdb/pom.xml
[NIFI-13943](https://issues.apache.org/jira/browse/NIFI-13943) This PR upgrades some libraries that support EOL products
=> NIFI-13943: Upgrade Dropbox, Salesforce, SNMP, and QuestDB depdendencies

nifi-commons/nifi-record/src/main/java/org/apache/nifi/serialization/RecordReader.java, nifi-commons/nifi-record/src/main/java/org/apache/nifi/serialization/record/MapRecord.java, nifi-extension-bundles/nifi-extension-utils/nifi-record-utils/nifi-json-record-utils/src/main/java/org/apache/nifi/json/JsonTreeRowRecordReader.java, nifi-extension-bundles/nifi-standard-bundle/nifi-standard-processors/pom.xml, nifi-extension-bundles/nifi-standard-bundle/nifi-standard-processors/src/test/java/org/apache/nifi/processors/standard/TestConvertRecord.java, nifi-extension-bundles/nifi-standard-bundle/nifi-standard-processors/src/test/resources/TestConvertRecord/input/person_dropfield.json
[NIFI-13843](https://issues.apache.org/jira/browse/NIFI-13843)
Consider the following use case:
- GFF Processor, generating a JSON with 3 fields: `a`, `b`, and `c`
- ConvertRecord with JSON Reader / JSON Writer
- Both reader and writer are configured with a schema only specifying fields `a` and `b`
The expected result is a JSON that only contains fields `a` and `b`.
We're following the below path in the code:
- `AbstractRecordProcessor` (L131)
````java
Record firstRecord = reader.nextRecord(); 
````
In this case, the default method for `nextRecord()` is defined in `RecordReader` (L50)
````java
default Record nextRecord() throws IOException, MalformedRecordException {
return nextRecord(true, false);
} 
````
where we are NOT dropping the unknown fields (Java doc needs some fixing here as it …
=> NIFI-13843 - use record.isDropUnknownFields() to honor JSON Writer Schema

nifi-assembly/NOTICE, nifi-extension-bundles/nifi-redis-bundle/nifi-redis-extensions/pom.xml, nifi-extension-bundles/nifi-redis-bundle/nifi-redis-nar/src/main/resources/META-INF/LICENSE, nifi-extension-bundles/nifi-redis-bundle/nifi-redis-nar/src/main/resources/META-INF/NOTICE, nifi-extension-bundles/nifi-redis-bundle/nifi-redis-service-api-nar/src/main/resources/META-INF/NOTICE, nifi-extension-bundles/nifi-redis-bundle/nifi-redis-service-api/pom.xml, nifi-extension-bundles/nifi-redis-bundle/pom.xml, pom.xml
[NIFI-13944](https://issues.apache.org/jira/browse/NIFI-13944) This PR upgrades the Redis library to 5.2.0 along with the corresponding Spring Redis version, and excludes the banned org.json:json dependency in favor of Ted Dunning's version.
=> NIFI-13944: Upgrade Redis to 5.2.0

nifi-extension-bundles/nifi-extension-utils/nifi-git-flow-registry/src/main/java/org/apache/nifi/registry/flow/git/AbstractGitFlowRegistryClient.java, nifi-extension-bundles/nifi-github-bundle/nifi-github-extensions/src/test/java/org/apache/nifi/github/GitHubFlowRegistryClientTest.java
[NIFI-13955](https://issues.apache.org/jira/browse/NIFI-13955) - Filter out .directories in Git Registry clients
If a Git Registry Client (GitHub/GitLab) is configured without a repo path (looking at the root of the repo), we should filter out directories with names starting with a dot (as we may have directories like `.github`), otherwise they will be showing as potential buckets.
=> NIFI-13955 - Filter out .directories in Git Registry clients

nifi-frontend/src/main/frontend/apps/nifi/src/app/pages/settings/ui/flow-analysis-rules/edit-flow-analysis-rule/edit-flow-analysis-rule.component.spec.ts, nifi-frontend/src/main/frontend/apps/nifi/src/app/pages/settings/ui/flow-analysis-rules/edit-flow-analysis-rule/edit-flow-analysis-rule.component.ts
[NIFI-13951](https://issues.apache.org/jira/browse/NIFI-13951)
In addition to adding the missing Warn policy level as an option to the enforcement policy select, the default selection is no longer hard coded as `Enforce` but instead reads the value returned from the backend.
cc @pvillard31 
=> NIFI-13951: Add warn policy to dropdown selection

nifi-frontend/src/main/frontend/apps/nifi/src/app/ui/common/extension-creation/extension-creation.component.ts, nifi-frontend/src/main/frontend/apps/nifi/src/app/ui/common/extension-creation/filter-predicate/camel-case.search.spec.ts, nifi-frontend/src/main/frontend/apps/nifi/src/app/ui/common/extension-creation/filter-predicate/camel-case.search.ts, nifi-frontend/src/main/frontend/apps/nifi/src/app/ui/common/extension-creation/filter-predicate/extensions.spec.ts, nifi-frontend/src/main/frontend/apps/nifi/src/app/ui/common/extension-creation/filter-predicate/extensions.ts, nifi-frontend/src/main/frontend/apps/nifi/src/app/ui/common/extension-creation/filter-predicate/filter-predicate.ts
[NIFI-13961](https://issues.apache.org/jira/browse/NIFI-13961)
This is my first contribution to the UI code, which is why I was quite unsure where to put these additions. 
I'd appreciate any feedback. Please let me know, if I should re-arrange the structure of functions added.
=> NIFI-13961 Allow camelCase search when filtering on component selection in UI

nifi-extension-bundles/nifi-kafka-bundle/nifi-kafka-3-service/pom.xml, pom.xml
[NIFI-13986](https://issues.apache.org/jira/browse/NIFI-13986) - Upgrade dependencies jackson, jetty, kafka and plugins
- kafka-clients from 3.8.0 to 3.9.0
- jetty from 12.0.14 to 12.0.15
- jackson from 2.18.0 to 2.18.1
- exec-maven-plugin from 3.4.1 to 3.5.0
- docker-maven-plugin from 0.43.4 to 0.45.1
- maven-checkstyle from 3.5.0 to 3.6.0
- checkstyle from 10.18.2 to 10.20.0
- swagger-codegen from 3.0.63 to 3.0.64
- dependency-check from 10.0.4 to 11.1.0
=> NIFI-13986 - Upgrade dependencies jackson, jetty, kafka and plugins

nifi-extension-bundles/nifi-standard-services/nifi-ssl-context-bundle/nifi-ssl-context-service/src/main/java/org/apache/nifi/ssl/StandardSSLContextService.java
There was a simple typo in StandardSSLContextService which caused the keystore file to be used where the truststore file was expected. This resulted in a StandardSSLContextService configuration with only a truststore and no keystore to be inaccurate.
[NIFI-13985](https://issues.apache.org/jira/browse/NIFI-13985)
- Performed a clean build using `-Pcontrib-check` profile
- Successfully passed a custom processor unit test which previously failed as a result of this bug
-
=> NIFI-13985 fixed typo which caused keystore file to not load by StandardSSLContextService

nifi-extension-bundles/nifi-extension-utils/nifi-record-utils/nifi-json-record-utils/src/main/java/org/apache/nifi/json/JsonTreeRowRecordReader.java, nifi-extension-bundles/nifi-py4j-extension-bundle/nifi-py4j-bridge/src/main/java/org/apache/nifi/python/processor/RecordTransformProxy.java, nifi-extension-bundles/nifi-salesforce-bundle/nifi-salesforce-processors/src/main/java/org/apache/nifi/processors/salesforce/QuerySalesforceObject.java, nifi-extension-bundles/nifi-standard-bundle/nifi-standard-processors/src/test/java/org/apache/nifi/processors/standard/TestForkRecord.java, nifi-extension-bundles/nifi-standard-services/nifi-record-serialization-services-bundle/nifi-record-serialization-services/src/test/java/org/apache/nifi/json/TestJsonTreeRowRecordReader.java
[NIFI-13989](https://issues.apache.org/jira/browse/NIFI-13989)
=> NIFI-13989 Reduced the number of constructors in JsonTreeRowRecordReader down to one.

nifi-docs/src/main/asciidoc/python-developer-guide.adoc, nifi-extension-bundles/nifi-py4j-extension-bundle/nifi-py4j-bridge/src/main/java/org/apache/nifi/python/processor/FlowFileSourceProxy.java, nifi-extension-bundles/nifi-py4j-extension-bundle/nifi-py4j-bridge/src/main/java/org/apache/nifi/python/processor/PythonProcessorProxy.java, nifi-extension-bundles/nifi-py4j-extension-bundle/nifi-py4j-integration-tests/src/test/java/org.apache.nifi.py4j/PythonControllerInteractionIT.java, nifi-extension-bundles/nifi-py4j-extension-bundle/nifi-python-test-extensions/src/main/resources/extensions/TestStateManager.py, nifi-extension-bundles/nifi-py4j-extension-bundle/nifi-python-test-extensions/src/main/resources/extensions/TestStateManagerException.py, nifi-framework-bundle/nifi-framework-extensions/nifi-py4j-framework-bundle/nifi-python-extension-api/src/main/python/src/nifiapi/componentstate.py, nifi-framework-bundle/nifi-framework-extensions/nifi-py4j-framework-bundle/nifi-python-extension-api/src/main/python/src/nifiapi/properties.py
[NIFI-13745](https://issues.apache.org/jira/browse/NIFI-13745)
=> NIFI-13745 StateManager available via the Python API

nifi-commons/nifi-record/src/main/java/org/apache/nifi/serialization/record/util/DataTypeUtils.java, nifi-commons/nifi-record/src/test/java/org/apache/nifi/serialization/record/TestDataTypeUtils.java, nifi-extension-bundles/nifi-poi-bundle/nifi-poi-services/src/test/java/org/apache/nifi/excel/TestExcelRecordReader.java
[NIFI-13988](https://issues.apache.org/jira/browse/NIFI-13988)
=> NIFI-13988 Refactored number handling to account for a blank string and treat it as a null when the inferred type is a number.

nifi-commons/nifi-web-client-api/src/main/java/org/apache/nifi/web/client/api/HttpRequestBodySpec.java, nifi-commons/nifi-web-client-api/src/main/java/org/apache/nifi/web/client/api/HttpResponseEntity.java, nifi-commons/nifi-web-client/src/main/java/org/apache/nifi/web/client/StandardHttpResponseEntity.java, nifi-commons/nifi-web-client/src/main/java/org/apache/nifi/web/client/StandardWebClientService.java
[NIFI-13982](https://issues.apache.org/jira/browse/NIFI-13982) - Web client - body as string and get request URI for response entity
In the web client API, we currently have in `HttpRequestBodySpec`:
````java
HttpRequestHeadersSpec body(InputStream inputStream, OptionalLong contentLength) 
````
It would be convenient to also have:
````java
HttpRequestHeadersSpec body(String body); 
````
Especially when the payload is very small and easy to craft.
In addition, in `HttpResponseEntity`, there is no way to know what endpoint has been accessed to generate that response. Having the possibility to retrieved the requested endpoint from the response entity might be useful when there is a separation between processors and controller services, in particular when generating the provenance events at …
=> NIFI-13982 - Web client - body as string and get request URI for response entity

nifi-frontend/src/main/frontend/apps/nifi/src/app/pages/flow-configuration-history/ui/flow-configuration-history-listing/action-details/action-details.component.html, nifi-frontend/src/main/frontend/apps/nifi/src/app/pages/flow-configuration-history/ui/flow-configuration-history-listing/action-details/action-details.component.ts, nifi-frontend/src/main/frontend/apps/nifi/src/app/pages/flow-designer/ui/canvas/items/connection/edit-connection/edit-connection.component.html, nifi-frontend/src/main/frontend/apps/nifi/src/app/pages/flow-designer/ui/canvas/items/connection/edit-connection/edit-connection.component.ts, nifi-frontend/src/main/frontend/apps/nifi/src/app/pages/flow-designer/ui/canvas/items/processor/edit-processor/edit-processor.component.html, nifi-frontend/src/main/frontend/apps/nifi/src/app/pages/flow-designer/ui/canvas/items/processor/edit-processor/edit-processor.component.ts, nifi-frontend/src/main/frontend/apps/nifi/src/app/pages/flow-designer/ui/canvas/items/remote-process-group/edit-remote-process-group/edit-remote-process-group.component.html, nifi-frontend/src/main/frontend/apps/nifi/src/app/pages/flow-designer/ui/canvas/items/remote-process-group/edit-remote-process-group/edit-remote-process-group.component.ts, nifi-frontend/src/main/frontend/apps/nifi/src/app/pages/parameter-contexts/ui/parameter-context-listing/edit-parameter-context/edit-parameter-context.component.html, nifi-frontend/src/main/frontend/apps/nifi/src/app/pages/parameter-contexts/ui/parameter-context-listing/edit-parameter-context/edit-parameter-context.component.ts, nifi-frontend/src/main/frontend/apps/nifi/src/app/pages/queue/ui/queue-listing/flowfile-dialog/flowfile-dialog.component.html, nifi-frontend/src/main/frontend/apps/nifi/src/app/pages/queue/ui/queue-listing/flowfile-dialog/flowfile-dialog.component.ts, nifi-frontend/src/main/frontend/apps/nifi/src/app/pages/settings/ui/flow-analysis-rules/edit-flow-analysis-rule/edit-flow-analysis-rule.component.html, nifi-frontend/src/main/frontend/apps/nifi/src/app/pages/settings/ui/flow-analysis-rules/edit-flow-analysis-rule/edit-flow-analysis-rule.component.ts, nifi-frontend/src/main/frontend/apps/nifi/src/app/pages/settings/ui/parameter-providers/edit-parameter-provider/edit-parameter-provider.component.html, nifi-frontend/src/main/frontend/apps/nifi/src/app/pages/settings/ui/parameter-providers/edit-parameter-provider/edit-parameter-provider.component.ts, nifi-frontend/src/main/frontend/apps/nifi/src/app/pages/settings/ui/registry-clients/edit-registry-client/edit-registry-client.component.html, nifi-frontend/src/main/frontend/apps/nifi/src/app/pages/settings/ui/registry-clients/edit-registry-client/edit-registry-client.component.ts, nifi-frontend/src/main/frontend/apps/nifi/src/app/pages/settings/ui/reporting-tasks/edit-reporting-task/edit-reporting-task.component.html, nifi-frontend/src/main/frontend/apps/nifi/src/app/pages/settings/ui/reporting-tasks/edit-reporting-task/edit-reporting-task.component.ts, nifi-frontend/src/main/frontend/apps/nifi/src/app/ui/common/controller-service/edit-controller-service/edit-controller-service.component.html, nifi-frontend/src/main/frontend/apps/nifi/src/app/ui/common/controller-service/edit-controller-service/edit-controller-service.component.ts, nifi-frontend/src/main/frontend/apps/nifi/src/app/ui/common/provenance-event-dialog/provenance-event-dialog.component.html, nifi-frontend/src/main/frontend/apps/nifi/src/app/ui/common/provenance-event-dialog/provenance-event-dialog.component.ts, nifi-frontend/src/main/frontend/libs/shared/src/assets/styles/_app.scss, nifi-frontend/src/main/frontend/libs/shared/src/directives/copy/copy.directive.spec.ts, nifi-frontend/src/main/frontend/libs/shared/src/directives/copy/copy.directive.ts, nifi-frontend/src/main/frontend/libs/shared/src/directives/index.ts
[NIFI-14002](https://issues.apache.org/jira/browse/NIFI-14002)
Added a new directive `copy` that just takes in a string. It adds the copy icon at the end of the element, but only displayed when it is hovered. Click it to copy to the clipboard.
Example usage to copy an id (assuming `id` is a variable):
```
<div [copy]="id">{{ id }}</div>
```
=> [NIFI-14002] - Quick copy of IDs

nifi-toolkit/nifi-toolkit-cli/src/main/java/org/apache/nifi/toolkit/cli/impl/client/NiFiClientFactory.java, nifi-toolkit/nifi-toolkit-cli/src/main/java/org/apache/nifi/toolkit/cli/impl/client/nifi/impl/request/OIDCClientCredentialsRequestConfig.java, nifi-toolkit/nifi-toolkit-cli/src/main/java/org/apache/nifi/toolkit/cli/impl/command/CommandOption.java
[NIFI-13998](https://issues.apache.org/jira/browse/NIFI-13998) - Add OIDC Client Credentials Flow support to NiFi CLI
With [NIFI-5302](https://issues.apache.org/jira/browse/NIFI-5302) #8532, we added support for Client Credentials Flow with OIDC. This should also be made available to the NiFi CLI.
````
$ cat nifi-cli-oidc.properties
baseUrl=https://localhost:8443
truststore=...
truststoreType=PKCS12
truststorePasswd=...
oidcTokenUrl=http://localhost:8080/realms/nifi/protocol/openid-connect/token
oidcClientId=...
oidcClientSecret=...
````
````
./bin/cli.sh nifi pg-list -p nifi-cli-oidc.properties
-   -------------   ------------------------------------   -------   -------   --------   -------
1   MyPG            b8bb5737-0191-1000-8462-b9822d6117f3   0         13        546        1
```` …
=> NIFI-13998 - Add OIDC Client Credentials Flow support to NiFi CLI

nifi-stateless/nifi-stateless-bundle/nifi-stateless-engine/src/main/java/org/apache/nifi/stateless/session/AsynchronousCommitTracker.java, nifi-stateless/nifi-stateless-bundle/nifi-stateless-engine/src/test/java/org/apache/nifi/stateless/session/TestAsynchronousCommitTracker.java
When more than one processor is ready we should allow the order of the queue to change to prevent execution from getting stuck on a single processor.
[NIFI-14003](https://issues.apache.org/jira/browse/NIFI-14003)
=> NIFI-14003: Allow stateless ready queue to update order.

nifi-framework-bundle/nifi-framework/nifi-framework-components/src/main/java/org/apache/nifi/groups/StandardProcessGroup.java
[NIFI-13608](https://issues.apache.org/jira/browse/NIFI-13608) - Handle NPE from Empty All Queues when there is no queue
=> NIFI-13608 - Handle NPE from Empty All Queues when there is no queue

nifi-framework-bundle/nifi-framework/nifi-framework-components/src/main/java/org/apache/nifi/controller/label/StandardLabel.java
[NIFI-13682](https://issues.apache.org/jira/browse/NIFI-13682) - Versioning breaks in case of style change on labels
Style for labels is a map which can have up to two keys: `font-size` and `background-color`. If between two versions, this map has a different key set, the current code creates an issue where we would always block any version change / any revert local changes because the current code merges the changes of the two versions and it will show as local changes that we'll never be able to revert. This PR changes the code to not merge the styles, but strictly apply the style of the desired version.
=> NIFI-13682 - Versioning breaks in case of style change on labels

nifi-framework-bundle/nifi-framework-extensions/nifi-provenance-repository-bundle/nifi-persistent-provenance-repository/src/main/java/org/apache/nifi/provenance/index/lucene/LuceneEventIndex.java
[NIFI-13731](https://issues.apache.org/jira/browse/NIFI-13731) - Catch NPE when no Provenance Lineage Submission
````
2024-11-15 14:06:58,024 ERROR [NiFi Web Server-804] o.a.nifi.web.api.config.ThrowableMapper An unexpected error has occurred: java.lang.NullPointerException: Cannot invoke "org.apache.nifi.provenance.AsyncLineageSubmission.getSubmitterIdentity()" because "submission" is null. Returning Internal Server Error response.
java.lang.NullPointerException: Cannot invoke "org.apache.nifi.provenance.AsyncLineageSubmission.getSubmitterIdentity()" because "submission" is null
at org.apache.nifi.provenance.index.lucene.LuceneEventIndex.retrieveLineageSubmission(LuceneEventIndex.java:761)
at org.apache.nifi.provenance.index.lucene.LuceneEventIndex.retrieveLineageSubmission(LuceneEventInd …
```
=> NIFI-13731 - Catch NPE when no Provenance Lineage Submission

nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-api/src/main/java/org/apache/nifi/web/StandardNiFiServiceFacade.java
[NIFI-14014](https://issues.apache.org/jira/browse/NIFI-14014) - Use Node ID instead of Instance ID for metrics endpoints
When NiFi is starting, if configured for clustering, the instance will get assigned a Node Identifier that will be persisted across restart via local cache. This Node ID should be used for identifying the data points of the metrics exposed by the `/flow/metrics/{provider}` endpoints. If NiFi is not configured for clustering, we can fallback to using the instance identifier. Besides, using the Node ID is better as this is the information made available via the Cluster view in the UI when looking at the details of nodes. …
=> NIFI-14014 - Use Node ID instead of Instance ID for metrics endpoints

nifi-extension-bundles/nifi-extension-utils/nifi-listed-entity/src/main/java/org/apache/nifi/processor/util/list/AbstractListProcessor.java, nifi-extension-bundles/nifi-gcp-bundle/nifi-gcp-processors/src/main/java/org/apache/nifi/processors/gcp/storage/FetchGCSObject.java, nifi-extension-bundles/nifi-gcp-bundle/nifi-gcp-processors/src/main/java/org/apache/nifi/processors/gcp/storage/ListGCSBucket.java, nifi-extension-bundles/nifi-gcp-bundle/nifi-gcp-processors/src/main/java/org/apache/nifi/processors/gcp/storage/StorageAttributes.java, nifi-extension-bundles/nifi-gcp-bundle/nifi-gcp-processors/src/test/java/org/apache/nifi/processors/gcp/storage/FetchGCSObjectTest.java, nifi-extension-bundles/nifi-gcp-bundle/nifi-gcp-processors/src/test/java/org/apache/nifi/processors/gcp/storage/ListGCSBucketTest.java
Add GCS file's ACL identities and roles to ListGCSBucket and FetchGCSObject processor's FlowFile Attribute output.
[NIFI-14007](https://issues.apache.org/jira/browse/NIFI-14007)
=> NIFI-14007 Add ACL entities to GCS Processor FlowFile attributes.

nifi-extension-bundles/nifi-standard-bundle/nifi-standard-processors/src/main/java/org/apache/nifi/processors/standard/GetFileResource.java, nifi-extension-bundles/nifi-standard-bundle/nifi-standard-processors/src/main/resources/META-INF/services/org.apache.nifi.processor.Processor, nifi-extension-bundles/nifi-standard-bundle/nifi-standard-processors/src/test/java/org/apache/nifi/processors/standard/TestGetFileResource.java
[NIFI-14005](https://issues.apache.org/jira/browse/NIFI-14005) - GetFileResource processor
The goal of this new GetFileResource processor is to provide a way for a user to inject a File Resource as a FlowFile with custom attributes. It means that the processor would be able to specify a path to a file and its content would be used as FlowFile's content. By leveraging the asset feature, it makes it easy to load a test dataset as a FlowFile in a cloud native environment (container based).
Alternatives that have been considered:
- GenerateFlowFile with a "Custom File/Content" property. However, a processor being able to access the local file system needs to be associated with a specific set of permissions and that would be a significant breaking change for all users already using …
=> NIFI-14005 - GetFileResource processor

nifi-toolkit/nifi-toolkit-cli/src/main/java/org/apache/nifi/toolkit/cli/impl/command/CommandOption.java, nifi-toolkit/nifi-toolkit-cli/src/main/java/org/apache/nifi/toolkit/cli/impl/command/nifi/NiFiCommandGroup.java, nifi-toolkit/nifi-toolkit-cli/src/main/java/org/apache/nifi/toolkit/cli/impl/command/nifi/pg/PGEmptyQueues.java, nifi-toolkit/nifi-toolkit-cli/src/main/java/org/apache/nifi/toolkit/cli/impl/command/nifi/pg/PGListProcessors.java
[NIFI-13948](https://issues.apache.org/jira/browse/NIFI-13948) - NiFi CLI - Add command pg-list-processors
Add a CLI command to recursively list the processors in a given process group. Also add the option to specify a filter that expects either 'source' or 'destination' as value.
- A source processor is defined as a processor that has no input relationship (unless this is a self relationship loop) and has at least one output relationship.
- A destination processor is defined as a processor that has no output relationship (unless this is a self relationship loop) and has at least one input relationship.
````
./bin/cli.sh nifi pg-list-processors -p nifi-cli.properties -pgid b5e0eb3a-0192-1000-6996-53ab1c85211b --filter foo
ERROR: Error executing command 'pg-list-processors' : Filter must …
```
=> NIFI-13948 - NiFi CLI - Add command pg-list-processors

nifi-toolkit/nifi-toolkit-cli/src/main/java/org/apache/nifi/toolkit/cli/impl/command/CommandOption.java, nifi-toolkit/nifi-toolkit-cli/src/main/java/org/apache/nifi/toolkit/cli/impl/command/nifi/NiFiCommandGroup.java, nifi-toolkit/nifi-toolkit-cli/src/main/java/org/apache/nifi/toolkit/cli/impl/command/nifi/registry/ListBranches.java, nifi-toolkit/nifi-toolkit-cli/src/main/java/org/apache/nifi/toolkit/cli/impl/command/nifi/registry/ListBuckets.java, nifi-toolkit/nifi-toolkit-cli/src/main/java/org/apache/nifi/toolkit/cli/impl/command/nifi/registry/ListFlowVersions.java, nifi-toolkit/nifi-toolkit-cli/src/main/java/org/apache/nifi/toolkit/cli/impl/command/nifi/registry/ListFlows.java, nifi-toolkit/nifi-toolkit-cli/src/main/java/org/apache/nifi/toolkit/cli/impl/result/nifi/RegistryBranchesResult.java, nifi-toolkit/nifi-toolkit-cli/src/main/java/org/apache/nifi/toolkit/cli/impl/result/nifi/RegistryBucketsResult.java, nifi-toolkit/nifi-toolkit-cli/src/main/java/org/apache/nifi/toolkit/cli/impl/result/nifi/RegistryFlowVersionsResult.java, nifi-toolkit/nifi-toolkit-cli/src/main/java/org/apache/nifi/toolkit/cli/impl/result/nifi/RegistryFlowsResult.java, nifi-toolkit/nifi-toolkit-client/src/main/java/org/apache/nifi/toolkit/client/FlowClient.java, nifi-toolkit/nifi-toolkit-client/src/main/java/org/apache/nifi/toolkit/client/impl/JerseyFlowClient.java
[NIFI-13950](https://issues.apache.org/jira/browse/NIFI-13950) - NiFi CLI - add commands to list branch, bucket, flows, versions through NiFi for Registry Clients
Currently, the CLI only provides access to branches / buckets / flows and versions via the use of `cli.sh registry ...` which only works when using the NiFi Registry.
Now that Registry Client is an extension point and that we have additional implementations, we should provide CLI commands to provide read-only access through a given registry client for listing branches / buckets / flows and versions. This will help users when they want to import a given flow with `cli.sh nifi pg-import ...`. In particular when it relates to versions because, when using a GitHub Registry Client, the version is a commit ID and it might not always …
=> NIFI-13950 - NiFi CLI - add commands to list branch, bucket, flows, versions through NiFi API

nifi-toolkit/nifi-toolkit-cli/src/main/java/org/apache/nifi/toolkit/cli/impl/command/CommandOption.java, nifi-toolkit/nifi-toolkit-cli/src/main/java/org/apache/nifi/toolkit/cli/impl/command/nifi/NiFiCommandGroup.java, nifi-toolkit/nifi-toolkit-cli/src/main/java/org/apache/nifi/toolkit/cli/impl/command/nifi/pg/PGImport.java, nifi-toolkit/nifi-toolkit-cli/src/main/java/org/apache/nifi/toolkit/cli/impl/command/nifi/registry/CreateRegistryClient.java, nifi-toolkit/nifi-toolkit-cli/src/main/java/org/apache/nifi/toolkit/cli/impl/command/nifi/registry/GetRegistryClientId.java, nifi-toolkit/nifi-toolkit-cli/src/main/java/org/apache/nifi/toolkit/cli/impl/command/nifi/registry/SetRegistryClientProperty.java, nifi-toolkit/nifi-toolkit-cli/src/main/java/org/apache/nifi/toolkit/cli/impl/command/nifi/registry/UpdateRegistryClient.java, nifi-toolkit/nifi-toolkit-cli/src/main/java/org/apache/nifi/toolkit/cli/impl/result/nifi/RegistryClientsResult.java, nifi-toolkit/nifi-toolkit-cli/src/test/java/org/apache/nifi/toolkit/cli/impl/result/TestRegistryClientResult.java
[NIFI-13905](https://issues.apache.org/jira/browse/NIFI-13905) - NiFi CLI - support for new Registry Clients
- Added support for giving a branch name in `pg-import`
- Removed the mandatory `url` argument for `create-reg-client`
- Removed the mandatory `url` argument for `get-reg-client`
- Removed the mandatory `url` argument for `update-reg-client`
- Added new command `set-reg-client-property` to configure a registry client
- Added Registry Client Type in the output of `list-reg-clients`
Steps to add a GitHub Registry Client and import flows using it:
````
./bin/cli.sh nifi create-reg-client -p nifi-cli.properties -rcn GitHubRegClient -rct org.apache.nifi.github.GitHubFlowRegistryClient
dd0aa635-0192-1000-2ee5-eb1ccc20d5c3
./bin/cli.sh nifi set-reg-client-property -p nifi-cli.properties …
```
=> NIFI-13905 - NiFi CLI - support for new Registry Clients

nifi-commons/nifi-properties/src/main/java/org/apache/nifi/util/NiFiProperties.java, nifi-commons/nifi-security-ssl/src/main/java/org/apache/nifi/security/ssl/InputStreamKeyStoreBuilder.java, nifi-commons/nifi-security-ssl/src/main/java/org/apache/nifi/security/ssl/PemCertificateKeyStoreBuilder.java, nifi-commons/nifi-security-ssl/src/main/java/org/apache/nifi/security/ssl/PemCertificateReader.java, nifi-commons/nifi-security-ssl/src/main/java/org/apache/nifi/security/ssl/PemPrivateKeyCertificateKeyStoreBuilder.java, nifi-commons/nifi-security-ssl/src/main/java/org/apache/nifi/security/ssl/PemPrivateKeyReader.java, nifi-commons/nifi-security-ssl/src/main/java/org/apache/nifi/security/ssl/ReadEntityException.java, nifi-commons/nifi-security-ssl/src/main/java/org/apache/nifi/security/ssl/StandardKeyStoreBuilder.java, nifi-commons/nifi-security-ssl/src/main/java/org/apache/nifi/security/ssl/StandardPemCertificateReader.java, nifi-commons/nifi-security-ssl/src/main/java/org/apache/nifi/security/ssl/StandardPemPrivateKeyReader.java, nifi-commons/nifi-security-ssl/src/test/java/org/apache/nifi/security/ssl/PemCertificateKeyStoreBuilderTest.java, nifi-commons/nifi-security-ssl/src/test/java/org/apache/nifi/security/ssl/PemPrivateKeyCertificateKeyStoreBuilderTest.java, nifi-commons/nifi-security-ssl/src/test/java/org/apache/nifi/security/ssl/StandardPemCertificateReaderTest.java, nifi-commons/nifi-security-ssl/src/test/java/org/apache/nifi/security/ssl/StandardPemPrivateKeyReaderTest.java, nifi-docs/src/main/asciidoc/administration-guide.adoc, nifi-framework-bundle/nifi-framework/nifi-framework-core/src/main/java/org/apache/nifi/framework/configuration/SslContextConfiguration.java, nifi-framework-bundle/nifi-framework/nifi-framework-core/src/main/java/org/apache/nifi/framework/ssl/FrameworkKeyManagerBuilder.java, nifi-framework-bundle/nifi-framework/nifi-framework-core/src/main/java/org/apache/nifi/framework/ssl/FrameworkSslContextProvider.java, nifi-framework-bundle/nifi-framework/nifi-framework-core/src/main/java/org/apache/nifi/framework/ssl/FrameworkTrustManagerBuilder.java, nifi-framework-bundle/nifi-framework/nifi-resources/pom.xml, nifi-framework-bundle/nifi-framework/nifi-resources/src/main/resources/conf/nifi.properties
[NIFI-14001](https://issues.apache.org/jira/browse/NIFI-14001) Adds framework support for PEM private keys and certificates as an alternative to Java Key Stores for TLS communication.
The implementation adds `PEM` as a supported value for the following application properties:
- `nifi.security.keystoreType`
- `nifi.security.truststoreType`
Configuring `PEM` for `nifi.security.keystoreType` requires setting the following properties:
- `nifi.security.keystore.privateKey`
- `nifi.security.keystore.certificate`
Configuring `PEM` for `nifi.security.truststoreType` requires setting the following property:
- `nifi.security.truststore.certificate`
The Administrator's Guide describes the new properties and supported values.
The new `certificate` properties support one or more X.509 certificates, …
=> NIFI-14001 Add Framework Support for PEM Keys and Certificates

nifi-mock/src/main/java/org/apache/nifi/util/MockPropertyValue.java, nifi-mock/src/test/java/org/apache/nifi/util/TestMockPropertyValue.java
[NIFI-14041](https://issues.apache.org/jira/browse/NIFI-14041) - Improve MockPropertyValue and EL evaluation validation
While building a processor, I noticed that the test framework would throw an error if I'm in the below situation:
- Processor with input forbidden
- Property with EL support with Environment scope
- Evaluation of the EL with .evaluateAttributeExpressions(Map<String,String>)
This should not throw an error. This PR is to fix this case as well as covering the overall EL evaluation in the test framework with proper unit testing.
=> NIFI-14041 - Improve MockPropertyValue and EL evaluation validation

nifi-extension-bundles/nifi-hazelcast-bundle/nifi-hazelcast-services-api/src/main/java/org/apache/nifi/hazelcast/services/cache/HazelcastCache.java, nifi-extension-bundles/nifi-hazelcast-bundle/nifi-hazelcast-services/src/main/java/org/apache/nifi/hazelcast/services/cache/IMapBasedHazelcastCache.java, nifi-extension-bundles/nifi-hazelcast-bundle/nifi-hazelcast-services/src/main/java/org/apache/nifi/hazelcast/services/cacheclient/HazelcastMapCacheClient.java, nifi-extension-bundles/nifi-hazelcast-bundle/nifi-hazelcast-services/src/test/java/org/apache/nifi/hazelcast/services/cache/HashMapHazelcastCache.java, nifi-extension-bundles/nifi-hazelcast-bundle/nifi-hazelcast-services/src/test/java/org/apache/nifi/hazelcast/services/cache/IMapBasedHazelcastCacheTest.java, nifi-extension-bundles/nifi-hazelcast-bundle/nifi-hazelcast-services/src/test/java/org/apache/nifi/hazelcast/services/cacheclient/HazelcastMapCacheClientTest.java
[NIFI-14043](https://issues.apache.org/jira/browse/NIFI-14043)
Applies minor refactoring (e.g. `x.isEmpty()` instead of `!x.isPresent()`).
Aligns names of private (de)serialisation methods. 
=> NIFI-14043 Add support for keySet in HazelcastMapCacheClient

minifi/minifi-assembly/src/main/resources/build.properties.template, nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-api/pom.xml, nifi-manifest/nifi-runtime-manifest/src/main/resources/build.properties, nifi-registry/nifi-registry-core/nifi-registry-web-api/pom.xml, pom.xml
[NIFI-14052](https://issues.apache.org/jira/browse/NIFI-14052) Removes non-deterministic build properties to address several findings from reviews of [reproducible builds](https://github.com/jvm-repo-rebuild/reproducible-central/blob/master/content/org/apache/nifi/nifi/README.md).
The Runtime Manifest generation process populates several build properties that are specific to the build environment, and none of these properties are used for the manifest itself. The following properties are removed:
- Built-By
- Maven-Home
- Build-Java-Home
- Build-Os-Version
Disabling [episode](https://github.com/highsource/jaxb-tools/wiki/Using-Episodes) file generation for code generated from XML Schema Definitions removes unused files that contain build timestamps.
Enabling the [sortOutput …
=> NIFI-14052 Remove non-deterministic build properties

nifi-framework-bundle/nifi-framework/nifi-framework-core-api/src/main/java/org/apache/nifi/controller/AbstractComponentNode.java, nifi-framework-bundle/nifi-framework/nifi-framework-core-api/src/test/java/org/apache/nifi/controller/TestAbstractComponentNode.java
[NIFI-14016](https://issues.apache.org/jira/browse/NIFI-14016)
To test fix:
Put QuerySalesforceObject on nifi graph.
Change Bulletin level to DEBUG (i.e. double click processor -> Settings -> Bulletin Level -> DEBUG)
Give some random value for `sObject Name` property (and click "Apply")
Notice that no bulletin appears.
Give another value for `sObject Name` property (and click "Apply")
Notice that a bulletin appears in processor's upper right corner noting that the [value has changed](https://github.com/apache/nifi/blob/rel/nifi-2.0.0/nifi-extension-bundles/nifi-salesforce-bundle/nifi-salesforce-processors/src/main/java/org/apache/nifi/processors/salesforce/QuerySalesforceObject.java#L358-#L359).
Prior to fix, the bulletin would not appear in this situation.
Please complete the following …
=> NIFI-14016 Resolved issue for onPropertyModified() where oldValue was always null

nifi-frontend/src/main/frontend/apps/nifi/src/app/app.module.ts, nifi-frontend/src/main/frontend/apps/nifi/src/app/pages/flow-designer/service/canvas-actions.service.ts, nifi-frontend/src/main/frontend/apps/nifi/src/app/pages/flow-designer/service/canvas-utils.service.ts, nifi-frontend/src/main/frontend/apps/nifi/src/app/pages/flow-designer/service/canvas-view.service.ts, nifi-frontend/src/main/frontend/apps/nifi/src/app/pages/flow-designer/service/copy-paste.service.ts, nifi-frontend/src/main/frontend/apps/nifi/src/app/pages/flow-designer/service/snippet.service.ts, nifi-frontend/src/main/frontend/apps/nifi/src/app/pages/flow-designer/state/flow/flow.actions.ts, nifi-frontend/src/main/frontend/apps/nifi/src/app/pages/flow-designer/state/flow/flow.effects.ts, nifi-frontend/src/main/frontend/apps/nifi/src/app/pages/flow-designer/state/flow/flow.reducer.ts, nifi-frontend/src/main/frontend/apps/nifi/src/app/pages/flow-designer/state/flow/flow.selectors.ts, nifi-frontend/src/main/frontend/apps/nifi/src/app/pages/flow-designer/state/flow/index.ts, nifi-frontend/src/main/frontend/apps/nifi/src/app/pages/flow-designer/ui/canvas/canvas.component.ts, nifi-frontend/src/main/frontend/apps/nifi/src/app/state/copy/copy.actions.ts, nifi-frontend/src/main/frontend/apps/nifi/src/app/state/copy/copy.effects.ts, nifi-frontend/src/main/frontend/apps/nifi/src/app/state/copy/copy.reducer.ts, nifi-frontend/src/main/frontend/apps/nifi/src/app/state/copy/copy.selectors.ts, nifi-frontend/src/main/frontend/apps/nifi/src/app/state/copy/index.ts, nifi-frontend/src/main/frontend/apps/nifi/src/app/state/index.ts, nifi-frontend/src/main/frontend/apps/nifi/src/app/state/shared/index.ts
* center pasted elements on screen. zoom out to fit them if needed
* offset pasted components if the originally copied content is still in view
[NIFI-13977](https://issues.apache.org/jira/browse/NIFI-13977)
_Review this in conjunction with the associated backend changes from PR #9535_
=> [NIFI-13977] - Updated Copy/Paste in UI to align with new backend API

nifi-commons/nifi-write-ahead-log/src/main/java/org/apache/nifi/wali/SnapshotRecovery.java, nifi-framework-bundle/nifi-framework-extensions/nifi-questdb-bundle/nifi-questdb/src/main/java/org/apache/nifi/questdb/mapping/RequestMappingBuilder.java, nifi-framework-bundle/nifi-framework/nifi-framework-nar-loading-utils/src/test/java/org/apache/nifi/nar/AbstractTestNarLoader.java
[NIFI-14069](https://issues.apache.org/jira/browse/NIFI-14069)
=> NIFI-14069 Replaced remaining explicit type arguments with diamonds.

nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-api/src/main/java/org/apache/nifi/web/StandardNiFiServiceFacade.java, nifi-frontend/src/main/frontend/.gitignore, nifi-frontend/src/main/frontend/apps/nifi/src/app/pages/flow-designer/state/flow/flow.actions.ts, nifi-frontend/src/main/frontend/apps/nifi/src/app/pages/flow-designer/state/flow/flow.effects.ts, nifi-frontend/src/main/frontend/apps/nifi/src/app/pages/flow-designer/state/flow/flow.reducer.ts, nifi-frontend/src/main/frontend/apps/nifi/src/app/pages/flow-designer/state/flow/flow.selectors.ts, nifi-frontend/src/main/frontend/apps/nifi/src/app/pages/flow-designer/state/flow/index.ts, nifi-frontend/src/main/frontend/apps/nifi/src/app/pages/flow-designer/ui/canvas/items/processor/edit-processor/_edit-processor.component-theme.scss, nifi-frontend/src/main/frontend/apps/nifi/src/app/pages/flow-designer/ui/canvas/items/processor/edit-processor/edit-processor.component.html, nifi-frontend/src/main/frontend/apps/nifi/src/app/pages/flow-designer/ui/canvas/items/processor/edit-processor/edit-processor.component.scss, nifi-frontend/src/main/frontend/apps/nifi/src/app/pages/flow-designer/ui/canvas/items/processor/edit-processor/edit-processor.component.ts, nifi-frontend/src/main/frontend/apps/nifi/src/app/service/client.service.ts, nifi-frontend/src/main/frontend/apps/nifi/src/styles.scss, nifi-frontend/src/main/frontend/libs/shared/src/assets/styles/_app.scss, nifi-frontend/src/main/frontend/libs/shared/src/services/session-storage.service.spec.ts, nifi-frontend/src/main/frontend/libs/shared/src/services/session-storage.service.ts
And for processors with invalid run status:
=> [NIFI-13318] processor stop and configure UX

nifi-docs/src/main/asciidoc/administration-guide.adoc
[NIFI-13865](https://issues.apache.org/jira/browse/NIFI-13865)
=> NIFI-13865: Add HeapDumpOnOutOfMemoryError description to Admin Guide

nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-api/src/main/java/org/apache/nifi/web/dao/impl/StandardLabelDAO.java
[NIFI-14072](https://issues.apache.org/jira/browse/NIFI-14072) - restore support for partial updates of labels
This PR restores the support for partial updates at labels level. It was removed in #9526. The logic is restored but moved in the DAO code that is not used when it comes to changing flow versions. This way proper behavior is restored and the fix from #9526 is maintained to not break flow versioning when style is changing.
=> NIFI-14072 - restore support for partial updates of labels

nifi-manifest/nifi-runtime-manifest/pom.xml
[NIFI-14098](https://issues.apache.org/jira/browse/NIFI-14098) Corrects the dependencies in `nifi-runtime-manifest` on the `nifi-assembly` package by introducing plugin-scoped dependencies, required for unpacking.
This change resolves dependency resolution issues when running a clean install with a new version of the project.
=> NIFI-14098 Correct runtime-manifest dependency on assembly packaging

nifi-commons/nifi-security-proxied-entity/src/main/java/org/apache/nifi/security/proxied/entity/StandardProxiedEntityEncoder.java
[NIFI-14103](https://issues.apache.org/jira/browse/NIFI-14103) Corrects the thread safety of `StandardProxiedEntityEncoder` by creating a new instance of `CharsetEncoder` for each method invocation. This change matches historical implementation approaches prior to the creation of `StandardProxiedEntityEncoder`.
=> NIFI-14103 Correct thread safety for Proxied Entity Encoder

nifi-framework-bundle/nifi-framework/nifi-framework-components/src/main/java/org/apache/nifi/controller/repository/StandardProcessSession.java, nifi-framework-bundle/nifi-framework/nifi-framework-components/src/main/java/org/apache/nifi/controller/repository/StandardProvenanceReporter.java, nifi-framework-bundle/nifi-framework/nifi-framework-components/src/test/java/org/apache/nifi/controller/repository/StandardProvenanceReporterTest.java
[NIFI-13808](https://issues.apache.org/jira/browse/NIFI-13808)
- [x ] [Apache NiFi Jira](https://issues.apache.org/jira/browse/NIFI) issue created
- [x ] Pull Request title starts with Apache NiFi Jira issue number, such as `NIFI-00000`
- [x ] Pull Request commit message starts with Apache NiFi Jira issue number, as such `NIFI-00000`
- [ x] Pull Request based on current revision of the `main` branch
- [x ] Pull Request refers to a feature branch with one commit containing changes
Tested clone event with Python Processor.  Send event with PutFile Processor.
=> NIFI-13808: Record attributes and content for clone, upload and send.

nifi-extension-bundles/nifi-amqp-bundle/nifi-amqp-processors/src/test/java/org/apache/nifi/amqp/processors/AMQPConsumerTest.java, nifi-extension-bundles/nifi-amqp-bundle/nifi-amqp-processors/src/test/java/org/apache/nifi/amqp/processors/AMQPPublisherTest.java
[NIFI-14148](https://issues.apache.org/jira/browse/NIFI-14148)
=> NIFI-14148 | typofix: Successfull -> Successful

nifi-extension-bundles/nifi-standard-bundle/nifi-standard-processors/src/main/java/org/apache/nifi/processors/standard/ssh/StandardSSHClient.java, nifi-extension-bundles/nifi-standard-bundle/nifi-standard-processors/src/main/java/org/apache/nifi/processors/standard/ssh/StandardSSHClientProvider.java, nifi-extension-bundles/nifi-standard-bundle/nifi-standard-processors/src/test/java/org/apache/nifi/processors/standard/ssh/StandardSSHClientTest.java
[NIFI-14068](https://issues.apache.org/jira/browse/NIFI-14068) Corrects the behavior of SFTP processors when configured for proxy access using a DNS name.
The current implementation of the SSHJ `SSHClient` always attempts to resolve DNS names to IP addresses when constructing an `InetSocketAddress` for the socket connection. This behavior is not ideal when connecting through a proxy server because NiFi may not be able to resolve the DNS address and should rely on the proxy server to perform DNS resolution.
The revised implementation introduces an extension of `SSHClient` that overrides the `makeInetSocketAddress` method to return an unresolved address when the client is configured with a Proxy Socket Factory. The unresolved status instructs HTTP and SOCKS proxy socket clients to send a …
=> NIFI-14068 Fix Domain Name Handling for SFTP Proxy Access

nifi-code-coverage/pom.xml, nifi-commons/nifi-metrics/pom.xml, nifi-extension-bundles/nifi-azure-bundle/nifi-azure-processors/pom.xml, nifi-extension-bundles/nifi-box-bundle/pom.xml, nifi-extension-bundles/nifi-extension-utils/nifi-record-utils/nifi-standard-record-utils/pom.xml, nifi-extension-bundles/nifi-gcp-bundle/pom.xml, nifi-extension-bundles/nifi-jms-bundle/nifi-jms-processors/pom.xml, nifi-extension-bundles/nifi-media-bundle/pom.xml, nifi-extension-bundles/nifi-redis-bundle/pom.xml, nifi-extension-bundles/nifi-registry-bundle/nifi-registry-service/pom.xml, nifi-extension-bundles/nifi-salesforce-bundle/nifi-salesforce-processors/pom.xml, nifi-extension-bundles/nifi-slack-bundle/nifi-slack-processors/pom.xml, nifi-extension-bundles/nifi-standard-bundle/nifi-standard-processors/pom.xml, nifi-extension-bundles/nifi-standard-bundle/pom.xml, nifi-extension-bundles/nifi-standard-services/nifi-lookup-services-bundle/nifi-lookup-services/pom.xml, nifi-extension-bundles/nifi-standard-services/nifi-record-serialization-services-bundle/nifi-record-serialization-services/pom.xml, nifi-framework-bundle/nifi-framework-extensions/nifi-py4j-framework-bundle/nifi-python-framework/pom.xml, nifi-framework-bundle/pom.xml, nifi-registry/nifi-registry-core/nifi-registry-test/pom.xml, nifi-registry/pom.xml, nifi-toolkit/nifi-toolkit-cli/pom.xml, pom.xml
[NIFI-14187](https://issues.apache.org/jira/browse/NIFI-14187) - Dep Upgrades - Spring, Netty, Bouncycastle, Flyway, AWS, GCP, etc
- AWS SDK v2 from 2.29.48 to 2.30.3 - https://github.com/aws/aws-sdk-java-v2/blob/master/CHANGELOG.md
- Spring Framework from 6.2.1 to 6.2.2 - https://github.com/spring-projects/spring-framework/releases
- ~~Spring Data Redis from 3.4.1 to 3.4.2 - https://github.com/spring-projects/spring-data-redis/releases~~
- PostgreSQL from 42.7.4 to 42.7.5 - https://jdbc.postgresql.org/changelogs/2025-01-14-42.7.5-release/
- MIME4J from 0.8.11 to 0.8.12 - https://github.com/apache/james-mime4j/compare/apache-mime4j-project-0.8.11...apache-mime4j-project-0.8.12
- Reactor Netty HTTP from 1.2.1 to 1.2.2 - https://github.com/reactor/reactor-netty/releases
- Reactor Core from …
=> NIFI-14187 - Dep Upgrades - Spring, Netty, Flyway, AWS, GCP, etc

nifi-toolkit/nifi-toolkit-cli/src/main/java/org/apache/nifi/toolkit/cli/impl/command/nifi/pg/PGImport.java, nifi-toolkit/nifi-toolkit-client/pom.xml, nifi-toolkit/nifi-toolkit-client/src/main/java/org/apache/nifi/toolkit/client/ProcessGroupClient.java, nifi-toolkit/nifi-toolkit-client/src/main/java/org/apache/nifi/toolkit/client/impl/JerseyProcessGroupClient.java
[NIFI-14134](https://issues.apache.org/jira/browse/NIFI-14134) - add support for JSON file upload to CLI pg-import
Currently, in the CLI,
````bash
./cli.sh nifi pg-import
````
only supports creating a process group based on references to a versioned flow through a Registry Client.
In, the UI, it is possible to drag and drop a process group onto the canvas and provide a JSON file definition to create a new process group based on the flow definition. This approach should also be supported by the CLI command `pg-import`.
With this change, it is now possible to execute a command like below:
````bash
$ ./bin/cli.sh nifi pg-import -i /my/flow.json -p nifi-cli.properties
42357e56-0194-1000-7b1f-ba830cac1de6
````
And it returns the UUID of the process group created with the uploaded JSON flow …
=> NIFI-14134 - add support for JSON file upload to CLI pg-import

nifi-extension-bundles/nifi-scripting-bundle/nifi-scripting-processors/src/main/java/org/apache/nifi/processors/script/InvokeScriptedProcessor.java, nifi-extension-bundles/nifi-scripting-bundle/nifi-scripting-processors/src/test/java/org/apache/nifi/processors/script/TestInvokeGroovy.java, nifi-extension-bundles/nifi-scripting-bundle/nifi-scripting-processors/src/test/resources/groovy/test_OnPrimaryStateChange.groovy, nifi-mock/src/main/java/org/apache/nifi/util/StandardProcessorTestRunner.java
[NIFI-14157](https://issues.apache.org/jira/browse/NIFI-14157) This PR adds the ability for scripts in InvokeScriptedProcessor to implement a method `onPrimaryNodeStateChange` to be able to process when the primary node changes.
=> NIFI-14157: Allow InvokeScriptedProcessor scripts to implement OnPrimaryNodeStateChange

nifi-frontend/src/main/frontend/apps/nifi/src/app/pages/queue/ui/queue-listing/flowfile-dialog/flowfile-dialog.component.html, nifi-frontend/src/main/frontend/apps/nifi/src/app/ui/common/provenance-event-dialog/provenance-event-dialog.component.html
=> [NIFI-13968] add title tooltip for truncated attribute values

nifi-frontend/src/main/frontend/apps/nifi/src/app/pages/flow-designer/service/manager/process-group-manager.service.ts, nifi-frontend/src/main/frontend/apps/nifi/src/app/pages/flow-designer/state/flow/flow.actions.ts, nifi-frontend/src/main/frontend/apps/nifi/src/app/pages/flow-designer/state/flow/flow.effects.ts, nifi-frontend/src/main/frontend/apps/nifi/src/app/pages/flow-designer/state/flow/flow.reducer.ts, nifi-frontend/src/main/frontend/apps/nifi/src/app/pages/flow-designer/state/flow/flow.selectors.ts, nifi-frontend/src/main/frontend/apps/nifi/src/app/pages/flow-designer/state/flow/index.ts, nifi-frontend/src/main/frontend/apps/nifi/src/app/pages/flow-designer/ui/canvas/items/flow/import-from-registry/import-from-registry.component.ts, nifi-frontend/src/main/frontend/apps/nifi/src/app/pages/flow-designer/ui/canvas/items/flow/save-version-dialog/save-version-dialog.component.ts, nifi-frontend/src/main/frontend/apps/nifi/src/app/pages/flow-designer/ui/common/tooltips/version-control-tip/version-control-tip.component.html, nifi-frontend/src/main/frontend/apps/nifi/src/app/pages/flow-designer/ui/common/tooltips/version-control-tip/version-control-tip.component.ts
[NIFI-14042](https://issues.apache.org/jira/browse/NIFI-14042)
* Updated the version control tooltip to be more detailed
* If the backing registry client supports branching, display the branch as part of the updated tooltip
* Fixed bugs in other registry-related dialogs where they would attempt to access registry client data that wasn't readable due to permissions (no "view" for "access to the controller"). Now, registry clients that aren't readable are not included.
=> [NIFI-14042] - Display the branch information for version controlled Process Groups

nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-security/src/test/java/org/apache/nifi/web/security/saml2/registration/StandardRelyingPartyRegistrationRepositoryTest.java, nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-security/src/test/java/org/apache/nifi/web/security/saml2/service/web/StandardRelyingPartyRegistrationResolverTest.java, nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-security/src/test/java/org/apache/nifi/web/security/saml2/service/web/StandardSaml2AuthenticationRequestRepositoryTest.java, nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-security/src/test/java/org/apache/nifi/web/security/saml2/web/authentication/logout/StandardSaml2LogoutRequestRepositoryTest.java
[NIFI-14227](https://issues.apache.org/jira/browse/NIFI-14227)
=> NIFI-14227 Replaced the deprecated methods in RelyingPartyRegistration with suggested replacements

nifi-frontend/src/main/frontend/apps/nifi/src/app/pages/documentation/feature/documentation.component.ts, nifi-frontend/src/main/frontend/package-lock.json
[NIFI-14239](https://issues.apache.org/jira/browse/NIFI-14239)
Regenerated the package-lock.json file: it now includes the missing dependencies for windows-specific builds as described in https://github.com/nrwl/nx/issues/29551.
Also ran prettier:fix and it found a minor thing in the doc component that is included here.
=> [NIFI-14239] - Address Windows build failures of the frontend

nifi-extension-bundles/nifi-elasticsearch-bundle/nifi-elasticsearch-client-service-api/pom.xml, nifi-extension-bundles/nifi-elasticsearch-bundle/nifi-elasticsearch-client-service-api/src/main/java/org/apache/nifi/elasticsearch/AuthorizationScheme.java, nifi-extension-bundles/nifi-elasticsearch-bundle/nifi-elasticsearch-client-service-api/src/main/java/org/apache/nifi/elasticsearch/ElasticSearchClientService.java, nifi-extension-bundles/nifi-elasticsearch-bundle/nifi-elasticsearch-client-service/pom.xml, nifi-extension-bundles/nifi-elasticsearch-bundle/nifi-elasticsearch-client-service/src/main/java/org/apache/nifi/elasticsearch/ElasticSearchClientServiceImpl.java, nifi-extension-bundles/nifi-elasticsearch-bundle/nifi-elasticsearch-client-service/src/main/java/org/apache/nifi/elasticsearch/ElasticSearchLookupService.java, nifi-extension-bundles/nifi-elasticsearch-bundle/nifi-elasticsearch-client-service/src/test/java/org/apache/nifi/elasticsearch/integration/ElasticSearchClientService_IT.java, nifi-extension-bundles/nifi-elasticsearch-bundle/nifi-elasticsearch-client-service/src/test/java/org/apache/nifi/elasticsearch/integration/ElasticSearchLookupService_IT.java, nifi-extension-bundles/nifi-elasticsearch-bundle/nifi-elasticsearch-client-service/src/test/java/org/apache/nifi/elasticsearch/unit/ElasticSearchClientServiceImplTest.java, nifi-extension-bundles/nifi-elasticsearch-bundle/nifi-elasticsearch-client-service/src/test/java/org/apache/nifi/elasticsearch/unit/ElasticSearchStringLookupServiceTest.java, nifi-extension-bundles/nifi-elasticsearch-bundle/nifi-elasticsearch-restapi-processors/pom.xml, nifi-extension-bundles/nifi-elasticsearch-bundle/nifi-elasticsearch-test-utils/pom.xml, nifi-extension-bundles/nifi-elasticsearch-bundle/nifi-elasticsearch-test-utils/src/main/java/org/apache/nifi/elasticsearch/integration/AbstractElasticsearchITBase.java, nifi-extension-bundles/nifi-elasticsearch-bundle/pom.xml
[NIFI-10831](https://issues.apache.org/jira/browse/NIFI-10831) enable JWT realm authentication with Elasticsearch.
Also allow for setting of `runas_user` in the Elasticsearch Controller Service, which may be of use to impersonate a user within Elasticsearch from NiFi, without having the user's credentials (but where the connecting NiFi user/token is granted permission to impersonate the alternate user).
Other changes include:
- removing unused dependencies from Elasticsearch component POMs
Testing:
- Attempted to verify changes using LogTo.io as an OIDC and JWT IdP, but it turns out that LogTo provides Access Token JWTs with a `typ` of `at+jwt`, which Elasticsearch cannot currently handle (https://github.com/elastic/elasticsearch/issues/119370)
- Verified using Keycloak instead (with a …
=> NIFI-10831 enable JWT realm authentication with Elasticsearch

nifi-toolkit/nifi-toolkit-client/src/main/java/org/apache/nifi/toolkit/client/ProvenanceClient.java, nifi-toolkit/nifi-toolkit-client/src/main/java/org/apache/nifi/toolkit/client/impl/JerseyProvenanceClient.java
[NIFI-14215](https://issues.apache.org/jira/browse/NIFI-14215) - nifi-client - retrieve input/output content via provenance data
=> NIFI-14215 - nifi-client - retrieve input/output content via provenance data

nifi-assembly/NOTICE, nifi-framework-bundle/nifi-framework-nar/src/main/resources/META-INF/NOTICE, nifi-framework-bundle/nifi-framework/nifi-framework-core/src/main/java/org/apache/nifi/controller/queue/clustered/partition/CorrelationAttributePartitioner.java, nifi-framework-bundle/nifi-framework/nifi-framework-core/src/test/java/org/apache/nifi/controller/queue/clustered/partition/CorrelationAttributeParserTest.java, nifi-framework-bundle/nifi-framework/nifi-framework-core/src/test/java/org/apache/nifi/controller/queue/clustered/partition/CorrelationAttributePartitionerTest.java
[NIFI-14236](https://issues.apache.org/jira/browse/NIFI-14236) Implements consistent hashing for FlowFile Attribute-based partitioning in the Correlation Attribute Partitioner. The changes restore the original behavior prior to NiFi 1.16.0 based on the Google Guava [Hashing.consistentHash](https://github.com/google/guava/blob/master/guava/src/com/google/common/hash/Hashing.java) method.
The implementation copies the `LinearCongruentialGenerator` class from Google Guava and updates applicable `NOTICE` files to avoid bringing in the Google Guava dependency.
Changes include a new unit test to validate expected results for attribute values. …
=> NIFI-14236 Implement consistent hash for Attribute Partitioner

nifi-commons/nifi-xml-processing/pom.xml, nifi-extension-bundles/nifi-amqp-bundle/nifi-amqp-processors/pom.xml, nifi-extension-bundles/nifi-aws-bundle/pom.xml, nifi-extension-bundles/nifi-azure-bundle/nifi-azure-processors/pom.xml, nifi-extension-bundles/nifi-azure-bundle/pom.xml, nifi-extension-bundles/nifi-email-bundle/nifi-email-processors/pom.xml, nifi-extension-bundles/nifi-gcp-bundle/nifi-gcp-processors/pom.xml, nifi-extension-bundles/nifi-gcp-bundle/pom.xml, nifi-extension-bundles/nifi-graph-bundle/nifi-graph-test-clients/pom.xml, nifi-extension-bundles/nifi-graph-bundle/nifi-graph-test-clients/src/main/java/org/apache/commons/lang/NotImplementedException.java, nifi-extension-bundles/nifi-graph-bundle/nifi-neo4j-cypher-service/pom.xml, nifi-extension-bundles/nifi-media-bundle/nifi-media-processors/pom.xml, nifi-extension-bundles/nifi-parquet-bundle/nifi-parquet-processors/pom.xml, nifi-extension-bundles/nifi-protobuf-bundle/nifi-protobuf-services/pom.xml, nifi-extension-bundles/nifi-slack-bundle/nifi-slack-processors/pom.xml, nifi-extension-bundles/nifi-snmp-bundle/nifi-snmp-processors/pom.xml, nifi-extension-bundles/nifi-standard-bundle/nifi-standard-processors/pom.xml, nifi-extension-bundles/nifi-standard-bundle/nifi-standard-processors/src/main/java/org/apache/nifi/processors/standard/ftp/NifiFtpServer.java, nifi-extension-bundles/nifi-standard-bundle/pom.xml, nifi-extension-bundles/nifi-standard-services/nifi-lookup-services-bundle/nifi-lookup-services/pom.xml, nifi-extension-bundles/nifi-standard-services/nifi-oauth2-provider-bundle/nifi-oauth2-provider-service/pom.xml, nifi-extension-bundles/nifi-standard-services/nifi-record-serialization-services-bundle/nifi-record-serialization-services/pom.xml, nifi-registry/pom.xml, nifi-toolkit/nifi-toolkit-cli/pom.xml, pom.xml
[NIFI-14253](https://issues.apache.org/jira/browse/NIFI-14253) - Dependency housekeeping - AWS, Azure, GCP, Tika, Slack, FTP, Parquet, etc
- spotbugs-maven-plugin from 4.8.5.0 to 4.8.6.6 - https://github.com/spotbugs/spotbugs-maven-plugin/releases
- AMQP client from 5.24.0 to 5.25.0 - https://github.com/rabbitmq/rabbitmq-java-client/releases
- AWS Kinesis client from 2.6.0 to 2.6.1 - https://github.com/awslabs/amazon-kinesis-client/releases
- Kusto from 5.1.1 to 5.2.0 - https://github.com/Azure/azure-kusto-java/releases/tag/v5.2.0
- Azure BOM from 1.2.30 to 1.2.31 - https://github.com/Azure/azure-sdk-for-java/blob/main/sdk/boms/azure-sdk-bom/CHANGELOG.md
- MSAL4J from 1.17.2 to 1.17.3 - https://github.com/AzureAD/microsoft-authentication-library-for-java/releases/tag/v1.17.3
- Greenmail …
=> NIFI-14253 - Dependency housekeeping - AWS, Azure, GCP, Tika, Slack, FTP, Parquet, etc

nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-api/src/main/java/org/apache/nifi/web/api/ParameterContextResource.java
[NIFI-14256](https://issues.apache.org/jira/browse/NIFI-14256) - Cannot update parameter that references no longer existing controller service
=> NIFI-14256 - Cannot update parameter that references no longer existing controller service

nifi-extension-bundles/nifi-groovyx-bundle/nifi-groovyx-processors/pom.xml, nifi-extension-bundles/nifi-groovyx-bundle/nifi-groovyx-processors/src/main/java/org/apache/nifi/processors/groovyx/ExecuteGroovyScript.java, nifi-extension-bundles/nifi-groovyx-bundle/nifi-groovyx-processors/src/test/java/org/apache/nifi/processors/groovyx/ExecuteGroovyScriptTest.java, nifi-extension-bundles/nifi-groovyx-bundle/nifi-groovyx-processors/src/test/resources/groovy/test_attributes_passed_to_SQL.groovy
[NIFI-5579](https://issues.apache.org/jira/browse/NIFI-5579) This PR allows ExecuteGroovyScript to use DBCPConnectionPoolLookup controller service(s) by passing in any available attributes
=> NIFI-5579: Allow ExecuteGroovyScript to DBCPConnectionLookup services

nifi-frontend/src/main/frontend/apps/nifi/src/app/pages/flow-designer/service/canvas-utils.service.ts, nifi-frontend/src/main/frontend/apps/nifi/src/app/pages/flow-designer/state/flow/flow.actions.ts, nifi-frontend/src/main/frontend/apps/nifi/src/app/pages/flow-designer/state/flow/flow.effects.ts, nifi-frontend/src/main/frontend/apps/nifi/src/app/pages/flow-designer/ui/canvas/canvas.component.ts, nifi-frontend/src/main/frontend/apps/nifi/src/app/pages/flow-designer/ui/canvas/graph-controls/operation-control/operation-control.component.html, nifi-frontend/src/main/frontend/apps/nifi/src/app/pages/flow-designer/ui/canvas/graph-controls/operation-control/operation-control.component.ts, nifi-frontend/src/main/frontend/libs/shared/src/directives/copy/copy.directive.spec.ts, nifi-frontend/src/main/frontend/libs/shared/src/directives/copy/copy.directive.ts
[NIFI-14237](https://issues.apache.org/jira/browse/NIFI-14237) - Disable copy when system clipboard is not available
[NIFI-14249](https://issues.apache.org/jira/browse/NIFI-14249) - Remove paste from operation panel as only keyboard shortcuts allow for paste.
Also removed the copy effect as it is not used and can not be used due to it making the copy asynchronous, a potential security issue prevented by browsers without explicit acceptance.
=> [NIFI-14327][NIFI-14249] - Copy/Paste handling when clipboard is not available

nifi-extension-bundles/nifi-standard-bundle/nifi-standard-processors/src/main/java/org/apache/nifi/processors/standard/UpdateDatabaseTable.java, nifi-extension-bundles/nifi-standard-bundle/nifi-standard-processors/src/main/java/org/apache/nifi/processors/standard/db/DatabaseAdapter.java, nifi-extension-bundles/nifi-standard-bundle/nifi-standard-processors/src/main/java/org/apache/nifi/processors/standard/db/DatabaseAdapterDatabaseDialectService.java, nifi-extension-bundles/nifi-standard-bundle/nifi-standard-processors/src/main/java/org/apache/nifi/processors/standard/db/impl/MSSQLDatabaseAdapter.java, nifi-extension-bundles/nifi-standard-bundle/nifi-standard-processors/src/main/java/org/apache/nifi/processors/standard/db/impl/MySQLDatabaseAdapter.java, nifi-extension-bundles/nifi-standard-bundle/nifi-standard-processors/src/main/java/org/apache/nifi/processors/standard/db/impl/Oracle12DatabaseAdapter.java, nifi-extension-bundles/nifi-standard-bundle/nifi-standard-processors/src/main/java/org/apache/nifi/processors/standard/db/impl/OracleDatabaseAdapter.java, nifi-extension-bundles/nifi-standard-bundle/nifi-standard-processors/src/main/java/org/apache/nifi/processors/standard/db/impl/PhoenixDatabaseAdapter.java, nifi-extension-bundles/nifi-standard-bundle/nifi-standard-processors/src/main/java/org/apache/nifi/processors/standard/db/impl/PostgreSQLDatabaseAdapter.java, nifi-extension-bundles/nifi-standard-bundle/nifi-standard-processors/src/test/java/org/apache/nifi/processors/standard/db/impl/DerbyDatabaseAdapter.java, nifi-extension-bundles/nifi-standard-bundle/nifi-standard-processors/src/test/java/org/apache/nifi/processors/standard/db/impl/TestOracle12DatabaseAdapter.java, nifi-extension-bundles/nifi-standard-bundle/nifi-standard-processors/src/test/java/org/apache/nifi/processors/standard/db/impl/TestOracleDatabaseAdapter.java
[NIFI-14275](https://issues.apache.org/jira/browse/NIFI-14275)
The decision about quoting column names during ALTER TABLE in the UpdateDatabaseTable processor was moved to database dialect services, causing inconsistency in behavior. This logic should remain part of the `UpdateDatabaseTable` processor, where users can explicitly choose whether to quote table and column names via the `QUOTE_COLUMN_IDENTIFIERS` and `QUOTE_TABLE_IDENTIFIER` properties.
=> NIFI-14275 Fix quoting configuration handling in UpdateDatabaseTable during ALTER

nifi-extension-bundles/nifi-aws-bundle/nifi-aws-processors/src/main/java/org/apache/nifi/processors/aws/credentials/provider/factory/strategies/ExplicitDefaultCredentialsStrategy.java, nifi-extension-bundles/nifi-aws-bundle/nifi-aws-processors/src/main/java/org/apache/nifi/processors/aws/credentials/provider/factory/strategies/ImplicitDefaultCredentialsStrategy.java, nifi-registry/nifi-registry-extensions/nifi-registry-aws/nifi-registry-aws-extensions/src/main/java/org/apache/nifi/registry/aws/S3BundlePersistenceProvider.java
[NIFI-12836](https://issues.apache.org/jira/browse/NIFI-12836) re-create AWS DefaultCredentialsProvider for AWS SDK v2 processors and connections
- ~[ ] New dependencies are compatible with the [Apache License 2.0](https://apache.org/licenses/LICENSE-2.0) according to the [License Policy](https://www.apache.org/legal/resolved.html)~
- ~[ ] New dependencies are documented in applicable `LICENSE` and `NOTICE` files~
- ~[ ] Documentation formatting appears as expected in rendered files~
=> NIFI-12836 re-create AWS DefaultCredentialsProvider for AWS SDK v2 processors and connections

nifi-extension-bundles/nifi-aws-bundle/nifi-aws-processors/src/main/java/org/apache/nifi/processors/aws/kinesis/stream/ConsumeKinesisStream.java
[NIFI-14283](https://issues.apache.org/jira/browse/NIFI-14283)
=> NIFI-14283 ConsumeKinesisStream non-static workerLock

nifi-extension-bundles/nifi-aws-bundle/nifi-aws-processors/src/main/java/org/apache/nifi/processors/aws/kinesis/stream/ConsumeKinesisStream.java
[NIFI-14284](https://issues.apache.org/jira/browse/NIFI-14284)
=> NIFI-14284 ConsumeKinesisStream migrate property names to new convention

nifi-commons/nifi-record/src/main/java/org/apache/nifi/serialization/record/field/ObjectLocalDateTimeFieldConverter.java, nifi-commons/nifi-record/src/test/java/org/apache/nifi/serialization/record/field/ObjectTimestampFieldConverterTest.java
[NIFI-14296](https://issues.apache.org/jira/browse/NIFI-14296) Corrects conversion from `java.sql.Timestamp` to `java.time.LocalDateTime` to ensure that nanosecond precision is retained.
The resolution adds specific handling for `java.sql.Timestamp` and uses the `toInstant()` method which retains nanosecond precision.
Additional unit tests verify the updated behavior and also add checks for `java.sql.Date` and `java.sql.Time` to confirm expected behavior for classes that do not support the `toInstant()` method.
=> NIFI-14296 Fix Timestamp to LocalDateTime nanosecond handling

nifi-extension-bundles/nifi-standard-bundle/nifi-standard-processors/src/main/java/org/apache/nifi/processors/standard/AbstractExecuteSQL.java, nifi-extension-bundles/nifi-standard-bundle/nifi-standard-processors/src/main/java/org/apache/nifi/processors/standard/ExecuteSQL.java, nifi-extension-bundles/nifi-standard-bundle/nifi-standard-processors/src/main/java/org/apache/nifi/processors/standard/ExecuteSQLRecord.java, nifi-extension-bundles/nifi-standard-bundle/nifi-standard-processors/src/test/java/org/apache/nifi/processors/standard/TestExecuteSQL.java, nifi-extension-bundles/nifi-standard-bundle/nifi-standard-processors/src/test/java/org/apache/nifi/processors/standard/TestExecuteSQLRecord.java
[NIFI-14266](https://issues.apache.org/jira/browse/NIFI-14266) - Allow ExecuteSQL to not overwrite flowfile content when no result
The ExecuteSQL processor may be used in a flow definition to execute SQL statements such as TRUNCATE TABLE, DROP TABLE, etc. While there is the option to use pre/post queries, it might not always be an option to have everything executed within the same processor. In such a scenario, it might be needed to not change the content of the FlowFile.
This improvement adds a property allowing a user to specify that the FlowFile's content should remain untouched when the execution of the query does not generate any result and, of course, when the processor was triggered by an incoming FlowFile.
Please complete the following tracking steps prior to pull request …
=> NIFI-14266 - Allow ExecuteSQL to not overwrite flowfile content when no result

nifi-extension-bundles/nifi-aws-bundle/nifi-aws-abstract-processors/src/main/java/org/apache/nifi/processors/aws/s3/AbstractS3Processor.java, nifi-extension-bundles/nifi-aws-bundle/nifi-aws-processors/src/main/java/org/apache/nifi/processors/aws/s3/CopyS3Object.java, nifi-extension-bundles/nifi-aws-bundle/nifi-aws-processors/src/main/java/org/apache/nifi/processors/aws/s3/DeleteS3Object.java, nifi-extension-bundles/nifi-aws-bundle/nifi-aws-processors/src/main/java/org/apache/nifi/processors/aws/s3/FetchS3Object.java, nifi-extension-bundles/nifi-aws-bundle/nifi-aws-processors/src/main/java/org/apache/nifi/processors/aws/s3/GetS3ObjectMetadata.java, nifi-extension-bundles/nifi-aws-bundle/nifi-aws-processors/src/main/java/org/apache/nifi/processors/aws/s3/GetS3ObjectTags.java, nifi-extension-bundles/nifi-aws-bundle/nifi-aws-processors/src/main/java/org/apache/nifi/processors/aws/s3/ListS3.java, nifi-extension-bundles/nifi-aws-bundle/nifi-aws-processors/src/main/java/org/apache/nifi/processors/aws/s3/PutS3Object.java, nifi-extension-bundles/nifi-aws-bundle/nifi-aws-processors/src/main/java/org/apache/nifi/processors/aws/s3/TagS3Object.java, nifi-extension-bundles/nifi-aws-bundle/nifi-aws-processors/src/main/java/org/apache/nifi/processors/aws/s3/api/MetadataTarget.java, nifi-extension-bundles/nifi-aws-bundle/nifi-aws-processors/src/main/java/org/apache/nifi/processors/aws/s3/api/TagsTarget.java, nifi-extension-bundles/nifi-aws-bundle/nifi-aws-processors/src/main/resources/META-INF/services/org.apache.nifi.processor.Processor, nifi-extension-bundles/nifi-aws-bundle/nifi-aws-processors/src/test/java/org/apache/nifi/processors/aws/s3/TestGetS3ObjectMetadata.java, nifi-extension-bundles/nifi-aws-bundle/nifi-aws-processors/src/test/java/org/apache/nifi/processors/aws/s3/TestGetS3ObjectTags.java
[NIFI-14288](https://issues.apache.org/jira/browse/NIFI-14288) fetch S3 Object Tags
- ~[ ] New dependencies are compatible with the [Apache License 2.0](https://apache.org/licenses/LICENSE-2.0) according to the [License Policy](https://www.apache.org/legal/resolved.html)~
- ~[ ] New dependencies are documented in applicable `LICENSE` and `NOTICE` files~
- ~[ ] Documentation formatting appears as expected in rendered files~
=> NIFI-14288 fetch S3 Object Tags

nifi-framework-bundle/nifi-framework-extensions/nifi-provenance-repository-bundle/nifi-persistent-provenance-repository/src/main/java/org/apache/nifi/provenance/store/WriteAheadStorePartition.java
Add a check to WriteAheadStorePartition to see if the file exists before logging a message and deleting
[NIFI-14111](https://issues.apache.org/jira/browse/NIFI-14111)
=> NIFI-14111 Add a check to WriteAheadStorePartition

nifi-docs/src/main/asciidoc/user-guide.adoc, nifi-extension-bundles/nifi-elasticsearch-bundle/nifi-elasticsearch-client-service/src/test/java/org/apache/nifi/elasticsearch/integration/AbstractElasticsearch_IT.java, nifi-extension-bundles/nifi-elasticsearch-bundle/nifi-elasticsearch-restapi-processors/src/main/java/org/apache/nifi/processors/elasticsearch/AbstractPutElasticsearch.java, nifi-extension-bundles/nifi-elasticsearch-bundle/nifi-elasticsearch-restapi-processors/src/main/java/org/apache/nifi/processors/elasticsearch/PutElasticsearchRecord.java, nifi-extension-bundles/nifi-elasticsearch-bundle/nifi-elasticsearch-restapi-processors/src/test/java/org/apache/nifi/processors/elasticsearch/PutElasticsearchJsonTest.java, nifi-extension-bundles/nifi-elasticsearch-bundle/nifi-elasticsearch-restapi-processors/src/test/java/org/apache/nifi/processors/elasticsearch/PutElasticsearchRecordTest.java, nifi-extension-bundles/nifi-elasticsearch-bundle/nifi-elasticsearch-restapi-processors/src/test/java/org/apache/nifi/processors/elasticsearch/integration/AbstractElasticsearch_IT.java, nifi-extension-bundles/nifi-elasticsearch-bundle/nifi-elasticsearch-restapi-processors/src/test/java/org/apache/nifi/processors/elasticsearch/integration/PutElasticsearchRecord_IT.java, nifi-extension-bundles/nifi-elasticsearch-bundle/nifi-elasticsearch-restapi-processors/src/test/java/org/apache/nifi/processors/elasticsearch/mock/AbstractMockElasticsearchClient.java, nifi-extension-bundles/nifi-elasticsearch-bundle/nifi-elasticsearch-restapi-processors/src/test/java/org/apache/nifi/processors/elasticsearch/mock/MockBulkLoadClientService.java, nifi-extension-bundles/nifi-elasticsearch-bundle/nifi-elasticsearch-test-utils/src/main/java/org/apache/nifi/elasticsearch/integration/AbstractElasticsearchITBase.java, nifi-extension-bundles/nifi-elasticsearch-bundle/pom.xml, nifi-mock/src/main/java/org/apache/nifi/util/MockProcessSession.java, nifi-mock/src/main/java/org/apache/nifi/util/MockSessionFactory.java, nifi-mock/src/main/java/org/apache/nifi/util/StandardProcessorTestRunner.java, nifi-mock/src/main/java/org/apache/nifi/util/TestRunner.java
[NIFI-14244](https://issues.apache.org/jira/browse/NIFI-14244) send original Records to errors output for PutElasticsearchRecord errors
Additional changes:
- update the `MockProcessSession` to allow for `recursive read` of a FlowFile (similar to the `StandardProcessSession` allows)
- rationalise `retriable` to `retryable`
- ~[ ] New dependencies are compatible with the [Apache License 2.0](https://apache.org/licenses/LICENSE-2.0) according to the [License Policy](https://www.apache.org/legal/resolved.html)~
- ~[ ] New dependencies are documented in applicable `LICENSE` and `NOTICE` files~
=> NIFI-14244 send original Records to errors output for PutElasticsearchRecord errors

nifi-frontend/src/main/frontend/apps/nifi/src/app/pages/flow-designer/state/flow/flow.effects.ts, nifi-frontend/src/main/frontend/apps/nifi/src/app/pages/flow-designer/ui/canvas/items/flow/change-version-progress-dialog/change-version-progress-dialog.html, nifi-frontend/src/main/frontend/apps/nifi/src/app/pages/flow-designer/ui/canvas/items/flow/change-version-progress-dialog/change-version-progress-dialog.ts, nifi-frontend/src/main/frontend/apps/nifi/src/app/ui/common/error-banner/error-banner.component.html, nifi-frontend/src/main/frontend/apps/nifi/src/app/ui/common/error-banner/error-banner.component.scss, nifi-frontend/src/main/frontend/apps/nifi/src/app/ui/common/error-banner/error-banner.component.ts
[NIFI-14317](https://issues.apache.org/jira/browse/NIFI-14317)
_Verification Note:_ You can force the error banner to appear when changing a flow version by modifying `FlowUpdateResource.java#createUpdateRequestResponse` to return a failureReason and setting complete to true.
From:
```
updateRequestDto.setComplete(asyncRequest.isComplete());
updateRequestDto.setFailureReason(asyncRequest.getFailureReason());
```
To: 
```
updateRequestDto.setComplete(true);
updateRequestDto.setFailureReason("There was an error");
```
=> [NIFI-14317] - Handle flow version change failure by displaying the failure reason in an error banner

nifi-extension-bundles/nifi-aws-bundle/nifi-aws-abstract-processors/src/main/java/org/apache/nifi/processors/aws/v2/AbstractAwsAsyncProcessor.java, nifi-extension-bundles/nifi-aws-bundle/nifi-aws-abstract-processors/src/main/java/org/apache/nifi/processors/aws/v2/AbstractAwsProcessor.java, nifi-extension-bundles/nifi-aws-bundle/nifi-aws-abstract-processors/src/main/java/org/apache/nifi/processors/aws/v2/AbstractAwsSyncProcessor.java, nifi-extension-bundles/nifi-aws-bundle/nifi-aws-processors/src/main/java/org/apache/nifi/processors/aws/kinesis/stream/ConsumeKinesisStream.java
[NIFI-14301](https://issues.apache.org/jira/browse/NIFI-14301)
=> NIFI-14301 ConsumeKinesisStream HTTPClient maxConcurrency increase

nifi-extension-bundles/nifi-aws-bundle/nifi-aws-processors/src/main/java/org/apache/nifi/processors/aws/kinesis/property/OutputStrategy.java, nifi-extension-bundles/nifi-aws-bundle/nifi-aws-processors/src/main/java/org/apache/nifi/processors/aws/kinesis/stream/ConsumeKinesisStream.java, nifi-extension-bundles/nifi-aws-bundle/nifi-aws-processors/src/main/java/org/apache/nifi/processors/aws/kinesis/stream/record/AbstractKinesisRecordProcessor.java, nifi-extension-bundles/nifi-aws-bundle/nifi-aws-processors/src/main/java/org/apache/nifi/processors/aws/kinesis/stream/record/KinesisRecordProcessorRecord.java, nifi-extension-bundles/nifi-aws-bundle/nifi-aws-processors/src/main/java/org/apache/nifi/processors/aws/kinesis/stream/record/converter/RecordConverter.java, nifi-extension-bundles/nifi-aws-bundle/nifi-aws-processors/src/main/java/org/apache/nifi/processors/aws/kinesis/stream/record/converter/RecordConverterIdentity.java, nifi-extension-bundles/nifi-aws-bundle/nifi-aws-processors/src/main/java/org/apache/nifi/processors/aws/kinesis/stream/record/converter/RecordConverterWrapper.java, nifi-extension-bundles/nifi-aws-bundle/nifi-aws-processors/src/main/resources/docs/org.apache.nifi.processors.aws.kinesis.stream.ConsumeKinesisStream/additionalDetails.md, nifi-extension-bundles/nifi-aws-bundle/nifi-aws-processors/src/test/java/org/apache/nifi/processors/aws/kinesis/stream/TestConsumeKinesisStream.java, nifi-extension-bundles/nifi-aws-bundle/nifi-aws-processors/src/test/java/org/apache/nifi/processors/aws/kinesis/stream/record/TestKinesisRecordProcessorRecord.java
[NIFI-14285](https://issues.apache.org/jira/browse/NIFI-14285)
=> NIFI-14285 ConsumeKinesisStream Record Wrapper

nifi-commons/nifi-record/src/main/java/org/apache/nifi/serialization/record/util/DataTypeUtils.java, nifi-commons/nifi-record/src/test/java/org/apache/nifi/serialization/record/TestDataTypeUtils.java, nifi-extension-bundles/nifi-standard-bundle/nifi-standard-processors/src/test/java/org/apache/nifi/processors/standard/TestConvertRecord.java
[NIFI-14297 ](https://issues.apache.org/jira/browse/NIFI-14297 )
This fix in this PR addresses the need to support Avro schema byes type and decimal logical type when a default is specified. As part of fix the unit test `testIsBigDecimalTypeCompatible` in `TestDataTypeUtils` was converted to a JUnit 5 Paramaeterized test and the particular use case of a decimal as bytes was added.
In addition a unit test was added to `TestConvertRecord` to exercise the use case of the user who submitted the ticket although this may not be necessary.
=> NIFI-14297 Added support for Avro schemas with String default for type bytes and 'decimal' logicalType.

nifi-mock/src/main/java/org/apache/nifi/util/StandardProcessorTestRunner.java, nifi-mock/src/main/java/org/apache/nifi/util/TestRunner.java
[NIFI-14276](https://issues.apache.org/jira/browse/NIFI-14276)
=> NIFI-14276 Added the clearQueue method to the TestRunner interface.

nifi-extension-bundles/nifi-elasticsearch-bundle/nifi-elasticsearch-client-service/src/main/java/org/apache/nifi/elasticsearch/ElasticSearchClientServiceImpl.java
[NIFI-14307](https://issues.apache.org/jira/browse/NIFI-14307)
Close InputStream after reading response content in multiple places in ElasticSearchClientServiceImpl class. 
=> NIFI-14307 Closing response entity stream after reading in ElasticSearchClientServiceImpl

nifi-extension-bundles/nifi-azure-bundle/pom.xml, nifi-extension-bundles/nifi-gcp-bundle/nifi-gcp-processors/pom.xml, nifi-extension-bundles/nifi-salesforce-bundle/nifi-salesforce-processors/pom.xml, pom.xml
[NIFI-14348](https://issues.apache.org/jira/browse/NIFI-14348) - Bump Azure, AWS, Salesforce, Google Drive dependencies
- Azure BOM from 1.2.31 to 1.2.32 (this updates azure-identity allowing us to upgrade MSAL4J to 1.19.0)
- Google Drive from v3-rev20250216-2.0.0 to v3-rev20250220-2.0.0
- Salesforce from 4.10.1 to 4.10.2
- AWS SDK from 2.30.33 to 2.30.36
=> NIFI-14348 - Bump Azure, AWS, Salesforce, Google Drive dependencies

nifi-commons/nifi-utils/src/main/java/org/apache/nifi/util/FormatUtils.java, nifi-commons/nifi-utils/src/test/java/org/apache/nifi/util/TestFormatUtils.java
[NIFI-14356](https://issues.apache.org/jira/browse/NIFI-14356)
Adding YearMonth and Year temporal queries to [DateTimeFormatter parser](https://github.com/apache/nifi/blob/fc04d49057d5208d70342c15ee1e18ea545b14aa/nifi-commons/nifi-utils/src/main/java/org/apache/nifi/util/FormatUtils.java#L245C45-L245C54) which is used in the date functions of the expression language. Patterns like 'yyyy' and 'yyyyMM' will work with this fix ([like the toDate example of the expression language documentation which is currently throwing an exception](https://nifi.apache.org/nifi-docs/expression-language-guide.html#todate)). 
no new dependencies
=> NIFI-14356 Add missing YearMonth and Year queries to DateTimeFormatter

nifi-extension-bundles/nifi-elasticsearch-bundle/nifi-elasticsearch-restapi-processors/src/main/java/org/apache/nifi/processors/elasticsearch/DeleteByQueryElasticsearch.java, nifi-extension-bundles/nifi-elasticsearch-bundle/nifi-elasticsearch-restapi-processors/src/main/java/org/apache/nifi/processors/elasticsearch/GetElasticsearch.java, nifi-extension-bundles/nifi-elasticsearch-bundle/nifi-elasticsearch-restapi-processors/src/main/java/org/apache/nifi/processors/elasticsearch/JsonQueryElasticsearch.java, nifi-extension-bundles/nifi-elasticsearch-bundle/nifi-elasticsearch-restapi-processors/src/main/java/org/apache/nifi/processors/elasticsearch/UpdateByQueryElasticsearch.java
[NIFI-14335](https://issues.apache.org/jira/browse/NIFI-14335)
=> NIFI-14335 Support NiFi framework batching in Elasticsearch processors

nifi-extension-bundles/nifi-standard-bundle/nifi-standard-processors/src/main/java/org/apache/nifi/processors/standard/InvokeHTTP.java, nifi-extension-bundles/nifi-standard-bundle/nifi-standard-processors/src/test/java/org/apache/nifi/processors/standard/InvokeHTTPTest.java, nifi-extension-bundles/nifi-standard-services/nifi-oauth2-provider-api/src/main/java/org/apache/nifi/oauth2/OAuth2AccessTokenProvider.java, nifi-extension-bundles/nifi-standard-services/nifi-oauth2-provider-api/src/main/java/org/apache/nifi/oauth2/TokenRefreshStrategy.java, nifi-extension-bundles/nifi-standard-services/nifi-oauth2-provider-bundle/nifi-oauth2-provider-service/src/main/java/org/apache/nifi/oauth2/StandardOauth2AccessTokenProvider.java
[NIFI-14389](https://issues.apache.org/jira/browse/NIFI-14389) - Provide the option to force refresh Access Token in OAuth2AccessTokenProvider
=> NIFI-14389 - Provide the option to force refresh Access Token in OAuth2AccessTokenProvider

pom.xml
[NIFI-14410](https://issues.apache.org/jira/browse/NIFI-14410) Upgrades the Apache NiFi API dependency from 2.0.0 to [2.1.0](https://cwiki.apache.org/confluence/display/NIFI/Release+Notes#ReleaseNotes-NiFiAPIVersion2.1.0) introducing support for the `DisallowRunOnce` annotation and improving the behavior of Runtime Manifest generation.
=> NIFI-14410 Upgrade Apache NiFi API from 2.0.0 to 2.1.0

nifi-extension-bundles/nifi-aws-bundle/nifi-aws-nar/src/main/resources/META-INF/NOTICE, nifi-extension-bundles/nifi-aws-bundle/pom.xml
[NIFI-14415](https://issues.apache.org/jira/browse/NIFI-14415)
=> NIFI-14415 Remove nifi-aws-bundle protobuf-java lib pin

.github/workflows/ci-workflow.yml
[NIFI-14420](https://issues.apache.org/jira/browse/NIFI-14420) Sets the GitHub `paths-filter` Action to version 3.0.2 to align with allowed versions.
=> NIFI-14420 Set GitHub paths-filter Action to version 3.0.2

nifi-framework-bundle/nifi-framework/nifi-framework-components/src/main/java/org/apache/nifi/controller/repository/StandardProcessSession.java
[NIFI-14399](https://issues.apache.org/jira/browse/NIFI-14399)
=> NIFI-14399 Removed finalize method from StandardProcessSession.

nifi-extension-bundles/nifi-aws-bundle/nifi-aws-processors/src/main/java/org/apache/nifi/processors/aws/kinesis/stream/record/converter/RecordConverterWrapper.java, nifi-extension-bundles/nifi-aws-bundle/nifi-aws-processors/src/main/resources/docs/org.apache.nifi.processors.aws.kinesis.stream.ConsumeKinesisStream/additionalDetails.md, nifi-extension-bundles/nifi-aws-bundle/nifi-aws-processors/src/test/java/org/apache/nifi/processors/aws/kinesis/stream/record/TestKinesisRecordProcessorRecord.java
[NIFI-14394](https://issues.apache.org/jira/browse/NIFI-14394)
=> NIFI-14394 ConsumeKinesisStream add Sub Seq Num to metadata

nifi-extension-bundles/nifi-gcp-bundle/pom.xml, nifi-extension-bundles/nifi-media-bundle/pom.xml, nifi-extension-bundles/nifi-poi-bundle/pom.xml, nifi-extension-bundles/nifi-salesforce-bundle/nifi-salesforce-processors/pom.xml, nifi-extension-bundles/nifi-snowflake-bundle/pom.xml, nifi-extension-bundles/nifi-standard-bundle/nifi-standard-processors/pom.xml, nifi-extension-bundles/nifi-standard-bundle/pom.xml, nifi-extension-bundles/nifi-standard-shared-bundle/nifi-standard-shared-bom/pom.xml, nifi-registry/pom.xml, pom.xml
[NIFI-14440](https://issues.apache.org/jira/browse/NIFI-14440) - Bump Netty to 4.2.0.Final, Jetty to 12.0.19, GCP BOM to 26.59.0 and others
- GCP BOM from 26.58.0 to 26.59.0 - https://github.com/googleapis/java-cloud-bom/releases/tag/v26.59.0
- Apache POI from 5.4.0 to 5.4.1 - https://poi.apache.org/changes.html
- Camel Salesforce from 4.10.3 to 4.11.0 - https://github.com/apache/camel/releases/tag/camel-4.11.0
- Snowflake JDBC from 3.23.1 to 3.23.2 - https://docs.snowflake.com/en/release-notes/clients-drivers/jdbc-2025#version-3-23-2-april-3-2025
- DataFaker from 2.4.2 to 2.4.3 - https://github.com/datafaker-net/datafaker/releases/tag/2.4.3
- JSON Flattener from 0.17.2 to 0.17.3 - https://github.com/wnameless/json-flattener/releases/tag/json-flattener-0.17.3
- checker-qual from 3.49.1 to …
=> NIFI-14440 - Bump Netty to 4.2.0.Final, Jetty to 12.0.19, GCP BOM to 26.59.0 and others

nifi-registry/nifi-registry-core/nifi-registry-flow-diff/src/main/java/org/apache/nifi/registry/flow/diff/FlowComparatorVersionedStrategy.java, nifi-registry/nifi-registry-core/nifi-registry-flow-diff/src/main/java/org/apache/nifi/registry/flow/diff/StandardFlowComparator.java, nifi-registry/nifi-registry-core/nifi-registry-flow-diff/src/test/java/org/apache/nifi/registry/flow/diff/TestStandardFlowComparator.java
[NIFI-14435](https://issues.apache.org/jira/browse/NIFI-14435) - FlowComparator should offer deep recursive comparison
> Consider a versioned process group PG.
> Add a new child process group inside of PG.
> Do many modifications in the child PG (add processors, etc).
> If showing local changes for PG, it'll only say that a process group childPG has been added but nothing about what has been done in childPG.
> This JIRA is to add a new Flow Comparator Versioned Strategy in order to offer the option for a full exhaustive listing of the differences to also include the list of what is being added inside a newly added process group.
> There is no intent with this work to change what is returned to the UI when showing local changes as it should be further evaluated in terms of side effects. …
=> NIFI-14435 - FlowComparator should offer deep recursive comparison

nifi-commons/nifi-web-client-api/src/main/java/org/apache/nifi/web/client/api/ContentType.java, nifi-commons/nifi-web-client-api/src/main/java/org/apache/nifi/web/client/api/HttpHeaderName.java, nifi-commons/nifi-web-client-api/src/main/java/org/apache/nifi/web/client/api/MediaType.java
[NIFI-14428](https://issues.apache.org/jira/browse/NIFI-14428) - Add common content types and header names in Web Client API
=> NIFI-14428 - Add common content types and header names in Web Client API

nifi-framework-bundle/nifi-framework/nifi-resources/src/main/resources/bin/nifi.cmd
[NIFI-14449](https://issues.apache.org/jira/browse/NIFI-14449) fixes a bug with nifi.cmd where it fails when NIFI_HOME has a space in the path on Windows.
- [NIFI-14449 ] [Apache NiFi Jira](https://issues.apache.org/jira/browse/NIFI-1449) issue created
=> NIFI-14449 - Fixed nifi.cmd to work with paths with spaces

nifi-extension-bundles/nifi-box-bundle/nifi-box-processors/src/main/java/org/apache/nifi/processors/box/ConsumeBoxEnterpriseEvents.java, nifi-extension-bundles/nifi-box-bundle/nifi-box-processors/src/test/java/org/apache/nifi/processors/box/ConsumeBoxEnterpriseEventsTest.java
[NIFI-14467](https://issues.apache.org/jira/browse/NIFI-14467)
=> NIFI-14467 Gracefully stop ConsumeBoxEnterpriseEvents

nifi-extension-bundles/nifi-kafka-bundle/nifi-kafka-3-service/src/main/java/org/apache/nifi/kafka/service/Kafka3ConnectionService.java
[NIFI-14270](https://issues.apache.org/jira/browse/NIFI-14270)
=> NIFI-14270 - Kafka3ConnectionService built-in documentation is missing

nifi-commons/nifi-calcite-utils/pom.xml, nifi-extension-bundles/nifi-standard-bundle/pom.xml
[NIFI-14499](https://issues.apache.org/jira/browse/NIFI-14499) - Override httpclient5 5.4.1 from calcite-core
=> NIFI-14499 - Override httpclient5 5.4.1 from calcite-core

nifi-frontend/src/main/frontend/apps/nifi/src/app/pages/flow-designer/service/canvas-utils.service.ts
🛠️ Fix: Label rendering issue in boundedMultilineEllipsis
This MR addresses a bug where SVG labels using boundedMultilineEllipsis were not displaying correctly when rendered via D3, especially during interactions like dragging or viewport changes.
✅ Root Cause:
The issue stemmed from inaccurate line height and line count calculations, which affected label wrapping and positioning. In some cases, the initial tspan was not receiving the proper y attribute, causing the entire label to be misaligned or not visible.
🔧 Fix Details:
Reordered the logic inside the while (word) loop to:
1. Assign y position immediately on first word append, ensuring the tspan gets positioned correctly even for single-word lines.
2. Calculate lineHeight and lineCount using getBoundingClientRect() only once (on the …
=> NIFI-14071: Labels not rendering lines starting with spaces

nifi-extension-bundles/nifi-box-bundle/nifi-box-services/src/main/java/org/apache/nifi/box/controllerservices/JsonConfigBasedBoxClientService.java, nifi-extension-bundles/nifi-box-bundle/nifi-box-services/src/test/java/org/apache/nifi/box/controllerservices/JsonConfigBasedBoxClientServiceTestRunnerTest.java
[NIFI-14501](https://issues.apache.org/jira/browse/NIFI-14501)
Allowing to overwrite [infinite timeouts set by default](https://github.com/box/box-java-sdk/blob/v4.16.0/doc/configuration.md#connection-timeout). 
The properties are similar to the ones used in [StandardWebClientServiceProvider](https://github.com/apache/nifi/blob/main/nifi-extension-bundles/nifi-standard-services/nifi-web-client-provider-bundle/nifi-web-client-provider-service/src/main/java/org/apache/nifi/web/client/provider/service/StandardWebClientServiceProvider.java#L58).
=> NIFI-14501 Set read and connect timeout in JsonConfigBasedBoxClientService

nifi-extension-bundles/nifi-websocket-bundle/nifi-websocket-services-jetty/src/main/java/org/apache/nifi/websocket/jetty/JettyWebSocketClient.java
[NIFI-14505](https://issues.apache.org/jira/browse/NIFI-14505) - Fix migrate properties in JettyWebSocketClient
See: https://github.com/apache/nifi/commit/87800b0a3684f051cbde043afca93373220cf1f3#diff-fb3881e91ff195e7fd700d9de72815d39d7d191d70e913ffb968ca7f8e882c64L111
=> NIFI-14505 - Fix migrate properties in JettyWebSocketClient

nifi-extension-bundles/nifi-poi-bundle/nifi-poi-services/src/main/java/org/apache/nifi/excel/ExcelHeaderSchemaStrategy.java, nifi-extension-bundles/nifi-poi-bundle/nifi-poi-services/src/main/java/org/apache/nifi/excel/ExcelReader.java, nifi-extension-bundles/nifi-poi-bundle/nifi-poi-services/src/main/java/org/apache/nifi/excel/ExcelRecordReader.java, nifi-extension-bundles/nifi-poi-bundle/nifi-poi-services/src/main/java/org/apache/nifi/excel/ExcelRecordReaderConfiguration.java, nifi-extension-bundles/nifi-poi-bundle/nifi-poi-services/src/main/java/org/apache/nifi/excel/ExcelRecordSource.java, nifi-extension-bundles/nifi-poi-bundle/nifi-poi-services/src/main/java/org/apache/nifi/excel/InputFileType.java, nifi-extension-bundles/nifi-poi-bundle/nifi-poi-services/src/main/java/org/apache/nifi/excel/RowIterator.java, nifi-extension-bundles/nifi-poi-bundle/nifi-poi-services/src/test/java/org/apache/nifi/excel/TestExcelRecordReader.java
[NIFI-14426](https://issues.apache.org/jira/browse/NIFI-14426): Add support for HSSF format in ExcelReader processor
=> NIFI-14426: Add support for HSSF format in ExcelReader processor

nifi-extension-bundles/nifi-standard-services/nifi-lookup-services-bundle/nifi-lookup-services/src/main/java/org/apache/nifi/lookup/maxmind/IPLookupService.java
[NIFI-14551](https://issues.apache.org/jira/browse/NIFI-14551)
=> NIFI-14551 Removed the use of MetroCode in IPLookupService.

nifi-extension-bundles/nifi-extension-utils/nifi-git-flow-registry/src/main/java/org/apache/nifi/registry/flow/git/AbstractGitFlowRegistryClient.java, nifi-extension-bundles/nifi-github-bundle/nifi-github-extensions/src/test/java/org/apache/nifi/github/GitHubFlowRegistryClientTest.java
[NIFI-14555](https://issues.apache.org/jira/browse/NIFI-14555) - Option to empty parameter values in git registry clients
The goal of this PR is to add an optional property for all Git based registry clients. The property "Empty Parameters" will default to false to retain current behavior. If set to true, all values of all parameters will be removed before the flow is being versioned and stored in the git repo.
Parameters are usually environment dependent and it might not be desirable to include in the versioned flow the parameters values that have been set in a lower/dev environment while designing the flow.
=> NIFI-14555 - Option to empty parameter values in git registry clients

nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-api/src/main/java/org/apache/nifi/prometheusutil/PrometheusMetricsUtil.java
[NIFI-14565](https://issues.apache.org/jira/browse/NIFI-14565) - fix Input Port reporting in Prometheus endpoint
=> NIFI-14565 - fix Input Port reporting in Prometheus endpoint

nifi-extension-bundles/nifi-kafka-bundle/nifi-kafka-3-integration/src/test/java/org/apache/nifi/kafka/processors/ConsumeKafkaInjectMetadataRecordIT.java, nifi-extension-bundles/nifi-kafka-bundle/nifi-kafka-3-integration/src/test/java/org/apache/nifi/kafka/processors/ConsumeKafkaRecordIT.java, nifi-extension-bundles/nifi-kafka-bundle/nifi-kafka-3-integration/src/test/java/org/apache/nifi/kafka/processors/ConsumeKafkaWrapperRecordIT.java, nifi-extension-bundles/nifi-kafka-bundle/nifi-kafka-processors/src/main/java/org/apache/nifi/kafka/processors/ConsumeKafka.java, nifi-extension-bundles/nifi-kafka-bundle/nifi-kafka-processors/src/main/java/org/apache/nifi/kafka/processors/consumer/convert/AbstractRecordStreamKafkaMessageConverter.java, nifi-extension-bundles/nifi-kafka-bundle/nifi-kafka-processors/src/main/java/org/apache/nifi/kafka/processors/consumer/convert/RecordStreamKafkaMessageConverter.java, nifi-extension-bundles/nifi-kafka-bundle/nifi-kafka-processors/src/main/java/org/apache/nifi/kafka/processors/consumer/convert/WrapperRecordStreamKafkaMessageConverter.java, nifi-extension-bundles/nifi-kafka-bundle/nifi-kafka-processors/src/main/java/org/apache/nifi/kafka/processors/consumer/wrapper/ConsumeWrapperRecord.java, nifi-extension-bundles/nifi-kafka-bundle/nifi-kafka-processors/src/main/java/org/apache/nifi/kafka/processors/consumer/wrapper/WrapperRecordKeyReader.java, nifi-extension-bundles/nifi-kafka-bundle/nifi-kafka-processors/src/main/java/org/apache/nifi/kafka/processors/producer/wrapper/InjectMetadataRecord.java, nifi-extension-bundles/nifi-kafka-bundle/nifi-kafka-processors/src/main/java/org/apache/nifi/kafka/processors/producer/wrapper/WrapperRecord.java, nifi-extension-bundles/nifi-kafka-bundle/nifi-kafka-processors/src/main/resources/docs/org.apache.nifi.kafka.processors.ConsumeKafka/additionalDetails.md, nifi-extension-bundles/nifi-kafka-bundle/nifi-kafka-processors/src/test/java/org/apache/nifi/kafka/processors/consumer/convert/WrapperRecordStreamKafkaMessageConverterTest.java, nifi-extension-bundles/nifi-kafka-bundle/nifi-kafka-shared/src/main/java/org/apache/nifi/kafka/shared/property/OutputStrategy.java
[NIFI-14566](https://issues.apache.org/jira/browse/NIFI-14566) - Introduce Inject Metadata Output Strategy in ConsumeKafka
=> NIFI-14566 - Introduce Inject Metadata Output Strategy in ConsumeKafka

nifi-extension-bundles/nifi-poi-bundle/nifi-poi-services/src/main/java/org/apache/nifi/excel/ExcelReader.java
[NIFI-14577](https://issues.apache.org/jira/browse/NIFI-14577)
=> NIFI-14577 Added Input File Type property descriptor to list of supported property descriptors.

nifi-docs/src/main/asciidoc/administration-guide.adoc
[NIFI-14578](https://issues.apache.org/jira/browse/NIFI-14578)
=> NIFI-14578 Fix default value for nifi.content.repository.archive.cleanup.frequency

nifi-framework-bundle/nifi-framework/nifi-framework-core/src/main/java/org/apache/nifi/controller/StandardReloadComponent.java
[NIFI-14574](https://issues.apache.org/jira/browse/NIFI-14574)
=> NIFI-14574 Clear validation state after reloading component

nifi-commons/nifi-hashicorp-vault/pom.xml, nifi-extension-bundles/nifi-extension-utils/nifi-syslog-utils/pom.xml, nifi-extension-bundles/nifi-redis-bundle/pom.xml, nifi-extension-bundles/nifi-standard-bundle/nifi-standard-processors/pom.xml, nifi-extension-bundles/nifi-standard-services/nifi-record-serialization-services-bundle/nifi-record-serialization-services/pom.xml, nifi-framework-bundle/nifi-framework-extensions/nifi-questdb-bundle/nifi-questdb/pom.xml, nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-security/src/main/java/org/apache/nifi/web/security/configuration/AuthenticationSecurityConfiguration.java, nifi-toolkit/nifi-toolkit-cli/pom.xml, pom.xml
[NIFI-14582](https://issues.apache.org/jira/browse/NIFI-14582) - Bump Spring Security to 6.5.0, Spring Vault to 3.2.0, and others
- Simple Syslog 5424 from 0.0.18 to 0.0.19 - https://github.com/palindromicity/simple-syslog-5424/releases/tag/simple-syslog-5424-0.0.19
- Spring Vault from 3.1.3 to 3.2.0 - https://github.com/spring-projects/spring-vault/releases/tag/3.2.0
- Spring Redis from 3.4.6 to 3.5.0 - https://github.com/spring-projects/spring-data-redis/releases/tag/3.5.0
- Spring Retry from 2.0.11 to 2.0.12 - https://github.com/spring-projects/spring-retry/releases/tag/v2.0.12
- Spring Security from 6.4.5 to 6.5.0 - https://github.com/spring-projects/spring-security/releases/tag/6.5.0
- XML Unit from 2.10.0 to 2.10.1 - https://github.com/xmlunit/xmlunit/releases/tag/v2.10.1
- JLine …
=> NIFI-14582 - Bump Spring Security to 6.5.0, Spring Vault to 3.2.0, and others

nifi-extension-bundles/nifi-extension-utils/nifi-git-flow-registry/src/main/java/org/apache/nifi/registry/flow/git/serialize/VersionedComponentCollectionSerializer.java, nifi-extension-bundles/nifi-extension-utils/nifi-git-flow-registry/src/test/java/org/apache/nifi/registry/flow/git/serialize/JacksonFlowSnapshotSerializerTest.java
[NIFI-14592](https://issues.apache.org/jira/browse/NIFI-14592) - Git registry client JSON normalization should sort parameters
=> NIFI-14592 - Git registry client JSON normalization should sort parameters

pom.xml
[NIFI-14595](https://issues.apache.org/jira/browse/NIFI-14595) - Downgrade Spring Security to 6.4.6
=> NIFI-14595 - Downgrade Spring Security to 6.4.6

nifi-extension-bundles/nifi-standard-bundle/nifi-standard-processors/pom.xml, nifi-registry/nifi-registry-core/nifi-registry-test/pom.xml
[NIFI-14651](https://issues.apache.org/jira/browse/NIFI-14651) - Bump postgresql to 42.7.7
=> NIFI-14651 - Bump postgresql to 42.7.7

nifi-extension-bundles/nifi-elasticsearch-bundle/nifi-elasticsearch-test-utils/pom.xml, nifi-extension-bundles/nifi-registry-bundle/nifi-registry-service/pom.xml, nifi-extension-bundles/nifi-standard-bundle/pom.xml, nifi-registry/pom.xml, pom.xml
[NIFI-14703](https://issues.apache.org/jira/browse/NIFI-14703) - Bump Test Containers to 1.21.3, Okio to 3.14.0, and others
- Docker Java API from 3.5.1 to 3.5.2 - https://github.com/docker-java/docker-java/releases/tag/3.5.2
- JSON Schema Validator from 1.5.7 to 1.5.8 - https://github.com/networknt/json-schema-validator/releases/tag/1.5.8
- FlywayDB from 11.9.2 to 11.10.0 - https://github.com/flyway/flyway/releases/tag/flyway-11.10.0
- AWS SDK v2 fron 2.31.70 to 2.31.73 - https://github.com/aws/aws-sdk-java-v2/blob/master/CHANGELOG.md
- Okio from 3.13.0 to 3.14.0 - https://github.com/square/okio/blob/master/CHANGELOG.md
- Test containers from 1.21.2 to 1.21.3 - https://github.com/testcontainers/testcontainers-java/releases/tag/1.21.3
Please complete the following tracking steps prior to …
=> NIFI-14703 - Bump Test Containers to 1.21.3, Okio to 3.14.0, and others

nifi-commons/nifi-utils/src/main/java/org/apache/nifi/util/concurrency/DebugEnabledTimedLock.java, nifi-commons/nifi-utils/src/main/java/org/apache/nifi/util/concurrency/TimedLock.java
[NIFI-14707](https://issues.apache.org/jira/browse/NIFI-14707)
Go with the simple approach to use a single logger for all instances of TimedLock and its debuggable counterpart. If you all still want the ability to configure logging on a specific TimedLock instance please drop a comment. I just wanted to get a PR up with the simplest solution.
- N/A New dependencies are compatible with the [Apache License 2.0](https://apache.org/licenses/LICENSE-2.0) according to the [License Policy](https://www.apache.org/legal/resolved.html)
- N/A New dependencies are documented in applicable `LICENSE` and `NOTICE` files
- N/A Documentation …
=> [NIFI-14707] Use a single logger for TimedLock

nifi-extension-bundles/nifi-box-bundle/nifi-box-nar/pom.xml, nifi-extension-bundles/nifi-gcp-bundle/nifi-gcp-processors/pom.xml, nifi-extension-bundles/nifi-graph-bundle/nifi-neo4j-cypher-service/pom.xml, nifi-extension-bundles/nifi-snmp-bundle/nifi-snmp-processors/pom.xml, nifi-extension-bundles/nifi-standard-bundle/pom.xml, nifi-extension-bundles/nifi-standard-shared-bundle/nifi-standard-shared-bom/pom.xml, nifi-registry/nifi-registry-core/nifi-registry-test/pom.xml, nifi-registry/pom.xml, pom.xml
[NIFI-14716](https://issues.apache.org/jira/browse/NIFI-14716) - Bump Jetty to 12.0.23, okio to 3.15.0, and others
- License Maven Plugin from 2.5.0 to 2.6.0 - https://github.com/mojohaus/license-maven-plugin/releases/tag/2.6.0
- Google Drive API from v3-rev20250511-2.0.0 to v3-rev20250701-2.0.0 - https://github.com/googleapis/google-api-java-client-services/tree/main/clients/google-api-services-drive/v3/2.0.0
- Neo4J Driver from 5.28.6 to 5.28.7 - https://github.com/neo4j/neo4j-java-driver/releases/tag/5.28.7
- SNMP4J from 3.9.5 to 3.9.6 - https://www.snmp4j.org/CHANGES.txt
- checker-qual from 3.49.4 to 3.49.5 - https://github.com/typetools/checker-framework/releases/tag/checker-framework-3.49.5
- MariaDB Java client from 3.5.3 to 3.5.4 - …
=> NIFI-14716 - Bump Jetty to 12.0.23, okio to 3.15.0, and others

nifi-extension-bundles/nifi-extension-utils/nifi-git-flow-registry/src/main/java/org/apache/nifi/registry/flow/git/AbstractGitFlowRegistryClient.java, nifi-extension-bundles/nifi-github-bundle/nifi-github-extensions/src/test/java/org/apache/nifi/github/GitHubFlowRegistryClientTest.java
[NIFI-14700](https://issues.apache.org/jira/browse/NIFI-14700) - Option to ignore parameter value changes in git registry clients
In [NIFI-14555](https://issues.apache.org/jira/browse/NIFI-14555) we added the option to commit a new versioned flow with empty values for all parameters. This is a good strategy in case you want to make sure that you're not inadvertently committing a new version that would contain some parameter values that are specific to a lower environment.
However this strategy is not great when you have parameters where you want to specify a default value. In such a case, and when using the strategy implemented in [NIFI-14555](https://issues.apache.org/jira/browse/NIFI-14555), you'd lose the default values for your parameters when you commit a new version.
This JIRA is to …
=> NIFI-14700 - Option to ignore parameter value changes in git registry clients

nifi-extension-bundles/nifi-elasticsearch-bundle/nifi-elasticsearch-restapi-processors/src/main/java/org/apache/nifi/processors/elasticsearch/PutElasticsearchRecord.java, nifi-extension-bundles/nifi-elasticsearch-bundle/nifi-elasticsearch-restapi-processors/src/test/java/org/apache/nifi/processors/elasticsearch/PutElasticsearchRecordTest.java, nifi-extension-bundles/nifi-elasticsearch-bundle/nifi-elasticsearch-restapi-processors/src/test/resources/PutElasticsearchRecordTest/2_flowFileContents.json, nifi-extension-bundles/nifi-elasticsearch-bundle/nifi-elasticsearch-restapi-processors/src/test/resources/PutElasticsearchRecordTest/2_flowFileContents_stringified.json, nifi-extension-bundles/nifi-elasticsearch-bundle/nifi-elasticsearch-restapi-processors/src/test/resources/PutElasticsearchRecordTest/recordPathTestSchema.json, nifi-extension-bundles/nifi-elasticsearch-bundle/nifi-elasticsearch-restapi-processors/src/test/resources/PutElasticsearchRecordTest/scriptParams.json
[NIFI-14685](https://issues.apache.org/jira/browse/NIFI-14685) convert script record path fields to JSON objects for PutElasticsearchRecord when FlowFile content parsed using schema inference
- ~~[ ] New dependencies are compatible with the [Apache License 2.0](https://apache.org/licenses/LICENSE-2.0) according to the [License Policy](https://www.apache.org/legal/resolved.html)~~
- ~~[ ] New dependencies are documented in applicable `LICENSE` and `NOTICE` files~~
- ~~[ ] Documentation formatting appears as expected in rendered files~~
=> NIFI-14685 convert script record path fields to JSON objects for PutElasticsearchRecord when FlowFile content parsed using schema inference

nifi-stateless/nifi-stateless-bundle/nifi-stateless-engine/src/main/java/org/apache/nifi/stateless/flow/StandardStatelessFlow.java, nifi-stateless/nifi-stateless-bundle/nifi-stateless-engine/src/test/java/org/apache/nifi/stateless/flow/TestStandardStatelessFlow.java
[NIFI-14710](https://issues.apache.org/jira/browse/NIFI-14710) - Stateless should trigger failure callback when queues are not empty after process group is stopped
=> NIFI-14710 - Stateless should trigger failure callback when queues are not empty after process group is stopped

nifi-commons/nifi-record/src/main/java/org/apache/nifi/serialization/RecordReader.java
[NIFI-14741](https://issues.apache.org/jira/browse/NIFI-14741)
=> NIFI-14741 Corrected interface name in javadocs.

nifi-extension-bundles/nifi-standard-services/nifi-record-serialization-services-bundle/nifi-record-serialization-services/src/main/java/org/apache/nifi/text/FreeFormTextWriter.java
[NIFI-14742](https://issues.apache.org/jira/browse/NIFI-14742)
I only found this one instance which was not caught by the PMD's ForLoopCanBeForeach rule.
I tried looking for other cases with Intellij's find in files with the following regular expression
`for \(int\s?.+\s?=\s?0`
but I did not find any other for loops which could be changed to a for each loop.
=> NIFI-14742 Replaced for loop missed by PMD's ForLoopCanBeForeach rule with for each loop.

nifi-extension-bundles/nifi-extension-utils/nifi-record-utils/nifi-json-record-utils/src/main/java/org/apache/nifi/json/AbstractJsonRowRecordReader.java
[NIFI-14743](https://issues.apache.org/jira/browse/NIFI-14743)
=> NIFI-14743 Removed unused class variable from AbstractJsonRowRecordReader.

nifi-extension-bundles/nifi-aws-bundle/pom.xml, nifi-extension-bundles/nifi-azure-bundle/nifi-azure-processors/pom.xml, nifi-extension-bundles/nifi-azure-bundle/nifi-azure-processors/src/main/java/org/apache/nifi/services/azure/data/explorer/StandardKustoIngestService.java, nifi-extension-bundles/nifi-azure-bundle/nifi-azure-processors/src/main/java/org/apache/nifi/services/azure/data/explorer/StandardKustoQueryService.java, nifi-extension-bundles/nifi-email-bundle/nifi-email-processors/pom.xml, nifi-extension-bundles/nifi-standard-bundle/nifi-standard-processors/pom.xml, pom.xml
[NIFI-14749](https://issues.apache.org/jira/browse/NIFI-14749) - Bump Log4J to 2.25.1, datafaker to 2.4.4 and others
- AWS Kinesis Client from 2.7.0 to 2.7.1 - https://github.com/awslabs/amazon-kinesis-client/blob/v2.x/CHANGELOG.md
- Microsoft Azure Kusto from 6.0.3 to 7.0.0 - https://github.com/Azure/azure-kusto-java/releases/tag/v7.0.0
- Greenmail from 2.1.3 to 2.1.4 - https://github.com/greenmail-mail-test/greenmail/releases/tag/release-2.1.4
- Datafaker from 2.4.3 to 2.4.4 - https://github.com/datafaker-net/datafaker/releases/tag/2.4.4
- Log4j2 from 2.25.0 to 2.25.1 - https://github.com/apache/logging-log4j2/releases/tag/rel%2F2.25.1
- Caffeine from 3.2.1 to 3.2.2 - https://github.com/ben-manes/caffeine/releases/tag/v3.2.2
Please complete the following tracking steps prior to pull …
=> NIFI-14749 - Bump Log4J to 2.25.1, datafaker to 2.4.4 and others

nifi-commons/nifi-expression-language/src/main/java/org/apache/nifi/attribute/expression/language/VariableImpact.java, nifi-commons/nifi-hl7-query-language/src/main/java/org/apache/nifi/hl7/query/evaluator/Evaluator.java, nifi-commons/nifi-write-ahead-log/src/main/java/org/wali/SyncListener.java, nifi-extension-bundles/nifi-extension-utils/nifi-file-transfer/src/main/java/org/apache/nifi/processor/util/file/transfer/FileTransfer.java, nifi-framework-api/src/main/java/org/apache/nifi/controller/Triggerable.java, nifi-framework-api/src/main/java/org/apache/nifi/events/EventReporter.java, nifi-framework-api/src/main/java/org/apache/nifi/provenance/IdentifierLookup.java, nifi-framework-api/src/main/java/org/apache/nifi/web/ViewableContent.java, nifi-framework-bundle/nifi-framework-extensions/nifi-provenance-repository-bundle/nifi-persistent-provenance-repository/src/main/java/org/apache/nifi/provenance/authorization/EventAuthorizer.java, nifi-framework-bundle/nifi-framework-extensions/nifi-provenance-repository-bundle/nifi-persistent-provenance-repository/src/main/java/org/apache/nifi/provenance/authorization/EventTransformer.java, nifi-framework-bundle/nifi-framework/nifi-framework-core/src/main/java/org/apache/nifi/controller/serialization/FlowSerializer.java
[NIFI-14771](https://issues.apache.org/jira/browse/NIFI-14771)
=> NIFI-14771 Removed redundant public static final modifiers from interface fields

nifi-extension-bundles/nifi-standard-bundle/nifi-standard-processors/src/main/java/org/apache/nifi/processors/standard/PutDatabaseRecord.java
[NIFI-14776](https://issues.apache.org/jira/browse/NIFI-14776) - Rename Catalog property in PutDatabaseRecord
We currently have a "Catalog Name" property in PutDatabaseRecord and while this is technically correct from a JDBC point of view, this can confuse people/users and they would not understand that, in most cases, that would be the property where the database name is specified. I suggest renaming this property to Database Name in order to be more user friendly and to adjust the description to mention the catalog aspect.
=> NIFI-14776 - Rename Catalog property in PutDatabaseRecord

nifi-frontend/src/main/frontend/apps/nifi/src/app/ui/common/status-history/status-history-chart/status-history-chart.component.ts, nifi-frontend/src/main/frontend/libs/shared/src/services/nifi-common.service.spec.ts, nifi-frontend/src/main/frontend/libs/shared/src/services/nifi-common.service.ts
[NIFI-14800](https://issues.apache.org/jira/browse/NIFI-14800)
**1. Enhanced `formatInteger` method in `NiFiCommon` service:**
- **Purpose:** Solve y-axis label clipping issues in charts when displaying large numbers
- **Implementation:** 
- Optional argument `useCompactNotation` added to support new behavior
- Numbers ≥ 100,000 now use compact notation via `Intl.NumberFormat` with `notation: 'compact'`
- Shows up to 2 decimal places for precision (`maximumFractionDigits: 2`)
- Numbers < 100,000 continue using existing comma formatting
- Examples: `100000` → `"100K"`, `1250000` → `"1.25M"`, `2750000000` → `"2.75B"`
**2. Comprehensive test coverage:**
- **Added:** new test cases covering:
- Small numbers with comma formatting (0 to 99,999)
- Large numbers with compact notation (≥ 100,000) …
=> NIFI-14800 - Shorten y-axis integer labels when 100,000 or more using standard abbreviations

nifi-mock/src/main/java/org/apache/nifi/util/MockParameterLookup.java, nifi-mock/src/main/java/org/apache/nifi/util/MockValidationContext.java, nifi-mock/src/test/java/org/apache/nifi/util/TestMockParameterLookup.java
[NIFI-14808](https://issues.apache.org/jira/browse/NIFI-14808)
=> NIFI-14808 Introduce MockParameterLookup class for parameters passing

nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-api/src/main/java/org/apache/nifi/web/util/ParameterUpdateManager.java, nifi-system-tests/nifi-system-test-extensions-bundle/nifi-system-test-extensions/src/main/java/org/apache/nifi/parameter/tests/system/PropertiesParameterProvider.java, nifi-system-tests/nifi-system-test-suite/src/test/java/org/apache/nifi/tests/system/parameters/ParameterContextIT.java
[NIFI-14599](https://issues.apache.org/jira/browse/NIFI-14599) - Use parameter context revision when updating multiple PCs via parameter groups from parameter provider
Note that the system test being added here does not, unfortunately, expose the problem because of the way the client ID is set via the system test NiFi Client Util. But since I created this test as part of investigating the issue and since this is still a good test to have, I kept it as part of this PR.
=> NIFI-14599 - Use parameter context revision when updating multiple PCs via parameter groups from parameter provider

nifi-framework-bundle/nifi-framework/nifi-framework-core/src/main/java/org/apache/nifi/controller/FlowController.java, nifi-framework-bundle/nifi-framework/nifi-resources/pom.xml, nifi-framework-bundle/nifi-framework/nifi-resources/src/main/resources/conf/nifi.properties
[NIFI-14728](https://issues.apache.org/jira/browse/NIFI-14728)
=> NIFI-14728 Allow git Flow Registry sync interval to be user defined

nifi-extension-bundles/nifi-protobuf-bundle/nifi-protobuf-services/pom.xml, nifi-extension-bundles/nifi-redis-bundle/pom.xml, nifi-toolkit/nifi-toolkit-cli/pom.xml, pom.xml
NIFI-14827 - Bump Jetty to 12.0.24, Nimbus JWT to 10.4.1, Jedis to 6.1.0, and others
- Wire from 5.3.5 to 5.3.7 - https://github.com/square/wire/blob/master/CHANGELOG.md
- Jedis from 6.0.0 to 6.1.0 - https://github.com/redis/jedis/releases/tag/v6.1.0
- JLine from 3.30.4 to 3.30.5 - https://github.com/jline/jline3/releases/tag/3.30.5
- AWS SDK v2 from 2.32.14 to 2.32.16 - https://github.com/aws/aws-sdk-java-v2/blob/master/CHANGELOG.md
- Jetty from 12.0.23 to 12.0.24 - https://github.com/jetty/jetty.project/releases/tag/jetty-12.0.24
- Nimbus JOSE JWT from 10.4 to 10.4.1 - https://bitbucket.org/connect2id/nimbus-jose-jwt/src/master/CHANGELOG.txt …
=> NIFI-14827 - Bump Jetty to 12.0.24, Nimbus JWT to 10.4.1, Jedis to 6.1.0, and others

nifi-extension-bundles/nifi-elasticsearch-bundle/pom.xml, nifi-extension-bundles/nifi-email-bundle/nifi-email-processors/pom.xml, nifi-extension-bundles/nifi-graph-bundle/nifi-graph-test-clients/pom.xml, nifi-extension-bundles/nifi-graph-bundle/nifi-other-graph-services/pom.xml, nifi-extension-bundles/nifi-graph-bundle/pom.xml, nifi-extension-bundles/nifi-media-bundle/nifi-media-processors/pom.xml, nifi-extension-bundles/nifi-protobuf-bundle/nifi-protobuf-services/pom.xml, nifi-extension-bundles/nifi-standard-bundle/pom.xml, nifi-extension-bundles/nifi-standard-services/nifi-dbcp-service-bundle/nifi-hikari-dbcp-service/pom.xml, nifi-registry/nifi-registry-core/nifi-registry-test/pom.xml, nifi-registry/pom.xml, pom.xml
NIFI-14840 - Bump Jersey to 3.1.11, Tika to 3.2.2, Checkstyle to 11.0.0, and others
- Elasticsearch from 9.1.0 to 9.1.1 - https://github.com/elastic/elasticsearch-java
- greenmail from 2.1.4 to 2.1.5 - https://github.com/greenmail-mail-test/greenmail/releases/tag/release-2.1.5
- Apache TinkerPop Gremlin from 3.7.3 to 3.7.4 - https://github.com/apache/tinkerpop/blob/3.7.4/CHANGELOG.asciidoc#release-3-7-4
- Apache Tika from 3.2.1 to 3.2.2 - https://github.com/apache/tika/releases/tag/3.2.2
- Wire from 5.3.7 to 5.3.8 - https://github.com/square/wire/blob/master/CHANGELOG.md#version-538
- HikariCP from 7.0.0 to 7.0.1 - https://github.com/brettwooldridge/HikariCP/releases/tag/HikariCP-7.0.1
- MariaDB from 3.5.4 to 3.5.5 - https://github.com/mariadb-corporation/mariadb-connector-j/compare/3.5.4. …
=> NIFI-14840 - Bump Jersey to 3.1.11, Tika to 3.2.2, Checkstyle to 11.0.0, and others

nifi-commons/nifi-properties/src/main/java/org/apache/nifi/util/NiFiProperties.java, nifi-docs/src/main/asciidoc/administration-guide.adoc, nifi-framework-bundle/nifi-framework-extensions/nifi-provenance-repository-bundle/nifi-persistent-provenance-repository/src/main/resources/META-INF/services/org.apache.nifi.provenance.ProvenanceRepository, nifi-framework-bundle/nifi-framework/nifi-framework-core/src/main/java/org/apache/nifi/controller/repository/WriteAheadFlowFileRepository.java
NIFI-14732 Delete references to removed classes:
EncryptedSequentialAccessWriteAheadLog
EncryptedWriteAheadProvenanceRepository
[NIFI-14732](https://issues.apache.org/jira/browse/NIFI-14732)
Ran the NiFi service locally and ran a data flow.
No changes
=> NIFI-14732 Delete references to removed encrypted repo classes

nifi-frontend/src/main/frontend/apps/nifi/src/app/pages/flow-designer/ui/canvas/items/remote-process-group/edit-remote-process-group/edit-remote-process-group.component.ts
[NIFI-14903](https://issues.apache.org/jira/browse/NIFI-14903)
Initial fields values for RPG proxy configurations are not being displayed in the UI because the values passed to the form control are referencing the form control name used on the frontend instead of the field name being returned from the backend.
This wasn't caught by the TS compiler because entity is of type `any`. In the file where that type interface is declared, we use `any` over 30 other times. This is a great example of why it would be greatly beneficial for this project to start using generated types based on the backend response's data model instead of manually providing types by hand.
Please indicate the verification steps performed prior …
=> NIFI-14903: Fix initial value reference for RPG proxy config fields

nifi-extension-bundles/nifi-aws-bundle/nifi-aws-nar/src/main/resources/META-INF/LICENSE, nifi-extension-bundles/nifi-aws-bundle/nifi-aws-service-api-nar/src/main/resources/META-INF/LICENSE
[NIFI-14908](https://issues.apache.org/jira/browse/NIFI-14908)
Bouncy castle library isn't bundled with any of the AWS nars. So, the mention of it shouldn't be present in the LICENSE files.
=> NIFI-14908 Remove the mention of bouncy castle from AWS nar licenses

nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-api/src/main/java/org/apache/nifi/web/StandardNiFiServiceFacade.java
NIFI-14905 - Improve error message in StandardNiFiServiceFacade when checking out a flow via a registry client
=> NIFI-14905 - Improve error message in StandardNiFiServiceFacade when checking out a flow via a registry client

nifi-code-coverage/pom.xml, nifi-commons/nifi-xml-processing/pom.xml, nifi-commons/nifi-xml-processing/src/main/java/org/apache/nifi/xml/processing/validation/StandardSchemaValidator.java, nifi-extension-bom/pom.xml, nifi-extension-bundles/nifi-compress-bundle/nifi-compress-processors/pom.xml, nifi-extension-bundles/nifi-email-bundle/nifi-email-processors/pom.xml, nifi-extension-bundles/nifi-redis-bundle/pom.xml, nifi-extension-bundles/nifi-scripting-bundle/nifi-scripting-processors/pom.xml, nifi-extension-bundles/nifi-standard-bundle/pom.xml, nifi-framework-bundle/nifi-jetty-nar/pom.xml, nifi-registry/nifi-registry-core/nifi-registry-jetty/pom.xml, nifi-registry/pom.xml, pom.xml
NIFI-14909 - Bump Jedis to 6.2.0, Clojure to 1.12.2, brotli4j to 1.20.0, and others
- XML Santuario from 2.3.5 to 4.0.4 - https://github.com/apache/santuario-xml-security-java/releases
- Spotbugs Maven Plugin from 4.8.6.6 to 4.9.4.0 - https://github.com/spotbugs/spotbugs-maven-plugin/releases
- FindSecBugs Plugin from 1.12.0 to 1.14.0 - https://github.com/find-sec-bugs/find-sec-bugs/releases
- Mortbay JSP and EL from 10.1.43 to 10.1.44
- Eclipse JDT ECJ from 3.40.0 to 3.42.0
- brotli4j from 1.18.0 to 1.20.0 - https://github.com/hyperxpro/Brotli4j/releases
- Jakarta Mail API from 2.1.3 to 2.1.4 - https://github.com/jakartaee/mail-api
- Clojure from 1.12.1 to 1.12.2 - https://clojure.org/news/2025/08/25/clojure-1-12-2
- AWS SDK v2 from 2.32.29 to 2.32.31 - …
=> NIFI-14909 - Bump Jedis to 6.2.0, Clojure to 1.12.2, brotli4j to 1.20.0, and others

.github/workflows/docker-tests.yml, c2/c2-client-bundle/c2-client-base/src/main/java/org/apache/nifi/c2/serializer/C2JacksonSerializer.java, minifi/minifi-bootstrap/src/main/java/org/apache/nifi/minifi/bootstrap/RunMiNiFi.java, minifi/minifi-commons/minifi-commons-framework/src/main/java/org/apache/nifi/minifi/commons/service/StandardFlowSerDeService.java, minifi/minifi-commons/minifi-commons-framework/src/test/java/org/apache/nifi/minifi/commons/service/StandardFlowEnrichServiceTest.java, minifi/minifi-nar-bundles/minifi-framework-bundle/minifi-framework/minifi-runtime/src/main/java/org/apache/nifi/minifi/bootstrap/BootstrapListener.java, minifi/minifi-toolkit/minifi-toolkit-configuration/src/main/java/org/apache/nifi/minifi/toolkit/configuration/json/ObjectMapperUtils.java, nifi-commons/nifi-metrics/pom.xml, nifi-extension-bundles/nifi-elasticsearch-bundle/nifi-elasticsearch-client-service/src/main/java/org/apache/nifi/elasticsearch/ElasticSearchClientServiceImpl.java, nifi-extension-bundles/nifi-elasticsearch-bundle/pom.xml, nifi-extension-bundles/nifi-enrich-bundle/nifi-enrich-processors/pom.xml, nifi-extension-bundles/nifi-extension-utils/nifi-git-flow-registry/src/main/java/org/apache/nifi/registry/flow/git/serialize/JacksonFlowSnapshotSerializer.java, nifi-extension-bundles/nifi-gcp-bundle/pom.xml, nifi-extension-bundles/nifi-slack-bundle/nifi-slack-processors/src/main/java/org/apache/nifi/processors/slack/ConsumeSlack.java, nifi-extension-bundles/nifi-standard-services/nifi-lookup-services-bundle/nifi-lookup-services/pom.xml, nifi-extension-bundles/nifi-standard-shared-bundle/nifi-standard-shared-bom/pom.xml, nifi-framework-bundle/nifi-framework-extensions/nifi-questdb-bundle/nifi-questdb/pom.xml, nifi-framework-bundle/nifi-framework/nifi-framework-cluster/src/test/java/org/apache/nifi/cluster/coordination/http/replication/io/TestJsonEntitySerializer.java, nifi-framework-bundle/nifi-framework/nifi-framework-core/src/main/java/org/apache/nifi/controller/serialization/VersionedFlowSerializer.java, nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-api/src/main/java/org/apache/nifi/web/api/ProcessGroupResource.java, nifi-framework-bundle/pom.xml, nifi-manifest/nifi-runtime-manifest-core/src/main/java/org/apache/nifi/runtime/manifest/impl/RuntimeManifestGenerator.java, nifi-registry/nifi-registry-core/nifi-registry-framework/src/main/java/org/apache/nifi/registry/serialization/jackson/ObjectMapperProvider.java, nifi-registry/nifi-registry-core/nifi-registry-jetty/pom.xml, nifi-registry/nifi-registry-core/pom.xml, nifi-registry/pom.xml, nifi-system-tests/nifi-system-test-extensions-bundle/nifi-system-test-extensions/src/main/java/org/apache/nifi/flow/registry/FileSystemFlowRegistryClient.java, nifi-toolkit/nifi-toolkit-cli/src/main/java/org/apache/nifi/toolkit/cli/impl/util/JacksonUtils.java, pom.xml
NIFI-14922 - Bump Zookeeper to 3.9.4, Google Cloud to 26.67.0, Jackson to 2.20.0, and others
- io.dropwizard.metrics core and jvm from 4.2.34 to 4.2.36 - https://github.com/dropwizard/metrics/releases/tag/v4.2.36
- Google Cloud SDK BOM from 26.66.0 to 26.67.0 - https://github.com/googleapis/java-cloud-bom/releases/tag/v26.67.0
- AWS SDK v2 from 2.32.31 to 2.33.0 - https://github.com/aws/aws-sdk-java-v2/blob/master/CHANGELOG.md
- geoip2 from 4.3.1 to 4.4.0 - https://github.com/maxmind/GeoIP2-java/releases/tag/v4.4.0
- checker-qual from 3.49.5 to 3.50.0 - https://github.com/typetools/checker-framework/releases/tag/checker-framework-3.50.0
- QuestDB from 9.0.2 to 9.0.3 - https://github.com/questdb/questdb/releases/tag/9.0.3
- oauth2-oidc-sdk from 11.27.1 to 11.28 - …
=> NIFI-14922 - Bump Zookeeper to 3.9.4, Google Cloud to 26.67.0, Jackson to 2.20.0, and others

nifi-extension-bom/pom.xml, nifi-extension-bundles/nifi-aws-bundle/nifi-aws-processors/pom.xml, nifi-extension-bundles/nifi-kafka-bundle/nifi-kafka-service-shared/src/main/java/org/apache/nifi/kafka/service/security/OAuthBearerLoginCallbackHandler.java, nifi-extension-bundles/nifi-kafka-bundle/pom.xml, nifi-extension-bundles/nifi-parquet-bundle/nifi-parquet-processors/pom.xml, nifi-extension-bundles/nifi-protobuf-bundle/nifi-protobuf-services/pom.xml, nifi-registry/pom.xml, pom.xml
NIFI-14937 - Bump Netty to 4.2.5.Final, Kafka to 4.1.0, Parquet to 1.16.0, and others
- Mortbay Jasper EL/JSP from 10.1.44 to 10.1.44.1
- Kafka from 4.0.0 to 4.1.0 - https://downloads.apache.org/kafka/4.1.0/RELEASE_NOTES.html
- Apache Parquet Avro from 1.15.2 to 1.16.0 - https://github.com/apache/parquet-java/releases/tag/apache-parquet-1.16.0
- Wire from 5.3.11 to 5.4.0 - https://github.com/square/wire/blob/master/CHANGELOG.md#version-540
- AWS SDK v2 from 2.33.0 to 2.33.1 - https://github.com/aws/aws-sdk-java-v2/blob/master/CHANGELOG.md
- Netty from 4.2.4.Final to 4.2.5.Final - https://netty.io/news/2025/09/03/4-2-5.html
=> NIFI-14937 - Bump Netty to 4.2.5.Final, Kafka to 4.1.0, Parquet to 1.16.0, and others

nifi-framework-bundle/nifi-framework/nifi-framework-nar-utils/src/test/java/org/apache/nifi/nar/NarUnpackerTest.java, nifi-framework-bundle/nifi-framework/nifi-nar-utils/src/main/java/org/apache/nifi/nar/NarUnpacker.java
NIFI-14759 - Handle out-of-order ZIP entries in NarUnpacker
=> NIFI-14759 - Handle out-of-order ZIP entries in NarUnpacker

nifi-extension-bundles/nifi-extension-utils/nifi-record-utils/nifi-avro-record-utils/src/main/java/org/apache/nifi/avro/AvroTypeUtil.java, nifi-extension-bundles/nifi-extension-utils/nifi-record-utils/nifi-avro-record-utils/src/test/java/org/apache/nifi/avro/TestAvroTypeUtil.java, nifi-extension-bundles/nifi-standard-services/nifi-record-serialization-services-bundle/nifi-record-serialization-services/pom.xml, nifi-extension-bundles/nifi-standard-services/nifi-record-serialization-services-bundle/nifi-record-serialization-services/src/test/java/org/apache/nifi/avro/TestWriteAvroResult.java, nifi-extension-bundles/nifi-standard-services/nifi-record-serialization-services-bundle/nifi-record-serialization-services/src/test/resources/avro/decimals-bytes-fixed.avsc, nifi-extension-bundles/nifi-standard-services/nifi-record-serialization-services-bundle/nifi-record-serialization-services/src/test/resources/avro/fixed16.avsc
NIFI-14897 - Fix Avro FIXED serialization to use GenericFixed
- Fixes ClassCastException when writing Avro FIXED: use GenericData.Fixed instead of ByteBuffer
- Preserves logical decimal behavior (BYTES to ByteBuffer; FIXED to GenericFixed)
- Adds unit tests to validate FIXED handling
=> NIFI-14897 - Fix Avro FIXED serialization to use GenericFixed

nifi-extension-bundles/nifi-kafka-bundle/nifi-kafka-service-aws/src/main/java/org/apache/nifi/kafka/service/aws/AmazonMSKConnectionService.java, nifi-extension-bundles/nifi-kafka-bundle/nifi-kafka-shared/src/main/java/org/apache/nifi/kafka/shared/component/KafkaClientComponent.java, nifi-extension-bundles/nifi-kafka-bundle/nifi-kafka-shared/src/main/java/org/apache/nifi/kafka/shared/login/AwsMskIamLoginConfigProvider.java, nifi-extension-bundles/nifi-kafka-bundle/nifi-kafka-shared/src/main/java/org/apache/nifi/kafka/shared/property/AwsRoleSource.java, nifi-extension-bundles/nifi-kafka-bundle/nifi-kafka-shared/src/test/java/org/apache/nifi/kafka/shared/login/AwsMskIamLoginConfigProviderTest.java
NIFI-14927 - Expose Assume Role (ARN/Session Name) for AWS_MSK_IAM in AmazonMSKConnectionService
=> NIFI-14927 - Expose Assume Role (ARN/Session Name) for AWS_MSK_IAM in AmazonMSKConnectionService

nifi-code-coverage/pom.xml, nifi-extension-bundles/nifi-azure-bundle/nifi-azure-processors/pom.xml, nifi-extension-bundles/nifi-azure-bundle/pom.xml, nifi-toolkit/nifi-toolkit-cli/pom.xml, pom.xml
NIFI-14954 - Bump Netty to 4.2.6.Final, Kotlin to 2.2.20, Fabric8 k8s to 7.4.0, and others
- reactor-netty-http from 1.2.9 to 1.2.10 - https://github.com/reactor/reactor-netty/releases/tag/v1.2.10
- reactor-core and reactor-test from 3.7.9 to 3.7.11 - https://github.com/reactor/reactor-core/releases/tag/v3.7.11
- jline from 3.30.5 to 3.30.6 - https://github.com/jline/jline3/releases/tag/jline-3.30.6
- AWS SDK v2 from 2.33.4 to 2.33.5 - https://github.com/aws/aws-sdk-java-v2/blob/master/CHANGELOG.md
- Fabric8 k8s from 7.3.1 to 7.4.0 - https://github.com/fabric8io/kubernetes-client/releases/tag/v7.4.0
- Kotlin from 2.2.10 to 2.2.20 - https://github.com/JetBrains/kotlin/releases/tag/v2.2.20
- Netty from 4.2.5.Final to 4.2.6.Final - https://netty.io/news/2025/09/08/4-2-6.html
Please complete …
=> NIFI-14954 - Bump Netty to 4.2.6.Final, Kotlin to 2.2.20, Fabric8 k8s to 7.4.0, and others

nifi-extension-bundles/nifi-atlassian-bundle/nifi-atlassian-extensions/src/main/java/org/apache/nifi/atlassian/bitbucket/BitbucketFlowRegistryClient.java, nifi-extension-bundles/nifi-atlassian-bundle/nifi-atlassian-extensions/src/main/java/org/apache/nifi/atlassian/bitbucket/BitbucketRepositoryClient.java, nifi-extension-bundles/nifi-github-bundle/nifi-github-extensions/src/main/java/org/apache/nifi/github/GitHubFlowRegistryClient.java, nifi-extension-bundles/nifi-github-bundle/nifi-github-extensions/src/main/java/org/apache/nifi/github/GitHubRepositoryClient.java, nifi-extension-bundles/nifi-gitlab-bundle/nifi-gitlab-extensions/src/main/java/org/apache/nifi/gitlab/GitLabFlowRegistryClient.java, nifi-extension-bundles/nifi-gitlab-bundle/nifi-gitlab-extensions/src/main/java/org/apache/nifi/gitlab/GitLabRepositoryClient.java
NIFI-14967 - Use ComponentLog in git registry clients
For some git-based registry client implementations, we're instantiating a dedicated logger using the SLF4J Logger Factory. We should instead leverage the existing component logger that comes from AbstractFlowRegistryClient. This is important to properly expose bulletins in case of warnings/errors.
=> NIFI-14967 - Use ComponentLog in git registry clients

nifi-extension-bundles/nifi-standard-bundle/nifi-standard-processors/src/main/java/org/apache/nifi/processors/standard/EvaluateXQuery.java
[NIFI-14970](https://issues.apache.org/jira/browse/NIFI-14970)
=> NIFI-14970 Replaced deprecated isEmpty method of net.sf.saxon.s9api.XdmValue with isEmptySequence().

nifi-registry/pom.xml, pom.xml
NIFI-14980 - Fix javadoc generation for NiFi Registry
Also removed duplicated `quiet` line
=> NIFI-14980 - Fix javadoc generation for NiFi Registry

nifi-extension-bundles/nifi-snowflake-bundle/nifi-snowflake-processors/pom.xml, nifi-extension-bundles/nifi-snowflake-bundle/nifi-snowflake-processors/src/main/java/org/apache/nifi/processors/snowflake/PutSnowflakeInternalStage.java, nifi-extension-bundles/nifi-snowflake-bundle/nifi-snowflake-processors/src/test/java/org/apache/nifi/processors/snowflake/SnowflakeIngestIT.java, nifi-extension-bundles/nifi-snowflake-bundle/pom.xml
NIFI-14982 - Bump Snowflake Ingest SDK to 4.3.0 and Snowflake JDBC to 3.25.1.
Also add an integration test that can be executed to confirm that all processors are working as expected.
The new integration test can be executed using:
````
JAVA_HOME=/Library/Java/JavaVirtualMachines/zulu-21.jdk/Contents/Home \
NIFI_SNOWFLAKE_URL=xxx \
NIFI_SNOWFLAKE_USER=xxx \
NIFI_SNOWFLAKE_PASSWORD=xxx \
NIFI_SNOWFLAKE_WAREHOUSE=xxx \
NIFI_SNOWFLAKE_PRIVATE_KEY_PATH=xxx \
NIFI_SNOWFLAKE_PRIVATE_KEY_PASSPHRASE=xxx \
NIFI_SNOWFLAKE_ROLE=ACCOUNTADMIN \
mvn -pl nifi-extension-bundles/nifi-snowflake-bundle/nifi-snowflake-processors \
-P integration-tests,skip-unit-tests \
-DargLine="--add-opens=java.base/java.nio=org.apache.arrow.memory.core,ALL-UNNAMED" \
-Dit.test=SnowflakeIngestIT verify
````
Please complete …
=> NIFI-14982 - Bump Snowflake Ingest SDK to 4.3.0 and Snowflake JDBC to 3.25.1

nifi-frontend/src/main/frontend/apps/nifi/src/app/ui/common/property-table/editors/combo-editor/combo-editor.component.spec.ts, nifi-frontend/src/main/frontend/apps/nifi/src/app/ui/common/property-table/editors/combo-editor/combo-editor.component.ts, nifi-frontend/src/main/frontend/apps/nifi/src/app/ui/common/property-table/editors/nf-editor/nf-editor.component.spec.ts, nifi-frontend/src/main/frontend/apps/nifi/src/app/ui/common/property-table/editors/nf-editor/nf-editor.component.ts
- In the combo editor, the form was not marked as dirty which caused the Apply button to not be enabled.
- In the nf editor, the default value was not considered.
=> NIFI-14988: Fixing issue with default values for dynamic properties.

nifi-extension-bundles/nifi-elasticsearch-bundle/pom.xml, nifi-extension-bundles/nifi-email-bundle/nifi-email-processors/pom.xml, nifi-extension-bundles/nifi-gcp-bundle/nifi-gcp-processors/pom.xml, nifi-registry/pom.xml, pom.xml
NIFI-14993 - Bump Spring Security to 6.5.5, Spring Boot to 3.5.6, Elasticsearch to 9.1.4, and others
- Elasticsearch from 9.1.3 to 9.1.4 - https://github.com/elastic/elasticsearch-java/releases/tag/v9.1.4
- Jakarta Activation API from 2.1.3 to 2.1.4 - https://github.com/jakartaee/jaf-api/releases/tag/2.1.4
- Google Drive from v3-rev20250829-2.0.0 to v3-rev20250910-2.0.0 - https://github.com/googleapis/google-api-java-client-services/blob/main/clients/google-api-services-drive/v3/2.0.0/README.md
- Spring Boot from 3.5.5 to 3.5.6 - https://github.com/spring-projects/spring-boot/releases/tag/v3.5.6
- FlywayDB from 11.13.0 to 11.13.1 - https://github.com/flyway/flyway/releases/tag/flyway-11.13.1
- AWS SDK v2 from 2.33.11 to 2.33.12 - …
=> NIFI-14993 - Bump Spring Security to 6.5.5, Spring Boot to 3.5.6, Elasticsearch to 9.1.4, and others

pmd-ruleset.xml
NIFI-14992 - Remove deprecated PMD rule UselessOperationOnImmutable
https://pmd.github.io/pmd/pmd_rules_java_errorprone.html#uselessoperationonimmutable
=> NIFI-14992 - Remove deprecated PMD rule UselessOperationOnImmutable

minifi/minifi-bootstrap/pom.xml, nifi-commons/pom.xml, nifi-extension-bom/pom.xml, nifi-extension-bundles/nifi-aws-bundle/pom.xml, nifi-extension-bundles/nifi-azure-bundle/pom.xml, nifi-extension-bundles/nifi-email-bundle/nifi-email-processors/pom.xml, nifi-extension-bundles/nifi-evtx-bundle/nifi-evtx-processors/pom.xml, nifi-extension-bundles/nifi-gcp-bundle/pom.xml, nifi-extension-bundles/nifi-graph-bundle/nifi-graph-test-clients/pom.xml, nifi-extension-bundles/nifi-hadoop-libraries-bundle/pom.xml, nifi-extension-bundles/nifi-opentelemetry-bundle/pom.xml, nifi-extension-bundles/nifi-protobuf-bundle/pom.xml, nifi-extension-bundles/nifi-sql-reporting-bundle/pom.xml, nifi-extension-bundles/nifi-standard-bundle/nifi-standard-processors/pom.xml, nifi-extension-bundles/nifi-standard-bundle/pom.xml, nifi-extension-bundles/nifi-standard-shared-bundle/nifi-standard-shared-bom/pom.xml, nifi-framework-bundle/nifi-framework-extensions/nifi-framework-zookeeper-bundle/nifi-framework-zookeeper-nar/pom.xml, nifi-framework-bundle/pom.xml, nifi-registry/nifi-registry-core/nifi-registry-test/pom.xml, nifi-registry/nifi-registry-core/pom.xml, pom.xml
NIFI-14998 - Bump Log4J2 to 2.25.2, Guava to 33.5.0-jre, Mockito to 5.20.0, and others
- Jetbrains Annotations from 24.1.0 to 26.0.2-1 - https://github.com/JetBrains/java-annotations/releases/tag/26.0.2-1
- Eclipse JDT ECJ from 3.42.0 to 3.43.0 - https://github.com/eclipse-jdt/eclipse.jdt.core
- Guava from 33.4.8-jre to 33.5.0-jre - https://github.com/google/guava/releases/tag/v33.5.0
- Jakarta Mail API from 2.1.4 to 2.1.5 - https://github.com/jakartaee/mail-api/releases/tag/2.1.5
- PostgreSQL from 42.7.7 to 42.7.8 - https://github.com/pgjdbc/pgjdbc/releases/tag/REL42.7.8
- Error Prone Annotations from 2.33.0 to 2.42.0 - https://github.com/google/error-prone/releases/tag/v2.42.0
- AWS SDK v2 from 2.33.12 to 2.34.0 - https://github.com/aws/aws-sdk-java-v2/blob/master/CHANGELOG.md
- Log4J2 …
=> NIFI-14998 - Bump Log4J2 to 2.25.2, Guava to 33.5.0-jre, Mockito to 5.20.0, and others

nifi-framework-bundle/nifi-framework/nifi-framework-components/src/main/java/org/apache/nifi/groups/StandardProcessGroup.java, nifi-framework-bundle/nifi-framework/nifi-framework-components/src/main/java/org/apache/nifi/util/FlowDifferenceFilters.java, nifi-framework-bundle/nifi-framework/nifi-framework-components/src/test/java/org/apache/nifi/util/TestFlowDifferenceFilters.java, nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-api/src/main/java/org/apache/nifi/web/api/dto/DtoFactory.java
NIFI-14995 - Improve Flow Differences Filter to account for renameProperty and createControllerService
As we use more and more the `migrateProperties` capabilities, we see that we have some corner cases where the automated changes are showing as local changes which is confusing because a user is upgrading without making any changes to their versioned flows and the UI is showing that some local modifications have been made. Such scenarios should be better handled to not show local changes.
One scenario has been handled in [NIFI-14985](https://issues.apache.org/jira/browse/NIFI-14985) to better deal with removed properties.
This change is to handle two additional scenarios (this is combined in a single PR because of the approach taken that is introducing a concept of environmental context) …
=> NIFI-14995 - Improve Flow Differences Filter to account for renameProperty and createControllerService

nifi-frontend/src/main/frontend/apps/nifi/src/app/pages/flow-designer/service/parameter-helper.service.ts, nifi-frontend/src/main/frontend/apps/nifi/src/app/pages/parameter-contexts/state/parameter-context-listing/index.ts, nifi-frontend/src/main/frontend/apps/nifi/src/app/pages/parameter-contexts/state/parameter-context-listing/parameter-context-listing.effects.spec.ts, nifi-frontend/src/main/frontend/apps/nifi/src/app/pages/parameter-contexts/state/parameter-context-listing/parameter-context-listing.effects.ts, nifi-frontend/src/main/frontend/apps/nifi/src/app/pages/parameter-contexts/state/parameter-context-listing/parameter-context-listing.reducer.ts, nifi-frontend/src/main/frontend/apps/nifi/src/app/pages/parameter-contexts/state/parameter-context-listing/parameter-context-listing.selectors.ts, nifi-frontend/src/main/frontend/apps/nifi/src/app/ui/common/parameter-context/edit-parameter-context/edit-parameter-context.component.html, nifi-frontend/src/main/frontend/apps/nifi/src/app/ui/common/parameter-context/edit-parameter-context/edit-parameter-context.component.spec.ts, nifi-frontend/src/main/frontend/apps/nifi/src/app/ui/common/parameter-context/edit-parameter-context/edit-parameter-context.component.ts
[NIFI-15028](https://issues.apache.org/jira/browse/NIFI-15028)
**Fix parameter context update polling cancellation and improve test quality**
Fixed critical issue where parameter context update polling would continue indefinitely when users cancelled the edit dialog, causing unnecessary backend requests and potential resource leaks.
- **Added event-driven cancellation**: `cancelUpdateRequest` EventEmitter in edit component
- **Enhanced effects**: Subscribe to cancellation events and dispatch stop polling action
- **Fixed broken cancellation**: Corrected parameter helper service to properly dispatch stop polling action and subscribe to the observable
- **Added comprehensive tests**: Created SIFERS-pattern tests for new polling cancellation functionality
- **Enhanced component tests**: …
=> NIFI-15028 - Ensure parameter context edit async polling stops after cancelling the update

nifi-frontend/src/main/frontend/apps/nifi/src/app/pages/flow-designer/ui/canvas/items/connection/edit-connection/edit-connection.component.ts, nifi-frontend/src/main/frontend/apps/nifi/src/app/pages/flow-designer/ui/canvas/items/process-group/edit-process-group/edit-process-group.component.ts, nifi-frontend/src/main/frontend/apps/nifi/src/app/pages/flow-designer/ui/canvas/items/processor/edit-processor/edit-processor.component.ts, nifi-frontend/src/main/frontend/apps/nifi/src/app/pages/queue/ui/queue-listing/flowfile-dialog/flowfile-dialog.component.ts, nifi-frontend/src/main/frontend/apps/nifi/src/app/pages/settings/ui/flow-analysis-rules/edit-flow-analysis-rule/edit-flow-analysis-rule.component.ts, nifi-frontend/src/main/frontend/apps/nifi/src/app/pages/settings/ui/parameter-providers/edit-parameter-provider/edit-parameter-provider.component.ts, nifi-frontend/src/main/frontend/apps/nifi/src/app/pages/settings/ui/registry-clients/edit-registry-client/edit-registry-client.component.ts, nifi-frontend/src/main/frontend/apps/nifi/src/app/pages/settings/ui/reporting-tasks/edit-reporting-task/edit-reporting-task.component.ts, nifi-frontend/src/main/frontend/apps/nifi/src/app/ui/common/controller-service/edit-controller-service/edit-controller-service.component.ts, nifi-frontend/src/main/frontend/apps/nifi/src/app/ui/common/parameter-context/edit-parameter-context/edit-parameter-context.component.ts, nifi-frontend/src/main/frontend/apps/nifi/src/app/ui/common/provenance-event-dialog/provenance-event-dialog.component.ts, nifi-frontend/src/main/frontend/apps/nifi/src/app/ui/common/system-diagnostics-dialog/system-diagnostics-dialog.component.ts, nifi-frontend/src/main/frontend/apps/nifi/src/app/ui/common/tabbed-dialog/tabbed-dialog.component.spec.ts, nifi-frontend/src/main/frontend/apps/nifi/src/app/ui/common/tabbed-dialog/tabbed-dialog.component.ts
[NIFI-15029](https://issues.apache.org/jira/browse/NIFI-15029)
**Core Implementation:**
- Created `TABBED_DIALOG_ID` injection token for passing custom dialog IDs
- Updated `TabbedDialog` constructor to use `inject(TABBED_DIALOG_ID, { optional: true })`
- Added proper null/undefined checking to handle empty string dialog IDs
- Added try-catch error handling for localStorage operations
**Component Integration:**
- Updated `EditParameterContext` to provide `TABBED_DIALOG_ID` token with `NiFiCommon.EDIT_PARAMETER_CONTEXT_DIALOG_ID`
- Maintained backward compatibility - components without providers use default dialog ID
**Testing:**
- Created comprehensive test suite (15 tests) covering:
- Default vs custom dialog ID behavior
- LocalStorage integration scenarios
- Error handling and edge …
=> NIFI-15029 - Update tabbed dialog to leverage InjectionToken, allowing subclasses to define their own dialogId

nifi-extension-bundles/nifi-aws-bundle/pom.xml, nifi-extension-bundles/nifi-email-bundle/nifi-email-processors/pom.xml, nifi-extension-bundles/nifi-gcp-bundle/pom.xml, nifi-extension-bundles/nifi-graph-bundle/nifi-neo4j-cypher-service/pom.xml, nifi-extension-bundles/nifi-salesforce-bundle/nifi-salesforce-processors/pom.xml, nifi-extension-bundles/nifi-scripting-bundle/nifi-scripting-processors/pom.xml, nifi-extension-bundles/nifi-standard-shared-bundle/nifi-standard-shared-bom/pom.xml, nifi-extension-bundles/nifi-windows-event-log-bundle/nifi-windows-event-log-processors/pom.xml, nifi-registry/pom.xml, pom.xml
NIFI-15035 - Bump JUnit to 6.0.0, Logback to 1.5.19, GCP BOM to 26.69.0, and others
- AWS Kinesis Client from 2.7.1 to 2.7.2 - https://github.com/awslabs/amazon-kinesis-client/releases/tag/v2.7.2
- Greenmail from 2.1.5 to 2.1.6 - https://github.com/greenmail-mail-test/greenmail/releases/tag/release-2.1.6
- Google Cloud SDK BOM from 26.68.0 to 26.69.0 - https://github.com/googleapis/java-cloud-bom/releases/tag/v26.69.0
- Neo4J Driver from 5.28.9 to 6.0.0 - https://github.com/neo4j/neo4j-java-driver/releases/tag/6.0.0
- Camel Salesforce from 4.14.0 to 4.14.1 - https://github.com/apache/camel/releases/tag/camel-4.14.1
- Clojure from 1.12.2 to 1.12.3 - https://clojure.org/news/2025/09/25/clojure-1-12-3
- checker-qual from 3.51.0 to 3.51.1 - …
=> NIFI-15035 - Bump JUnit to 6.0.0, Logback to 1.5.19, GCP BOM to 26.69.0, and others

nifi-framework-bundle/nifi-framework/nifi-client-dto/src/main/java/org/apache/nifi/web/api/dto/ProcessorDTO.java, nifi-framework-bundle/nifi-framework/nifi-client-dto/src/main/java/org/apache/nifi/web/api/entity/ProcessorEntity.java, nifi-framework-bundle/nifi-framework/nifi-framework-cluster/src/main/java/org/apache/nifi/cluster/manager/ProcessorEntityMerger.java, nifi-framework-bundle/nifi-framework/nifi-framework-cluster/src/test/java/org/apache/nifi/cluster/manager/ProcessorEntityMergerTest.java, nifi-framework-bundle/nifi-framework/nifi-framework-components/src/main/java/org/apache/nifi/controller/StandardProcessorNode.java, nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-api/src/main/java/org/apache/nifi/web/api/dto/DtoFactory.java, nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-api/src/main/java/org/apache/nifi/web/api/dto/EntityFactory.java, nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-api/src/main/java/org/apache/nifi/web/dao/impl/StandardProcessorDAO.java, nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-api/src/test/java/org/apache/nifi/web/dao/impl/StandardProcessorDAOTest.java, nifi-frontend/src/main/frontend/apps/nifi/src/app/pages/flow-designer/service/canvas-utils.service.spec.ts, nifi-frontend/src/main/frontend/apps/nifi/src/app/pages/flow-designer/service/canvas-utils.service.ts
This PR adds support for exposing the **physical state** of processors in the NiFi API, enabling the UI to allow stopping processors that are in the `STARTING` physical state.
Previously, when a processor was starting up (executing `@OnScheduled` methods), its logical state was `STOPPED` but the physical state was `STARTING`. The UI had no visibility into this physical state. Users couldn't stop processors that were stuck in the `STARTING` state, requiring process group-level stops as a workaround
Added `physicalState` field to processor DTOs and entities, with full support for:
- API exposure with proper schema documentation
- Cluster response merging with transition state prioritization  
- Backend validation allowing stops of `STARTING` processors
- Frontend updates to allow the user …
=> NIFI-14999: Adding support to stop a starting processor.

nifi-frontend/src/main/frontend/apps/nifi/src/app/pages/documentation/ui/common/property-definition/property-definition.component.html
[NIFI-15045](https://issues.apache.org/jira/browse/NIFI-15045)
If there is no description for an allowable value, the UI would still show an info icon with an empty tooltip. This PR just removes the icon so they can't see the empty tooltip if there is no description.
One example can be found in the docs for `org.apache.nifi.controller.MonitorMemory`, in particular the Memory Pool allowable values:
This is what it looked like before:
=> NIFI-15045 - Prevent empty tooltip in help docs for property definition allowable values

nifi-extension-bundles/nifi-asana-bundle/nifi-asana-processors/pom.xml, nifi-extension-bundles/nifi-azure-bundle/pom.xml, nifi-extension-bundles/nifi-box-bundle/pom.xml, nifi-extension-bundles/nifi-graph-bundle/nifi-neo4j-cypher-service/pom.xml, nifi-extension-bundles/nifi-kafka-bundle/nifi-kafka-service-aws/pom.xml, nifi-framework-bundle/nifi-framework-extensions/nifi-questdb-bundle/nifi-questdb/pom.xml, pom.xml
NIFI-15054 - Bump Azure SDK to 1.3.0, AWS v1 SDK to 1.12.792, AWS v2 SDK to 2.35.0, and others
- Google HTTP Client (Asana Bundle) from 1.36.0 to 1.47.1 - https://github.com/googleapis/google-http-java-client/releases/tag/v1.47.1
- Azure SDK BOM from 1.2.38 to 1.3.0 - https://github.com/Azure/azure-sdk-for-java/releases/tag/azure-sdk-bom_1.3.0
- MSAL4J from 1.22.0 to 1.23.1 - https://github.com/AzureAD/microsoft-authentication-library-for-java/releases/tag/v1.23.1
- Box Java SDK from 4.16.3 to 4.16.4 - https://github.com/box/box-java-sdk/releases/tag/v4.16.4
- Neo4J Driver from 6.0.0 to 6.0.1 - https://github.com/neo4j/neo4j-java-driver/releases/tag/6.0.1
- AWS MSK IAM Auth from 2.3.2 to 2.3.4 - https://github.com/aws/aws-msk-iam-auth/releases/tag/v2.3.4
- QuestDB from 9.0.3 to 9.1.0 - …
=> NIFI-15054 - Bump Azure SDK to 1.3.0, AWS v1 SDK to 1.12.792, AWS v2 SDK to 2.35.0, and others

nifi-docs/src/main/asciidoc/python-developer-guide.adoc
NIFI-13672 - Add documentation for controller service referencing in Python processors
=> NIFI-13672 - Add documentation for controller service referencing in Python processors

nifi-extension-bundles/nifi-standard-bundle/nifi-standard-processors/src/main/java/org/apache/nifi/processors/standard/AbstractExecuteSQL.java
NIFI-15024 - Add executed query as a FlowFile attribute for ExecuteSQL and ExecuteSQLRecord
=> NIFI-15024 - Add executed query as a FlowFile attribute for ExecuteSQL and ExecuteSQLRecord
